apostrophecms/apostrophe

lib/templates.js
update date apostrophe filter to set moment locale from i18n defaultLanguage setting
=> Set moment.lang() to default language if set in i18n for date filter

lib/modules/apostrophe-modal/public/css/components/modal-filters.less, lib/modules/apostrophe-modal/public/css/components/modal-header.less, lib/modules/apostrophe-ui/public/css/components/tables.less
=> Modal styles

views/aposMacros/formArea.html, views/aposMacros/formBoolean.html, views/aposMacros/formBooleanStandalone.html, views/aposMacros/formCheckboxes.html, views/aposMacros/formDate.html, views/aposMacros/formDateSelect.html, views/aposMacros/formDateSelectComponent.html, views/aposMacros/formEmail.html, views/aposMacros/formMultiSelect.html, views/aposMacros/formPassword.html, views/aposMacros/formPill.html, views/aposMacros/formPillStandalone.html, views/aposMacros/formSelect.html, views/aposMacros/formSelectStandalone.html, views/aposMacros/formSelective.html, views/aposMacros/formSingleton.html, views/aposMacros/formTags.html, views/aposMacros/formText.html, views/aposMacros/formTextarea.html, views/aposMacros/formTime.html, views/formMacros.html
Refactored the contents of formMacros.html into sub-templates under aposMacros. This allows your project to override individual macros easily.
=> Refactored the contents of formMacros.html into sub-templates

lib/appy.js, public/js/content.js
Also please review:
https://github.com/punkave/appy/commit/003e15280ba8ea28753e53c0ddea1c2ede695364
Which I forgot to do a PR on and hit publish on already (: I did test it thoroughly but please review for possible insanity.
cc @jth-
=> email should match case insensitively at login time

lib/modules/apostrophe-areas/lib/routes.js, lib/modules/apostrophe-areas/views/virtualArea.html, lib/modules/apostrophe-schemas/public/js/user.js
=> Fixed virtual singleton editing in schemas.

lib/modules/apostrophe-areas/lib/routes.js, lib/modules/apostrophe-images/lib/api.js, lib/modules/apostrophe-images/lib/cursor.js, lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/js/user.js
=> bless areas and singletons in schemas

lib/modules/apostrophe-docs/public/js/manager.js, lib/modules/apostrophe-pages/index.js, lib/modules/apostrophe-pages/lib/browser.js, lib/modules/apostrophe-pages/public/css/jqtree.css, lib/modules/apostrophe-pages/public/css/user.less, lib/modules/apostrophe-pages/public/js/reorganize.js, lib/modules/apostrophe-pages/views/reorganize.html
Preliminarily styled reorganize modal. Also fixed a couple bugs around trashing pages.
Resolve #486
=> Style reorganize modal

lib/modules/apostrophe-assets/index.js, lib/modules/apostrophe-assets/public/css/vendor/jquery.Jcrop.less, lib/modules/apostrophe-attachments/public/js/cropEditor.js, lib/modules/apostrophe-attachments/views/attachment.html, lib/modules/apostrophe-attachments/views/cropEditor.html, lib/modules/apostrophe-images/public/css/editor.less, lib/modules/apostrophe-images/public/js/relationship-editor.js, lib/modules/apostrophe-pieces-widgets/public/js/editor.js
Added some basic styles for the crop editor. Also, fixed some options being passed through so that the current crop is passed to the editor and made it so the crop can be dragged and resized.
Resolve #450
=> Style crop editor

lib/modules/apostrophe-docs/public/js/chooser.js, lib/modules/apostrophe-images-widgets/public/js/editor.js, lib/modules/apostrophe-modal/public/js/modal.js, lib/modules/apostrophe-pieces/public/js/editor-modal.js, lib/modules/apostrophe-widgets/public/js/editor.js
=> Add confirm cancel dialog

lib/modules/apostrophe-pieces-pages/index.js, lib/modules/apostrophe-pieces/public/js/user.js, lib/modules/apostrophe-versions/public/css/user.less, lib/modules/apostrophe-versions/views/versions.html
page menu for a piece now properly triggering versions for the instance of that piece, rather than the parent.  slight improvements to the version styling, giving the diff a little more room
=> Page versions for pieces

views/loginWindow.html, views/logoutWindow.html
Adding prefix support to the login/logout windows that appear when you use the "fast login" with shift+escape.
=> Prefix support for fast login

lib/modules/apostrophe-versions/lib/api.js, lib/modules/apostrophe-versions/lib/routes.js
=> Add published(null) filter to two queries within apostrophe-versions

lib/modules/apostrophe-assets/public/js/always.js, lib/modules/apostrophe-templates/index.js, lib/modules/apostrophe-templates/views/refreshLayout.html
=> Fix #578: req.browserCall works with refreshable, apos.change does not duplicate logic

lib/modules/apostrophe-attachments/index.js, lib/modules/apostrophe-attachments/lib/api.js, lib/modules/apostrophe-attachments/lib/tasks/rescale.js
=> apostrophe-attachments:rescale task

lib/modules/apostrophe-areas/lib/api.js, lib/modules/apostrophe-areas/lib/helpers.js, lib/modules/apostrophe-areas/views/area.html
If no options are specified for a given area or singleton, fallback to use the options specified for the schema field declaring the area or singleton, if they exist.
Not sure if I have this quite right, let me know what you think @boutell
=> Fallback area and singletons to schema field options

lib/modules/apostrophe-schemas/public/css/user.less, lib/modules/apostrophe-ui/public/css/mixins/ornaments.less
Remove text for default state and provide clearer error state cc/ @stuartromanek
=> Adjust styles for required fields

lib/modules/apostrophe-modal/public/css/components/modal-tabs.less, lib/modules/apostrophe-schemas/public/css/components/help.less
=> Set font size for tab and help label

lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/public/js/user.js, lib/modules/apostrophe-modal/public/js/modal.js, lib/modules/apostrophe-schemas/views/arrayItems.html, lib/modules/apostrophe-schemas/views/macros.html
let me know if you want to step through this IRL
=> Area control hover changes

lib/modules/apostrophe-express/index.js
=> Defines and requires fs

lib/modules/apostrophe-ui/public/css/components/fields.less
=> Give textarea focus state apos glow

lib/modules/apostrophe-assets/public/css/vendor/cropper.less
=> Bigger crop handles

lib/modules/apostrophe-ui/public/css/components/fields.less
Center arrow in input wrapper and add cursor pointer for hover state
=> Select input type style enhancements

lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/css/components/array-editor.less, lib/modules/apostrophe-schemas/public/js/array-modal.js, lib/modules/apostrophe-schemas/views/arrayEditor.html
Also:
* Refactored crazy redundant event handlers
* Documented methods
* Reduced redundant refreshes
=> limit for arrays, field defaults for arrays, refactoring

lib/modules/apostrophe-modal/public/css/components/modal-tabs.less, lib/modules/apostrophe-schemas/public/css/components/array-editor.less, lib/modules/apostrophe-schemas/views/arrayItems.html
- modal array tabs are a bit wider
- modal array tabs don't wrap for long titles, they truncate with `text-overflow:ellipsis`
- padding added to the bottom of the modal array tabs container to account for the `position:fixed` Add Item button
=> Modal array tab ui

lib/modules/apostrophe-admin-bar/views/adminBar.html
Previously not closing the a markup
=> Fix test on adminBar subItem a link

lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/js/user.js
=> enforce string field min and max properties on server side, also activate correct tab and scroll to first error on failed save

defaults.js, lib/modules/apostrophe-notifications/index.js, lib/modules/apostrophe-notifications/public/css/user.less, lib/modules/apostrophe-notifications/public/js/user.js, lib/modules/apostrophe-notifications/views/notification.html
Built out a reasonable starting place for the front-end for these. Note: @boutell, we still need to add support for passing parameters into the message that don't need to be considered for the localization in the template.
```
apos.notify('Your changes have been saved.');
apos.notify('Your changes have been saved.', { type: 'success' });
apos.notify('Your changes have been saved. But something is weird.', { type: 'warn' });
apos.notify('There was an error!', { type: 'error' });
apos.notify('There was an error! This message will self destruct.', { type: 'error', dismiss: true });
apos.notify('There was an error! This message will self destruct in 1 second.', { type: 'error', dismiss: 1 });
```
Not shown here is that you can simply click on a notification to dismiss it.
And yes, I am on …
=> notifications!

lib/modules/apostrophe-areas/views/area.html
=> Add space between attributes to W3C validate

lib/modules/apostrophe-areas/lib/routes.js
Done following the model of the other in this file.
=> Improves render widget unblessed error

lib/modules/apostrophe-areas/lib/api.js, lib/modules/apostrophe-areas/lib/cursor.js, lib/modules/apostrophe-areas/lib/protectedApi.js, lib/modules/apostrophe-areas/lib/routes.js, lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-widgets/index.js
=> permissions for widget fields

lib/modules/apostrophe-pages/lib/api.js, test/pages.js
=> implemented 1271

lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-areas/public/js/user.js
=> fixed in my tests

defaults.js, lib/modules/apostrophe-soft-redirects/index.js, test/soft-redirects.js
=> soft redirects, with tests

lib/modules/apostrophe-modal/public/css/components/modal-tabs.less
=> Give tabs position, so they don't scroll in FF

lib/modules/apostrophe-soft-redirects/index.js
Fixes bug when piece didn't have `_url` for reasons.
=> Adds check for soft-redirect docs filtering

lib/modules/apostrophe-soft-redirects/index.js, test/soft-redirects.js
Closes #1352
Happy to elaborate or adapt the changes!
=> Set 301 HTTP status code when redirecting with apostrophe-soft-redirects

lib/modules/apostrophe-doc-type-manager/public/js/chooser.js, lib/modules/apostrophe-doc-type-manager/views/chooserChoices.html, lib/modules/apostrophe-global/index.js, lib/modules/apostrophe-images/views/chooserChoices.html, lib/modules/apostrophe-pieces/views/managerModalBase.html, lib/modules/apostrophe-ui/public/css/global/type.less, test/global.js
Kinda guess at how you would 'validate' good choices vs hacked in choices, that could probably be more elegant, lmk.
but whoah Nelly
=> sortable choosers roughed in

lib/modules/apostrophe-templates/views/outerLayoutBase.html
Hey guys,
Just needed a new block to add some custom data inside the html tag (personal need: open graph)
Tell me if it's ok for you and if `extraHtml` is enough relevant 👍 
Thank you
=> new block for adding content/data in the html tag

lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-areas/public/js/user.js, lib/modules/apostrophe-confirm/public/js/user.js, lib/modules/apostrophe-modal/public/js/modal.js, lib/modules/apostrophe-ui/public/css/components/context-menu.less
Includes fix for the context menu getting in the way of the add content menu. That fix is pretty blunt, it hides the context menu until the add content menu is dismissed. Without this tests don't pass (and usability on small screens is genuinely busted).
=> Accommodations for reliable functional browser testing

lib/modules/apostrophe-pieces/views/managerModalBase.html
=> Reverts instructions for manager modal

lib/modules/apostrophe-pieces/public/js/editor-modal.js
This is an update to a prior already merged PR, attention @boutell.
=> Improve check for current page is piece being deleted

lib/modules/apostrophe-polymorphic-manager/index.js
=> Require declared dependency `@sailshq/lodash`

lib/modules/apostrophe-search/index.js, lib/modules/apostrophe-search/lib/browser.js, lib/modules/apostrophe-search/public/js/always.js, lib/modules/apostrophe-search/views/suggest.html
There is bc here because some people got the quasi-baked to work for their needs.
=> Search suggestions on 404 page are now fully baked, they were quasi-baked before

lib/modules/apostrophe-docs/lib/cursor.js
Please read https://github.com/apostrophecms/apostrophe/issues/1601 before approving.
=> well that was easy... the implementation, not the performance proofs

CHANGELOG.md
=> svgEnabled is a new option for apostrophe-attachments, not for apostrophe-images

lib/modules/apostrophe-rich-text-widgets/public/js/editor.js
Fixes #1618 by working around ckeditor bug. We should upgrade ckeditor soon.
=> work around bug in ckeditor 4.6.1

lib/modules/apostrophe-files/index.js
Probably needs some work, but wanted to get this in before I forgot.
=> Add _url prop to files

lib/modules/apostrophe-areas/lib/api.js
Reverts apostrophecms/apostrophe#1647
=> Revert "Need to wrap text in a paragraph tag when converting to rich text"

lib/modules/apostrophe-attachments/lib/api.js, lib/modules/apostrophe-images/lib/api.js
building off of PR #1600 returns title too
=> Returns title as part of apos.images.all and apos.images.first

lib/modules/apostrophe-pieces/src/apos/components/ApostrophePiecesInsertModal.vue, lib/modules/apostrophe-schemas/src/apos/components/ApostropheSchemaEditor.vue, lib/modules/apostrophe-schemas/src/apos/components/ApostropheSlugField.vue, lib/modules/apostrophe-schemas/src/apos/components/ApostropheStringField.vue
slug field now uses the mixin, does live enforcement of what is allowed in a slug, does live syncing with the title when appropriate, etc.
=> 3.0 slug field

lib/modules/apostrophe-attachments/index.js, lib/modules/apostrophe-attachments/lib/api.js
Including croped and scaled versions. Useful for migration and mirroring purposes.
=> command line task to list the URLs of all attachments

lib/modules/apostrophe-login/index.js
Returns a promise, so you can `await` it, etc.
=> factored out sendPasswordResetEmail method

lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/js/user.js, lib/modules/apostrophe-schemas/views/email.html, lib/modules/apostrophe-schemas/views/macros.html
Add schema field type email #1254
=> Add schema field type email 

lib/modules/apostrophe-pieces/index.js, lib/modules/apostrophe-pieces/lib/api.js, lib/modules/apostrophe-pieces/lib/routes.js, lib/modules/apostrophe-pieces/public/css/manager.less, lib/modules/apostrophe-pieces/public/js/manager-modal.js, lib/modules/apostrophe-pieces/views/manageHeadings.html, lib/modules/apostrophe-ui/public/css/components/tables.less
Stuart, please style and review. Note that "title" and "updated at" should both be sortable out of the box so it should be simple to review. If your pieces are all generated stuffs, it might be hard to distinguish the default sort from sort by title forwards, but backwards should be pretty obvious.
Thanks!
=> implemented column sort in manage view of pieces

index.js, lib/modules/apostrophe-assets/index.js, lib/modules/apostrophe-module/index.js, lib/modules/apostrophe-push/index.js
See also the following which should have been reviewed but I was in a hurry; this is where it really got interesting:
...
https://github.com/punkave/moog/commits/v1
https://github.com/punkave/moog-require/commits/v1
OK so yeah I should take you through this rather than expecting you to comb through that.
I sent you a meeting request. Thanks!
=> Support for namespaced npm modules, a requirement for private npm modules in apostrophe

CONTRIBUTING.md, README.md, lib/modules/apostrophe-admin-bar/index.js, lib/modules/apostrophe-assets/index.js, lib/modules/apostrophe-attachments/index.js, lib/modules/apostrophe-browser-utils/index.js, lib/modules/apostrophe-custom-pages/index.js, lib/modules/apostrophe-doc-type-manager/index.js, lib/modules/apostrophe-docs/index.js, lib/modules/apostrophe-express/index.js, lib/modules/apostrophe-files-widgets/index.js, lib/modules/apostrophe-files/index.js, lib/modules/apostrophe-groups/index.js, lib/modules/apostrophe-images-widgets/index.js, lib/modules/apostrophe-images/index.js, lib/modules/apostrophe-login/index.js, lib/modules/apostrophe-pages/index.js, lib/modules/apostrophe-pieces-pages/index.js, lib/modules/apostrophe-pieces-widgets/index.js, lib/modules/apostrophe-pieces/index.js, lib/modules/apostrophe-pieces/lib/api.js, lib/modules/apostrophe-pieces/public/js/editor-modal.js, lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/js/user.js, lib/modules/apostrophe-search/index.js, lib/modules/apostrophe-templates/index.js, lib/modules/apostrophe-ui/public/js/ui.js, lib/modules/apostrophe-versions/public/js/user.js, lib/modules/apostrophe-video-fields/index.js, lib/modules/apostrophe-video-widgets/index.js
In gitbook these are all broken
=> Fix all the internal documentation links i could find

lib/modules/apostrophe-groups/index.js
Adds grouping here to quiet the unarranged warning.
=> Arranges basic fields for groups

lib/modules/apostrophe-docs/lib/api.js, lib/modules/apostrophe-docs/lib/cursor.js
Adjustments based on comments in #1900
=> Updates based on PR comments

test/images.js
`assert.equal` is deprecated, hence that change.
=> Converts image tests

lib/modules/apostrophe-schemas/views/fieldset.html, lib/modules/apostrophe-video-widgets/index.js
Clarifying video options for apostrophe-video for end users.
=> Adds help text regarding video options

lib/modules/apostrophe-rich-text-widgets/public/js/editor.js
see comments inline for why we can't fix this entirely so far
re #1875
=> partial resolution, an empty toolbar is better than console errors and a nonfunctional editor

lib/modules/apostrophe-schemas/public/js/user.js
=> fixed bad logic for detecting empty required arrays

lib/modules/apostrophe-notifications/public/css/user.less, lib/modules/apostrophe-notifications/public/js/user.js, lib/modules/apostrophe-notifications/views/notification.html, lib/modules/apostrophe-ui/public/css/global/utils.less
I'm just a backend hacker but I think this came out surprisingly unterrible:
What say you @stuartromanek?
=> ui for closing notifications closes #1870

lib/modules/apostrophe-pages/public/css/user.less
Helps to differentiate from the clickable links in the row.
=> Uses grab cursor on draggable row

lib/modules/apostrophe-users/index.js
This PR solves the issue [#1313](https://github.com/apostrophecms/apostrophe/issues/1313)
=> Apostrohe-users title required

lib/modules/apostrophe-admin-bar/index.js, lib/modules/apostrophe-any-page-manager/index.js, lib/modules/apostrophe-assets/index.js, lib/modules/apostrophe-attachments/index.js, lib/modules/apostrophe-browser-utils/index.js, lib/modules/apostrophe-custom-pages/index.js, lib/modules/apostrophe-doc-type-manager/index.js, lib/modules/apostrophe-docs/index.js, lib/modules/apostrophe-express/index.js, lib/modules/apostrophe-files-widgets/index.js, lib/modules/apostrophe-files/index.js, lib/modules/apostrophe-groups/index.js, lib/modules/apostrophe-images-widgets/index.js, lib/modules/apostrophe-images/index.js, lib/modules/apostrophe-login/index.js, lib/modules/apostrophe-pages/index.js, lib/modules/apostrophe-pieces-pages/index.js, lib/modules/apostrophe-pieces-widgets/index.js, lib/modules/apostrophe-pieces/index.js, lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-search/index.js, lib/modules/apostrophe-templates/index.js, lib/modules/apostrophe-video-fields/index.js, lib/modules/apostrophe-video-widgets/index.js, lib/modules/apostrophe-widgets/index.js
@boutell - here are the updates for the links. If I missed any, they should be caught by the redirects.
=> updated links for new documentation locations and to fix existing errors

lib/modules/apostrophe-express/index.js, lib/modules/apostrophe-utils/index.js, lib/modules/apostrophe-utils/lib/api.js
reinforce blessings using mongo $addToSet which is not subject to race conditions
Closes #2072
=> Ding-dong, "not blessed" is dead

lib/modules/apostrophe-pages/public/js/reorganize.js, lib/modules/apostrophe-users/index.js
cc @paulisloud this should do the trick for you, but I don't have write access in your environment this morning, so please apply this change yourself and let me know.
=> Fast add user task

lib/modules/apostrophe-attachments/lib/api.js
=> Updates an image object's orientation properties based on crop

lib/modules/apostrophe-schemas/views/macros.html
=> Adds help text to the array field macro

lib/modules/apostrophe-express/index.js, lib/modules/apostrophe-login/index.js, lib/modules/apostrophe-login/views/passwordReset.html, lib/modules/apostrophe-login/views/passwordResetRequest.html
add option loginUrl to change the default login url.
=> add option loginUrl

CHANGELOG.md, lib/modules/apostrophe-users/index.js
update CHANGELOG and inline doc for apostrophe-users option "disableInactiveAccounts"
=> update CHANGELOG and inline doc for apostrophe-users option "disableInactiveAccounts"

lib/modules/apostrophe-login/index.js
=> fix disableInactiveAccounts

lib/modules/apostrophe-modal/public/js/modal.js
=> include the position offset in the calculation of what is fillable

lib/modules/apostrophe-schemas/index.js
Alternate implementation of #2170 to allow for null date values. Currently you can't leave date fields empty, or else they'll submit the current date.
=> Allows for empty date fields

lib/modules/apostrophe-assets/index.js
=> Adds warning for projects not using jQuery 3

lib/modules/apostrophe-schemas/public/js/user.js
=> Fixes 0 label for arrays

lib/modules/apostrophe-images/lib/api.js
=> restore thumbnail manage view of apostrophe images pieces, closes #2185

lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-db/index.js, lib/modules/apostrophe-pages/lib/pagesCursor.js, lib/modules/apostrophe-tasks/index.js, lib/modules/apostrophe-templates/index.js, lib/modules/apostrophe-ui/public/js/context.js, lib/modules/apostrophe-versions/lib/api.js
These signature comments all generate into documentation, so they should be cleaned up.
=> Clears signatures that generate to docs

lib/modules/@apostrophecms/notifications/index.js, lib/modules/@apostrophecms/schemas/index.js
https://apostrophecms.atlassian.net/browse/A30U-302
=> Notifications: REST API routes

defaults.js, lib/modules/@apostrophecms/files-tags/index.js, lib/modules/@apostrophecms/files/index.js, lib/modules/@apostrophecms/images-tags/index.js, lib/modules/@apostrophecms/images/index.js, lib/modules/@apostrophecms/schemas/index.js, test/admin-bar.js
https://apostrophecms.atlassian.net/browse/A30U-115
=> 3.0 media tags

lib/modules/apostrophe-docs/lib/api.js
This has been hanging around. I think it was meant to be merged a while back.
=> Deletes confusing documentation code block

lib/modules/@apostrophecms/storybook/template/.storybook/main.tmpl.js, lib/modules/@apostrophecms/storybook/template/.storybook/preview.tmpl.js
These tripped me up as I was trying to "tidy up" the files and then broke the build.
=> Adds build comments

lib/modules/@apostrophecms/storybook/src/apos/scss/storybook.scss, lib/modules/@apostrophecms/storybook/template/.storybook/webpack.js, lib/modules/@apostrophecms/ui/src/apos/scss/storybook.scss
The storybook styles were not included in the Storybook build.
=> Updates storybook SCSS with dark mode styles

modules/@apostrophecms/asset/index.js
=> Tolerate missing data-apos attribute again

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, test/pages-public-api.js, test/pages-rest.js, test/pages.js, test/pieces-public-api.js, test/pieces.js
I also fixed several bugs that were preventing projections from actually projecting anything, and a bug that revealed itself when projections started working.
=> For security, public REST APIs are not available unless a projection is set for them

CHANGELOG.md, lib/modules/apostrophe-schemas/views/macros.html, package.json
=> Removes superfluous macro

modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue
Fixes a context menu bug: https://apostrophecms.atlassian.net/browse/A30U-319
=> Fixes context menus staying open

CHANGELOG.md, lib/modules/apostrophe-docs/lib/cursor.js, package.json, test/docs.js
Fixes https://github.com/apostrophecms/apostrophe-workflow/issues/326
=> mongo 4.4 raised the pickiness bar, lower it again for bc

modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue, modules/@apostrophecms/login/ui/apos/scss/login.scss, modules/@apostrophecms/schema/ui/apos/components/AposInputPassword.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue, modules/@apostrophecms/ui/ui/apos/scss/_inputs.scss
- https://apostrophecms.atlassian.net/browse/A30U-334: Login Password Field not a password field
- https://apostrophecms.atlassian.net/browse/A30U-338: Login page does not submit with the enter key
- https://apostrophecms.atlassian.net/browse/A30U-335: Login Remove margin top from Button
=> Login fixes

modules/@apostrophecms/notification/ui/apos/components/AposNotification.stories.js, modules/@apostrophecms/notification/ui/apos/components/AposNotification.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.stories.js
This had not been moved to the correct directory.
=> Moves notifications story

modules/@apostrophecms/schema/ui/apos/components/AposInputBoolean.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-354
=> Switches boolean fields to radio inputs

modules/@apostrophecms/doc-type/ui/apos/components/AposDocHistory.vue, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-350
=> Updates title and adds a11y title

modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposFilterMenu.stories.js, modules/@apostrophecms/ui/ui/apos/components/AposFilterMenu.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-295
=> Adds filter labels for piece manager

modules/@apostrophecms/modal/ui/apos/components/AposModalToolbar.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManagerToolbar.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue, modules/@apostrophecms/ui/ui/apos/components/AposPager.stories.js, modules/@apostrophecms/ui/ui/apos/components/AposPager.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-126
=> Adds pagination to piece manager

CHANGELOG.md, lib/modules/apostrophe-express/index.js, package.json
Adds an option to apos-express to make resolving https://github.com/apostrophecms/apostrophe-workflow/issues/126 easier.
=> Adds the trustProxy option to apos-express

modules/@apostrophecms/area/ui/apos/components/AposAreaMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue
=> button modifiers to accomodate area menu context menu

modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputSelect.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-372 with the recent published filter update.
=> Fixes Both filter and select input

modules/@apostrophecms/schema/ui/apos/components/AposInputJoin.vue
- On A3-demo, create an article and add joins for products.
- Re-open this article after save, check it is displayed correctly in the slat list.
- Modify the joins by adding a new one, and check again it is displayed correctly again.
=> Joins: fix creation and modification

modules/@apostrophecms/image/index.js, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue, modules/@apostrophecms/storybook/template/public/lib/mock-images.js, package.json
Fixes the media manager to get actual image paths to display images.
=> Updates image getAll to include img paths

modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue
Resolves: https://apostrophecms.atlassian.net/browse/A30U-390, "As a user, I can see placeholder images prepended to the top of the media library as they are uploaded"
=> Adds sized placeholder images while image is uploading

CHANGELOG.md, modules/@apostrophecms/any-page-type/index.js, modules/@apostrophecms/area/index.js, modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/file/index.js, modules/@apostrophecms/global/index.js, modules/@apostrophecms/group/index.js, modules/@apostrophecms/image/index.js, modules/@apostrophecms/modal/ui/apos/components/AposModalLip.vue, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-page-type/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/lib/joinr.js, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/search/index.js, modules/@apostrophecms/storybook/template/public/mocks.js, modules/@apostrophecms/user/index.js, modules/@apostrophecms/util/index.js, modules/@apostrophecms/version/index.js, modules/@apostrophecms/widget-type/index.js, test/docs-http.js, test/docs.js, test/pieces.js, test/schemaBuilders.js, test/schemas.js, test/versions.js
Title says it all. Phew.
See also a3-demo PR, which requires this PR.
=> Rename joins to relationships

modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue
Fixes regressions from #2372.
These might not be the best ways, but uploading breaks without them.
=> Fixes uploader regressions

modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/ui/apos/components/AposInputString.vue, modules/@apostrophecms/ui/ui/apos/scss/_inputs.scss
- Backend validation
- Frontend style
- In a3-demo, add this to `product/index.js`:
```js
// in `fields/add object`
email: {
type: 'email'
}
```
- `npm run dev`
- go to a product or create one, and try to add a wrong email address, and then a valid one
=> Email field

DEVELOPMENT.md, modules/@apostrophecms/notification/ui/apos/apps/ApostropheNotification.js
Clarifies the standard rule for scoping component styles.
CC @falkodev @gregvanbrug @breyell
=> Adds development note about scoped styles

lib/modules/apostrophe-attachments/public/js/user.js
See description here: https://gitlab-dcadcx.michelin.net/pa/apostrophe-enhancements/-/issues/1023
=> The "View file" button not return the original file in the "Edit file" modal

modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue
Resolves
- https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?assignee=5ddbce7e47baa50cfd05eed2&selectedIssue=A30U-456
- https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?assignee=5ddbce7e47baa50cfd05eed2&selectedIssue=A30U-442
=> Relationship editor: customize modal

modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue
https://apostrophecms.atlassian.net/browse/A30U-439
=> Fixes the height of the media library drop zone

modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalLip.vue, modules/@apostrophecms/ui/ui/apos/scss/mixins/_responsive.scss
Fixes the funky right rail lip. Width didn't match the right rail. https://apostrophecms.atlassian.net/browse/A30U-438
💋
=> Ties modal lip width to right rail width

modules/@apostrophecms/notification/ui/apos/components/AposNotification.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_theme.scss
https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?selectedIssue=A30U-420
=> adds inverse text, applies theme level notification colors

modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue
https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?selectedIssue=A30U-452
http://localhost:9001/?path=/story/input-attachment--attachment-input
=> lil bit darker

modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue
https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?selectedIssue=A30U-450
also pad size line height
=> color remove icon when slat is engaged

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.stories.js, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js
Resolves https://apostrophecms.atlassian.net/browse/A30U-573: As a user I see title/slug synchronization in the media editor the same as in the regular doc editor
Prepares us to share more functionality between editor components.
=> Fixes AposDocEditor story

CHANGELOG.md, package.json
This was added after the hotfix release.
=> Moves changelog entry to new version

modules/@apostrophecms/asset/lib/webpack.config.js, modules/@apostrophecms/modal/ui/apos/apps/AposModals.js, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/modal/ui/apos/components/TheAposModals.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, package.json
Other apps will need to be set up separately.
=> Sets up portal-vue and uses it for modals app.

modules/@apostrophecms/image/index.js
resolves https://apostrophecms.atlassian.net/browse/A30U-179, primarily adding an explicit alt text field.
=> adds alt text field to images

modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue
Controversy...
Resolves https://apostrophecms.atlassian.net/browse/A30U-403, "As a user, I can download an image in the schema preview"
=> Allows AposButton to be an anchor and adds download link

CHANGELOG.md, lib/modules/apostrophe-groups/index.js, lib/modules/apostrophe-pieces/index.js, lib/modules/apostrophe-pieces/lib/api.js, lib/modules/apostrophe-users/index.js
=> Remove published columns in apostrophe-users and apostrophe-groups

modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue
=> Updates button label

CHANGELOG.md, lib/modules/apostrophe-pieces/index.js, lib/modules/apostrophe-pieces/lib/api.js
Following the #1365 issue, don't you think that type should be considered as a forbbiden field for apostrophe-pieces.
=> Check that schema field does not contain any forbidden field

modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
* Detect changes from original properly on cancel
* Trigger validation properly on save
=> Widget editor fixes

modules/@apostrophecms/express/index.js
Avoid race conditions by setting resave: false. Since we are using the latest connect-mongo, which supports "touch" operations that do not alter the session data but just refresh the expiration time, we can do this right in 3.x. No need for the crazy "durable sessions" and "read-only session just for this request" hacks in 2.x. Hugs to Past Tom for leaving a trail of bread crumbs next to those hacks reminding us to do it this way instead in 3.x.
=> more reliable and performant session storage ("login randomly fails to let you access pieces sometimes, feels bad")

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarUser.vue, modules/@apostrophecms/admin-bar/ui/apos/components/data.js, modules/@apostrophecms/login/index.js, modules/@apostrophecms/ui/ui/apos/components/AposAvatar.vue
I'm choosing among the gradients Stu provided via a little math on the _id, which is fun, but of course there's no guarantee two users of interest won't happen to have the same one.
The "My Profile" and "Log Out" buttons here are hooked up now, so I removed "Log Out" from the regular admin bar.
The context menu looks a little weird here, the pointer at top kinda misses the mark, Stu maybe there's a way to adjust that?
There might be a better way to do the vertical centering of the initials here.
=> Avatar menu works (correct PR this time with no extraneous guff)

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
=> Labels on top, not inside

modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue
Aligns the quiet buttons in the media manager
=> Creates vertical alignment on the quiet buttons in the media manager

modules/@apostrophecms/rich-text-widget/index.js
Resolves https://apostrophecms.atlassian.net/browse/A30U-604?focusedCommentId=13476,
1. Remove backwards/forwards buttons
2. Remove HR
3. Remove redundant dividers
4. Remove code block
=> Reduces default rte options

modules/@apostrophecms/file-tag/index.js, modules/@apostrophecms/file/index.js, modules/@apostrophecms/image-tag/index.js, modules/@apostrophecms/image/index.js, modules/@apostrophecms/user/index.js
Removes low level piece types from the quick create menu.
=> Disables quickCreate for images, files, and users

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-674, "Remove contextual widget redundancies"
=> Removes editing property from AposAreaEditor

modules/@apostrophecms/area/index.js
… code in the fromRichText and fromPlaintext methods
=> Area-from-text fixes (for the blurb migration)

modules/@apostrophecms/user/index.js, package.json
=> 3.0: prompt → prompts (#1)

modules/@apostrophecms/admin-bar/index.js, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/doc/index.js
Satisfies https://apostrophecms.atlassian.net/browse/A30U-623?atlOrigin=eyJpIjoiZGQzNWQ5ZjdmN2RlNGNkYjk2OGYwNGViZDQ1ZWM4ZGIiLCJwIjoiaiJ9
=> last saved timestamp + author displayed in admin UI

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue
Cleaning up some debris from my recent prs
=> better empty color pickers, no More menu for New docs

CHANGELOG.md
This was confusing to me in a release that does have code changes. I think it's referring to that PR or commit, but it made my dog turn her head sideways.
=> Remove potentially confusing changelog line

modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/ui/ui/apos/components/AposTagList.vue, modules/@apostrophecms/ui/ui/apos/components/AposTagListItem.vue
only filter a single tag at a time in media lib, remove broken transitions
satisfies https://apostrophecms.atlassian.net/browse/A30U-577?atlOrigin=eyJpIjoiYjE4NmYzZTExMGMyNDBhMDlhYzZiMTRlZThjMGZkMTAiLCJwIjoiaiJ9
=> media lib: single tag filter

README.md
The little arrow thing isn't really doing anything for us.
=> Remove accordion

modules/@apostrophecms/ui/ui/apos/components/AposContextMenuTip.vue
satisfies https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?assignee=5d9f805f30387c0dbe48415e&selectedIssue=A30U-911
=> Tighter scoping for context menu tip position that allows for dynamic repositioning of the menu based on scroll

modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue
https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4
This causing flashing in Safari and is not an intended experience anyway.
requesting Tommy 'lock the page' Boutell for the official blessing
=> do not block page when relationship autocomplete is searching

modules/@apostrophecms/video-widget/ui/public/video.js
https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?assignee=5d9f805f30387c0dbe48415e&selectedIssue=A30U-852
- add window resize handler when we size video
- move video widget player player to `video-widget` module
=> responsive video widget

modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue
Adds the html help option to the input wrapper
=> adds htmlHelp to the input wrapper

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/busy/ui/apos/components/TheAposBusy.vue, modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue, modules/@apostrophecms/modal/ui/apos/components/TheAposModals.vue, modules/@apostrophecms/notification/ui/apos/components/TheAposNotifications.vue, modules/@apostrophecms/template/views/outerLayoutBase.html, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuItem.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_normalize.scss, modules/@apostrophecms/ui/ui/apos/scss/global/import-all.scss, package.json
I come to bury normalize, not to praise it.
It was doing too much. Scoping would be going outside it's purpose. We'll likely find some more minor regressions to fix, but we can fix those more surgically.
=> Replaces normalize

.gitignore, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputString.vue
A few input bits I found while writing docs.
=> Fixes min/max input issues

CHANGELOG.md, lib/modules/apostrophe-tags/lib/api.js
=> pass the entire tag piece to be updated

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputColor.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_inputs.scss
This addresses the color leakage I found in core.
=> Color leaks in core

lib/moog.js, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/ui/apos/components/AposArrayEditor.vue, modules/@apostrophecms/ui/ui/apos/components/AposTree.vue, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue, package.json
Updates klona to 2.x. Fewer files changed than I expected, to be honest.
=> Updates the klona major version

CHANGELOG.md, modules/@apostrophecms/widget-type/index.js
=> Infers the widget label as we do with pieces

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalTabs.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue
=> wip remove splitting

modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue
Separate ticket, separate PR, but it merges to the first one so they should be reviewed in order.
=> Media advisory locks

modules/@apostrophecms/piece-page-type/index.js
Fixes a typo in the piece page type module.
=> Fixes typo in the piece page module

modules/@apostrophecms/area/ui/apos/components/AposAreaMenu.vue
Caught some leftover methods from my refactor.
=> Dead code removal

modules/@apostrophecms/doc-type/index.js
This is related to PRO-985 but that might not be the whole story, see ticket.
=> choices for a filter should ignore the setting of that filter

modules/@apostrophecms/widget-type/ui/apos/mixins/AposWidgetMixin.js
=> fixes bug where images, other relationships do not appear in the editor

modules/@apostrophecms/modal/ui/apos/components/AposModal.vue
https://linear.app/apostrophecms/issue/PRO-1023/files-regression-in-the-buttons-menu
=> PRO-1023 3/fix modal primary spacing

modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue
https://linear.app/apostrophecms/issue/PRO-1024/page-manager-new-page-not-following-patterns-as-other-modals
Manager primary button UI spacing fixed in another castle.
=> PRO-1024 3/fix pages manager buttons

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
https://linear.app/apostrophecms/issue/PRO-1025/nested-widgets-wrapping-in-the-menu
=> PRO-1025 3/fix area breadcrumb wrapping

modules/@apostrophecms/http/index.js
This is as much for devs like me to not try to delete it later.
=> PRO-1000 Adds note clarifying addError method use.

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
Fixes:
* PRO-1063 "when I trash a page, it doesn't show up in the trash"
* PRO-1059 "free up 'slugs' once they're trashed"
=> no trash buttons for pages

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/page/index.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue
If the context document winds up in the trash, or the current page (not always the same thing) winds up in the trash, redirect home.
=> PRO-1057 flee if in trash

CHANGELOG.md, package.json
Updates the version and changelog for the new release.
=> Bumps version to 2.117.0

CHANGELOG.md, package.json
* Conditional fields (`if`) and the "following values" mechanism now work properly in array item fields.
* When editing "Page Settings" or a piece, the "publish" button should not be clickable if there are errors.
=> point release: 3.0.0-alpha.6.1

CHANGELOG.md, lib/modules/apostrophe-schemas/public/js/user.js
field.idField always should be empty for a joinByArray
=> deleted unnecesary assignation of choices

CHANGELOG.md
=> Adds changelog credit

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarMenu.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarUser.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextModeAndSettings.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextUndoRedo.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposSavingIndicator.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue
Also the tray (for palette toggle) needs to be styled.
=> PRO-164 refactor of admin bar, also includes PRO-1002

modules/@apostrophecms/rich-text-widget/index.js
Updates the code comment since there is no more template configuration for RTE.
=> Updates comment for toolbar to sanitize-html

modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue
This will throw a bunch of console errors as you type, that is an unrelated bug which I just fixed in a different PR, the search will work.
I also cleaned up a bunch of inaccurate `emits` sections.
=> PRO-1121 search in media

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarUser.vue
I'm done with the current sprint, so I'm working on the next one and targeting the beta 1 branch here to avoid any conflict with landing the last alpha smoothly this week.
=> PRO-383 remove profiles

CHANGELOG.md, modules/@apostrophecms/html-widget/views/widget.html, modules/@apostrophecms/image-widget/views/widget.html, modules/@apostrophecms/rich-text-widget/views/widget.html, modules/@apostrophecms/video-widget/views/widget.html, test/areas.js
Supports the option (to be documented) to set the widget class name on the area as well as the widget module. (blessed by @localghost443)
=> Allows area level widget class setting

CHANGELOG.md, package.json
Updates the version number and changelog for tomorrow's release.
=> Updates version number

modules/@apostrophecms/attachment/index.js, test/attachments.js
Fixes a bug where the response to uploading an image didn't include its URL.
=> PRO-171 Removes extra object kloning in all method

modules/@apostrophecms/pager/views/macros.html
Removes a comment outdated by #2651
=> Removes slanderous comment

modules/@apostrophecms/page/index.js
=> PRO-1173 the second chance logic was confused by the way req.params changes due to the dispatch feature

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaUploader.vue, modules/@apostrophecms/notification/ui/apos/components/AposNotification.vue, modules/@apostrophecms/notification/ui/apos/components/TheAposNotifications.vue, modules/@apostrophecms/notification/ui/apos/scss/notification.scss, modules/@apostrophecms/ui/ui/apos/components/AposIndicator.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_theme.scss
technically part of [PRO-1086](https://linear.app/apostrophecms/issue/PRO-1086/media-library-lip) although that issue has changed over time.
This PR:
- Changes the position of notification to be from the bottom right corner to bottom center, unblocking some apostrophe UI
- Removes the initial Uploading .. notification from the media manager and puts the final upload count into the confirmation notification
- various style updates to notification UI itself
=> PRO-1086 3/notification position etc

CHANGELOG.md, modules/@apostrophecms/admin-bar/index.js, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/user/index.js
This is ready for review after PRO-1161, on which it is based. Please go there first.
=> PRO-366 admin and context bar permissions

modules/@apostrophecms/notification/ui/apos/components/AposNotification.vue
long boys get a softer radius, but let'em live, let'em work
https://linear.app/apostrophecms/issue/PRO-1165/notification-messages-should-not-be-truncated
=> PRO-1165 3/longer notification length

modules/@apostrophecms/permission/ui/apos/components/AposInputRole.vue
400 error at startup of editor when editing a user is fixed
Bug was never released, so no changelog entry
This was never fatal but it was noisy
=> PRO-1188 400 error when editing a user

modules/@apostrophecms/piece-type/index.js
No changelog because this never shipped (contributors are new).
=> PRO-1191 contributors were seeing discard draft at inappropriate times

CHANGELOG.md, modules/@apostrophecms/admin-bar/index.js, modules/@apostrophecms/asset/lib/globalIcons.js, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/modal/ui/apos/apps/AposModals.js, modules/@apostrophecms/modal/ui/apos/components/AposModalConfirm.vue, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/ui/ui/apos/mixins/AposArchiveMixin.js, modules/@apostrophecms/ui/ui/apos/mixins/AposPublishMixin.js
https://linear.app/apostrophecms/issue/PRO-1144/implement-the-archive-confirmation-modal
designs: https://www.sketch.com/s/1663b37a-402f-4441-9c48-2e907707bf32/p/pages-organize
=> PRO-1144 archive choices

modules/@apostrophecms/permission/index.js, modules/@apostrophecms/permission/ui/apos/components/AposInputRole.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_tooltips.scss, modules/@apostrophecms/ui/ui/apos/scss/mixins/_theme_mixins.scss
https://linear.app/apostrophecms/issue/PRO-1171/roles-ui-fix-it-lol
fix it, lol
=> PRO-1171 3/permissions grid UI

CHANGELOG.md, modules/@apostrophecms/pager/views/macros.html, modules/@apostrophecms/template/index.js
Also cleaned up superfluous append=1 parameter.
I know replacing the query parameter by hand is a lot, but I'm doing it rather than fully parsing the URL because this is needed on every page load.
=> Fixed pager links when logged in

modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js
Contributors had no access to the plus menu, fixed.
=> contributors plus menu

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue, modules/@apostrophecms/modal/ui/apos/components/AposDocsManagerToolbar.vue, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuItem.vue
https://linear.app/apostrophecms/issue/PRO-1204/archive-filter
=> PRO-1204 Archive/Published switcher for Page Manager

modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
Fixes a couple of bugs from #2950
=> Fixes bugs

modules/@apostrophecms/ui/ui/apos/components/AposCellContextMenu.vue
No changelog because contribs are new in this release.
=> PRO-1229 contributors can delete drafts via the kebab menu

CHANGELOG.md, modules/@apostrophecms/express/index.js
Just couldn't take it another day
=> PRO-1040: retry once on EADDRINUSE in a dev environment

modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
`this.new()` -> `this.create()` at some point and broke this
=> fix new shortcut

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/ui/ui/apos/mixins/AposPublishMixin.js
New bug never published, so changelog entry not needed.
=> fix publish parents

modules/@apostrophecms/doc-type/ui/apos/components/AposDocMoreMenu.vue
https://linear.app/apostrophecms/issue/PRO-1275/archive-restore-from-archive-should-read-restore
=> pro-1275 restore from archive -> restore

modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue
https://linear.app/apostrophecms/issue/PRO-1251/the-archive-itself-has-an-archive-label
https://linear.app/apostrophecms/issue/PRO-1252/archive-remove-labels
=> PRO-1251 PRO-1252 Remove labels from Archive, Remove archive node

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextModeAndSettings.vue
All three of the below tickets are in this PR 🤞 😵
=> PRO-1267 PRO-1265 PRO-1266 language updates for saving

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/image/index.js
https://linear.app/apostrophecms/issue/PRO-1253/visibility-field
=> PRO-1253 Move Visibility to util rail for most, remove from image schema + filters

modules/@apostrophecms/ui/ui/apos/scss/global/_tables.scss
https://linear.app/apostrophecms/issue/PRO-1260/last-edited-column-appears-clickable
=> PRO-1260 Remove hover pointers on table fields and labels

.circleci/config.yml, modules/@apostrophecms/doc-type/index.js
We need to be running CI tests on Node 14 in addition to 12.
=> Adds a2 Node 14 test jobs

modules/@apostrophecms/file/index.js
=> remove Visibility field + filter from Files

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue
https://linear.app/apostrophecms/issue/PRO-1259/context-bar-update-draft-pill-to-nu-style
=> PRO-1259 update Draft label style

modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
=> PRO-1281 drop labels header in archive view

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/ui/ui/apos/mixins/AposArchiveMixin.js
=> PRO-1261 PRO-1272 contributors restoring

modules/@apostrophecms/ui/ui/apos/components/AposCellLabels.vue
this label is not concerned with contributor action, only that edits have been made to a previously published document
=> PRO-1282 fix pending updates label again

modules/@apostrophecms/submitted-draft/index.js
Thanks for contributing!### ###
=> PRO-1295 date cell -> relative time cell

CHANGELOG.md, package.json
Version update for tomorrow's release.
=> Updates version to 2.118.0

CHANGELOG.md, modules/@apostrophecms/util/ui/public/2-http.js
Found this while reviewing your docs.
=> restored ability to parse objects and arrays properly

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
=> center those buttons gd

CHANGELOG.md, modules/@apostrophecms/template/lib/custom-tags/fragment.js, modules/@apostrophecms/template/lib/custom-tags/render.js, test/modules/fragment-all/views/fragment.html, test/modules/fragment-all/views/page.html, test/templates.js
=> Fix skipping of positional fragment arguments

modules/@apostrophecms/template/views/outerLayoutBase.html
=> PRO-1313 Removes refreshable class

modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
ModifiedMixin is looking for the solution, not a function. This gets the widget editor in line with the doc editor.
=> PRO-1389 moves widget editor isModified to computed

modules/@apostrophecms/any-page-type/index.js
Removes the duplicate quickCreate jawn
=> PRO-1384 prevents a duplicate page item in plus menu

modules/@apostrophecms/schema/ui/apos/components/AposInputRadio.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputSelect.vue
Also gets the select and radio validation in sync since they work the same way.
=> PRO-1371 Allows an empty radio input

modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlatList.vue
Makes sure there are actual relationship fields there before we show the context menu.
=> PRO-1379 no relationship

modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
=> PRO-1385 PRO-1245 Fixes slug troubles.

CHANGELOG.md, lib/modules/apostrophe-oembed/index.js, lib/modules/apostrophe-oembed/views/openGraphEmbed.html, lib/modules/apostrophe-users/index.js
Replaces the last uses of whitelist in core code documentation.
=> Replaces uses of whitelist

CHANGELOG.md, package.json
Regression tests have been passed.
=> release hotfix for CSRF vulnerability

modules/@apostrophecms/user/index.js
Very simple text fix off the back of trying the demo.
`Dislay` ➡️ `Display`
=> Fix typo in Edit User interface

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/area/ui/apos/components/AposWidgetControls.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRange.vue, modules/@apostrophecms/submitted-draft/ui/apos/components/AposSubmittedDraftIcon.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue, modules/@apostrophecms/ui/ui/apos/components/AposButtonGroup.vue, modules/@apostrophecms/ui/ui/apos/components/AposPagerDots.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue, modules/@apostrophecms/ui/ui/apos/components/AposTagListItem.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_scrollbars.scss, modules/@apostrophecms/ui/ui/apos/scss/global/_theme.scss, modules/@apostrophecms/ui/ui/apos/scss/mixins/_theme_mixins.scss, modules/@apostrophecms/ui/ui/apos/scss/mixins/_type_mixins.scss
- widgets at all depths have the same visual look
- breadcrumbs are now theme inverted along with widget controls
- secondary theme color removed
=> PRO-1582 normalize widget chrome

LICENSE.md
It identified the previous organizational maintainers.
=> PRO-1649 Updates license copyright

README.md
Previously referencing the old 3.0 branch
=> Fixes README badge

CHANGELOG.md, package.json
=> 3.1.0 release

modules/@apostrophecms/util/index.js
Some house keeping to get rid of some `/n` line breaks.
=> Reformats warning message for easier reading

CODE_OF_CONDUCT.md
update the code of conduct email address. It was out of date.
=> Updates the CoC email address

modules/@apostrophecms/area/index.js, modules/@apostrophecms/area/lib/custom-tags/widget.js, modules/@apostrophecms/module/index.js, modules/@apostrophecms/template/index.js, modules/@apostrophecms/util/ui/src/util.js
More cleanup of the singleton area from A2.
=> Removes singleton tag refs

CHANGELOG.md, lib/modules/apostrophe-login/views/login-totp.html
=> Removes stray error log

CONTRIBUTING.md
I copied the A2 contrib file. There a few small updates. I changed the Mongo version recommendations to 3 and 4.
=> PRO-1795 Updates contribution file

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/index.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapButton.vue
Resolves a bug with the text align rich text options.
=> Pro 1807 alignment

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarLocale.vue, modules/@apostrophecms/i18n/index.js
This is a total work in progress right now, getting it on our radar that a branch exists.
=> PRO-1845 locale switcher roughed in, needed for testing of other things

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarLocale.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/i18n/l10n/en.json, modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
To show this works and give Greg a starting point I also created the AposI18nLocalize modal, with no logic or content yet other than passing the doc id to it.
=> Button to open AposI18nLocalize modal

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextModeAndSettings.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue
saw these in my travels, cleans up some old camelcase vue event names
=> cleans up some stray camelcase vue names

modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
also a computed action property to base API calls on
=> PRO-1869 provide entire doc as a prop to AposI18nLocalize

modules/@apostrophecms/asset/lib/globalIcons.js, modules/@apostrophecms/i18n/l10n/en.json, modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
Resolves:
- https://linear.app/apostrophecms/issue/PRO-1825
- https://linear.app/apostrophecms/issue/PRO-1832
Second step of the wizard. Includes UI, filtering, and selecting/de-selecting locales.
=> localize wizard select locales

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarLocale.vue
Resolves:
- https://linear.app/apostrophecms/issue/PRO-1898
Update to locale switcher button style. Also updates the dropdown width to prevent polluting other context menus
=> Pro 1898 dropdown style

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/scss/mixins/_theme_mixins.scss
this prevents unintended project-level style leaking for our type styles
=> PRO-1911 adds color to base type var, all type styles extend this var to receieve benefits

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue
Resolves:
- https://linear.app/apostrophecms/issue/PRO-1905
Adds the current locale name to the modal header.
=> add locale to the modal

CHANGELOG.md, modules/@apostrophecms/i18n/index.js
=> Fixes typos

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarLocale.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarUser.vue, modules/@apostrophecms/ui/ui/apos/lib/i18next.js
Fixes the vue i18n object format
=> Changes phrase object property to key

modules/@apostrophecms/ui/ui/apos/mixins/AposArchiveMixin.js
Including in release because of very-busted appearance (see ticket).
=> PRO-2004 PRO-2005 PRO-2006 missing translation leading to very busted-looking archive confirm prompt

CHANGELOG.md
=> Fixes changelog placement

modules/@apostrophecms/permission/ui/apos/components/AposInputRole.vue
this was left out of the original work done for [PRO-1911](https://linear.app/apostrophecms/issue/PRO-1911/palette-styles-being-applied-in-admin-modals)
=> PRO-1911 set role input headings

CHANGELOG.md, modules/@apostrophecms/db/index.js
Code cleanup, removing an intentionally temporary method.
=> Removes temporary method from db module

.gitignore, CHANGELOG.md, lib/modules/apostrophe-modal/public/js/modal.js
The scoped pieces test does have to be removed, see separate PR.
=> PRO-2057 fixed the regression tests

modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
when locale search input is backspaced to empty that is still a valid search
small regression reported by @agilbert
=> Fix/localization search UI

CHANGELOG.md, modules/@apostrophecms/schema/index.js, test/reverse-relationship.js
=> PRO-1917 fix bug when piece types with multiple relationships are configured in a certain order

CHANGELOG.md
=> Fixes changelog error

CHANGELOG.md
Moving Changelog line to Unreleased section and adding credit.
=> Updates changelog from community PR

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/job/index.js, modules/@apostrophecms/piece-type/index.js, test-lib/util.js, test/job.js
=> PRO-2211 adds job tests

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/i18n/es.json, modules/@apostrophecms/i18n/i18n/pt-BR.json, modules/@apostrophecms/i18n/i18n/sk.json, modules/@apostrophecms/job/index.js, modules/@apostrophecms/notification/index.js, modules/@apostrophecms/notification/ui/apos/components/AposNotification.vue, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
Gets the manager refreshing following a batch action.
=> PRO-2262 batch refresh

CHANGELOG.md, package.json, test/job.js
=> Removes npm audit from tests

modules/@apostrophecms/db/index.js
I've had this sitting around. Likely since some September work on the db module.
=> Fixes for db module inline reference

.eslintrc, CHANGELOG.md, modules/@apostrophecms/job/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputAttachment.vue, modules/@apostrophecms/task/index.js, modules/@apostrophecms/ui/ui/apos/components/AposFile.vue
* Uses total in job instead of array of IDs.
* Creates AposFile.vue component to abstract file dropzone UI.
* Uses AposFile.vue component in AposInputAttachment.vue
* Creates handleUtilityOperation method in AposDocsManager.vue to trigger a new modal or the confirmation modal.
This code has been reviewed already, just resolved two minor conflicts.
=> Pro 2282 pro 2236 import button and modal (#3530)

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js
See changelog for description. Test steps in internal ticket.
closes #3542
=> PRO-2290 fixed (thanks Miro) closes #3542

modules/@apostrophecms/modal/ui/apos/components/AposDocsManagerToolbar.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManagerSelectBox.vue
Nice work on this @ValJed, some minor style and behavior adjustments, notably the Select All box never appears if **all** pieces are displayed on page 1 of the manager
=> Select all adjustments

CHANGELOG.md, modules/@apostrophecms/asset/index.js
=> PRO-2121 PRO-2353 support for overriding Vue components at project level

CHANGELOG.md, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/search/index.js
This resolves two of the issues raised in #3193: piece types not being added to search and the index task errors.
________________________
=> Pro 884 search

CHANGELOG.md, modules/@apostrophecms/schema/index.js
Closes #3586
------------------
=> Applies slug field default values to their slugify options

CHANGELOG.md, modules/@apostrophecms/widget-type/index.js
These methods don't do anything in A3 and are artifacts from A2. They should be removed next go-round.
-------------------
=> Deprecate widget class

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js
Deprecating this query builder per discussion in https://github.com/apostrophecms/a3-docs/pull/160
-------------------
=> Deprecates the addLateCriteria query builer

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/apps/AposAdminBar.js, modules/@apostrophecms/area/ui/apos/apps/AposAreas.js, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/asset/lib/webpack/apos/webpack.config.js, modules/@apostrophecms/asset/lib/webpack/src/webpack.config.js, modules/@apostrophecms/busy/ui/apos/apps/AposBusy.js, modules/@apostrophecms/login/ui/apos/apps/AposLogin.js, modules/@apostrophecms/modal/ui/apos/apps/AposModals.js, modules/@apostrophecms/notification/ui/apos/apps/AposNotification.js
See the PR for the security-headers module for testing details.
=> Part of PRO-2387: supporting changes for content-security-policy

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputCheckboxes.vue
Resolves #3590 
----------------------
=> Fixes required checkbox bug

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js
A small simplification in toCount where we were using Math.floor and an additional step of math to replicate what Math.ceil does.
---------------
=> Simplifies toCount with Math.ceil

CHANGELOG.md, package.json
=> Pin vue click outside element

CHANGELOG.md, package.json
package.json and changelog date only
=> release 3.11.0

CHANGELOG.md, modules/@apostrophecms/express/index.js, modules/@apostrophecms/login/index.js, test/login-requirements.js
Did this as TDD (Test Driven Development for anyone peeping in), feel good about the correctness as a result.
=> PRO-2393 server side of PRO-2392, support for imposing custom login requirements

CHANGELOG.md, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/piece-type/index.js
In doing documentation I found a few comment notes that look to have been copied from elsewhere and not fully updated.
Review the comment updates for accuracy.
=> Fixes inline comment copy errs

CHANGELOG.md, modules/@apostrophecms/module/index.js
Removes unimplemented cascade
N/A
=> remove unimplemented csrfExceptions cascade

CHANGELOG.md, lib/modules/apostrophe-modal/public/css/components/modal-tabs.less, package.json
Closes #3612 
*For example:*
> 2. Open a piece manager modal that contains an area with at least 3 elements
> 3. Click on the area to reveal the dropdown
> 4. The dropdowns bottom part isn't cut off anymore and you don't have to scroll to see the bottom options.
=> Editor modal area options overflowing

modules/@apostrophecms/login/index.js, modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue
A few code cleanup bits I found while working on login requirement features.
Nothing new.
- [n/a] The changelog is updated
- [n/a] Related documentation has been updated
- [n/a] Related tests have been updated
=> Code tidying

lib/modules/apostrophe-modal/views/batch.html
=> fix batch modal translations

CHANGELOG.md
Changelog update and credit.
N/A
- [N/A] Related documentation has been updated
- [N/A] Related tests have been updated
=> changelog for stepanjakl change

CHANGELOG.md, modules/@apostrophecms/page/index.js, test/pages-rest.js
Resolves #3488 #3613
1. create a page or piece (if there's an associated piece page) titled "Dopravná nehoda pri Ilave - Mikšík Jozef"
2. Save that as a draft and try to preview the page. without this change it will trigger a 404 response. With the change it will display as expected.
=> PRO-2202 diacritics

CHANGELOG.md
Moves and updates a community changelog entry.
Review for accuracy.
=> Updates changelog entry for slovak string updates.

CHANGELOG.md, package.json
Release 2.220.9
Release, changelog
=> release 2.220.9

CHANGELOG.md, package.json
Release 3.13.0
N/A
Release (changelog, package.json version)
=> release 3.13.0

CHANGELOG.md, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/page/index.js
* See changelog (fixes bug in in-context editing)
*For example:*
You could sync down `a3-assembly-client-demo` (private project) and verify that you can repeatedly edit nested rich text widgets on-page on the `vivian` site, however this was shipped already to that cloud as a hotfix, so this has already been verified in production by Ashleigh and Alex.
=> PRO-2526 repeated rich text edits should work in the presence of recursive relationships to the page

CHANGELOG.md, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue, modules/@apostrophecms/login/ui/apos/components/TheAposLoginHeader.vue
…
See changelog
Dev QA:
* Add some obvious nonsense to the bottom of your `ui/src/index.js` file, like a pile of obviously buggy punctuation, and run `node app`. You should get a hard stop along with an error message.
* Do the same with `NODE_ENV=production node app @apostrophecms/asset:build`.
=> PRO-2547 handle build error reporting properly, also fix minor nits discovered this way

CHANGELOG.md, package.json
* Release notes and package.json version for 3.16.0 release
* Moved a release note to the right section
* Clarified language in changelog
N/A
=> version bump and adjustment of release notes

CHANGELOG.md, package.json
* Hotfix for bug in cache being released (already reviewed and merged). Also linked to the caching documentation from the changelog for the previous release for the first time.
See previous PR, this is just a release PR
=> hotfix for the cache bug

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/ui/apos/components/AposInputObject.vue, test/areas.js, test/pieces.js
* Support for the object field type, per the design
See pro-2625 branch of `testbed`. The `topic` piece type now has an object field, with a nested sub-object field, in its "fancy fields" tab.
- [separate PR coming] Related documentation has been updated
=> PRO-2625 object fields

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/schema/index.js, test/docs.js
[PRO-2575](https://linear.app/apostrophecms/issue/PRO-2575/as-a-developer-i-can-find-the-documents-that-have-relationships-to-a)
When saving a doc, update its related documents' `relatedReverseIds` field accordingly.
For instance, when adding related topic(s) to an article, we add the article ID to the topic(s)' `relatedReverseIds` field.
This is done by the `updateBacklinks` beforeSave handler.
- Add some related docs to a doc's `relationship` field (for instance, add some topics to an article, if you follow the example from the [doc](https://v3.docs.apostrophecms.org/guide/relationships.html#the-anatomy-of-a-relationship-field))
- Check that for all these related docs, their `relatedReverseIds` field now have the doc ID in the DB
- Removing related docs should also remove the doc ID …
=> implement backlinks of related docs

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/src/webpack.config.js
Fixes es5 webpack error (which reveals an issue with our build after that)
Set the es5: true option for the asset module (in app.js of testbed, since that seems to override the options section of the module)
=> Fix es5 at webpack level

CHANGELOG.md, package.json
Release PR (added links to changelog, set version number).
N/A
=> Release 3.17.0

modules/@apostrophecms/attachment/index.js, test/attachments.js
[PRO-2679](https://linear.app/apostrophecms/issue/PRO-2679/unit-test-and-complete-the-crop-api-route-of-the-attachment-module)
Test for cropping route was already existing. But attachments tests was not passing all the time (like two on 4 tries). I suppose because the uploads was not clean at the end of the test but at start which is not really logical and could pollute next tests
Check that attachments tests are working.
=> Pro 2679 test crop route

CHANGELOG.md, package.json
Release 3.18.0 (previously approved work)
N/A
=> release 3.18.0

CHANGELOG.md, modules/@apostrophecms/asset/index.js, package.json
Merging an already released hotfix back to main so the version number is reflected in the history. The actual code change was previously accepted and merged.
N/A
=> Hotfix 3.18.1 b

modules/@apostrophecms/schema/ui/apos/components/AposInputDateAndTime.vue, modules/@apostrophecms/ui/ui/apos/components/AposToggle.vue
I forgot to rebase #3742 before merging it, hence the new stylelint errors that have to be fixed on `main` (now that stylelint is run in CI).
`npm run lint`
=> fix remaining stylelint errors

CHANGELOG.md, package.json
Release PR. No new code, but please review changelog updates.
Review changelog updates.
=> release 3.19.0 and changelog cleanup / clarification

CHANGELOG.md
Fixed more changelog errors, several 3.19 items were listed under 3.18.1 due to merge goofs
=> more changelog errors

CHANGELOG.md, package.json
=> Release 2.31.0

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/page/index.js, test-lib/util.js, test/pieces.js
Add a share & unshare methods on `@apostrophecms/doc-type` & `@apostrophecms/page` modules
Closes #PRO-2812
1. Run pieces tests `npx mocha test/pieces.js`
=> Pro 2812 share method

modules/@apostrophecms/modal/ui/apos/components/AposModalShareDraft.vue
=> remove duplicated border css property

CHANGELOG.md, package.json
Fixes `SassError: RangeError: Invalid value: Not in inclusive range 0..145: -1` error by upgrading to dart-sass 1.52.3
1. Make sure you are npm linked to that checkout in a3-boilerplate
2. Check out this branch and run `npm install` in your apostrophe folder.
3. `APOS_DEV=1 npm run dev` should work.
=> upgrade to sass 1.52.3

modules/@apostrophecms/modal/ui/apos/components/AposModalShareDraft.vue, modules/@apostrophecms/page/index.js, modules/@apostrophecms/template/index.js
=> generate front-end base url

modules/@apostrophecms/i18n/i18n/es.json, modules/@apostrophecms/i18n/i18n/fr.json, modules/@apostrophecms/i18n/i18n/pt-BR.json, modules/@apostrophecms/i18n/i18n/sk.json
Related to #3741.
Fix bad copy/paste for `es`, `fr` , `pt-BR` and `sk` languages
=> fix takeActionAndCreateNew translation

CHANGELOG.md, package.json
=> Release 2.221.1

lib/locales.js, modules/@apostrophecms/i18n/index.js
Needed for code reuse.
*For example:*
=> extract locales verification into a method

CHANGELOG.md, package.json
Just a release PR, changelog and package.json version numbers only, previously approved work
=> release 2.221.2

CHANGELOG.md, index.js, package.json
*For example:*
This fix is only for Mocha version 10 issue where `findTestModule()` function does not return the appropriate module. It also does have backward compatibility that can run older Mocha …
=> Test module fix for Apostrophe version 2

CHANGELOG.md, package.json
No new code, just undoing premature version change and adding thanks to contributor
N/A
=> Undo version bump

CHANGELOG.md, package.json
=> release 2.222.0

CHANGELOG.md, modules/@apostrophecms/permission/index.js, modules/@apostrophecms/permission/ui/apos/components/AposInputRole.vue, test/permissions.js, test/utils/permissions.js
Implement the `grid` `POST` route of the permission module.
Keep the `GET` route for backward compatibility.
This grid in User edition modal should not be broken:
=> implement permission's grid post route

CHANGELOG.md, package.json
* Release version number
* Changelog update for accuracy
N/A release only
=> release 3.26.0 no code changes

CHANGELOG.md, modules/@apostrophecms/express/index.js
PRO-2832 task to list routes
```
node app @apostrophecms/express:list-routes
```
In assembly projects you'll need `--site=dashboard` or `--site=somesite.localhost`
This is a draft PR only because we're waiting on QA and release this morning before merging more PRs to main.
=> PRO-2832 task to list routes

modules/@apostrophecms/admin-bar/index.js
i
Some comments n the admin-bar module 'index.js` file were factually incorrect or documented non-existent options. THis PR updates those comments. Closes PRO-3028.
*For example:*
1. Open the 'modules->@apostrophecms->admin-bar->index.js` file.
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for …
=> Minor update to code comments for correctness

CHANGELOG.md, package.json, scripts/find-heavy-npm-modules
Tool to find heavy npm modules; moved stylelint to dev deps
Apostrophe still builds and works normally
=> Tool to find heavy npm modules; moved stylelint to dev deps

CHANGELOG.md, package.json
=> release 3.27.0

CHANGELOG.md
Changelog and credit only
N/A (previously reviewed and approved)
=> webp changelog and credit

CHANGELOG.md
Developer credit in changelog, changelog addition
=> thank you note

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
Fix UI bug when creating a document via a relationship.
Closes PRO-3107
Creating a relationship doc should behave as expected.
=> PRO-3107: Check for id on content change

modules/@apostrophecms/module/index.js
Avoid having the length of the string as the result, better to have a boolean.
This method is used internally and is not documented for the public.
*For example:*
=> isShareDraftRequest returns a boolean as expected

CHANGELOG.md, package.json
=> release 3.28.1

CHANGELOG.md, modules/@apostrophecms/piece-page-type/index.js
in order to override the query for the "show" page as "indexQuery" does it for the index page
*For example:*
=> Add "showQuery" in piece-page-type

modules/@apostrophecms/area/index.js, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/rich-text-widget/index.js, modules/@apostrophecms/widget-type/index.js, modules/@apostrophecms/widget-type/ui/apos/components/AposWidget.vue, modules/@apostrophecms/widget-type/ui/apos/mixins/AposWidgetMixin.js
Closes:
- [PRO-3131](https://linear.app/apostrophecms/issue/PRO-3131/as-a-developer-i-can-tell-when-it-is-appropriate-to-display-the)
- [PRO-3149](https://linear.app/apostrophecms/issue/PRO-3149/implement-initialmodal-false-option-for-widget-type-modules)
Add a `apos-placeholder` class to the widgets wrapper div when they have `initialModal: false` set in their options.
Use the class set in the `placeholderClass` option if set, or do not add any class if set to `false`.
When the widget is set actual data, the `widget.aposPlaceholder` is set to `false`, resulting in having the placeholder class removed.
For now, use a simple background as the placeholder:
In testbed:
- add `topic` widget to some area
- add the `initialModal: false` option to `topic-widget`
👉  you should have the …
=> display placeholder for modal-driven widgets

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/area/ui/apos/components/AposAreaContextualMenu.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaMenu.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/schema/lib/addFieldTypes.js, modules/@apostrophecms/schema/ui/apos/components/AposInputArea.vue, modules/@apostrophecms/widget-type/index.js, test/areas.js, test/schemas.js
Adds the widget previews feature.
> 1. 
=> widget previews

CHANGELOG.md, package.json
Review changelog & package.json
=> release 3.29.0

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js, package.json
Hotfix for Node 14 incompatibility introduced in 3.29.0
=> Hotfix 3.29.1 node 14

CHANGELOG.md
This PR makes a small change to the CHANGELOG. It fixes and substitutes for a mistaken merge from desktop to main. 
Text from the PR for the mistaken merge:
The current help message for using the `clear-cache` CLI task of the `cache` module is incorrect. It gives the task name as `clear`, rather than `clear-cache`. Additionally, the message has a property of `help`, which is incorrect. It should be `usage`. This PR corrects these errors . 
Closes PRO-3140.
*For example:*
> 3. Click the "Archive" button on the top left of the manager and …
=> Small changelog alteration do to mistaken merge

CHANGELOG.md, modules/@apostrophecms/express/index.js
env var to log all middleware and routes touched by a URL.
Same general pattern as the existing `APOS_LOG_ALL_QUERIES` and `APOS_TRACE_STARTUP`.
Needs a corresponding docs PR.
```
APOS_LOG_ALL_ROUTES=1 node app
```
Now access something.
=> PRO-3188 env var to log all middleware and routes touched by a URL

CHANGELOG.md, package.json
=> release 3.30.0

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/login/index.js, modules/@apostrophecms/login/ui/apos/components/AposForgotPasswordForm.vue, modules/@apostrophecms/login/ui/apos/components/AposLoginForm.vue, modules/@apostrophecms/login/ui/apos/components/AposResetPasswordForm.vue, modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue
Refactor login UI, add Forgot Password login trigger and screen.
Closes PRO-3252
Verify that the login core feature works as expected and clicking the "Forgot Password" link switches the login form on the login page to the stubbed `AposForgotPasswordForm.vue` component.
=> PRO-3252: Login UI Refactoring

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/mixins/AposAdvisoryLockMixin.js
See changelog
User A starts editing a document, user B attempts to open the document for editing. User A's name should be displayed properly as part of the confirmation prompt for the takeover
=> fix advisory message

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/Default.js, modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/Heading.js, modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/Link.js
[PRO-3189](https://linear.app/apostrophecms/issue/PRO-3189/tiptap-breaking-change-and-duplicates-warnings)
Before:
After:
And added options now taken into account (**TODO: check also for other extensions than Link**)
**TODO**
=> remove tiptap breaking change and duplicates warnings

modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue
PR to your PR to my PR:
* If an item has errors always toggle it open
* If there is no title field open all the items and do not offer a toggle (probably most natural for single field scenarios)
* Make a subfield required and mess about with saving the document without completing it
* Check out the behavior with a single subfield and no titleField configured, see if you like my tweak there
=> Toggle errata

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalBody.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalTabs.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue
- Space saving adjustments for modals / editor modals smaller 'desktop' sizes
=> Responsive editor modal tweaks

modules/@apostrophecms/login/ui/apos/components/AposLoginForm.vue
Fix the incompatibility with custom login requirements
recaptcha and password reset work in same project
=> use created, not mounted, to fix captcha

CHANGELOG.md, package.json
Just a release, note changelog tweaks.
=> release-3.32.0

CONTRIBUTING.md
Adds more info about creating a PR for contributing to core or the documentation. This change is due to problems that a community member was experiencing. Closes PRO-3368
*For example:*
1. Open and read the `CONTRIBUTING.md` file.
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before …
=> add more info about PR contribution

modules/@apostrophecms/piece-type/index.js
**Update icon for publish batch feature in manager modal**
*For example:*
> 3. Click the "Publish" button on the top left of the manager and confirm that the icon is an earth
=> Publish batch icon

CHANGELOG.md, lib/modules/apostrophe-schemas/index.js, test/concurrent-array-joins.js
Fixes DCAD-1191.
New unit tests are provided, you can run `npx mocha test/concurrent-array-joins.js`
Unfortunately I haven't been able to get these tests to fail without the new patch, but it should be possible as the client describes, and they have much higher load than can ever be simulated locally. The tests are still useful to catch any further regression in this area.
=> Fix high concurrency issue with joins

CHANGELOG.md, package.json
=> release 2.223.0

modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
Fixes:
```
apostrophe git:(main) run lint                                                        
> apostrophe@3.33.0 lint
> npm run eslint && npm run i18n && npm run stylelint
> apostrophe@3.33.0 eslint
> eslint --ext .js,.vue .
/Users/etienne/Sites/apostrophecms/apostrophe/modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
122:9  error  Missing semicolon  semi
✖ 1 problem (1 error, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.
```
*For example:*
*(Check at least …
=> fix lint error in vue component

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
See above. This fixes PRO-3413, aka the IC nested areas bug you reported to me.
Verify fix in the IC 3.x migration project.
=> PRO-3413 nested areas work properly with initialModal: false

.github/workflows/main.yml
Tweak the CI config because npm 6 never works with tiptap now
=> use npm 8 with node 14, because tiptap

CHANGELOG.md, package.json
=> release 3.34.0

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
2 tasks added:
- unlocalize: remove duplicated content when localized false
- localize: create localized content from existing documents when localized true
1. Add option `localized: false` to a module 
2. Run the command `node app [moduleName]:unlocalize` and check the DB
3. Switch `localized` to `true` and run `node app  [moduleName]:localize` and check the DB
4. Run ``ode app help  [moduleName]unlocalize` and ``node app help  [moduleName]:unlocalize`
=> Pro 3412 remove duplicated content when localized false

CHANGELOG.md
Adds in a thank-you for the German translation to the CHANGELOG.md file.
*For example:*
1. Check the CHANGELOG.md file.
=> add contribution recognition to changelog

test/concurrent-array-relationships.js
console.log was spamming github actions.
=> this test is unnecessarily LOUD

modules/@apostrophecms/command-menu/index.js
Fix missing error.cause in Node 14
1. Run `npx mocha test/command-menu.js`
=> set error.cause if missing

modules/@apostrophecms/command-menu/ui/apos/apps/AposCommandMenu.js
Prevent error during login
1. Open the login page
2. Check the browser console
3. Login without errors
=> check apos.commandMenu exists before using it

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue
Add clipboard to expanded area widgets
1. Create a widget area with some expanded widgets
2. Add a widget to the area and cut it
3. Check that the first group in the expanded area is the clipboard
=> add clipboard to expanded widgets

modules/@apostrophecms/command-menu/ui/apos/components/AposCommandMenuKey.vue, modules/@apostrophecms/command-menu/ui/apos/components/AposCommandMenuShortcut.vue
- Nudges some UI in the shortcut popover
1. symlink to local project
2. run project
3. use `shift` + `?` to open the popover
=> shortcut ui styling and tweaks

CHANGELOG.md, package.json
=> release 3.35.0

CHANGELOG.md, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/ui/apos/components/AposArrayEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputObject.vue, modules/@apostrophecms/schema/ui/apos/mixins/AposInputChoicesMixin.js
- Passes parent `docId` to dynamic choice functions in schemas (selects, checkboxes, radios) for further inspections
- Properly passes `docId` through array fields and into their child schemas 
=> Pass docid to choices fns

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/module/index.js, test/widgets.js
* Fix a bug that prevented placeholderUrl from being honored in the presence of placeholderImage
* Fix outdated test
* Fix nasty bug I found this morning that sometimes broke editing a widget added via the expanded menu
=> Fix another expanded menu bug, also test issues and an option priority issue

CHANGELOG.md, package.json
=> release 3.37.0

CHANGELOG.md, modules/@apostrophecms/notification/index.js
Emit `beforeSave` for  notification
1. npm test
=> emit beforeSave for notification

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/notification/index.js, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue
Notify `minSize` error after upload
1. Add an image widget to an area with minSize option
```js
'@apostrophecms/image': {
aspectRatio: [ 1, 1 ],
minSize: [ 500, 500 ],
max: 1
```
2. Upload an image that doesn't validate with the minSize requirements
3. Check that you see an error notification 
4. The browser console must not contain any `Invalid XML` error in response to the `POST` `xx/xx/notification` requests.
=> Pro 3463 min size error

CHANGELOG.md, package.json
Release, with changelog updates. No code changes.
=> release 3.38.0

package.json
package.json version number only, the rest is already approved
=> release 3.38.1

modules/@apostrophecms/rich-text-widget/index.js
=> merge did not catch this missing comma error

CHANGELOG.md
Adds an acknowledgement to the changelog for a community contribution
*For example:*
1) Read the CHANGELOG.md file.
=> Adds acknowledgement to changelog

CHANGELOG.md, package.json
=> release 3.39.0 and changelog cleanup

CHANGELOG.md, modules/@apostrophecms/command-menu/index.js
=> Shortcut conflicts not displayed when empty

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposSelect.vue
A `Future Posts` filter with boolean as choices ("Future" choices has a value set to `true`):
before:
after:
=> allow selected value as boolean

CHANGELOG.md, package.json
release + tweaked one line of changelog
=> Release 3.40.0

CHANGELOG.md, package.json
=> correct version

CHANGELOG.md, package.json
For release, no code changes. Hope I did this correctly. 
*For example:*
=> No code change, just patch bump

CHANGELOG.md, modules/@apostrophecms/soft-redirect/index.js, package.json
get url with prefix to look after in `historicalUrls` and return the local version of the doc via `doc._url`
*For example:*
1. Create a new locale
2. Go into that locale and create a page
3. Rename that page and save
4. Go to the previous URL of the page and wonder why you are not redirected.
=> Bugfix: locale soft-redirect

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/area/ui/apos/apps/AposAreas.js, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue
[PRO-3833](https://linear.app/apostrophecms/issue/PRO-3833/fix-the-issue-with-very-slow-performance-in-editing-mode-when-editing)
Research on UI performances issue. The page refresh that happens to update context of the page doesn't destroy appropriate Vue components and associates events. We basically have a Vue apps leak.
* Run a project with palette for example
* Open it and close it multiple times to refresh the page multiple times
* Check that page edition performances stay stable meaning that vue apps leak has been fixed
=> Pro 3833 UI perfs

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/schema/index.js, test/schemas.js
- notify on external condition api error
- send clean 400 error
- fix module retrieving
- remove log
- add missing changelog entry
- add tests
cf #4068
=> external conditions follow-up

CHANGELOG.md, package.json
=> release 2.226.0

CHANGELOG.md, package.json
=> release 3.41.0

CHANGELOG.md, package.json
=> release 3.41.1

CHANGELOG.md
Moves rich text fix from released to unreleased.
=> fixes changelog

CHANGELOG.md, lib/modules/apostrophe-schemas/views/macros.html
Add a read-only overlay to prevent users from interacting with areas set as read-only, as it was done for checkboxes and color field types.
| ![image](https://user-images.githubusercontent.com/8301962/224775448-b7bc8142-f248-4a62-b231-9419780be455.png) | ![image](https://user-images.githubusercontent.com/8301962/224775539-f6953add-deb9-4b48-bee8-1b319e7553dd.png) |
|-----------|--------------|
```
addFields: [
{
name: 'select',
def: 'one',
choices: [
{
label: 'Make color and area readonly',
value: 'one',
readOnlyFields: [ 'color', 'areaMain' ]
},
{
label: 'Make all other fields readonly',
value: 'two',
readOnlyFields: [ 'age', 'shoeSize' ]
}
]
},
{
name: 'age',
type: 'integer',
min: 18,
max: 150,
def: 30,
required: true
},
{
name: 'shoeSize',
type: 'float',
def: 36, …
```
=> add readonly overlay to areas

modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue
UI fixes for inline array displays
1. Check the visuals for inline array display in per document permissions
=> Pro 3986 qa visual notes

lib/modules/apostrophe-schemas/public/js/user.js, lib/modules/apostrophe-ui/public/css/components/fields.less
=> hide widgets controls for readonly areas

modules/@apostrophecms/ui/ui/apos/components/AposCombo.vue
=> Combobox style tweaks

modules/@apostrophecms/doc-type/index.js
Move updateCacheField from handler to a method
N.A.
=> wrap updateCacheField handler in a method

modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/schema/ui/apos/components/AposSearchList.vue
=> fix search when empty

CHANGELOG.md, modules/@apostrophecms/piece-type/index.js, test/pieces-tasks.js
Add `touch` task that updates every record (except archived) of a given piece type. It triggers all relevant events.
- Generate pieces. (generate task)
- Execute `node app pieceName:touch`
- `updatedAt` times should be updated
- All `update` related events should be triggered
=> PRO-3909 Add touch task for pieces

CHANGELOG.md, package.json
=> release 3.43.0

CHANGELOG.md, modules/@apostrophecms/module/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, test-lib/util.js, test/pieces-public-api.js, test/pieces.js
* implemented guestApiAccess
* related improvements to test library
* Set `guestApiAccess: true` as an option to a piece type
* Guest users (those who have accounts but no editing privileges) can now call the GET APIs of that type
=> PRO-4047: guestApiAccess

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js
Add `findOneForLocalizing` method
Check that you can still localize content
=> add findOneForLocalizing method

CHANGELOG.md, package.json
Release, with clarification of changelog to avoid inside baseball about certain details
=> release 3.44.0

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue
https://linear.app/apostrophecms/issue/PRO-3809/cant-add-child-page-slug-if-title-deleted
=> Fix child page slug when title is deleted

modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue
Fix bug introduced by new defaults logic.
=> fix relationship with no fields

CHANGELOG.md, package.json
release + changelog edits only
=> release 3.45.0

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/apps/AposModals.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, package.json
* Hotfixed the issue where on most sites the insert menu has the wrong font and font size (I am embarrassed).
* Hotfixed the issue where a click on an image in the media manager will close the inline image dialog box of the rich text editor (this was subtle and I am not embarrassed).
=> Hotfixes for the insert menu

CHANGELOG.md, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
Debounce calls to search in manager modal
1. Open a manager modal
2. Open the browser network panel and search for `autocomplete`
3. In the search field, type a word at a steady pace, you should see only one API call to `GET /api/v1/%my-module%`
4. Do the same thing but stop in the middle of the word and continue later on, you should see 2 calls
=> debounce search in manager modal

CHANGELOG.md, package.json
=> Release 3.46.0

CHANGELOG.md, package.json
=> release 3.47.0

CHANGELOG.md, modules/@apostrophecms/page-type/index.js
Add a default value to avoid inserting an empty value by default in the dropdown.
Issue raised by a customer.
The following dropdown should not contain an empty choice:
=> add default page type

CHANGELOG.md, package.json
=> release 2.227.1

CHANGELOG.md, lib/modules/apostrophe-modal/public/js/modal.js, package.json
I failed to run apostrophe-enterprise-testbed's nightwatch tests, resulting in this getting into the wild. Mea culpa.
=> Hotfix for break in build process

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/util/ui/src/http.js
fixes localizing issue introduced in #4112
=> add and use the `prefix` option in http frontend util to fix localization

modules/@apostrophecms/util/ui/src/http.js
bring the changes requested in https://github.com/apostrophecms/a3-docs/pull/335#discussion_r1213173414 to the core
=> improve doc for the prefix option in the http util frontend module

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/ui/ui/apos/components/AposCombo.vue
Adds typehead feature for the internally only used component AposCombo.
No regressions (Checboxes component).
=> PRO-4218: Add combo typehead

modules/@apostrophecms/ui/ui/apos/components/AposCombo.vue
Emit `input` when resetting the internal model.
-
=> PRO-4218: Emit when resetting

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
=> reverts change that removed add content UI on widget focus

modules/@apostrophecms/ui/ui/apos/components/AposCombo.vue
Prevents list toggle when a selected item is clicked (removed).
- Clicking on a selected item when the choices list is closed will remove the selected item and it won't toggle the list.
- Clicking on a selected item when choices list is opened will just toggle the list, selected item won't be removed
=> PRO-4218: Disable toggle on selected item click

modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
=> remove if statement to keep toolbar if we have archived documents

CHANGELOG.md, package.json
=> release 2.227.3

CHANGELOG.md, package.json
=> release 3.49.0

package.json
=> forgot version number

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputObject.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue, modules/@apostrophecms/schema/ui/apos/lib/conditionalFields.js, modules/@apostrophecms/schema/ui/apos/mixins/AposInputConditionalFieldsMixin.js
Adds support for conditional fields within `array` and `object` types.
Conditional fields withing `array` and `object` field types should work as expected.
=> PRO-4367: Add array and object conditional fields support

CHANGELOG.md, package.json
=> release 3.51.0

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js
Fix wrong value sent to conditional fields processor, leading to conditional fields not working in Array Editor Modal.
Conditional fields in editor modal should work as expected. Tests should pass.
=> HOTFIX: Conditional fields in array editor

CHANGELOG.md, package.json
hotfix release to fix conditionals in array field modals
=> release 3.51.1

CHANGELOG.md, package.json
=> release 3.52.0

CHANGELOG.md, index.js, lib/moog-require.js
* See changelog
* You don't have to add an Apostrophe module to `package.json` if you are using `npm link modulename` to link it to your project
* In `a3-demo`, the `localizations` module no longer generates a "this module has no code" warning (because an `i18n` subdir is enough to justify its existence)
=> PRO-4523 and PRO-4524

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/modal/ui/apos/components/AposDocsManagerToolbar.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalTabs.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposModalTabsMixin.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/lib/addFieldTypes.js, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue, modules/@apostrophecms/schema/ui/apos/lib/conditionalFields.js, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue
* Hide empty schema groups
* Support for `false` when checking `if`
You can use https://github.com/apostrophecms/doc-template-library/pull/17 or do it yourself by
1. Update the piece or page schema and add an `if` to all fields of a schema groups
2. Check that the schema group is now hidden
3. Try `if` with a matching `false` value
=> Pro 4020 create from template

CHANGELOG.md, modules/@apostrophecms/admin-bar/index.js, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue
Add support to add context labels in admin bars  (for templates library purposes).
Test with [this PR](https://github.com/apostrophecms/doc-template-library/pull/29).
=> Add support for context labels

CHANGELOG.md, modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/schema/ui/apos/logic/AposSubform.js, modules/@apostrophecms/settings/index.js, modules/@apostrophecms/ui/ui/apos/components/AposSubformPreview.vue
Adds detailed in-code docs. Fixes tiny UI preview bug.
-
=> PRO-4560: User settings in-code docs

CHANGELOG.md, package.json
=> release 3.53.0

modules/@apostrophecms/log/index.js, modules/@apostrophecms/module/index.js, test-lib/util.js, test/log.js
Add structured logging for REST API and render routes.
See acceptance criteria of PRO-4485.
=> PRO-4485 API error log

modules/@apostrophecms/log/index.js, modules/@apostrophecms/login/index.js, test/log.js
> NOTE: built on top of https://github.com/apostrophecms/apostrophe/pull/4249, should await merging to avoid double code review.
- Add structured logging  for login related operations.
- Improve the developer log reading experience (CLI colorized and formatted objects).
See acceptance criteria of PRO-4484.
=> PRO-4484 Login structured logging

CHANGELOG.md, modules/@apostrophecms/page/index.js
See above
Regression tests pass, page tests pass
=> getTarget should use findForEditing

CHANGELOG.md, package.json
release + minor changelog edits
=> release 3.54.0

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue
Refresh schema when page type changes
1. Replicate https://github.com/apostrophecms/starter-kit-essentials/compare/page-type-choices-showcase?expand=1
2. Create a page and change the page type value, the choices must be updated
=> add field._id to schema field key

CHANGELOG.md, package.json
=> release 3.55.0

CHANGELOG.md, package.json
=> release 3.56.0

test/pages.js
Remove leftover test "console.log".
-
=> Remove test leftover debug

.github/workflows/main.yml
=> Add MongoDB 7.0 to workflow

CHANGELOG.md, package.json
=> PRO-4869 for A2

CHANGELOG.md
Adds thank you to CHANGELOG for community contribution.
=> Add community member thank you.

CHANGELOG.md, package.json
=> release 3.57.0

CHANGELOG.md, package.json
=> release 2.227.4

.github/workflows/main.yml, package.json
=> PRO-4812: test supported releases of mongodb and nodejs with A2

.github/workflows/outdated-dependencies.yml
=> change icon in the outdated dependencies slack message

CHANGELOG.md, package.json
=> release 3.58.0

CHANGELOG.md, DEVELOPMENT.md, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/asset/lib/webpack/apos/webpack.config.js, modules/@apostrophecms/asset/lib/webpack/apos/webpack.vue.js, modules/@apostrophecms/asset/lib/webpack/src/webpack.config.js, package.json
* See changelog
* asset builds still works after npm update (I tested it)
* Image conversion still works after npm update (I tested it)
=> PRO-4988 PRO-4989

CHANGELOG.md, modules/@apostrophecms/piece-page-type/index.js
=> chooseParentPage warning is smart

CHANGELOG.md, package.json
=> release 3.59.0

CHANGELOG.md, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/page/index.js, test/pages-rest.js, test/published-pages.js
See changelog.
* See tests
* Also verify it resolves your specific issue on the HO project without the need for any workarounds
=> PRO-5092: fix bugs surrounding page tree

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue
This PR fixes a bug in the expanded widget preview menu where group labels wouldn't be translated. Closes PRO-5199
*For example:*
1. Bring up testbed with this code linked.
2. Change the `widget-preview-page` module to include a localized label (I used `apostrophe:addContent`).
3. Create a new page of that type and chack that the label changes correctly ('Add Content'). …
=> Pro 5199 fix translation

CHANGELOG.md, package.json
=> release 3.60.0

modules/@apostrophecms/notification/index.js
This PR updates some details in the notification module code comments. Closes PRO-5146.
*For example:*
=> Minor changes to code comments

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js
Update conditional fields when you open the editor modal on pages
1. Add a conditional fields on a page schema, the field should be visible by default
2. Open the editor modal, you should see the field when you load the editor modal and when you interact with it
=> run evaluateConditions after evaluateExternalConditions

modules/@apostrophecms/login/index.js
=> oops do not change a signature that already exists

CHANGELOG.md, modules/@apostrophecms/cache/index.js, modules/@apostrophecms/login/index.js
This PR updates the cache and login modules. It was needed to allow for the cache-redis extension to function. Before this PR the number of login attempts was cleared by deleting the cached value from the MongoDB directly. As the cache-redis extension doesn't use MongoDB for caching, this led to an error. A new `delete` function was added to the cache module and the login module `clearLoginAttempts` method was altered to this new method. Closes PRO-5297.
*For example:*
> 3. Click the "Archive" button on the top left of the manager and confirm …
=> Pro 5297 cache fix

CHANGELOG.md, package.json
release only; I reorganized the changelog items a little
=> release 3.61.0

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js, test/schema-queryBuilders.js
This PR adds a `launder` method to the `float` query builder in order to handle both single and array searches. It also fixes the `finalize` method to correctly handle range arrays.
*For example:*
1. Confirm that `schema-queryBuilders.js` tests pass.
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for …
=> Pro 5301 float launder

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js, test/schema-queryBuilders.js
This PR fixes the `integer` query builder and adds test coverage. Closes PRO-5300.
*For example:*
1. Run the `schema-queryBuilders.js` tests
=> Fix integer query builder and add tests

CHANGELOG.md
just cleaning up the changelog
=> fix changelog heading error, this stuff has not shipped

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/doc-type/ui/apos/logic/AposDocContextMenu.js, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/ui/ui/apos/components/AposCellContextMenu.vue, modules/@apostrophecms/ui/ui/apos/scss/mixins/_theme_mixins.scss
=> Fix frontend permission

modules/@apostrophecms/doc-type/ui/apos/logic/AposDocContextMenu.js
=> fixes delete draft in core

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/doc-type/ui/apos/logic/AposDocContextMenu.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js
Fixes did during manual testing.
=> Fixes following manual tests

CHANGELOG.md, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/page-type/index.js
…
See title
* Admin creates a DRAFT ONLY page (use "save draft" only do NOT publish it)
* A user without any other permissions, "perdoc1", is given per-doc permission to modify, archive and publish that page
* Log out as admin
* Log in as perdoc1
* Try to publish the never-published page in question
* You can do so
=> PRO-5389 if I can publish a certain draft page then I can create it in the published mode if necessary even if I cannot otherwise "create"

modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue
Fixes problems with the media manager editor component such that clicking on the selected item to deselect it would produce an exception, breaking the tests.
N/A. It's really all about the CI regression tests 🙏  But you can try the test above. I note that the image still has a blue outline after you deselect it, but I have checked and that is not a new bug, so not in scope here.
- [N/A, bug never shipped] The changelog is updated
=> fix for all of the regression test errors relating to media

CHANGELOG.md, package.json
=> release 3.62.0

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js
This PR adds a `launder` method to the `slug` schema field query builder so that it can be used in an API query. Closes PRO-5575
*For example:*
1. Add a piece-type and several pieces
2. Set a publicApiProjection that includes the slug
3. Using postman (or similar), make a GET request to the API endpoint with a query parameter of `slug=<some-piece-slug>`
4. Verify that documents matching the …
=> Update slug query builder

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/schema/ui/apos/components/AposSearchList.vue, modules/@apostrophecms/schema/ui/apos/logic/AposInputRelationship.js, test/pages-autocomplete.js, test/pages.js
We can now define relationships with a specific page type:
```
// eg:
test: {
label: 'Test',
type: 'relationship',
withType: 'default-page'
},
```
| Header | Header | Header | Header |
|--------|--------|--------|--------|
| <img width="563" alt="image" src="https://github.com/apostrophecms/apostrophe/assets/8301962/0cbad1e9-770b-40e0-92ca-93c65357fa69"> | <img width="913" alt="image" src="https://github.com/apostrophecms/apostrophe/assets/8301962/d5d6c3d8-dfbb-4dcf-ba77-2c7e6c55f151"> | <img width="918" alt="image" src="https://github.com/apostrophecms/apostrophe/assets/8301962/e98246f8-2e3c-4e14-b524-2bf36ba2f0e8"> | <img width="561" alt="image" src="https://github.com/apostrophecms/apostrophe/assets/8301962/fe6248fa-1f86-4369-9353-c7a9a74d9e46"> | 
If adding a …
=> relationship's withType property supports specific page types

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/mixins/AposPublishMixin.js
[PRO-4801](https://linear.app/apostrophecms/issue/PRO-4801/cypress-tests-for-advanced-permission-level-3)
Submit a draft while checking the console
=> set content-changed with complete doc

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue, modules/@apostrophecms/translation/index.js
=> Pro 5356 see translated stuff

CHANGELOG.md, package.json
For release only.
*For example:*
=> release 3.63.0

CHANGELOG.md, package.json
dependency bump to release security fix
=> release 3.63.1

CHANGELOG.md, modules/@apostrophecms/oembed/index.js, modules/@apostrophecms/polymorphic-type/index.js, modules/@apostrophecms/schema/index.js, package.json, test/schemas.js
security fix previously reviewed
=> Release 3.63.2

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue, modules/@apostrophecms/schema/ui/apos/logic/AposSchema.js, modules/@apostrophecms/ui/ui/apos/scss/global/_theme.scss
https://linear.app/apostrophecms/issue/PRO-5465/as-an-editor-i-can-see-the-differences-between-the-two-document
Goes with         https://github.com/apostrophecms/document-versions/pull/46
=> Highlight differences when comparing

modules/@apostrophecms/admin-bar/ui/apos/apps/AposAdminBar.js, modules/@apostrophecms/area/ui/apos/apps/AposAreas.js, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/busy/ui/apos/apps/AposBusy.js, modules/@apostrophecms/command-menu/ui/apos/apps/AposCommandMenu.js, modules/@apostrophecms/login/ui/apos/apps/AposLogin.js, modules/@apostrophecms/modal/ui/apos/apps/AposModals.js, modules/@apostrophecms/notification/ui/apos/apps/AposNotification.js, modules/@apostrophecms/ui/ui/apos/lib/vue.js
See above.
The normal app experiences e.g. admin bar, dialog boxes, busy indicator, etc. still work, and so do does the tiptap menu (since I refactored nearby).
I found that I had to make this branch a dependency of my project and properly npm install it to get past some weird vue warnings and no admin UI. That seems like a personal build problem of some kind.
=> PRO-5736: support named component overrides, even for root components of apps

CHANGELOG.md, modules/@apostrophecms/translation/index.js
=> temporary warning

CHANGELOG.md, package.json
=> release 4.1.0

CHANGELOG.md
=> Add thank you

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue
⚠️ This is an A3 PR
Add `metaType` to newly inserted widgets
1. Add a widget to an area
2. With the `vue-dev-tools`, check that the `metaType` property is set after insert
3. Check that the `metaType` property is still there after a widget update
4. Check that the `metaType` property is still there after a full page reload
=> [A3] add meta type to widget

test/docs.js
Fix stray it.only call. No changelog because it did not ship
=> fix a stray it.only call that eliminated all other tests

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapMarks.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapStyles.vue
=> PRO-5879 add missing localization

modules/@apostrophecms/ui/ui/apos/lib/i18next.js, package.json
=> Remove unused dep

CHANGELOG.md
just a thank you and a changelog rewrite
=> thanks to Gauav Kumar

test/base-url-env-var.js
just one pesky test was using it causing my one failure
=> one pesky test used port 3000

package.json
=> [A4] use @apostrophecms/emulate-mongo-3-driver@1.0.2

package.json
=> [A3] use @apostrophecms/emulate-mongo-3-driver@1.0.2

CHANGELOG.md, package.json
=> [A2] use emulate-mongo-2-driver@1.3.2

CHANGELOG.md, package.json
=> release 4.2.0

CHANGELOG.md, package.json
=> Release 3.64.0

package.json
=> [A2] Hotfix/emulate mongo 2 driver a2 binary

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/schema/ui/apos/mixins/AposInputMixin.js, modules/@apostrophecms/ui/ui/apos/utils/index.js, test/utils.js
Allows to disable page refresh on content changed for page types when added to options.
=> Allow to disable page refresh

CHANGELOG.md
Forgot to add changelog infos about new stuff added.
=> improves changelog

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue, package.json
=> hotfix 4.2.1: drag and drop in page tree

CHANGELOG.md
=> reword changelog entry and credit Michelin

modules/@apostrophecms/modal/ui/apos/components/AposModalTabs.vue, modules/@apostrophecms/modal/ui/apos/components/AposWidgetModalTabs.vue, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
see code comments
(no changelog because fixing stuff that's not been released)
cf https://github.com/apostrophecms/testbed/pull/248
*For example:*
=> fix cypress tests

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposImageCropper.vue
Changing aspect ratio using the `aspectRatio` from the `vue-advanced-cropper` library reduces the stencil each time.
The solution here is to reset the stencil before changing its ratio:
=> Pro 5871 aspect ratio

CHANGELOG.md, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
Do not show single widget editor tab.
No "Ungrouped" tab shown when there is no tabs configuration.
=> PRO-6051: Hide single tab

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/apos/webpack.config.js
Adds function to set vue alias targetting a unique instance based on where it's installed, for development purpose.
=> Solves development multiple vue instances being loaded with npm links

CHANGELOG.md, package.json
=> release 4.3.0

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/components/AposWidgetModalTabs.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuItem.vue, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue, package.json
Merging the hotfix from Miro now that it has been released atop 4.3.1
=> release 4.3.2: hotfix for widget validation

modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
=> fix typo in field name

modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue, modules/@apostrophecms/schema/ui/apos/logic/AposInputString.js, modules/@apostrophecms/ui/ui/apos/scss/global/_inputs.scss
- Properly class textarea inputs as such
- add line-height to text areas
- add field meta options and position
=> properly tag textareas, add textarea line-height, field meta positioning

CHANGELOG.md, modules/@apostrophecms/image/index.js, modules/@apostrophecms/schema/ui/apos/components/AposSearchList.vue, modules/@apostrophecms/schema/ui/apos/logic/AposSearchList.js
Suggestion with images UI improvements
1. Create relationship fields with images, files, pages, ...
2. Check the UI for images (images should be 50px wide, the slug should not be visible, the title should be on a single line with ellipsis at the end)
3. Check the UI for other types (pages, files,...), the icon should be 32px wide
=> suggestion images size

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js, test/schemas.js
Prevent read-only fields from being reverted to default value on `array`, `object` and `relationship` types
1. Run the test
=> Pro 5938 read only default value

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/schema/ui/apos/components/AposSearchList.vue, modules/@apostrophecms/schema/ui/apos/logic/AposInputRelationship.js
Relationship suggestion UI for images (part 2)
Targets only the UI in inline rich-text images
1. Check the suggestion UI when using inline images in rich text and compare it with the image widget UI
=> grab suggestionFields from browser data

modules/@apostrophecms/schema/lib/addFieldTypes.js, test/schemas.js
=> Pro 6140 no def in convert

CHANGELOG.md, package.json
=> release 4.4.0

CHANGELOG.md, package.json
=> release 3.67.0

CHANGELOG.md, package.json
=> release 4.4.1

CHANGELOG.md, package.json
release plus minor changelog tweaks
=> release 4.4.3

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposImageRelationshipEditor.vue
=> image cropping: select configured aspect ratio and add data-test attributes

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/logic/AposInputArea.js
Prevent broken admin UI when there is a missing widget. 
Add a non existent widget to any area. Ensure the area is visible and functional in any editor modal. 
=> PRO-6143: A3 missing widget regression

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue
"Closes #4608 "*
> 1. Add a New Area type
> 2. set expanded: true and columns: 1
> 3. Open that expanded menu on the UI
> 4. Check that there should be only 1 column and only 1 widget in each row.
=> #4608 Adding styles for one column in expanded area

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/logic/AposInputArea.js
Prevent broken admin UI when there is a missing widget.
> NOTE: The failing tests are inherited from `main`
Add a non existent widget to any area. Ensure the area is visible and functional in any editor modal.
=> PRO-6143: Guard for missing widget

CHANGELOG.md, package.json
=> use emulate-mongo-3-driver 1.0.4

package.json
=> use emulate-mongo-3-driver 1.0.5

package.json
=> [A3] Pro 6303 mongodb 6.8.0 a3

package.json
=> [A2] Pro 6303 mongodb 6.8.0 a2

CHANGELOG.md, package.json
=> bumps oembetter version, bumps package

modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapColor.vue
This PR eliminates the bugs Stu noted with the toolbar losing focus and allows for pasting of hex values in the RTX color picker.
*For example:*
=> allows pasting of hex values

CHANGELOG.md, package.json
=> release 3.67.1

CHANGELOG.md, package.json
=> release 2.227.2

CHANGELOG.md, package.json
=> release 4.5.0

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
Allow to open modals and keep the tiptap toolbar open
1. Select some text in a rich text
2. Click on the `Link` icon
3. Select `Pages` then `Browse`
4. Select a page and save the link
If you have the `Image` icon in the toolbar
1. Select some text in a rich text
2. Click on the `Image` icon
3. Click `Browse`
4. Select an image and save the image
=> allow to open modals without closing tiptap toolbar

CHANGELOG.md, package.json
=> For release only

CHANGELOG.md, modules/@apostrophecms/doc/index.js, package.json
=> release 4.5.2: hotfix for infinite loops in apos.doc.walk

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/logic/AposInputRelationship.js, package.json
=> Hotfix/windows relationship UI

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManagerSelectBox.vue
Update manager modal checked according to current context
1. In a manager modal, use `Select All` checkbox. You should see `10 XXX on this page selected. Select all 11 XXX.` on all pages.
2. In relationship mode, select some items and archive one of the selected items. It should be removed from the list in the left page.
3. In relationship mode, select all should respect the max settings on the relationship
4. In manager mode, select multiple items and use the batch operation to archive them. The manager modal view should be refreshed.
=> add title and _url to select all projection

CHANGELOG.md, modules/@apostrophecms/any-page-type/index.js, modules/@apostrophecms/search/index.js, package.json, test/search.js
=> fix search request timeouts by adding a default projection

CHANGELOG.md, package.json
things that go bump in the night
=> oembetter version bump only

package.json
Just the oembetter bump (second one in this release cycle)
=> Fix youtube (a2)

CHANGELOG.md, package.json
=> fix youtube (a3)

CHANGELOG.md, package.json
just the youtube oembetter bump
=> fix youtube (a4)

CHANGELOG.md
Adds a thank you message to the CHANGELOG, no code changes
*For example:*
=> Add thank you message.

CHANGELOG.md, package.json
=> [A2] hotfix / update emulate-mongo-2-driver

CHANGELOG.md, package.json
=> [A3] hotfix / update emulate-mongo-3-driver

CHANGELOG.md, package.json
=> release 3.67.2

CHANGELOG.md, package.json
=> release 4.6.0

.github/workflows/main.yml
Trigger tests for A3.
*For example:*
=> CI testing for A3

CHANGELOG.md, lib/modules/apostrophe-rich-text-widgets/public/css/components/ckeditor-controls.less
Target all combos and not just styles in the rich-text toolbar
Follow the steps in https://github.com/apostrophecms/apostrophe-documentation/pull/417
=> target all combos and not just styles

modules/@apostrophecms/area/ui/apos/components/AposAreaMenu.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue
- Achieve the same leveling without side effects to neighboring UI
=> remove z-index bump on area schema fields, boost menu index

CHANGELOG.md, package.json
just merging back the release, which mostly impacts the changelog
=> Release 4.6.1 mergeback

modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/schema/ui/apos/logic/AposInputSlug.js, modules/@apostrophecms/ui/ui/apos/utils/index.js, test/utils.js
This is incomplete, I have to finish making the remaining functions stateless and test the whole thing. You can see what I intend to do in the documentation comment and in the media manager.
=> WIP on if not canceled approach

CHANGELOG.md, package.json
=> bump uploadfs dep

modules/@apostrophecms/schema/lib/addFieldTypes.js
=> fix subfield imports (it was a bug in fetchRelationships: false)

CHANGELOG.md, package.json
=> release 4.7.0

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/index.js
Unblock a customer by providing a simple way to import images. See notes on ticket for a test procedure.
Documentation will be needed too. I can do it.
See notes on ticket.
=> PRO-6578: auto import of inline images

package.json
=> upgrate stylelint-config-apostrophe to 4.2.0

CHANGELOG.md, package.json
=> Release 4.8.0

CHANGELOG.md, package.json
Remove unused dependency.
cf. https://github.com/apostrophecms/apostrophe/security/dependabot/4
*For example:*
=> remove unused vue-template-compiler dependency

CHANGELOG.md, modules/@apostrophecms/asset/index.js
N/A, I've reproduced the bug and the fix in the client's repo, it's unclear if it can be done with a simple test configuration but the issue was obvious
=> fix a rare race condition

CHANGELOG.md, modules/@apostrophecms/asset/index.js, package.json
=> release 4.7.2

CHANGELOG.md, modules/@apostrophecms/asset/index.js, package.json
=> release 4.8.1

CHANGELOG.md
Just the changelog update to show the hotfixes happened and take this out of "unreleased"
=> Hotfix changelog

CHANGELOG.md
=> Update changelog for translations

modules/@apostrophecms/asset/index.js, modules/@apostrophecms/asset/lib/build/manager-apos.js, modules/@apostrophecms/asset/lib/build/manager-bundled.js, modules/@apostrophecms/asset/lib/build/manager-custom.js, modules/@apostrophecms/asset/lib/build/manager-index.js, modules/@apostrophecms/template/lib/bundlesLoader.js, modules/@apostrophecms/ui/ui/apos/components/AposLoading.vue, modules/@apostrophecms/ui/ui/apos/components/AposSpinner.vue, test/asset-external.js
=> PRO-6645, PRO-6646: dev server and HMR

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/asset/lib/build.js, modules/@apostrophecms/asset/lib/build/manager-apos.js, modules/@apostrophecms/asset/lib/build/manager-bundled.js, modules/@apostrophecms/asset/lib/build/manager-custom.js, modules/@apostrophecms/asset/lib/build/manager-index.js, modules/@apostrophecms/asset/lib/build/managers.js, modules/@apostrophecms/piece-type/ui/apos/components/AposRelationshipEditor.vue, modules/@apostrophecms/schema/ui/apos/lib/newInstance.js, modules/@apostrophecms/schema/ui/apos/logic/AposArrayEditor.js, modules/@apostrophecms/schema/ui/apos/logic/AposInputArray.js, modules/@apostrophecms/schema/ui/apos/logic/AposInputRelationship.js, modules/@apostrophecms/template/lib/bundlesLoader.js, modules/@apostrophecms/ui/ui/apos/components/AposLoading.vue, modules/@apostrophecms/ui/ui/apos/components/AposSpinner.vue, modules/@apostrophecms/ui/ui/apos/utils/index.js, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue, test/asset-external.js, test/utils.js
This is a change against a feature branch.
Implement abstract core system for handling builds from external systems based on a manifest. Provide the required helpers (public API) for the build process. 
External modules can build.
=> PRO-6643, PRO-6644 external build, bundles and manifest

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/apos/webpack.scss.js, modules/@apostrophecms/asset/lib/webpack/src/webpack.scss.js, package.json
Minimum version so it doesn't whine LOL
=> Sass import warning

package.json
=> bump package version to 4.8.1

modules/@apostrophecms/asset/lib/webpack/apos/webpack.scss.js, modules/@apostrophecms/ui/ui/apos/scss/mixins/_responsive.scss, modules/@apostrophecms/ui/ui/apos/scss/mixins/_theme_mixins.scss
=> Pro 6707 sass warnings

CHANGELOG.md, package.json
release only (doozy of a release)
=> release 4.9.0

modules/@apostrophecms/asset/lib/build/external-module-api.js
=> sort glob result

package.json
Resolve yaml dependency conflicts introduced with other modules.
The only Breaking Change listed in the CHANGELOG is NodeJS version requirement, that does comply with the Apostrophe requirements: https://github.com/webpack-contrib/postcss-loader/blob/master/CHANGELOG.md
Testbed builds
=>  Bump postcss-loader

modules/@apostrophecms/asset/lib/build/internals.js
Fixing a bad guard.
*For example:*
=> Fix assets not being copied in some edge cases

CHANGELOG.md, package.json
=> release 4.10.0

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js
=> warn about a common configuration oversight

CHANGELOG.md
Rearranges CHANGELOG to consolidate the two Add sections
*For example:*
=> Consolidates Changelog Add sections

CHANGELOG.md, package.json
=> release 4.11.0

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/piece-type/index.js
=> PRO-7041: bug fix for main content area refresh when on a show page

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposButtonSplit.vue
- Refactor the component markup to follow the HTML5 specification
- Improve the component architecture so that there is a clear separation between "display" and "logic" elements
- Improve performance with removing unnecessary focus trapping (the base Context Menu takes care of that) and refs
- Fix visual glitches (bottom outline not shown in some cases, see screenshots)
- Add test attributes to improve the component testability 
- Split button still works as expected (test in Editor modal, primary actions)
- Existing tests are passing
- Visual glitch below is fixed
Before
After
=> PRO-6917: Fix split button markup, visuals, performance

modules/@apostrophecms/ui/ui/apos/components/AposButtonSplit.vue
Fixes leftover instances of already removed handlers (introduced in https://github.com/apostrophecms/apostrophe/pull/4837)
No millions of Vue warnings in development.
=> PRO-6917: Fix missing handlers

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue
Fixes a case where releationship button overlaps a context menu.
No overlapping. 
=> PRO-6953: Fix relationship button overlaps context menu

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputRange.vue, modules/@apostrophecms/schema/ui/apos/logic/AposInputRange.js
One last one, for palette?
- Updates range styles, adds progress state
*For example:*
Open a schema with a range field
=> range updates

CHANGELOG.md, modules/@apostrophecms/asset/index.js
Expecting just a review from Bob today, but when you get a chance Miro feel free to comment.
=> PRO-7071 silence unnecessary error message

CHANGELOG.md, package.json
=> release 4.12.0

modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/i18n/ui/apos/apps/AposI18nBatchReporting.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js
> NOTE: this is a change against a feature branch.
Show a summary of issues per item after batch localization. It's shown only if there are any errors.
If any documents or related documents queued for batch localization fails, a modal should be shown, showing all failed items. 
=> PRO-6965 Batch localization error reporting (UI)

CHANGELOG.md, package.json
=> release 4.13.0

CHANGELOG.md, modules/@apostrophecms/template/views/outerLayoutBase.html, test/i18n.js, test/modules/i18n-test-page/views/page.html
Use `data.locale` to set the current locale in the `lang` attribute of the `html` tag.
|--------|--------|
| <img width="165" alt="image" src="https://github.com/user-attachments/assets/89d1ba57-9e43-4bd2-ba5a-6bde562e789b" /> | <img width="167" alt="image" src="https://github.com/user-attachments/assets/05a67ba5-bda8-47c7-9503-3c93be605bb5" /> | 
| `/fr` | `/fr` | 
=> set html lang attribute to current locale

CHANGELOG.md, modules/@apostrophecms/piece-type/index.js
- Bump perPage to 50 for piece managers
=> bump per page to 50

CHANGELOG.md, package.json
beta release with Etienne's locking fix.
=> release 2.227.10-beta.1

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/ui/ui/apos/scss/mixins/_zindex.scss
No Issue, Improvements made while testing Apollo.
Tiny UI improvements.
See comments in code
=> clear error when widget badly configured in aposAreaExpandedWidget

CHANGELOG.md, modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue, modules/@apostrophecms/login/ui/apos/components/TheAposLoginHeader.vue
Needed in https://github.com/apostrophecms/testbed/pull/326
=> add data-test attributes to the login page

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalBody.vue, modules/@apostrophecms/ui/ui/apos/utils/index.js, test/utils.js
Fixes Media Manager infinite scroll and related issues. Loading media items initially until scroll is present is part of the solution. 
Infinite scroll should work as expected. Images will be loaded until a scroll is available (if enough total items available). 
=> PRO-7135: media manager infinite scroll fix

modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapInsertItem.vue
=> context menu in rich text insert menu behaves like in toolbar

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/scss/mixins/_zindex.scss
=> Fix area z index

CHANGELOG.md, package.json
=> release 4.14.0

CHANGELOG.md, package.json
=> release 2.227.10

CHANGELOG.md, modules/@apostrophecms/express/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, package.json
=> backport hotfix for express-cache-on-demand scoping

CHANGELOG.md, modules/@apostrophecms/i18n/i18n/de.json, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/i18n/es.json, modules/@apostrophecms/i18n/i18n/fr.json, modules/@apostrophecms/i18n/i18n/it.json, modules/@apostrophecms/i18n/i18n/pt-BR.json, modules/@apostrophecms/i18n/i18n/sk.json, modules/@apostrophecms/login/ui/apos/components/AposForgotPasswordForm.vue, modules/@apostrophecms/login/ui/apos/logic/AposForgotPasswordForm.js
Mark email field with type email for validation
Change reset password form submit button label
1. Enable login `passwordReset` option
```javascript
// modules/@apostrophecms/login/index.js
export default {
options: {
passwordReset: true
}
};
```
2. Load the login page
3. Use the `Reset Password` link
4. Check that the submit button label is `Reset Password` instead of `Send Email`
5. Type something other than an email in the input field, it should mark the field as an error
=> replace forgot password form submit button label

CHANGELOG.md, modules/@apostrophecms/express/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, package.json
=> Merge 4.14.1

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/modal/ui/apos/components/AposDocsManagerToolbar.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/ui/ui/apos/mixins/AposArchiveMixin.js
https://linear.app/apostrophecms/issue/PRO-7519/incomplete-modal-when-batch-archiving-media
See issue, missing wording
=> wip fix images labels

CHANGELOG.md
just fix the changelog to show the accurate timing of release
=> the new table editing UI did not ship yet, fix changelog

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposFilterMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposPager.vue
|--------|--------|
| <img width="166" alt="image" src="https://github.com/user-attachments/assets/62f4dc34-8f39-4e2a-be3a-6a2745d94ac1" /> | <img width="177" alt="image" src="https://github.com/user-attachments/assets/ba55f629-bf52-4722-bd0a-33a6356651b1" /> | 
| <img width="226" alt="image" src="https://github.com/user-attachments/assets/bd9333cb-a08a-4acf-88ae-ec5ed44d826f" /> | <img width="212" alt="image" src="https://github.com/user-attachments/assets/21ea0a3b-dd08-4af1-8c08-5291c3c9b7bc" /> | 
=> fix clipped text in select elements

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/logic/AposInputRelationship.js
Fixes an error when pressing Enter in a relationship input without a focused suggestion.
Pressing enter in an empty relationship input field - nothing should happen, no errors.
=> PRO-7388: Fix empty relationship field submit issue

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue, modules/@apostrophecms/area/ui/apos/components/AposWidgetControls.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapColor.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuDialog.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuItem.vue, modules/@apostrophecms/ui/ui/apos/components/AposFilterMenu.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_theme.scss, modules/@apostrophecms/ui/ui/apos/scss/mixins/_theme_mixins.scss
- Make new widget control styles the house context menu style
=> Widget operations/styles

CHANGELOG.md, modules/@apostrophecms/i18n/index.js
=> fixes i18n locale route

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuItem.vue, package.json
=> Release 4.15.1

CHANGELOG.md, package.json
=> release 2.227.11

CHANGELOG.md, package.json
=> Hotfix 4.15.2 mergeback

CHANGELOG.md, modules/@apostrophecms/piece-type/index.js
This PR stemmed from trying to document `getManageApiProjection()` and finding that changing the default null projection would place a heavy burden on the developer. This PR adds the fields originally suggested in the code comments for the `options.manageApiProjection` to the core method.
*For example:*
If adding a new feature without an already open issue, it's best to …
=> Update getMangageApiProjection defaults

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/image-widget/index.js
Remove the help text and update the value labels.
No help, labels show `%`.
=> PRO-7737: Update range labels

modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue, modules/@apostrophecms/widget-type/ui/apos/mixins/AposWidgetMixin.js
Replace the time out implementation with `debounceAsync`
Fixes PRO-7745, PRO-7738
Shouldn't experience `required` errors and the need of double clicks on slow connections.
=> PRO-7745: Switch live preview to async debounce

CHANGELOG.md, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/image-widget/index.js, modules/@apostrophecms/image-widget/views/widget.html
Revert the image resize feature
- 
=> PRO-7753: Revert image resize

CHANGELOG.md, package.json
=> release 4.16.0

CHANGELOG.md, package.json
=> release 4.17.0

modules/@apostrophecms/page/ui/apos/logic/AposPagesManager.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposImageControlDialog.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/schema/ui/apos/components/AposSearchList.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_inputs.scss
height is coming in at 588px when fully populated
=> Pro 7726/micro tweaks

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue
Does what it says on the label now
=> PRO-7850 fixed the download button in the media library

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/image-widget/index.js, modules/@apostrophecms/rich-text-widget/index.js
Add help text for URL schema. 
The Rich text image and the image widgets show a help text for manual URLs.
=> PRO-7890: Add URL help text

CHANGELOG.md, modules/@apostrophecms/i18n/i18n/de.json, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/i18n/es.json, modules/@apostrophecms/i18n/i18n/fr.json, modules/@apostrophecms/i18n/i18n/it.json, modules/@apostrophecms/i18n/i18n/pt-BR.json, modules/@apostrophecms/i18n/i18n/sk.json, modules/@apostrophecms/rich-text-widget/index.js
https://linear.app/apostrophecms/issue/PRO-7894/move-horizontal-rule-from-the-toolbar-to-the-insert-menu
*For example:*
=> adds horizontal rule to insert menu

CHANGELOG.md, package.json
=> release 4.18.0

modules/@apostrophecms/ui/ui/apos/components/AposTagApply.vue
Minor fix
Reassign searchValue instead of updating its sub value.
*For example:*
=> Fix searchValue in tag apply for tests

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/index.js
This PR adds the import of any alt text contained in an attribute when importing rich text inline images by API. This PR also fixes a past error in the changelog documenting the incorrect change. 
*For example:*
**Other …
=> Add alt text

modules/@apostrophecms/page/ui/apos/logic/AposPagesManager.js
Fix regression introduced in https://github.com/apostrophecms/apostrophe/pull/5005
Archive pages are shown.
=> Fix regression introduced by validating pages by type feature

test/relationships-area.js
Add regression testing for https://github.com/apostrophecms/apostrophe/pull/5015
=> PRO-8108: Regression testing

modules/@apostrophecms/i18n/i18n/de.json, modules/@apostrophecms/i18n/i18n/es.json, modules/@apostrophecms/i18n/i18n/fr.json, modules/@apostrophecms/i18n/i18n/it.json, modules/@apostrophecms/i18n/i18n/pt-BR.json, modules/@apostrophecms/i18n/i18n/sk.json, modules/@apostrophecms/image-widget/ui/apos/components/AposImageWidget.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaUploaderUi.vue
[PRO-8140](https://linear.app/apostrophecms/issue/PRO-8140/quick-image-upload-translate-in-all-locales)
Just translations and lint fixes.
*For example:*
=> Pro 8140 image upload translations

modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue
Looks the same to me, but I did remove a qualifier (to satisfy the stylelint rule about no qualifiers on element types), so running this past you in order to get our tests passing
=> stylelint mad about buttons

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue, test/add-missing-schema-fields.js
🙏 hoping it doesn't shift under my feet again after your next approvals
=> more merge stuff

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js
See changelog for rationale. I made this mess, I am reverting it heh
=> revert strict enforcement of "required" and "min" for relationships

modules/@apostrophecms/image/ui/apos/components/AposImageRelationshipEditor.vue
Tiny fix following last PR fixing missing config from  area (in image cropping modal).
=> fixes widgetOptions and minSize

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarMenu.vue, modules/@apostrophecms/submitted-draft/ui/apos/components/AposSubmittedDraftIcon.vue
See [this PR](https://github.com/apostrophecms/testbed/pull/373)
=> adds missing admin bar submitted draft test identifiers

modules/@apostrophecms/area/ui/apos/components/AposBreadcrumbOperations.vue, modules/@apostrophecms/layout-widget/ui/apos/components/AposGridLayout.vue, modules/@apostrophecms/layout-widget/ui/apos/components/AposGridManager.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue
- revert the resize preview
- always show "grab" pointer
- add teleport content context menu feature
=> PRO-8312 resolve clone desync

CHANGELOG.md, package.json
=> release 4.22.0
