apostrophecms/apostrophe

lib/modules/apostrophe-pager/index.js, lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-search/index.js, lib/modules/apostrophe-utils/lib/api.js, test/docs.js, test/locales/en.json, test/pieces-widgets.js
Should resolve failed tests referenced in #414 and #415 
Renamed all instances of `sortTitle` to `titleSortified`.
Updated `pieces-widgets` autocomplete test to use a `POST` instead of a `GET`. I also had to add a get request in order to get a CSRF token, and then had to get a modal that had the join in it to bless the join in the session. @boutell Let me know if I'm jumping through any unnecessary steps there, because it did seem a bit complicated to get that route to work.
=> Test fixes

lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-areas/views/areaControls.html, lib/modules/apostrophe-attachments/public/js/user.js, lib/modules/apostrophe-custom-pages/lib/dispatch.js, lib/modules/apostrophe-docs/public/js/chooser.js, lib/modules/apostrophe-docs/views/chooser.html, lib/modules/apostrophe-files/public/js/files.js, lib/modules/apostrophe-modal/public/js/modal.js, lib/modules/apostrophe-pieces-pages/index.js, lib/modules/apostrophe-pieces/index.js, lib/modules/apostrophe-pieces/lib/api.js, lib/modules/apostrophe-pieces/lib/browser.js, lib/modules/apostrophe-pieces/lib/routes.js, lib/modules/apostrophe-pieces/public/css/manager.less, lib/modules/apostrophe-pieces/public/js/create-modal.js, lib/modules/apostrophe-pieces/public/js/editor-modal.js, lib/modules/apostrophe-pieces/public/js/user.js, lib/modules/apostrophe-pieces/views/manageLink.html, lib/modules/apostrophe-pieces/views/menu.html, lib/modules/apostrophe-ui/public/css/components/buttons.less, lib/modules/apostrophe-ui/public/js/ui.js, lib/modules/apostrophe-ui/views/components/buttons.html, lib/modules/apostrophe-ui/views/components/dropdowns.html, lib/modules/apostrophe-versions/public/js/user.js
@boutell @colpanik 
This PR has two major components:
- Namespacing all of the data attributes that I could find with `apos` and fixing their corresponding click handlers. (We’ll want to keep an eye out for any of these that fell through the cracks, but we needed to do this at some point).
- Adding a `contextual` option to pieces, which if turned to true, defaults the published state to false and redirects users to the created piece upon creation. If a piece type is contextual, the corresponding `pieces-pages` allows editor users to view unpublished show pages. If the `_url` field isn’t populated, which means there isn’t a corresponding pieces page, we don’t redirect. The `contextual` option also adds an extra column for Links, which link to the piece using the `_url` property.
I'm down …
=> Contextual pieces

lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-areas/public/js/user.js, lib/modules/apostrophe-areas/views/itemSeparator.html, lib/modules/apostrophe-areas/views/lockedItemButtons.html, lib/modules/apostrophe-docs/public/js/manager.js, lib/modules/apostrophe-pieces/public/css/chooser.less, lib/modules/apostrophe-pieces/public/js/manager-modal.js, lib/modules/apostrophe-pieces/views/manageListPage.html, lib/modules/apostrophe-templates/index.js, lib/modules/apostrophe-widgets/index.js
@boutell @colpanik 
- Added an option to pass an optional path at project level to set a fallback folder for views for all modules, essentially allowing a developer to declare a global views folder.
- Added an option to set a different template for widgets (though it still falls back to `widget.html` if not set)
=> Views fallback

lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/public/js/always.js, lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-areas/public/js/user.js, lib/modules/apostrophe-areas/views/area.html, lib/modules/apostrophe-areas/views/areaControls.html, lib/modules/apostrophe-areas/views/editor.html, lib/modules/apostrophe-areas/views/richText.html, lib/modules/apostrophe-areas/views/widget.html, lib/modules/apostrophe-images-widgets/public/css/user.less, lib/modules/apostrophe-rich-text-widgets/index.js, lib/modules/apostrophe-rich-text-widgets/public/css/components/rich-text-widget.less, lib/modules/apostrophe-rich-text-widgets/public/js/always.js, lib/modules/apostrophe-rich-text-widgets/public/js/editor.js, lib/modules/apostrophe-rich-text-widgets/public/js/user.js, lib/modules/apostrophe-schemas/public/js/user.js, lib/modules/apostrophe-templates/index.js, lib/modules/apostrophe-ui/public/js/ui.js, lib/modules/apostrophe-widgets/index.js, lib/modules/apostrophe-widgets/public/js/user.js
Several sizable chunks here:
- Refactor the rest of the rich text widget out of `apostrophe-areas`. `apostrophe-rich-text-widgets` now subclasses and fully obeys the contract specified by `apostrophe-widgets`.
- Add in contextual 'Add Content' insertion menus, so now you can add content between two existing widgets instead of perpetually at the top of an area. Some work around styling this appropriately as well.
- Attempt at namespacing all `data-area`, `data-widgets`, and `data-widget` to `data-apos-area`, `data-apos-widgets`, and `data-apos-widget` respectively.
- Remove all lockup logic. Eventually, we'll reimplement lockups as a nested area within rich text widgets, which is a much more elegant solution than in 0.5.
@boutell cc @mcoppola @colpanik
=> Refactor Areas

lib/modules/apostrophe-areas/lib/helpers.js, lib/modules/apostrophe-docs/public/js/chooser.js, lib/modules/apostrophe-images-widgets/public/js/editor.js, lib/modules/apostrophe-images/public/css/grid-item.less, lib/modules/apostrophe-images/public/css/grid-view.less, lib/modules/apostrophe-images/public/js/manager-modal.js, lib/modules/apostrophe-pieces/public/css/chooser.less, lib/modules/apostrophe-schemas/public/js/user.js
This should resolve #518 , along with an issue where the manager/chooser modal wasn't really enforcing limits properly. There is still an issue where the chosen selection isn't reflected in checkboxes on populate, this is due to a bug between the actual checkbox element (which is hidden) and the green box that user's actually interact with, and the fact that one doesn't always reflect the state of the other. One of those cases where two-way data-binding would be handy.
=> Fix singleton limits

lib/modules/apostrophe-docs/public/js/chooser.js, lib/modules/apostrophe-images-widgets/public/js/editor.js, lib/modules/apostrophe-images/public/js/chooser.js, lib/modules/apostrophe-images/public/js/manager-modal.js
subclassing decorateManager for images-chooser, allows us to add the proper hook to visually denote existing choices in image-manager
=> singleton limits working

lib/modules/apostrophe-schemas/index.js
fixes bug where contextual fields such as trash were causing info schema tab to display without any fields
=> Resolves "info" tab appearing in editors without fields (#515)

lib/modules/apostrophe-pieces-pages/index.js, lib/modules/apostrophe-pieces/lib/api.js
findForEditing method provides a logical extension point for changing the filters used when fetching things for editing purposes, fixes #574
=> Find for editing

lib/modules/apostrophe-login/index.js, lib/modules/apostrophe-module/index.js, lib/modules/apostrophe-pages/lib/api.js, lib/modules/apostrophe-pages/lib/pagesCursor.js, lib/modules/apostrophe-templates/index.js, test/lib/modules/apostrophe-pages/views/notFound.html, test/lib/modules/apostrophe-pages/views/pages/default.html, test/lib/modules/apostrophe-pages/views/pages/testPage.html, test/oembed.js, test/pages.js
Introduced data.home and data.tabs properties, which are available by default anywhere the new self.sendPage method is called to render an HTML page, and in regular CMS pages as well. The login module now calls self.sendPage, so you can access data.home and data.tabs in login.html. You can also access them in notFound.html and everywhere else. here is a new beforeSendPage metamethod which is invoked on all modules, creating an opportunity to implement things like this. Also improved some inline documentation. Stop calling self.renderPage, self.sendPage is less work and gives you these features.
=> Introduced data.home and data.tabs properties

lib/modules/apostrophe-schemas/public/css/components/help.less, lib/modules/apostrophe-schemas/public/css/user.less, lib/modules/apostrophe-schemas/views/macros.html
Example use:
```
{
name: 'title',
label: 'Sample Label',
help: 'Sample Help Text'
}
```
Screenshot:
=> Adding help text to field schema

lib/modules/apostrophe-templates/views/outerLayoutBase.html
Declaring the lanaguage attribute on the html element helps screen readers with pronunciation
=> Explicilty set language attribute

lib/modules/apostrophe-areas/public/js/editor.js
this lets the widget take the shape of the new area you've dropped into without refresh
=> set width and height to `auto` after dropping a dragged widget

lib/modules/apostrophe-schemas/public/css/user.less, lib/modules/apostrophe-schemas/public/js/user.js
separate generic error and warning states from the specific instructions/actions the user needs to know in order to submit a happy form.
=> Schema error css separation

lib/modules/apostrophe-custom-pages/index.js, lib/modules/apostrophe-doc-type-manager/index.js, lib/modules/apostrophe-doc-type-manager/lib/api.js, lib/modules/apostrophe-doc-type-manager/lib/cursor.js, lib/modules/apostrophe-groups/index.js, lib/modules/apostrophe-images/index.js, lib/modules/apostrophe-module/index.js, lib/modules/apostrophe-pieces/index.js, lib/modules/apostrophe-pieces/lib/api.js, lib/modules/apostrophe-pieces/lib/cursor.js, lib/modules/apostrophe-tags/lib/browser.js, lib/modules/apostrophe-users/index.js
With this change, any subclass of pieces with a "lib/cursor.js" will automatically load it. This includes project level.
It must export a moog definition (an object with `construct` or perhaps `afterConstruct` functions). The cursor is "self" in these functions. In other words it looks just like a module "index.js" file. 
No "extend" property is required, unless you're actually looking to avoid extending the usual thing.
Boom!
No overriding "self.find", no calling "apos.define". Nuttin. It just works. 
This addresses the pain point of remembering how to `apos.define` and require cursors, the one thing we frequently have to manually define on the server side, every time we want to add filters. I think this has been one of the reasons why folks have been slow to stop adding filters in …
=> autoload cursor definitions

lib/modules/apostrophe-login/public/css/always.less, lib/modules/apostrophe-ui/public/css/components/admin-bar.less
fix for boilerplate `login.html` styles. feels a little strange pushing styles for `html` and `body` just within this module.
=> 100% height for login takeover page

lib/modules/apostrophe-images-widgets/index.js
Was missing a ".html" extension, and the hash wasn't quite right either
=> Corrected link to tutorial page

lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-areas/public/js/user.js, lib/modules/apostrophe-areas/views/area.html, lib/modules/apostrophe-rich-text-widgets/public/css/components/rich-text-widget.less, lib/modules/apostrophe-ui/public/css/components/buttons.less
Addresses #647 & #699 
A couple subtle changes:
Rich text widget controls now float completely above the widget, leaving the content of the widget unobscured while interacting with it. To achieve this without interfering with the widget above I'm toggling the `pointer-events` property to only be active when moving from the widget to the control set.
The classic Areas inside Areas pattern where the top and bottom controls of the outer widget are on the same horizontal as the first widgets of the inner areas
I've added a `role` option to the `apos.area` configuration that can be set to `layout`
```
{# ########################### #}
{# THE LAYOUT WIDGETS #}
{% macro layout(context, name) %}
{{ apos.area(context, name, {
widgets: {
'pl-marquee': {},
'pl-block-title-column': {}, …
```
=> [Area UX] Changes to Areas controls

CHANGELOG.md, index.js, lib/modules/apostrophe-areas/lib/helpers.js, lib/modules/apostrophe-module/index.js, package.json
* Introduce a syntax error, like an extra {, into a cursor.js file and you'll see that you get a much more useful error message than before when you type "node app", because the line number is included.
* With any error during apostrophe startup, you get just one error message and stack trace, not multiple copies.
=> Smart errors

lib/modules/apostrophe-areas/lib/routes.js
I ran into this when I had a `-` in my singleton name. Took a while to track it down.
=> better save-area error messages

lib/modules/apostrophe-express/index.js
Apostorphe uses body-parser however this cannot be customized at the application level. Not even by overriding the middlewares using the "middelware" array.
body-parser also provides a way to set the "limit" of the request body, which is a common solution for the *request entity too large* nodejs error.
The proposed change allows the developer to customize the body-parser "limit" at the app.js level, or data/local.js level
=> Allow body-parser customization at the app.js level

lib/modules/apostrophe-assets/index.js
This is just basic sourcemap support for less files in dev, where the less-middleware is in use. Just needed to be configured properly.
However there is a known issue in both Chrome and Firefox that hampers the utility of this:
https://github.com/less/less.js/issues/2033
=> sourcemaps in dev

lib/modules/apostrophe-rich-text-widgets/public/js/editor.js
Fixes #802. Previously, a new CKEditor instance would be initialized after a timeout of 250ms. With this change, it's initialized when the `instanceReady` event is fired.
=> In apostrophe-rich-text-widgets, initialize CKEditor on instanceReady

lib/modules/apostrophe-assets/index.js
This PR fixes #809. LESS will preserve @import statements for regular CSS files when compiling files, which means that when minifying, clean-css is the module responsible for the final concatenation of all CSS files. Before this change, the @import paths would be absolute, and clean-css wouldn't know where to start looking.
Looks like my editor removed a bit of trailing whitespace here as well, so the diff is a bit larger than the actual change.
=> Pass root option to clean-css when minifying CSS

lib/modules/apostrophe-areas/public/css/user.less
The issue I'm trying to solve for is when you have a widget that with editing controls that would always be obscured by the Apostrophe menu button or the page menu button. In my specific case, it was the footer:
Without this change, it's basically impossible to edit my footer content.
The change does mean that as you scroll by widget controls will hover over the Apostrophe menu button. This might be something we don't like:
Not sure if this is the best solution, but I think we should figure out a way to make this work that doesn't require doing area/widget specific overrides in the project level
=> wondering if it makes sense to give the area widget controls more z-index

lib/modules/apostrophe-areas/public/css/user.less
Some CSS must have with item separators, this makes sure that empty area's dropzones are nice, juicy targets, unlike this
http://recordit.co/ihWPvWEHeK
=> Better empty area droppable state

lib/modules/apostrophe-assets/index.js, lib/modules/apostrophe-global/index.js, lib/modules/apostrophe-global/public/js/user.js, lib/modules/apostrophe-global/views/editorModal.html, lib/modules/apostrophe-pieces/lib/browser.js
See #843
Implemented this, and also fixed a deep, hilarious bug: the pieces module has been clobbering the pushAsset call for user.js and certain others all this time. We missed it because people kept re-pushing these for their subclasses rather than kicking me hard enough. A simple application of the super pattern resolves this forever.
I think people probably just figured pushAsset didn't really cascade and push the same files in subclasses (it absolutely does, but if you override pushAsset and never call superPushAsset...)
=> Implemented #843, global preferences editing via the apostrophe-global module

lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/views/widgetControls.html, lib/modules/apostrophe-ui/public/css/components/buttons.less
Reverts punkave/apostrophe#849
@stuartromanek your branch seems to have eliminated singleton edit controls (possibly only if the singleton already exists, I'm not sure). Sending this back to your workshop for that one.
Also, it contains a reference to `@white`, which fails on projects without a @white and should probably be `@apos-white`.
=> Revert "each widget now has one piece of admin chrome that combines Edit butt…"

lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/views/widgetControls.html, lib/modules/apostrophe-ui/public/css/components/buttons.less
(this is a cleaned up version of https://github.com/punkave/apostrophe/pull/849)
=> consolidate Edit and Move controls in the editing interface

.travis.yml
I haven't removed the CI build against Node.js 0.10 in case you still have some clients using this version. But running the CI against "stable" and "lts" is preferable over 0.10 anyway.
PS : "lts" has been added to NVM (which Travis CI relies on) recently: https://github.com/creationix/nvm/pull/1070
=> Add Node.js stable and Node.js LTS versions to CI

lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/js/user.js, lib/modules/apostrophe-schemas/views/macros.html, lib/modules/apostrophe-schemas/views/object.html
I closed PR#872 to respect whitespaces.
Add a new field type "object" to handle nested objects in mongo data.
It can be used as an "array" type, that is to say with a schema using other field types, even objects (so objects in objects) and complex structures (attachments, areas, joinByOne, joinByArray, ...):
```js
extend: 'apostrophe-pieces',
name: 'module-test',
label: 'Test',
addFields: [
{
name: 'objectFirstLevel',
label: 'Object First Level',
type: 'object',
schema: [
{
name: 'randomField1',
label: 'Random Field 1',
required: true
}, {
name: 'randomField2',
label: 'Random Field 2',
type: 'boolean'
}, {
name: 'objectSecondLevel',
label: 'Object Second Level',
type: 'object',
schema: [{
name: 'randomField3',
label: 'Random Field 3', …
```
=> Sanitize field type object

lib/modules/apostrophe-pieces/index.js, lib/modules/apostrophe-schemas/index.js
Implements #652 
This is fully bc with the existing implementation of join configuration.
Here is a very well fleshed-out example, in which implicit configuration is used for many types of joins, plus the new `reverseOf` property is used to avoid having to guess at what `idField` or `idsField` might be.
Configuration is now implied wherever that is possible, and can still be explicit wherever it is not.
Also, "label" is now implied by "name" for all types, using the `_.startCase` method of lodash.
```
'opinions': {
name: 'opinion',
extend: 'apostrophe-pieces',
addFields: [
{
name: '_author',
type: 'joinByOne'
}
]
},
// authors module
'authors': {
name: 'author',
extend: 'apostrophe-pieces',
addFields: [
{
name: '_opinions',
type: 'joinByOneReverse'
},
{
name: '_comments',
type: …
```
=> lazy join configuration has been implemented

lib/modules/apostrophe-express/index.js
Rationale for this:
1. It will always be http for a local dev server.
2. In some terminal programs, you can click a valid URL to have it open in the browser. Prepending the protocol allows this.
=> Prepend protocol to dev server URL

lib/modules/apostrophe-attachments/lib/api.js
Allow backend modules to insert attachments. Basically it's an override of the `accept` method with a `permissions: false` option.
=> Add an insert method to apostrophe-attachments to match pieces behaviour

.travis.yml
v0.10.x is End-of-Life since 2016-10-31 cf. https://github.com/nodejs/LTS
This will speed up CI tests
=> Remove CI tests on utterly obsolete 0.10 Node.js

lib/modules/apostrophe-ui/public/css/components/admin-bar.less, lib/modules/apostrophe-ui/public/css/components/context-menu.less
Specifically fixes a Michelin bug #73, found in their workflow testing.
=> Moving the apostrophe buttons and menu above the WYSWYG editor.

lib/modules/apostrophe-pages/public/js/reorganize.js
I didn't make it a font awesome icon, since it was passed as a label param, and I didn't see any other precedent in the code for passing HTML as a label in the code. Plus, it was a quick fix, and we already use the text string "Home" to label the root of the tree.
=> Changed page tree trashcan from utf8 icon to a simple text label

lib/modules/apostrophe-templates/views/outerLayoutBase.html
Added a Nunjucks block to allow overriding Apostrophe's `create` and `mirror` calls. The goal here is to allow overriding the modules calls to easily plug in Webpack.
=> Addition of a nunjucks block wrapping the modules calls in `outerLayoutBase.html` in `apostrophe-templates`

lib/modules/apostrophe-modal/public/css/components/modal-header.less, lib/modules/apostrophe-modal/public/css/components/modal.less
1. The modal-header update is related to the fact that the title was squished together if the content was more than one line long.
2. The hover state is added, because the contrast between locales that were links and locales that weren't links was not distinct enough which made it unclear which were clickable.
=> A couple style changes to improve UI/UX related to workflow changes

lib/modules/apostrophe-login/views/loginBase.html
Pull request to fix apostrophe-login/loginBase.html to use apos.prefix instead of aposPrefix.
=> fixed aposPrefix to apos.prefix

lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/views/widgetControls.html
https://github.com/punkave/apostrophe/issues/919
Allows developers to position widget controls by passing in a 'position' property into a widget. The following values can be passed in:
- bottomLeft
- bottom RIght
- topRIght
- topLeft (default position, but developer may use it for granularity)
`{{ apos.singleton(data.global, 'footer', 'my-footer', { position: "bottomLeft" }) }}`
=> TKT-919 / Position widget controls via options object in widget

lib/modules/apostrophe-ui/public/css/vendor/font-awesome/variables.less
There is a conflict between this variable **@fa-font-path** which finish with a slash, and urls inside **paths.less** which are beginning with a slash.
Exemple -> 
`@fa-font-path: '/modules/apostrophe-ui/fonts/';`
`url('@{fa-font-path}/fontawesome-webfont.eot?v=@{fa-version}');`
=> Removing slash from @fa-font-path variable

lib/modules/apostrophe-ui/public/css/components/dropdown.less
Fixes the overflowing inactive dropdown area issue:
=> Fixes overflowing bottom area menu

lib/modules/apostrophe-assets/index.js
It seems that previously, the docs have instructed to use the `options.scene` property rather than `options.when`. I believe this was just a plain error, let me know if not.
Some trailing whitespace was also removed in the diff, didn't think it would be much of an issue.
=> Fix error in apostrophe-assets documentation for self.pushAsset method

lib/modules/apostrophe-doc-type-manager/public/js/chooser.js, lib/modules/apostrophe-images/views/manageGridView.html, lib/modules/apostrophe-pieces/lib/api.js, lib/modules/apostrophe-pieces/lib/routes.js, lib/modules/apostrophe-pieces/public/css/manager.less, lib/modules/apostrophe-pieces/public/js/manager-modal.js, lib/modules/apostrophe-pieces/views/manageListView.html, lib/modules/apostrophe-pieces/views/manageResultLabel.html, lib/modules/apostrophe-pieces/views/manageSelectEverything.html, lib/modules/apostrophe-pieces/views/piecesMacros.html, lib/modules/apostrophe-schemas/index.js, package-lock.json
Assigning to Bob for code review and Stuart for styling.
Stuart, note that in a grid view there is one checkbox which is currently hanging out north of the filters it's meant to be next to. In a list view, you get that, and you also get the checkbox you always got before. Both work sensibly, but feel free to hide the new one with CSS if you don't think that is a good idea.
=> Support for "select everything" (#1097), requires styling

defaults.js, lib/modules/apostrophe-jobs/index.js, lib/modules/apostrophe-jobs/lib/api.js, lib/modules/apostrophe-jobs/lib/browser.js, lib/modules/apostrophe-jobs/lib/implementation.js, lib/modules/apostrophe-jobs/lib/routes.js, lib/modules/apostrophe-jobs/public/css/user.less, lib/modules/apostrophe-jobs/public/js/modal.js, lib/modules/apostrophe-jobs/public/js/user.js, lib/modules/apostrophe-jobs/views/modal.html, lib/modules/apostrophe-jobs/views/progress.html, lib/modules/apostrophe-pieces/index.js, lib/modules/apostrophe-pieces/lib/api.js, lib/modules/apostrophe-pieces/lib/routes.js, lib/modules/apostrophe-pieces/public/js/manager-modal.js, lib/modules/apostrophe-schemas/index.js
From the apostrophe-jobs docs:
The `apostrophe-jobs` module runs long-running jobs in response
to user actions. Batch operations on pieces are a good example.
The `apostrophe-jobs` module makes it simple to implement
progress display, avoid server timeouts during long operations,
and implement a "stop" button.
See the `run` method for the easiest way to use this module.
The `run` method allows you to implement routes that are designed
to be paired with the `progress` method of this module on
the browser side. All you need to do is make sure the
ids are posted to your route and then write a function that
can carry out the operation on one id.
If you just want to add a new batch operation for pieces,
see the examples already in `apostrophe-pieces` and those added
by the …
=> DGAD 266: batch operations now run via the new apostrophe-jobs module

lib/modules/apostrophe-modal/public/css/components/modal-breadcrumbs.less, lib/modules/apostrophe-modal/public/css/components/modal-header.less, lib/modules/apostrophe-modal/public/css/components/modal-tabs.less
I attempted to make a few adjustments to the overlay UI for improved consistency in where borders are placed, the colors of those borders and the spacing of the breadcrumb items.
I realize that these things are always subjective, but I still felt that these changes had some pretty clear aesthetic gains.
If there is something you are unsatisfied with, then what I feel most strongly about is the bottom border of .apos-modal-breadcrumb as well as the lighter border color of the .apos-schema-tab's
I attached two before and after screenshots for reference.
Before:
After:
=> Miscellaneous UI improvements

lib/modules/apostrophe-doc-type-manager/public/css/chooser.less, lib/modules/apostrophe-images/public/css/grid-view.less, lib/modules/apostrophe-modal/public/css/components/modal-tabs.less, lib/modules/apostrophe-modal/public/css/components/modal.less, lib/modules/apostrophe-pages/public/css/user.less, lib/modules/apostrophe-schemas/public/css/components/array-editor.less, lib/modules/apostrophe-ui/public/css/components/tables.less
`overflow: scroll` will force browsers to always render scrollbars, while `overflow: auto` will tell them to only do it when necessary. On mac OS, this is less of an issue, since users will often have overlay scrollbars, but a lot of other platforms don't, in which case it gives a more elegant impression to use `overflow: auto`.
Reference screenshots for comparison:
`overflow: scroll`
`overflow: auto`
=> Use overflow: auto; rather than overflow: scroll; in UI

lib/modules/apostrophe-attachments/lib/api.js, lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-utils/lib/api.js
Hello,
I was giving a try to your amazing framework, and I have seen that there was something missing in attachment insertion (upload or copy), from what I could test, I saw that the file length was present in data returned by uploadfs (as size field and not length), but in case of a copy, this info is not present, so I have added an utility function to get file size in bytes (in utils) and use it to fill the length property before inserting.
I also notice that there was a typo in schema for area and singleton field type in the isEmpty method.
=> fix: fill attachment length on insert

lib/modules/apostrophe-docs/lib/api.js, lib/modules/apostrophe-jobs/lib/api.js
Necessary accommodations to implement apostrophe-site-review. These are:
* New `runNonBatch` method of `apostrophe-jobs`. Similar to the `run` method, but it is for long-running jobs that don't just iterate doing the same exact thing to many pieces.
* Factored out an `ensureSlug` method, for modules that need that to exist in `docBeforeInsert`, before `docBeforeSave` has a chance to do it.
=> apostrophe-site-review accommodations 1

lib/modules/apostrophe-browser-utils/public/js/always.js
`clonePermanent` was updated on server but not browser to treat only true arrays as arrays. Now this is consistent, fixing a problem with attachments in schemas seen on CP.
=> clonePermanent 

lib/modules/apostrophe-images-widgets/views/widgetBase.html
Allows the title to be hidden using CSS when not required. 
It's not always pretty to show the image title when the widget is used, and especially when it's embedded in other widgets. Adding a class to the h4 image title allows it to be easily hidden using CSS only when it's not required.
=> Added class to h4 image title

lib/modules/apostrophe-html-widgets/index.js
When adding an HTML field for a client it seemed that help text would be valuable to head off and deal with code conflicts. I figured that might be worth including by default. Some of the text is taken from the comment at the top of that file.
=> Adds help text to html fields by default

lib/modules/apostrophe-docs/lib/api.js, lib/modules/apostrophe-docs/lib/cursor.js, lib/modules/apostrophe-pages/lib/pagesCursor.js, lib/modules/apostrophe-permissions/lib/api.js, lib/modules/apostrophe-permissions/lib/strategiesApi.js
* Filters like `children` and `ancestors` should not make any query at all if there are no docs returned by the original request. Formerly this was handled by making a query that never matches. To make matters worse, it was an extremely inefficient, unindexed query that never matches. 😢 
* In cases where we really do need to add a clause that never matches, at least for now, in order to avoid a major refactoring of code that is trying to stick to good separation of concerns and not try to cancel or even touch the larger query it is becoming a part of, we should write `{ _id: '__iNeverMatch' }` instead of `{ iNeverMatch: true }`, because `_id` queries are always indexed. In most of these cases, there are other clauses making the query efficient anyway, but the `explicitOrder` filter could …
=> dgad 417: query optimizations

lib/modules/apostrophe-templates/views/outerLayoutBase.html
Added a block surrounding the context menu code. This will allow developers to control access to this menu by simply overriding the block inside of their local "lib/modules/apostrophe-templates/views/outerLayout.html"
=> Added block to the context menu

lib/modules/apostrophe-attachments/public/js/cropEditor.js
Closes #1217 
Disable Cross Origin Check of copper.js plugin by passing relevant option, as per discussion here https://github.com/apostrophecms/apostrophe/issues/1217
=> Fix preview of crop image in Cross-Domain scenario

lib/modules/apostrophe-templates/index.js
In an older 2.x project we're passing a date from the Twitter API through the date filter, bypassing the normal processing in apostrophe-twitter-widgets' [`getRelativeTime`](https://github.com/apostrophecms/apostrophe-twitter-widgets/blob/master/index.js#L159) method. This caused Moment.js to kick out this warning:
> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
The change here uses the `Date.parse()` method in the date filter the same as apostrophe-twitter-widgets does to prep the …
=> Parses date before moment processing

lib/modules/apostrophe-attachments/index.js, lib/modules/apostrophe-attachments/lib/api.js, lib/modules/apostrophe-images/views/manageGridPage.html, test/attachments.js
=> fixed the issue (see #1370) and added a migration to address it retroactively

lib/modules/apostrophe-templates/index.js
Reverts apostrophecms/apostrophe#1362
The ISO conversion removes consideration of the time zone. The issue with MomentJS requiring strict ISO or RFC formats in a future release does need to be dealt with, but there's not an obvious solution and this is causing problems now.
=> Revert "Parses date before moment processing"

lib/modules/apostrophe-tags/public/js/manager-modal.js
Currently, in the tag management modal (in the admin bar category "Tags"), if the input is empty and the user clicks the "+" button to add a tag, there is an error message "An error occurred. Please try again.".
Several users complained it is not clear the problem is coming from an empty value. That is why I propose this pull request to have a clearer explanation. Also, this PR blocks the whole process of going through apostrophe-pieces and apostrophe-db `insert` method only to find out the there is no title in the new piece to add (because the title is filled with an empty tag value).
=> Tag creation: check if value before adding tag

lib/modules/apostrophe-utils/lib/api.js, package.json, test/utils.js
See #1427 
Placeholder implementation, with tests verifying it does no harm. For now at least the version in the core intentionally does nothing, profiler modules then have an open door to implement it (and the overhead it might involve). The apostrophe-debug module now expects this API.
=> implemented profiling API (with do-nothing placeholder version, so it is always safe to call)

lib/modules/apostrophe-ui/public/css/components/fields.less
This ensures that these arrows are vertically centered – no matter what height the field has in different browsers.
I could imagine a mix-in like
```less
.apos-center-vertical-abs() {
top: 50%;
transformY: (-50%);
}
```
to enable consistent styles across Apostrophe and project level changes.
And how about using `::` instead of `:` for pseudo-elements, since that is the current spec?
=> Vertically center dropdown arrows for select fields

lib/modules/apostrophe-ui/public/css/global/infinitescroll.less, lib/modules/apostrophe-ui/public/js/ui.js
**Problem 1:**
Some browsers (among them Safari) fails to find the scroll position from html / body using jQuery. This is potentially related to the site having `overflow-x: hidden;` on the `html`tag.
This PR strengthens the browser lookup for the scroll position in all browsers (that I was able to test).
**Problem 2:**
Additionally jQuery fails to find the `offset.top` of the hidden "load more" button, due the button being `display: none;` in CSS/LESS. According to the jQuery documentation an element being styled with `display: none;` is excluded from the rendering tree and thus has a position that is undefined. This has been changed to `display:block;` and `visibility:hidden` This can affect the invisible space on existing sites below the AJAX content, but there's no other way and site …
=> Strengthen broken infinite scroll in some browsers and site configurations

lib/modules/apostrophe-tags/views/manager.html
This PR corrects the label for the tags modal.
This modal is the only modal using the label "Finish", where all the other modals use "Finished".
=> Fix label for finished button in tags

lib/modules/apostrophe-pages/index.js, lib/modules/apostrophe-templates/views/outerLayoutBase.html
This PR fixes a bad route on the "red" context menu to publish a page. It seems that the "route" was renamed at some point and this created inconsistency from the data attribute to the JS resposible for kicking off the request to publish the page.
I also moved this publish menu to the right of the normal context menu to avoid the main context menu "jumping around" when moving to and from pages which are unpublished. I don't think it's good UX practice to have a consistent menu move around rather "randomly" unless the user herself decides to by interacting with the UI.
=> Fix broken publish context menu for pages

lib/modules/apostrophe-pieces/public/js/editor-modal.js
This PR fixes a missing redirect of the user after deleting a piece within the modal editor of the piece.
When deleting a piece in the context menu, Apostrophe would redirect correctly, but when doing it in the modal, it would stick around on the new delete piece creating confusion.
=> Redirect after deleting piece

lib/modules/apostrophe-modal/public/css/components/modal-batch-operations.less, lib/modules/apostrophe-pieces/public/js/manager-modal.js, lib/modules/apostrophe-pieces/views/managerModalBase.html, lib/modules/apostrophe-ui/public/css/components/fields.less
This PR improves batch operations in the editor modal.
Due to missing disabled attributes on the button, the button is clickable even if no items has been selected for a batch operation. This is now corrected with a check in JavaScript.
At the same time the text for the confirmation has also been made "plural aware".
The UI is improved by rounding the dropdown, fixing the arrow position, by removing specific styling for the dropdown, and relying on the recent flexbox additions to arrows in general.
For tags, the field to add tags has been moved to the left, so it appears between the batch operation dropdown and the button to perform the action. It was appearing to the right of button before this PR, which could be confusing.
=> Improve batch operations UI

lib/modules/apostrophe-attachments/lib/routes.js
This fixes the static 'err' message when uploading unsupported file via apostrophe-attachments. The change renders a meaningful message in the frontend in case of error.
=> Fix for error message sent by attachments module

lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/css/user.less, lib/modules/apostrophe-schemas/public/js/user.js, test/schemas.js
This PR aims to decouple the `required` field configuration with `min` and `max` values for fields (pieces, pages etc).
Currently, if a field is not required, then it will become required by a `min` or `max` value configuration. This means it's not possible to validate the user input without also requiring the field.
With this PR, if a field additionally has `required: true` then it will both be required and the value has to be in the range of `min` / `max` or either of them if only one is set.
This gives the maximum flexibility in relation to ensuring that a value is properly filtered / checked without also geting 0 values into the field value for example for floats. Currently if a `min` value was set to 1 and `max` was set to 10, then it would not be possible to save the field which …
=> Decouple min/max validations from required for integer, float and string fields

lib/modules/apostrophe-ui/public/css/components/autocomplete.less
This relates to PR #1432 which never made it in, because it was modifying the vendor file.
This overrules the basic styling of jQuery UI in a way that jQuery UI vendor can be updated without this breaking (unless there's changes to the class names or structure of the autocomplete of course).
I kept the styling pretty basic (bold font on active), but I could add more transitions if someone would point me in the direction of what you would like.
=> Fix styling of autocomplete item active state

lib/modules/apostrophe-pieces-widgets/index.js
It's possible to define pieces selected through the property `by` in custom pieces widget.
However set `by` to `['all']` crashs the application, which try to read a property of an undefined value in an if condition.
Create a custom pieces widget extending `apostrophe-pieces-widgets` with the following `by` restriction:
```
extend: 'apostrophe-pieces-widgets',
by: ['all'],
...
}
```
Try to run the application, which will crash with the following error
```
TypeError: Cannot read property 'relationship' of undefined
at Object.self.pushPieceForWidget (/Users/seao/Travail/Stage/Michelin/bicycle/node_modules/apostrophe/lib/modules/apostrophe-pieces-widgets/index.js:297:24)
at ...
```
Change
`if (self.joinById.relationship && (widget.by === 'id'))`
to
`if (self.joinById && …
=> Fix condition that use potential undefined variable and crash the application 

lib/modules/apostrophe-pages/views/reorganize.html
The current pages admin modal is not completely consistent with the rest of the admin modals in Apostrophe.
This PR introduces a new button on the upper right side of the of the modal with the label "New Page" (same as bottom menu uses), styled as a major button.
The "Finished" button was styled as a major button before, which was inconsistent for the UI as every other admin modal uses minor styling for the "Finished" button.
Hope to see this PR make it into the core as it improves usability in relation to page management and at the same time corrects inconsistencies in the Apostrophe admin UI.  I do have other concerns and improvements in mind for this area, but I will probably get back to those in another PR if this one is accepted.
=> Improve Pages admin UI

lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/js/user.js, test/schemas.js
This PR improves earlier work I did on validation of integers and floats.
Before this PR it would be possible to submit a non numeric value and get through validations for a integer or float field.
This PR introduces a new check that validates the value (if a value is subitted) and does a callback with `invalid` as the argument, so the error can be output.
This validation is not relying on neither `required` nor `min` or `max`.
Added plenty of tests to cover this new validation, and the existing ones are still passing.
=> Improve NaN validations for integers and floats

lib/modules/apostrophe-login/index.js
This PR adds a **one second** delay in the response on a brute force attack or incorrect login.
This is a common technique to make it harder make many (automated) login attempts to "guess" a users password.
I would like to implement a more sophisticated method for this, which would gradually slow down the possibility of trying a login, for example after x attempts in n minutes, Apostrophe would reject any login route from that IP. That will be a more complex implementation though, which would require the use of a database collection to to keep track of failed logins.
Before starting the more advanced one, if there's interest for such an improvement, I would like to have a discussion about the goals for such an implementation. I'm thinking that there could be some sensible default values …
=> Slow down brute force attacks

CODE_OF_CONDUCT.md, CONTRIBUTING.md
The contributor convenant code of conduct is used by many open source projects, including Vue.js. It is a straightforward document laying out that discriminatory behavior and harassment won't fly here. The Apostrophe community is a very welcoming place at present, and now is the time to lock in that norm as the community begins to grow rapidly.
This would be in addition to, not in place of, Bob's revisions to the "contributing" file as those have more to do with the specifics of how to contribute.
=> Adds the contributor covenant code of conduct

lib/modules/apostrophe-schemas/lib/routes.js, lib/modules/apostrophe-schemas/public/js/array-modal.js
This PR fixes the left sidebar state for an array item. Before this PR there would be no indicator of which array item is currently active.
With this fix, the background of the active clicked item goes light to clearly indicate which item you are currently editing.
This seems to be a forgotten implementation or a regression, because the template did have a check for active item, but the browser side JS never sends the current active/clicked item, so the route cannot pass it on to the template when rendering.
This PR potentially conflicts with the fairly important tolerant-arrays branch/fix, but if that branch is merged, I will update this one to merge cleanly with master thereafter.
Not so super related note: Doing this one I got a bit better insight in the UI issue with required fields …
=> Fix active state of array items

lib/modules/apostrophe-attachments/public/js/user.js
This PR fixes the file upload busy state check.
The busy check was done on the fieldset, when it should be done on the "uploader button" which holds the busy state.
Tested that with this fix, the form will not finish converting and subsequently submitting, until the file has finished uploading.
As a bonus for fixing this one, I hope that #1509 will also be accepted, as making use of that one let's me do UI stuff while the upload is in progress. This one will be more of a safe guard to make sure the form is not submitted until the file has finished uploading.
=> Fix file upload busy state check

lib/modules/apostrophe-notifications/public/css/user.less
This PR fixes notification colors, also when the modal overlay is not present.
Before this PR notifications of type success, warning and error would sometimes display with a white background. Both on top of a modal and when there was no modal.
This PR takes a simple approach to make those notifications get a higher priority so that the background colors will always display.
Fixes #1491.
=> Fix notification colors

lib/modules/apostrophe-attachments/public/js/user.js
This PR adds a few more emit events to file uploads.
Currently there's only one event that one can listen on inside a widget player.
My use case is a public user submitted form which includes a upload field for files.
Before this PR it would be hard for me to lock up the UI **while** the file(s) are being uploaded, which would result in a potential form submitted without the file actually attached.
Having more events to listen on, one can listen to various events and have the UI react accordingly. It will even be possible to discard events or differentiate depending on the field name / field schema configuration.
I'm open to renaming these of course, and I don't have a specific use case for each and every one of them now, but since I am adding the ones I need, I thought I would try to …
=> Add more upload emit events

lib/modules/apostrophe-attachments/public/js/user.js
This PR sets the type error of the notification, when a file upload extension is not allowed by configuration.
Before this PR it would be white (no background) — after this PR it will be red.
=> Fix background color on notification on uploads when file extension is not accepted

lib/modules/apostrophe-schemas/public/css/user.less, lib/modules/apostrophe-schemas/public/js/user.js
This PR fixes nested error messages.
Consider a checkbox field with a fieldset containing a label for the main label, and checkboxes with a label for each checkbox.
Before this PR, all labels would get the "required" error and become styled accordingly.
This PR fixes that behavior and ensures the error and styling is only applied to the first label within the fieldset.
=> Fix nested error messages

lib/modules/apostrophe-attachments/views/attachment.html
This PR fixes a small design flash/jump in the design, when loading an attachment field in a schema.
Before this PR, the preview area would flash/jump due to it being hidden `with jQuery.hide()`.
`.hide()` is still in use, just to make sure, but additionally an inline style is added with `display: none;` to make sure there's the browser is not waiting for jQuery to kick in. This removes the jump/flash. When the user later adds a file and the preview becomes available, jQuery is doing `.show()` and with that removes the inline style so the preview image is shown.
It's the small things, I know... But they all count :) And yes, this could be styled in a less file, but considering that the same template has another inline style I thought I would keep it like that. This can always be moved …
=> Fix initial flash/jump of attachments preview

lib/modules/apostrophe-areas/views/widgetControls.html, lib/modules/apostrophe-images/views/manageViewChoices.html, lib/modules/apostrophe-modal/views/macros.html, lib/modules/apostrophe-pieces/views/manageViewChoices.html, lib/modules/apostrophe-schemas/views/macros.html, lib/modules/apostrophe-versions/views/macros.html
This PR corrects unnecessary spacing inside HTML tags in various places.
Instead of adding a space, then doing a condition which may add an attribute or class, this PR corrects that, so that the space is only added if the condition is true.
This is minor nitpicking, but Apostrophe should of course, try to output HTML as clean as possible. This is one tiny step in that direction.
=> Cleanup HTML output

lib/modules/apostrophe-areas/public/js/editor.js
When widgets are rerendered, this change makes it so that we also account for the possibility of the classes having changes on the widget wrapper.
Basically, if the module has a `getWidgetWrapperClasses` method that changes its output when the properties of the widget change, this change makes it so that we pick that up without having to reload the page.
=> Update class of widget wrapper in self.replaceWidget

lib/modules/apostrophe-versions/lib/api.js
This PR fixes a crash that happens when `oldText` or `currentText` is for some reason undefined.
The diff library is trying to split on a string value that's undefined and that chokes, resulting in a server crash for me.
Corrected by skipping the diff if either is undefined. There may be a better way, let me know and I will update the PR.
**Stacktrace:**
```javascript
/path/to/apostrophe/node_modules/diff/lib/diff/sentence.js:16
return value.split(/(\S.+?[.!?])(?=\s+|$)/);
^
TypeError: Cannot read property 'split' of undefined
at Diff.sentenceDiff.tokenize (/path/to/apostrophe/node_modules/diff/lib/diff/sentence.js:16:16)
at Diff.diff (/path/to/apostrophe/node_modules/diff/lib/diff/base.js:35:39)
at Object.diffSentences (/path/to/apostrophe/node_modules/diff/lib/diff/sentence.js:20:23)
at …
```
=> Versions compare: Fix crash when oldText or currentText is undefined

lib/modules/apostrophe-versions/public/js/editor.js, lib/modules/apostrophe-versions/views/versions.html
This PR improves the usability of the versions modal.
With this PR Apostrophe will now allow the user to click on the same "See Changes" link to close a version change, which is nice when comparing many and long changes.
Additionally a default message is shown if there is no changes to display. This message is added in the template and fetched in JS to make it localizable.
=> Improve versions UI

lib/modules/apostrophe-images/lib/api.js, test/images.js
Firstly, this change makes it so that the `apos.attachments.isSized` return value is respected. If a particular attachment isn't sizes (eg. if it's an SVG), we return an empty srcset attribute. This change was prompted by #1595.
Secondly, we now never return image sizes that are larger than the original. And we also make sure to include the original image size in the srcset return value. I would just like to check if including the `original` image size in the srcset attribute seems reasonable to the core devs (@boutell, @stuartromanek etc). Does uploadsfs compress that image as well, or could it be that `original` is a huge images, whereas the other image sizes are compressed?
=> Improvements to apos.images.srcset function

lib/modules/apostrophe-rich-text-widgets/public/css/components/rich-text-widget.less
This PR adds rich text editor styling for the most common tags in the Apostrophe modal rich text editor.
It seems these were forgotten, leading to random styling depending on how the project was styled. This PR adds basic support for the most common tags.
Tags like H1, H2 is not included as they are not considered by me to be basic and those tags should be added using the `styles` option of the rich text editor.
To test use the following configuration on a field:
```javascript
options: {
toolbar: [ 'Styles', 'Bold', 'Italic', 'Link', 'Unlink', 'BulletedList', 'NumberedList' ]
}
```
I will post a screenshot to display the various styles based on the improvements introduced in this PR.
And yes, underline is not there, because the underline tag is no included html 5, and ckeditor does not …
=> Add rich text styling for most common tags in Apostrophe modal rich text editor

lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-schemas/public/js/array-modal.js, lib/modules/apostrophe-schemas/public/js/user.js, lib/modules/apostrophe-widgets/public/js/editor.js, lib/modules/apostrophe-widgets/public/js/user.js
This fixes common problems when "required" is added to the schema later, or when the site formerly ran a version of Apostrophe that didn't enforce all constraints browser- or server-side.
=> Apostrophe schema fields, including arrays with nested fields, can now return the user to the scene of a server-determined error for further editing

lib/modules/apostrophe-global/index.js, lib/modules/apostrophe-global/views/busy.html, lib/modules/apostrophe-locks/index.js, package.json, test/caches.js, test/global.js, test/lib/modules/apostrophe-pages/views/pages/home.html, test/locales/en.json
This method allows you to run a function to completion while the entire site is paused. Obviously this should be super rare, used for things like deploying entirely new content to the site, and would have a hideous performance impact if used routinely. But it's very useful for a big operation like replacing all the content without a period of inconsistent results (as requested in DGAD-449).
HOW YOUR FUNCTION GETS RUN
A lock is obtained, the `global` doc is marked busy, and then requests in progress are waited out with a simple timer rather than trying to actually track them because the performance cost of tracking them across load-balanced cores and servers would be too high.
Next your function runs. If it returns a promise the promise is awaited. This is a new API and supporting both can …
=> Added apos.global.whileBusy(fn) method

lib/modules/apostrophe-versions/public/css/user.less, lib/modules/apostrophe-versions/views/versions.html
As discussed in #1515, "Revert" is somewhat ambigous compared to "Revert to" - does it mean "undo this change" or "go back to this change"? Well it does mean the latter, and labelling it "Revert to" clarifies that.
Also, I took the chance to run some more labels in there through the i18n `__` function.
Lastly, I added some additional pixels to the subtracted width of `.apos-changes-meta`, because in viewports wider than 1450px, `.apos-button--major` receives an increase in font-weight. This adds 1 additional pixel to the width of "Revert to" now that we have more characters in there, so we need to counteract that.
=> Update versions modal "Revert" labels to "Revert to"

lib/modules/apostrophe-attachments/lib/api.js
Fix for #1653 
Please test your cropping scenario with a NEW upload initially using the .jpeg extension.
I am not sure a migration is urgently needed, it would be a significant lift and these are probably uncommon.
Thanks
=> we need to map jpeg to jpg earlier on upload, not the fault of uploadfs

lib/modules/apostrophe-ui/public/css/components/buttons.less, lib/modules/apostrophe-ui/views/components/buttons.html
As discussed in #1111.
Previously it would render an `<a>`. `<button>`s are generally better suited for this purpose, but above all it solves the problem where `<a>` elements can't be nested.
@stuartromanek, if there are other places that need updating – I'm happy to address those as well!
=> Make apostrophe-ui button macro render a <button>

lib/modules/apostrophe-assets/public/js/vendor/jquery.onSafe.js
`jQuery.fn.onSafe` would previously not pass the return value of event handlers to jQuery. That meant that even if the event handler would `return false`, event.stopPropagation and event.preventDefault would not be called.
This came up as an issue for me after the recent merging of #1638, where I now had a set of .apos-buttons inside of an area, that was wrapped in an `<a>` element. Clicking the .apos-buttons would trigger a click on the link as well, and so the browser would navigate away from the page.
=> Respect return values of event handlers in jQuery.fn.onSafe

lib/modules/apostrophe-areas/lib/api.js
Anchor elements can still be created by the button macros by passing a `url` parameter through their options. `<button>` elements don't seem to be compatible drag handles for jQuery UI so fake in an `<a>` element with a `url` of `#`. Addresses #1680
=> Button element breaks jQuery UI Draggable's drag handles

lib/modules/apostrophe-html-widgets/index.js
I realize this risks a BC break, but it seems like an oversight. Was there a reason that the HTML widget doesn't concat its `addFields` with the `options.addFields` now?
I think this might only be a BC break if someone has an HTML widget extension that intentionally leaves out the `code` field for the embed code. Which would be odd.
=> concats rather than replaces html-widget fields

lib/modules/apostrophe-docs/lib/api.js, lib/modules/apostrophe-migrations/lib/implementation.js, lib/modules/apostrophe-users/index.js
This migration code was loose in the add-missing-locales task of workflow which meant it happened more than once. It's quite slow because it requires an unindexed query. That's OK once but not every time somebody adds a locale.
=> Missing values for join relationships relating to permissions should be fixed by a one-time migration in apostrophe, not redundantly in workflow

lib/modules/apostrophe-assets/index.js
That prevents the cleanup routine from holding a lock forever. Very simple and common async module bug reported by enterprise client.
Also added missing provision to stop if the lock method fails completely.
TEST PROCEDURE FOLLOWED (I do not think you need to duplicate this to review this simple fix):
Background: 
https://apostrophecms.org/docs/tutorials/howtos/deploying-apostrophe-in-the-cloud-with-heroku.html#efficient-asset-delivery
I manually tested this via several runs of:
```
APOS_MINIFY=1 node app apostrophe:generation --create-bundle=prod-bundle --sync-to-uploadfs
```
Followed by:
```
APOS_MINIFY=1 APOS_BUNDLE=prod-bundle APOS_BUNDLE_IN_UPLOADFS=1 APOS_BUNDLE_CLEANUP_DELAY=1000 node app
```
This yielded just one folder in `public/uploads/assets` that actually had any files. …
=> added missing eachSeries callback to asset bundle cleanup

lib/modules/apostrophe-schemas/index.js
In a `joinByArray` field, a "relationship" property cannot have a nested object. 
For example, this field will trigger the warning ("unblessed array") and will not save the "relationship" data:
```
{
name: '_whatever-join',
type: 'joinByArray',
filters: {
projection: {
title: 1,
slug: 1
}
},
relationship: [
{
name: 'nestedStructure',
label: 'Nested Structure',
type: 'array',
schema: [
{
name: 'nestedField1',
label: 'Nested Field 1',
required: true
},
{
name: 'nestedField2',
label: 'Nested Field 2',
required: true
}
]
}
]
}
```
This is because the `nestedStructure` array has not been blessed. To overcome this problem, I propose the following solution: bless every nested property in the `joinByArray` definition in `apostrophe-schemas`.
=> Bless relationship nested objects

lib/modules/apostrophe-schemas/index.js
As discussed today with @boutell, the `slug` filter misses a `launder` function for filters. Here is the quick fix.
=> Add launder function to slug filter

lib/modules/apostrophe-pieces-widgets/index.js
closes #1073 
Could be improved further by removing the `limitByAll` and `limitByTag` integer fields if these options are set.
=> Option to set cursor limit for pieces

lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-areas/views/editor.html, lib/modules/apostrophe-areas/views/undoRemove.html
@stuartromanek I am assigning review to you because it looks good in the sandbox but I can't figure out how to use apos-text-normal (?) without getting an undefined error. Scoped it in apos-ui and still got one of those. Not sure if I'm barking up the right tree to make sure these get a reasonable font in any project context.
I went with the original @carlykaras suggestion of apos-purple and avoided the notification styles because the border on those turns out to be jarring when in context in a stream of widgets. This is more of an inline thing than an "unrelated context layered on top" thing.
=> 1728 undo remove widget

lib/modules/apostrophe-schemas/index.js
In https://github.com/apostrophecms/apostrophe/pull/1712, I intended to solve the problem of a nested structure not blessed. But I forgot one part in `joinByArray` bless function.
Here is the fix.
=> bless relationship in joinByArray

lib/modules/apostrophe-schemas/public/js/user.js
In the PR #1540 "Enable showFields on checkboxes", I forgot to add the line to hide/show fields in user.js for checkboxes.
Here is the fix.
=> fix missing "enableShowFields" for checkboxes

lib/modules/apostrophe-areas/src/apos/components/ApostropheAreaEditor.vue
VDDL drops the ball by creating a duplicate with a duplicate ID when a thing is moved. [They note a change in Vue's `nextTick` implementation.](https://github.com/hejianxian/vddl#warning)
This is [their current recommendation](https://github.com/hejianxian/vddl/blob/master/example/src/views/simple.vue#L131-L144) for dealing with that issue, but keeping IDs as we want them in Apos.
VDDL issue: https://github.com/hejianxian/vddl/issues/23
=> Handles duplicate ids when dragging area widgets

lib/modules/apostrophe-areas/public/js/vendor/ckeditor/config.js, lib/modules/apostrophe-rich-text-widgets/public/js/editor.js
This will include `removeButtons` in the CKEDITOR config only if those buttons haven't been listed in the toolbar config for this CKEDITOR instance. It should make the experience of reconfiguring the CKEDITOR toolbar a lot more intuitive for end developers.
=> Only conditionally apply removeButtons logic to CKEDITOR

lib/modules/apostrophe-pages/lib/api.js
This commit updates the docAfterDenormalizePermissions
method and makes it propagate the docPermissions property
as part of the the “Apply to sub-pages” functionality.
=> Fix 1783 - update apostrophe-pages api.js

lib/modules/apostrophe-db/index.js, lib/modules/apostrophe-migrations/lib/api.js, lib/modules/apostrophe-migrations/lib/implementation.js, package.json
* Progress display for `apostrophe-migrations:migrate` when individual migrations take time. If node is not running in a TTY (an interactive terminal) this automatically goes away to avoid flooding log files with progress information or creating problems for people who have already scripted Apostrophe.
* Previously if a migration function returned a promise it was executed, but its success was not recorded, so it got re-run each time. This has been fixed.
=> Migration progress and fixes

README.md
Most of the URLs automatically redirected, but punkave/apostrophe-saml for some reason did not, so I took the opportunity to change all of them.
=> Change from punkave GitHub org to apostrophecms in README

lib/modules/apostrophe-schemas/index.js
Fix the error below by checking `value` is an array:
```
TypeError: (value || []).join is not a function
at Object.index (/app/node_modules/apostrophe/lib/modules/apostrophe-schemas/index.js:1384:70)
at /app/node_modules/apostrophe/lib/modules/apostrophe-schemas/index.js:435:19
at arrayEach (/app/node_modules/@sailshq/lodash/lib/index.js:1463:13)
at Function.<anonymous> (/app/node_modules/@sailshq/lodash/lib/index.js:3525:13)
at Object.self.indexFields (/app/node_modules/apostrophe/lib/modules/apostrophe-schemas/index.js:427:9)
at Object.self.searchIndexListener (/app/node_modules/apostrophe/lib/modules/apostrophe-doc-type-manager/lib/api.js:422:23)
at Object.self.emit (/app/node_modules/apostrophe/index.js:105:19)
at Object.self.getSearchTexts …
```
=> Apostrophe-schemas/index: check if value is array

lib/modules/apostrophe-assets/index.js
Added check to see if running in a container as symlinks don't play well. If true assume same processing as windows environments for copying the static assets from Apostrophe into the public folder. Documentation for Docker needs updating to include system.env.APOS_ALWAYS_COPY_ASSETS: '1'
=> Check for type of asset copy operation

lib/modules/apostrophe-schemas/index.js
Allows pieces-import to be fully compatible with pieces-export (unfortunately we're stuck with the difference in default behavior for bc)
=> option to convert strings as rich text when importing areas

lib/modules/apostrophe-schemas/index.js
Issue -> Nested Field Types under type **object** were not blessed and the call to edit-virtual-area threw an unblessed error.
Steps to Reproduce => https://www.notion.so/Unblessed-Object-d219424afd954f7f80b82bb26a144da8
Changes => Add a new bless method for type object that will internally call the bless method of nested field types.
=> Bless nested widgets under object

lib/modules/apostrophe-attachments/lib/api.js, lib/modules/apostrophe-images/index.js, lib/modules/apostrophe-pieces/lib/routes.js, package.json
This adds select exif metadata to apostrophe-images when available. There's a ton that could be pulled from EXIF data, but I'm keeping it limited at the moment. Location was a good next candidate, but there are privacy implications to suddenly having that stored in newly updated Apostrophe sites.
Regarding the schema update, one option would be to start a new "Metadata" tab group, but "Info" currently overlaps with that pretty significantly.
=> Adds select image exif data to the image document if available.

lib/modules/apostrophe-pieces/public/css/manager.less, lib/modules/apostrophe-pieces/public/js/manager-modal.js
More logic was needed to indicate the next sorting state correctly on hover in all of the cases.
=> always indicate the next sorting state correctly on hover

lib/modules/apostrophe-schemas/public/js/array-modal.js
**Steps to reproduce :-**
1. In schema, add a two item back to back in an array
2. Ensure the active item in an array to be a last item
3. Delete any one item in an array other than last item
4. Now click add new item in an array. It’ll throw an error and the whole saved items in an array will become lose.
=> Active array item in last to be resetted when deleting other items

lib/modules/apostrophe-assets/index.js
This is probably a fairly urgent fix. Don't know if this is the ideal implementation, but it was minimal and worked!
Btw, if you want to push a quick release, please note that I had to update the required version of `moog-require` in package.json to get the latest `master` to run.
As of e3282c64244b051a42616cfc60e2e0e3c6a3711f, clean-css is no longer being used, instead LESS does all the minification. But where clean-css flattened all `@import` statements, LESS will only flatten those that target LESS files by default. `@import` statements targeting CSS files are left as they are. This change makes it so that we always signal to LESS to inline CSS files when minifying the CSS.
=> Send a signal to less to inline CSS files (not LESS) when minifying

index.js
The version **2.86.0** released few days ago brings to Apostrophe the support for scoped NPM modules as apostrophe modules. Thanks for that, it's so cool! 👍
I played a little with this new feature, and meet an issue to unit test a scoped npm module that extends Apostrophe. Core function `testModule()` is not fully able to work with scoped packages for several reasons:
1. It uses the directory name to determine the name of the apostrophe module tested, which is a problem with scoped modules that are at a sub-level.
2. It doesn't create the potential scope folder in `node_modules` that is necessary before the symlink creation.
This pull request brings the following changes:
- The module name is retrieved from `name` property in `package.json` file. If the file doesn't exists, is not valid …
=> Support unit testing for scoped NPM modules

lib/modules/apostrophe-pages/lib/api.js
This fixes a bug where, when creating pages via the API (eg via `apostrophe-headless` REST API), pages which have a multi-path slug cannot be created because "/about-us/members/someone" is translated into a slug of "about-us-members-someone".
=> API does not support slugs with path separators

index.js
When Apostrophe encounters an error during startup it is difficult to know what module is responsible because async code does not produce especially good stack traces.
With this PR, we can do:
`APOS_TRACE_STARTUP=1 node app`
And find out how far the startup process went before the error.
Here is sample output. We could do more - for instance it would be useful to print module names as we proceed through phases like 'modulesReady' and 'modulesAfterInit' - but I submit that this is incremental progress and there's no reason we can't add that when we get a minute.
Also, I think the formatting here builds on the general style of what we're doing for warnings, using a cute unicode character that conveys what kind of message it is, etc.
``` …
```
=> nice complete trace feature for the startup process

lib/modules/apostrophe-templates/index.js
This could be an optional to other devs that wanted to organize their views on multiple project views. This could be done as example :
```js
// in app.js
const path = require('path');
// other modules ...
'apostrophe-templates': { viewsFolderFallback: [path.join(__dirname, 'main-views'), path.join(__dirname, 'lib/modules/widget-views')] }
}
```
=> Support ''apostrophe-templates': { viewsFolderFallback:' by accepting an array of views folder.

lib/modules/apostrophe-areas/public/js/always.js, lib/modules/apostrophe-assets/index.js, lib/modules/apostrophe-assets/public/js/always.js, lib/modules/apostrophe-browser-utils/index.js, lib/modules/apostrophe-browser-utils/public/js/always.js, lib/modules/apostrophe-browser-utils/public/js/lean.js, lib/modules/apostrophe-push/index.js, lib/modules/apostrophe-rich-text-widgets/index.js, lib/modules/apostrophe-rich-text-widgets/public/js/lean-user.js, lib/modules/apostrophe-video-widgets/index.js, lib/modules/apostrophe-video-widgets/public/js/lean.js
Implements #1938. 
This is a WIP until I test what happens if you try to use the existing `apostrophe-lean-frontend` module with it. Probably nothing good, so I'll have to figure out a workaround to let that work before we merge.
But otherwise this works well, see the `lean-tests` branch of `apostrophe-enterprise-testbed`.
=> merge of lean frontend into core

package.json
This is in response to a vulnerability alert: https://github.com/apostrophecms/apostrophe/network/alert/package.json/diff/open. The only reported v3 breaking change reported is on a method we're not using and all tests are passing.
=> Updates the major version of diff

lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/js/array-modal.js
Fixed three array bugs:
(1) a required array hidden by showFields is in effect not required (same as other field types).
(2) Cancelling an edit operation on an array actually does revert everything, notably it does not leave you with a halfassed first entry in an array you never meant to create at all.
(3) Dynamic select and checkboxes fields work in arrays.
If you wish you can experience these fixes via the array-bug-tests branch of apostrophe-enterprise-testbed, which moves a bunch of fields of "Products" into a "Profiles" array field (look at the "Info" tab). The entire array becomes visible when you check "Has Profiles." (These are not actually regression tests, just a nice testbed for validating these fixes manually.)
closes #1969
=> phew OK just the array bug fixes in this PR I hope

lib/modules/apostrophe-pages/lib/api.js
Objective: The 'Apply to subpages' option overrides the entire permission set of subfolders/subpages with the new set of permission. But in some instances we might need to keep the existing subpages permissions while adding the new set of permission from the parent page. To achieve this i have made following changes in the code
- I have added an option for user to append permissions to subpages and subfolder, instead of completely overriding them by copying the new set of permissions from parent.
- I have optionally modified the mongoDB update query to reflect the user selection.
=> Append permissions to subpages instead of overriding them

lib/modules/apostrophe-schemas/public/js/array-modal.js
Hey guys. I found myself very frustrating when I tried to edit an array schema after I cancel the array editor modal. When I want to edit the array schema again for the second time, guess what?! My array schema is missing! The only to fix this behavior is to cancel the entire editor-modal and edit it again, then edit array schema again to view my array schema on placed. 
Well, I decided to take a look deep dive on apostrophe schemas code on array-editor modal. At first thought, it was something to do with `beforeCancel` method. But turns out, it just a simple typo when you guys wanted to clone the array items from `_.cloneDeep(self.arrayitems)` to `_.cloneDeep(self.arrayItems)`. 
Hopefully, this fix is going to patch as soon as possible. I believe other users might face this problem as …
=> Simple typo breaks important functionality

lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-areas/public/js/user.js, lib/modules/apostrophe-schemas/public/js/user.js
See #1984
Solution: robust recalculation of dotPath attributes, correction of a timing error, and elimination of area editor reuse mechanism that does not make sense because a dotPath is not a permanently unique identifier and the order changes, associating the editor with the wrong data.
Man I can't wait for 3.x to make this logic obsolete.
=> Fix #1984: apostrophe losing content of nested sub-areas when editing their attributes

lib/modules/apostrophe-jobs/lib/api.js, lib/modules/apostrophe-pages/views/publishMenu.html, lib/modules/apostrophe-pieces-pages/index.js, lib/modules/apostrophe-templates/index.js, lib/modules/apostrophe-templates/views/outerLayoutBase.html, test/templates.js
Closes #1982 
Closes #2000 
TL;DR: the context menu is no longer popping up at dumb times, busted-feeling and generally confusing people.
In #1982 we see there is a context menu when sendPage is being used to render a page directly with no `data.page` or `data.piece`. There should be none. The context menu's visibility is now predicated on both `req.user` and at least one of `req.data.page._edit` and `req.data.piece._edit`. This eliminates a great many situations where people wind up overriding things they shouldn't just to get rid of the context menu.
We used to be afraid to do this because "Reorganize" had, wrongly, crept into the "context" menu and in theory you might want to "Reorganize" from a specialized template that has no `data.page`. However (1) "Reorganize" has also been …
=> clean up the context menu in several ways

lib/modules/apostrophe-schemas/index.js
closes #1991 
We now have a `ui: false` option available for schema field types. Specifically, reverse joins have no ui (neither contextually nor in a modal, just plain not editable, therefore "contextual" wouldn't sound right). This beats adding hardcoded checks for the (currently) two kinds of reverse joins.
As a result `artists` does not have an empty `Info` tab due to the `_artworks` reverse join.
=> reverse joins should not cause empty tabs

lib/modules/apostrophe-express/index.js, test/express-random-port.js
_Original issue:_ https://github.com/apostrophecms/apostrophe/issues/1992
This PR removes the limitation that prevents using the port 0 for `apostrophe-express` (due to 0 being falsy). Using this port (either via the `data/port` file, `PORT` environment, or `port`/`forcePort` options) requests a random available port to the operating system, thus avoiding the trouble of finding one by trial and error ourselves.
The code has been tested successfully on Linux/*NIX systems and Windows, and on Node versions 6, 8, 10 and 12 (probably overkill, but just in case).
I included a test case in the PR. Not sure it abides by your guidelines and best practices though.
=> Allow picking a random port for Apostrophe to listen to

index.js
The issue on `findTestModule` is resolved by using a different type of regex :
- Windows's file path using `.match()` regex appears to must-have `/\\\\file\\\\to\\\\path/g` double backward slash that is equal to `\\file\\to\\path`.
I hope this issue will raise to any file path matching using regex should follow the same format as above stated.
=> Fix `findTestModule` on Mocha Test

lib/modules/apostrophe-video-widgets/views/widget.html
To tell screen readers to ignore these. The image shouldn't be shown long, and the heading would state the title already.
=> Adds empty alt tag to video placeholder img

lib/modules/apostrophe-video-widgets/public/js/lean.js
The height was being set against something its size, so could end up staying very small. This uses the parent to get the dimensions instead.
=> Sets video height (and width) based on parent

lib/modules/apostrophe-widgets/public/js/editor.js
This changes brought from [Remove `callback` from afterShow(callback)](https://github.com/apostrophecms/apostrophe-documentation/pull/160) . 
I don't know what to do on the `async.series` callback, and I just return `console.error` for that case. Let me know if you wanted me to change on anything.
=> Remove callback on Widget Editor afterShow method

CONTRIBUTING.md
Update contributing.md to show link to Discord instead of Gitter because in the Gitter there is an announcement to migrate to Discord
=> Update contributing.md to show link to Discord instead of Gitter

lib/modules/apostrophe-login/index.js, lib/modules/apostrophe-login/views/loginBase.html, lib/modules/apostrophe-login/views/passwordReset.html, lib/modules/apostrophe-login/views/passwordResetRequest.html, lib/modules/apostrophe-module/index.js, lib/modules/apostrophe-pieces/public/js/editor-modal.js, lib/modules/apostrophe-schemas/public/js/user.js, lib/modules/apostrophe-schemas/views/macros.html, lib/modules/apostrophe-users/index.js, lib/modules/apostrophe-users/public/js/editor-modal.js
`passwordMinLength`
The minimum length for passwords. You should set this, as there
is no default for bc reasons (effectively the default is `1`).
`passwordRules`
An optional array of password rule names, as strings. The standard rules
available are `noSlashes`, `noSpaces`, `mixedCase`, `digits`, and
`noTripleRepeats`. The `noTripleRepeats` rule forbids repeating a
character three times in a row. By default no rules are in effect.
When this option is set, the rules are consulted when a password
is set or reset. Existing passwords that do not follow the rules
are tolerated. If you wish to enforce them for existing passwords
as well, see below.
`passwordRulesAtLoginTime`
By default, password rules are enforced only when a password is 
being set or reset. If you wish, you can set …
=> Dgad 862: optional password complexity rules for apostrophe

README.md
The "ApostropheCMS documentation" link in the "Getting started" section currently points to a not found page. I edited it with what seems to be the right link.
=> Update README.md with the right link for doc

lib/modules/apostrophe-login/public/css/always.less
translateX(-50%) was causing horizontal scroll in edge, centered .apos-login-content block in a way that doesn't create horizontal scroll in edge.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13475965/
=> Centered .apos-login-content relative block, fixed #2081

lib/modules/apostrophe-modal/public/js/modal.js
Previously this method would always undersize the modal by 50px. I believe 50px was a stand-in for footerHeight, so this commit replaces the hardcoded value with the calculated footer height. In my testing, this change does work to:
* Size the window appropriately if there is a footer present in the modal
* Size the window to leave no space for the footer if no footer is present
=> Only add footer height to modal if footer is present

CHANGELOG.md, lib/modules/apostrophe-attachments/public/js/user.js, package.json
Attachments can be direct properties of any doc type, not just images or files. And we use this feature, but we have mostly used it for PDFs and the like. Now I want to use it for an image in apostrophe-global to better implement apostrophe-favicons 3.x, and I run into the fact that we never fleshed out support for the aspectRatio option at the attachment level. Introduce support for this, as well as the necessary autocropping if the user doesn't manually crop (this is not new UX, it's taken directly from how we handle it when choosing images if the aspect ratio does not match and the user does not crop).
=> aspect ratio support for direct attachment properties in a doc schema

lib/modules/apostrophe-attachments/index.js
Making this request per the instruction of @boutell to enable EPS files as a valid file attachment for `apostrophe-attachments`.
=> adding eps file type

lib/modules/apostrophe-attachments/public/js/user.js
I stumbled upon an error with schemas having an optional attachment. If I had no attachment, there was an error in the browser console saying "cannot read crop of undefined in user.js". I figured out it might be due to recent changes in this file.
If the attachment is null, the error was triggered. So, here is a fix to not enter in the `if` condition where no attachement added by the user in the apostrophe modal of a piece.
=> enable attachment to be non-required

lib/modules/apostrophe-widgets/index.js
Changing these here to not be overwritten in documentation when generated as done here: https://github.com/apostrophecms/apostrophe-documentation/pull/216.
=> Fixes urls for documentation

CHANGELOG.md, lib/modules/apostrophe-pieces/lib/api.js, lib/modules/apostrophe-schemas/index.js, package.json
These workarounds are necessary because of the changes in 2.102.0. We fixed Apostrophe to allow users to clear a field that has a default value (which is good), but this broke the tests and, for many users, the expected behavior of the headless module because it considers the undefined properties not passed to POST or PUT to be blank rather than assigning their defaults like it used to.
There is a corresponding PR coming on headless, both are needed to get the fix.
=> Fix headless by providing ways to limit the fields convert() will look at in the schema

lib/modules/apostrophe-areas/lib/cursor.js
We too often forget that pieces-widgets have joins built-in as well that can contribute to this.
=> Updates recursion warning to ref pieces-widgets

lib/modules/apostrophe-express/index.js
There is a small typo in lib/modules/apostrophe-express/index.js.
Should read `sessions` rather than `sesions`.
=> docs: Fix simple typo, sesions -> sessions

lib/modules/apostrophe-browser-utils/public/js/lean.js
Awful IE11 truths from ECG:
* CustomEvent exists, but is not a constructor, so our old sniff for it was not valid on IE11. Ow.
* The trick of using the host property of an anchor tag to check if it is the same site as location.host is not valid on IE11. Ow ow.
=> portable event emit and same site test

lib/modules/apostrophe-widgets/index.js
This change is to get a consistent example style that uses "my-widget," "my-module" etc. In this case that didn't even seem necessary, but the "your" would buck the convention.
=> Changes documentation comment style

lib/modules/apostrophe-schemas/public/js/user.js
With the <base> tag in html, the href='#' in button to open the array modal redirect in home, return false in this function prevents this redirect.
=> add return false to preventi href redirect

lib/modules/apostrophe-areas/public/js/editor.js
Cloning a widget was always supposed to create a widget with the old id, but actually we were changing the id(s) of the old one and then copying it, so we wound up with two the same 🙄 Cloning the jquery object first avoids this problem.
=> cloning a widget changes the id properly

CHANGELOG.md, lib/modules/apostrophe-schemas/index.js, test/schemas.js
Time fields do not currently seem to support empty values, defaulting to current time. Included is a fix using the approach that was used to allow empty values for dates in PR #2171. I've also included a test for the handling of empty values for date fields.
=> Allow empty values in time fields

lib/modules/apostrophe-docs/lib/cursor.js
closes #2215
I attempted to incorporate a test but the burden on the project of adding the driver you're not even using to the dependencies was high and there seemed to be complex npm cache issues frustrating the test.
So instead I pushed up a branch of `apostrophe-enterprise-testbed`, named `test-distinct-count-with-mongo-3-driver`, where a command line task can be run to test this:
```
node app products:distinct-count-tags
```
This requires a new `npm install` to actually have the driver.
If you wish to test this make sure you have products in draft that have tags.
The normal case, with our regular driver, is already tested in `test/docs.js`.
=> The `distinctCounts(true)` feature is now compatible with apostrophe-db-mongo-3-driver, when present

lib/modules/apostrophe-utils/lib/api.js
I was thrown by the original phrasing at first since the `o` naming is not immediately obvious.
=> Clarifies clonePermanent docs

CHANGELOG.md, lib/modules/apostrophe-attachments/lib/routes.js, lib/modules/apostrophe-express/index.js, package.json
This adds a [middleware](https://github.com/boutell/heic-to-jpeg-middleware) to handle heic/heif image uploads coming from recent iPhones.
closes #1349
=> 1349: support heic images

CHANGELOG.md, lib/modules/apostrophe-ui/public/css/user.less
With no `line-height` set for `.apos-ui` it will use the `line-height` on `<body>` if one is present, which can lead to drastic sizing changes for the UI. Explicitly setting one will ensure the UI remains consistent across projects.
=> Set line height for Apostrophe UI

lib/modules/apostrophe-login/index.js, lib/modules/apostrophe-users/index.js, test/docs.js, test/express-anon-csrf.js, test/login-throttle.js, test/login.js
In addition to the unit test coverage, you can test it with this configuration:
```
'apostrophe-login': {
throttle: {
attempts: 3,
per: 1,
lockout: 1
}
},
```
Now three invalid login attempts in one minute for the same account will lock you out for one minute, even if your credentials for the fourth attempt are correct. The issue is disclosed to the user so they know why they still can't get in. As discussed this feature was implemented with an async function and it's ever so much more readable as a result, but since for bc it must have a callback based interface, I plumbed it carefully to avoid returning any promises that might generate warnings or confuse developers.
=> Login throttle dgad 1005

lib/modules/apostrophe-browser-utils/public/js/always.js
Documentation minor improvement. Another docs edit that never got PR'd.
=> Replaces pseudo arrows in docs with unicode arrows

CHANGELOG.md, lib/modules/apostrophe-groups/index.js, lib/modules/apostrophe-login/index.js
The developer can set `totp: { groups: true }`, and then the TOTP requirement is in place only for groups for which it has been checked off in the backend.
Note that if you are logged in as an admin and you apply this rule to the admin group, the rule is immediately enforced for you, so leaving the manage modal you will discover a TOTP prompt and you won't be able to do anything else until you address it.
=> TOTP (google auth) by group, if specified

lib/modules/@apostrophecms/schemas/src/apos/components/AposInputString.stories.js, lib/modules/@apostrophecms/storybook/template/.storybook/main.tmpl.js
Updated the knobs addon, the `knobStore` state object was empty without knobs being "registered". This looked like a pretty much direct copy from the `apostrophe-storybook` repo so not totally sure why it just "worked" there. 
Also, re-added the decorators to the `AposInputString` so those should also work now too.
=> ensure knobs work in storybook

CHANGELOG.md, lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/js/user.js
DCAD needs the ability to restrict characters in usernames in apostrophe-signup. I was about to make it complicated and realized we are missing this simple option in apostrophe-schemas. Simpler to fix it there.
I named the option `pattern` rather than `regExp` because it will be familiar to HTML5 developers. However I do not use the `pattern` attribute in the actual input field because we are not always performing an HTML5 submit event, so there is no context for it to perform validation in; instead I do a simple match of the regular expression in the browser-side `convert` code. The end result is nicely consistent with the rest of our functionality and still very little code.
=> pattern option for string fields

modules/@apostrophecms/template/index.js, modules/@apostrophecms/template/views/refreshLayout.html
got it all except for wrappers unavoidable for infogram and wufoo embeds, if you do not like inline javascript you can not use those.
This is necessary because some recent security scanners consider all script tags without a src to be forbidden, as they can generally be avoided and they pose an XSS risk.
=> Eliminate inline script tags (script tags with no src)

CHANGELOG.md, lib/modules/apostrophe-areas/public/css/user.less, lib/modules/apostrophe-areas/public/js/editor.js, lib/modules/apostrophe-areas/public/js/user.js, lib/modules/apostrophe-areas/views/areaControls.html, package.json
Developers use it like this:
```
{{ apos.area(data.page, 'body', {
widgets: { ... configure like always },
widgetGroups: {
'Basic': [ 'apostrophe-rich-text', 'image', 'slideshow', 'apostrophe-video', 'logo-mask' ],
'Layout': [ 'columns' ],
'Content': [ 'link', 'artworks', 'locations', 'content', 'articles', 'events', 'random-met-artwork' ]
}
}) }}
```
I did it this way because it avoids opening a can of worms in the zillion lines of code that think they know how `options.widgets` is structured. Feels like a good way to retrofit this feature, which is very late in the game for A2, yet coming up in a pressing way for clients and needed enough that we kinda fake it in our own demo 😆 
If you don't use `widgetGroups` your widget menu behaves normally.
I forgot to demo it, but you can click the …
=> widget groups (hierarchy for the Add Widget menu)

modules/@apostrophecms/schema/ui/apos/mixins/AposInputMixin.js
Resolves the immediate error on input fields: https://apostrophecms.atlassian.net/browse/A30U-331
=> Uses focusout instead of immediately validating inputs

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/lib/joinr.js, test/pieces.js
The model layer of apostrophe now expects you to just pass an array of docs to be joined as a property with the name of the join field. For instance, `_products` can be set by literally passing in an array of product pieces. Same thing you get back later when you fetch the doc. Same thing you probably just got from find() and were hoping to painlessly join with. Intuitive.
Transition to the idsField and relationshipsField is handled at a lower level in a promise event handler. Thus both front and backend developers no longer have to think about them at all, and the REST APIs also automatically work in this simple and intuitive way.
This is NOT a way to *create new docs* of the type you're joining with, or update the joined docs themselves. You should still do that separately.  For …
=> simple joins

modules/@apostrophecms/ui/ui/apos/components/AposEmptyState.vue, modules/@apostrophecms/ui/ui/apos/components/AposTagApply.vue
For some reason the build was not ignoring the AposTagApply disable comment with the `//` format.
=> Updates stylelint disable format

modules/@apostrophecms/login/index.js, modules/@apostrophecms/notification/ui/apos/apps/ApostropheNotification.js, modules/@apostrophecms/util/ui/public/http.js
Also cc @falkodev, it's not necessary that he be one of the two reviewers but he'll be interested in the fix:
1. The notifications module was trying to fetch notifications because it had no way of knowing no user was logged in. You can now look in `apos.login.user` for a minimal amount of info about the current user. If that object does not exist, there is no logged-in user. (See `apos.user` in 2.x browserland.)
2. The notifications module was displaying duplicates because of a dumb mistake of mine in `apos.http.remote`. This is fixed, `options.qs` now works like it is supposed to.
NOTE: I am not sure exactly how this will play with old notifications that predate Anthony's work. So if you still get redundant notifications, try `db.aposNotifications.remove({})` once before opening a …
=> Don't try to fetch notifications when there is no user; don't fetch notifications redundantly

modules/@apostrophecms/notification/index.js, modules/@apostrophecms/notification/ui/apos/apps/ApostropheNotification.js
The string substitution thing doesn't even work in 2.x I think? 😆 Well, it works properly now in 3.x...
=> fixed duplicates, i18n, string substitution, replaced apply with ES2020 syntax

modules/@apostrophecms/ui/ui/apos/components/AposSlatList.vue
Slat list (used for relationships) were not draggable anymore since my last PR on relationship browse button.
Fix for this situation.
Edit an article in a3-demo, configure relationship with products and try to reorder the slat list by dragging one joined product above the first one.
=> Slat: fix draggable list

modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManagerToolbar.vue
Resolves https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?assignee=5ddbce7e47baa50cfd05eed2&selectedIssue=A30U-453
- In A3-demo, go to "articles", and click on "Browse products".
- Select 3 products. The toggle to select/unselect all products should still be enabled.
- Unselecting all products should also empty the slat list on the right rail.
=> Relationship editor: toggle not disabled if limit reached

modules/@apostrophecms/modal/ui/apos/mixins/AposTableMixin.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-462. The involvement of `selectedItems` when it was not needed in the pieces manager was mutating `checked` when it shouldn't have been. I also removed an argument from `toggleRowCheck` that wasn't actually used.
=> Prevents relationship methods when not needed

modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue
Fields like Relationships bring their own modals with them, this enhancement allows those modals to live outside the field's own validation status, preventing leaky css on inputs inside additional modals
solving https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?selectedIssue=A30U-454
=> adds secondary slot to field base that lets modals escape error css

modules/@apostrophecms/schema/index.js, modules/@apostrophecms/user/index.js
The configuration was inconsistent leading to problems.
=> fix storage of group ids so apostrophe works without hardcoded groups

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
this broke during inline event emit refactor .. it worked prior because we were passing it to a method and calling `$event` "widget"
=> pass correctly named event

modules/@apostrophecms/schema/index.js
The handler that handles translating a relationship array of docs into its idsStorage property at the last minute before saving was consulting the wrong kind of manager for the case of a relationship that resides in a widget.
BTW, what you see here is the method that handles that translation. It gets hooked up to a `beforeSave` promise event handler. This means that nobody else ever has to deal with idsStorage, as long as they are using apostrophe model APIs to save the doc.
=> Use right manager for widgets when storing relationship ids

modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-466, "Media Library: Users should receive a notification that their work is saved."
To test, upload an image and look for the success notification.
=> Adds success and error notifications to media editor

modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-425, "As a user, when done uploading a single image in the media manager, I can view and edit image piece properties in the right rail"
To test, upload an image to the media editor. It should open in the right rail editor. Then check a few items and upload an image. The checked items should become un-checked and the new one should be checked and in the editor.
=> Open newly uploaded image in media editor

modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-468
Moves the exit button on the media manager to the secondary slot and changes the label to "Exit"
=> Updates media manager modal header btns

modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/storybook/template/public/lib/mock-images.js
Resolves https://apostrophecms.atlassian.net/browse/A30U-430
Displays the uploaded image size, created date (for the image piece) and dimensions in the editor view:
=> Displays file size, created date, and dimensions for images

modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/scss/mixins/_theme_mixins.scss
Satisfies https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?selectedIssue=A30U-455
As modals get nested v-tooltip starts to misplace them, I've confirmed placing it higher up works as expected.
Not spending too much time wrestling them now but we need to make sure they get sorted after vue3/teleport
=> adds New Piece UI to relationship modal

modules/@apostrophecms/area/index.js, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/rich-text-widget/index.js
I added the ability to register material design icons from any module. I also thew in the ability to register an icon to be imported from somewhere else, by starting the `importFrom` argument with a `~`, for symmetry with the way you escape the normal import rules and get to "real" webpack imports in SASS.
This PR includes an example: the rich text widget now registers an appropriate icon.
I have verified that the icon appears in the "add widget" dropdown (plumbing for this mostly existed already but needed a little lashing-together).
=> Register icons

modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue
Needs the designer blessing.
Our transition group put a `span` in between the draggable component and the target list. This looks to have got in the way when the list was empty. No one is happy, the sign if a good compromise.
=> Removes the transition for the sake of nesting

modules/@apostrophecms/schema/ui/apos/components/AposArrayEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputAttachment.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlatList.stories.js, modules/@apostrophecms/ui/ui/apos/components/AposSlatList.vue
Acceptance of this PR does not mean the whole ticket is done because I'm waiting on Stu's design to deal with things like the add button better, but accepting the PR soon would be good because it fixes issues for both slats and attachments too (slat related).
Now uses slat list Also, refactored slat list to support selection and removed logic that modified props (not permitted in Vue).
Slat list now supports the v-model pattern, although we are currently choosing to pass in "value" and accept the "input" event directly in the three components that use it (that is also what v-model does).
=> Slats array editor

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/global/index.js, modules/@apostrophecms/piece-type/index.js
Resolves https://apostrophecms.atlassian.net/browse/A30U-669, populating the quick-create menu with real piece types.
This merges into the global admin menu item branch (#2502) since it uses the piece editor actions set up there.
=> Sets up quick create menu in admin menu

modules/@apostrophecms/admin-bar/index.js, modules/@apostrophecms/global/index.js, modules/@apostrophecms/modal/ui/apos/components/TheAposModals.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue
You can pick pages both via autocomplete in the relationship field and via browsing the page tree.
I also fixed a bug in the implementation of the "Global" button so that you can edit the singular, existing global preferences doc now. previously it was trying to make a new one every time.
See corresponding a3-demo PR, which introduces a simple set of footer links via the global doc.
=> Page picker picks pages passably

modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaUploader.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputAttachment.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue, modules/@apostrophecms/user/index.js
* Display simple string errors properly (like browser-side "required") as well as the more complex object errors that come from the server on failed save attempts.
* Users must have a full name (title). Caught this just now: a user with no name can't be edited, so make sure they have one.
* For array inputs, "min: 1" messaging is now inferred from "required: true" if "min" is not otherwise present. This is for consistency with the array editor, where the "*" marker would lack context so I've been treating required as an implicit "min: 1".
* Restrict file extensions properly for all file inputs, including but not limited to the media browser one. Bea had this worked out for the media browser one and I broke it earlier this week. However this led me to really sort it out completely for all …
=> Errata: display simple string errors properly, file extension restrictions, require user to have a full name, infer min from required for arrays

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/ui/apos/components/AposArrayEditor.vue, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
We've been seeing errors that boil down to the fact that `relationshipReverse` fields have no UI.
That's intentional but our frontend needed to know how to deal with it. Now the schemas are filtered appropriately and we don't get console errors and empty tabs.
(The possibility of making relationshipReverse an editable field type has lots of ins and outs and pros and cons and wouldn't be in-scope right now, this PR is just about un-breaking things.)
=> handle field types with no ui (reverse relationships) properly

modules/@apostrophecms/schema/ui/apos/components/AposInputArea.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-706, "Areas in modals's controls are being masked by the inner column of the modal, need to be accessible"
I tested this with the old canvas era style where the controls float outside the area and it works. This was the issue, not that the controls were visually hidden.
=> Fixes bug preventing area widget controls in editor modal

modules/@apostrophecms/login/index.js
resolves: https://apostrophecms.atlassian.net/browse/A30U-418, "At start up, check if there is a user"
This looks like it might have had an outdated event handler syntax. It didn't seem to be triggering in the login module.
=> Fixes login event handler and checks for existing user

modules/@apostrophecms/busy/ui/apos/components/TheAposBusy.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-784
Prevents the busy screen from scrolling out of view.
=> Locks the busy overlay in place

modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManagerDisplay.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-441, "Entire row in (piece) manager windows should click through the primary action of editing the item."
=> Allows clicks anywhere on piece manager table row to open piece

modules/@apostrophecms/area/ui/apos/apps/AposAreas.js, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/area/views/area.html, modules/@apostrophecms/widget-type/ui/apos/components/AposWidget.vue, modules/@apostrophecms/widget-type/ui/apos/mixins/AposWidgetMixin.js
Saves a zillion render-widget requests.
Currently if the page request has `apos-edit=1` the server renders areas as just a div with a data attribute and lets Vue call back for renderings of the widgets so it can encapsulate them in components, etc. This is great in principle, slow and visually weird in practice.
So with this PR, in addition to the div with the data attribute, we do render the widgets in a div for each one, with a data attribute containing its _id. The AposAreas app finds these and passes them to the areas as advance renderings, then snips them out of the DOM, allowing Vue to put them back as it sees fit.
Since props don't change but the widgets can be edited, we pass in enough information to figure out if these pre-renderings are still relevant or not; if not we call …
=> pre-render widgets on the initial apos-edit=1 request for the page

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
I added undo/redo buttons to the context bar, as I understand the original design to have been.
This undoes and redoes operations on the context document (the only document that we're going to be editing in context soon, remember, that ticket is open but not done). You can only undo back to the last save operation. 
The strategy is to leverage the existing array of pending patches that we are already building in order to "save all at once" rather than "save as you go." Nothing *really* happens in the database until you save, but we need the server's help to re-render the content with the change undone.
In principle we'd handle that with a GET request containing all the patches we do still want to apply in the query string, as a way of doing a "virtual patch" that gives us back the content …
=> page level undo/redo support

modules/@apostrophecms/login/index.js
This method used to be called ensureIndex, that still works but throws a warning, just using the modern name.
=> Enable index correctly, avoid deprecation warning at startup

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue
=> undo/redo: only the current context doc should be considered part of the basis

modules/@apostrophecms/oembed/lib/youtube.js
YouTube videos usually come back from their oembed endpoint with a thumbnail that is not the best available. We change that URL to get the best available, then make sure it exists, and if not, we flunk the embed... which works for most videos, but for a few, that "max" version just doesn't exist.
So I changed the code to gracefully accept that situation and fall back to the original thumbnail, and that fixed the issue with your video.
PLEASE NOTE: when you test this you may still get the error because of the oembed cache of apostrophe, which lasts an hour. You could clear that:
```
mongo a3-demo
(at the mongo prompt:)
db.aposCache.remove({})
```
=> Youtube invalid url fix

modules/@apostrophecms/doc/index.js, modules/@apostrophecms/rich-text-widget/index.js
. I cannot reproduce the issue from scratch anymore (I tested the migration by manually modifying my database).
But it existed on staging in existing content at one point, so others might have this problem with alpha 1 databases and need this migration to have better success in alpha 2.
I don't see a clear point at which the original bug was fixed though. So if we see it creep back in then I will need to know how to reproduce it. Just using the clone button does not reproduce it.
=> Migration to fix duplicate or missing widget ids

modules/@apostrophecms/schema/ui/apos/components/AposInputString.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-865, "Float/integer "string" fields with existing value trigger `required` error".
If a field is an integer or float type and has an existing value, that'll be a number, which doesn't have a `length`. But if you do any edits to that value, it'll become a string, so our existing check works at that point. We're also already checking for `null` values, so this update seems like the right move.
=> String field checks if value is a string for required

modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManagerDisplay.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellBasic.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellButton.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellDate.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellLink.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-690, "Date columns look bad in the piece manager"
Introduces a manager cell component option to allow project-level introduction of other manager cell formats. This is limited to the piece manager now. It _could_ be introduced in the page manager. That is arguably more fundamental to core (being that there's only one page manager view) and is more finicky with the dragging that I'm holding off on adding it there for now. Plus that's out of scope of this ticket.
=> Uses cell components for piece manager display

CHANGELOG.md, lib/modules/apostrophe-images/public/css/grid-item.less, lib/modules/apostrophe-images/public/css/grid-view.less, package.json
Resolves #2130 , a double scroll bar bug somehow created by introducing CSS Grid styles.
=> Image scrolls 2130

.circleci/config.yml
The CircleCI cache will now be fresh for every branch, in addition to every version of the `package.json` file.
=> Updates CircleCI cache naming

CHANGELOG.md, lib/modules/apostrophe-rich-text-widgets/public/js/editor.js, package.json
The current handling of `defaultStyle` for `apostrophe-rich-text-widgets` isn't really documented, but works as follows:
- firstly, look for a `defaultElement` option and create a new `CKEDITOR.style` from that if available
- secondly, look for a `defaultStyle` option and look up the corresponding `style` object if available
I think a logical third option to add would be:
- if a `styles` option is available and contains a single style object, use it as the `defaultStyle`
This PR makes it so!
Sorry for not opening an issue first, this is sort of a drive by contribution in the middle of other work.
=> CKEDITOR: When only one style is available, make it default

modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue
using the outer container as a reference was giving safari a hard time…, we weren't getting fancy with it anyway, removed
=> use default container behavior for context menus

modules/@apostrophecms/pager/index.js, modules/@apostrophecms/pager/views/macros.html
Updates the pager macro to end the tyranny of the 5-item intermediary range. A `shown` option can be included in the macro to change the number of items in the middle of the pager.
See a test PoC for this: https://codepen.io/alexbea/pen/NWRRPyV?editors=0012, changing the variables at the top of the JS section.
=> Updates pager to allow flexible number of intermediate pgs

modules/@apostrophecms/area/index.js, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/express/index.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/task/index.js, modules/@apostrophecms/template/lib/custom-tags/component.js, modules/@apostrophecms/util/index.js, modules/@apostrophecms/widget-type/index.js, test/modules/recursion-test-page/index.js, test/modules/recursion-test-page/views/page.html, test/modules/recursion-test-page/views/test.html, test/recursionGuard.js
Previous discussion:
Resolves #2406 
* By popular demand, this is "option 1d," plus a much better error message if the problem does still occur.
* A widget type will never recursively load itself unless this is explicitly turned on by the developer. This stops most cases of runaway recursion immediately.
* A widget type can also be configured not to recursively load specific other widget types.
* Relationships, widgets *and* async components now all contribute to a combined "apostrophe async stack trace" showing the relationship loaders, widget loaders and async components that were nested at that point in time.
* We limit this stack depth to 50 by default. That limit can be configured.
* If the limit is reached the stack trace is printed with helpful suggestions and recursion stops …
=> Shiny new recursion guard system with an effective "stack trace" and no false positives

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/file/index.js, modules/@apostrophecms/image/index.js, modules/@apostrophecms/page/index.js
This turns out to be a very simple solution to an otherwise sticky problem.
Images and files can still be localized when we get around to building i18n UI, since locales are still in play. They just don't need to be published. And other types can be given the `autopublish: true` option as needed.
=> autopublish images and files

modules/@apostrophecms/schema/ui/apos/components/AposInputColor.vue
- Fixes case where the editor engaged an un-required color picker but didn't select a color and got an erroneous error
- Unscopes `AposContextMenu` styles that now live in a different part of the DOM tree
=> color field bugs

modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js
The method that sometimes infers the locale from the _id was at fault. Need to check whether it's appropriate to the type before doing that.
=> users and other nonlocalized piece types can be edited again

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4?selectedIssue=A30U-904
From the Jira ticket:
> We’re implementing this proxy focus behavior at the `<AposAreaWidget />` level, not specifically on videos. Most widgets will not seem different, but largely interactive content will have its mouse events blocked until it is full ‘focused’ in the Apostrophe sense.
> As noted, this will be implemented slightly differently when we move widget controls out of the immediate widget DOM
=> block click events on widgets until they are focused with their controls revealed

modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
Our default styles were making it to our UI controls, but not to our tiptap extensions, so the styles extension didn't know what to make of the existing markup and reverted to the default p tag.
=> Fix the headers bug

modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapLink.vue, modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/Link.js
https://apostrophecms.atlassian.net/browse/A30U-935?atlOrigin=eyJpIjoiYmQxNWExMzBiOWFjNDkwNGE1YWNjNWI4ZGY0ZjU0OGUiLCJwIjoiaiJ9
- remove unused form. In certain states this would be submitted, causing page refresh and loss of changes
I don't know if there is value in having the form. The tiptap example goes to lengths to use a form and prevent submissions but /shrug
=> remove unused form el that can be mistakenly submitted, breaking link UI

modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_theme.scss
In a previous PR I styled the base modal blackout to play off the theme's primary color, but that looks weird when placing modals on that overlay.
This PR separates prominent busy overlays and themes them, from generic modal overlays which are the base blackouts
=> Busy overlays and modal overlays get different treatments

modules/@apostrophecms/express/index.js
connect-mongo does its best to store sessions in the right database by looking at the database name in the connection URL associated with the mongodb client object given to it. However this won't work in situations where a single client object is being used to access multiple logical databases. So pass the actual database name associated with the current apos object. This way sessions are not inadvertently shared between sites in this situation.
=> make sure we use the same logical database name for the session store

modules/@apostrophecms/ui/ui/apos/components/AposButton.vue
A normalize regression. The button has no visible label to center using padding and the padding make it look like this:
The alternative would be to set box-sizing to border-box, but I'd like to not default to that always.
=> Removes padding from color button

modules/@apostrophecms/schema/ui/apos/lib/detectChange.js
This fixes the problem where the images widget doesn't reliably save it when you swap out one of the images.
=> Detect changes in relationships (does not yet support alternate `idsStorage` settings)

modules/@apostrophecms/asset/index.js, modules/@apostrophecms/asset/lib/webpack.config.js, package.json
* Namespace the asset build. This allows for different builds to exist in parallel. The exact namespacing behavior desired is decided by project level or npm module level code that extends the asset module.
* In a Docker environment, it's actually better not to push to uploadfs, unless it is configured to use something external like S3. If it is using a local Docker volume, the build phase won't be able to see the volume and the assets will be lost.
=> ability to namespace asset builds. Do not push asset builds to uploadfs unless specified

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack.config.js, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/module/index.js
This allows doc type modules to use the `options.browser` setting.
=> Extends getBrowserData in doc-type rather than overwrites

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/rich-text-widget/index.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/lib/joinr.js, modules/@apostrophecms/schema/ui/apos/lib/detectChange.js, modules/@apostrophecms/widget-type/index.js, package.json
Related changes:
* A relationship that has no ids or no findable ids should still populate as an empty array, so it can be saved again as empty, rather than falling back to a nonempty ids array that wasn't part of what was copied during "discard" because relationships are writable in 3.x.
* In revert methods, documents should be loaded as if they went through the full query process so their relationships can be compared; this includes calling finalize to make sure relationships defaults to true.
* The relationship comparison logic should only care about _id and _fields, even for a top level relationship field.
Unrelated minor change:
* Removed jsdiff and dead code that used it, to quiet npm audit.
=> Fix relationship change detection so the global doc does not always offer "discard changes"

modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapStyles.vue
Resolves https://apostrophecms.atlassian.net/browse/A30U-1035, "Rich Text Toolbar is chunky and busted"
This was another instance of removing normalize.css inflicting content-box on everything. Rather than set these individual things to `border-box`, I removed some padding and used flex powers. We could decide to use border-box for all our things, but if not we should live with what we have set.
Previously:
=> Addresses wonky toolbar buttons (due to content-box)

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue
Fix noise in the browser console due to a ref no longer existing when switching from draft to published.
=> fix a minor race condition bug causing console noise on context switches

modules/@apostrophecms/ui/ui/apos/mixins/AposAdvisoryLockMixin.js
This language isn't quite what you suggested because:
* 1. In the case of another person taking the lock, they actively, affirmatively did that, so the language should make this clear to discourage slapfights between users.
* 2. The suggested language didn't quite address the issue when you take control from yourself. The new language is accurate in either scenario: you can only edit a particular document in one place (tab or window) at a time.
=> tweaked lock language

modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue
buttons have a new `inline-block` wrapper, account for that in the absolutely positioned relationship Browse button
=> account for new button wrapper

modules/@apostrophecms/schema/ui/apos/components/AposInputSelect.vue
The logic to select the first choice when required was failing to actually emit that choice as a change, now it is compatible with conditional fields.
=> Implied default of select field should work with conditionalFields

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
https://linear.app/apostrophecms/issue/PRO-980/nested-area-breadcrumbs-seems-to-be-bleeding-into-the-button
=> PRO-980 update secondary UI selector to match new button structure 

modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue
https://linear.app/apostrophecms/issue/PRO-986/multisite-logo-image-still-doesnt-show-up-in-modal
Trying to take a light touch on this ..
Our stock image widget has no CSS, no classes forced in the markup. I assume we still like this.
This forces `img` tags to have a max-width of 100% only while in schemas.
=> PRO-986 fix overflowing imgs in schemas

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaMenu.vue, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/ui/apos/components/AposInputArea.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputAttachment.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputColor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRadio.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRange.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputSelect.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputString.vue, modules/@apostrophecms/schema/ui/apos/mixins/AposInputMixin.js, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue, modules/@apostrophecms/ui/ui/apos/components/AposCheckbox.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlatList.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_inputs.scss
- `readOnly`'ify everything
- correct disabled states and slat behavior for Relationships
- Separate `disabled` from `limitReached` concepts in Attachment fields to preserve correct edit states
- provide `field` to areas so they can be disabled in editors
- Ability to disable `AposContextMenu`s from the top level props
- Provide generic `disabled` tooltip message as computed property from the inputMixin
- be able to disable `range`, `color`, `select`, `radio`
- Various style updates to slats, buttons
=> PRO-94 ensure disabled fields

modules/@apostrophecms/asset/lib/globalIcons.js, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocMoreMenu.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/piece-type/index.js
Moving pieces to the trash is now an action, and that action autopublishes. This fixes the loophole where it is impossible to publish the fact that you've moved something to the trash if it's just a boolean field, you don't publish on the first try, and you can't edit the trash.
=> PRO-1008: trash is an action, with autopublish

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue
fixed the infinite loop warning / performance hit when editing page titles. Had to do with slugifying the final component correctly when the slug is following the title.
=> PRO-1053 infinite loop warning editing page titles

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/busy/ui/apos/components/TheAposBusy.vue, modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue, modules/@apostrophecms/modal/ui/apos/components/TheAposModals.vue, modules/@apostrophecms/notification/ui/apos/components/TheAposNotifications.vue, modules/@apostrophecms/ui/index.js, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/mixins/AposThemeMixin.js, modules/@apostrophecms/ui/ui/apos/scss/global/_theme.scss
This PR goes beyond the [scope of the ticket](https://linear.app/apostrophecms/issue/PRO-19/trash-filter-missing-radio-button-for-the-active-state)
- tees up a theme object that might contain various UI preferences by cascading through user and global preferences
- pushes it to the browser's `apos` object
- top level apos vue apps apply it to there wrapper, replacing the hardcoded version
- ✅ context menus now apply the theme, which solves the original bug of missing UI from the ticket
requesting review from both @abea and @boutell for their perspectives
=> PRO-19 3/UI theme plumbing

modules/@apostrophecms/admin-bar/index.js, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/express/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/template/index.js, modules/@apostrophecms/ui/ui/apos/mixins/AposAdvisoryLockMixin.js, test/docs.js, test/pages-rest.js, test/pieces.js
Advisory locking based on an id that remains constant for the lifetime of the tab. This eliminates nuisance logging about locks but more importantly it gives us the ability to detect when we really are taking control from another tab that belongs to ourselves and ask if we want to go through with that. This prevents lost work without nuisance prompts.
Also removed some dead code to parse a header we no longer use to transmit the lock identifier.
=> PRO-1075 3/tab id replaces html page id

modules/@apostrophecms/page/index.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue
The "all" option of the pages rest API needed an upgrade to respect a "trash" query parameter and the component needed to send it.
=> PRO-1020 the page chooser should not allow choosing trash.

modules/@apostrophecms/doc-type/index.js
Without this followup in modules like multisite is not possible. I had it as input to schema.convert whereas it should have been attached directly.
=> a copy operation must set copyOfId properly

modules/@apostrophecms/doc/index.js, modules/@apostrophecms/migration/index.js
There is no need to run migrations on a new site. We must detect new-ness early enough that there's no possibility of being faked out by inserts in another module.
This won't detect a site that was constructed in advance in mongo by some custom script, but that advanced developer is probably not going to care, and migrations have a documented obligation to do no harm.
=> PRO-1074 skip migrations on new sites

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
It's a prop in its own right on AposButton, but it was being passed as a modifier class. That looked right, so the bug went undiscovered until Ben did some thorough QA 👍 
There are no other modifier classes in play right now so I stopped passing that prop but it could come back anytime if there was a use case.
=> PRO-1106 disable save properly

.circleci/config.yml
Adds a CI test to start checking Node 14 on the latest version of MongoDB and npm as well.
=> Adds CI test for node 14 with mongo 4

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposArrayEditor.vue
Conditional fields were broken in arrays, and following values were missing the same piece of plumbing.
=> PRO-1098: allow "if" and "following values" in arrays

CHANGELOG.md, modules/@apostrophecms/db/index.js
A3 uses the database similarly enough that if a developer tries pointing A3 at an existing A2 database, it'll make a mess, but just subtly enough that they might not figure out what happened. Ouch. So prevent that.
Content migration tools from A2 to A3 are planned of course.
=> PRO-1108 Detect a2

CHANGELOG.md, modules/@apostrophecms/piece-type/index.js
We PATCH special `_` properties to do things like grabbing a lock on a document, which generally speaking feels like a good extension of REST without using verbs browsers might not support, but modifying `updatedAt` merely because we grabbed a lock is both slow and inappropriate. This will also prevent other follow-on effects of calling `update` that would be undesirable, for instance if a custom extension is present that adds versioning, grabbing a lock should not create a version.
=> PRO-222 leave updatedAt alone if all our PATCH is doing is getting an advisory lock

CHANGELOG.md, modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/image-widget/views/widget.html
Turns out we were very close to doing this already, so I just updated the list of attributes that make sense to capture.
I simplified the logic a bit by always cloning the attachment object, which is not complex.
=> find the alt attribute as we pass by in image.first and friends

modules/@apostrophecms/area/index.js
I did not try to address the thing about file links specifically yet because there is a separate ticket for it, but I have fixed the original PRO-1049 foreign document trap complaint here: if you build out a card widget fully with image and rich text widgets and save it to the page, you are now able to edit those subwidgets on the page, without a foreign document warning.
=> PRO-1049 redux

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue
disables document switcher UI when there is no published version to switch to. Works for pages and pieces, nice UI reactivity when you do publish
https://linear.app/apostrophecms/issue/PRO-1109/unpublished-drafts-context-menu-switcher-draftlive-should-be-disabled
=> PRO-1109 3/disable document switcher when unpublished

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue
https://linear.app/apostrophecms/issue/PRO-1087/contextbar-widgets-at-the-top-of-a-page-are-hidden-beneath
this provides clearance for an area that might be flush to the global admin bar
See a demo of a flush area here https://github.com/apostrophecms/a3-demo/pull/72
=> PRO-1087 add margin to spacer element

modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue
implementation for https://linear.app/apostrophecms/issue/PRO-1060/trash-media-library-follow-up
consolidates cancel/archive UI in media editor to a single more menu
=> PRO-1060 3/media editor more menu

modules/@apostrophecms/user/index.js
It may not always be a full human name or they  may not want to give their full name. We're requiring it, so we can reduce mental friction by calling it Display Name instead.
=> Changes users title field to Display Name

CHANGELOG.md, modules/@apostrophecms/admin-bar/index.js, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/express/index.js, modules/@apostrophecms/global/index.js, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/permission/index.js, modules/@apostrophecms/permission/ui/apos/components/AposInputRole.vue, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/task/index.js, modules/@apostrophecms/user/index.js, test/login.js, test/pages-rest.js, test/permissions.js, test/pieces.js, test/users.js
Permissions restrictions by role are now fully enforced.
This is *not* a PR to adjust the UI so we don't show inappropriate functionality, etc. I'll be addressing that in other tickets. However it's actually pretty convenient for evaluation purposes, because you can try things and get appropriate error messages. (Bearing in mind that most of those would never be seen under normal circumstances once we do add the UI affordances, so we don't need to go nuts making every "forbidden" pretty.)
=> PRO-1161 restrict permissions by role

.eslintrc
We've got out of the habit of being consistent about this. I thought our linter was already catching this, but I guess not. Just a warning to not hold us up with eslint fixes.
CC @boutell
=> Adds eslint rules to warn when not kebab-casing Vue events

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarMenu.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocMoreMenu.vue, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/notification/ui/apos/components/AposNotification.vue, modules/@apostrophecms/page/index.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposPiecesManagerDisplay.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellDate.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellLabels.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellLastEdited.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposLabel.vue, modules/@apostrophecms/ui/ui/apos/components/AposTree.vue, modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue, modules/@apostrophecms/ui/ui/apos/mixins/AposArchiveMixin.js, modules/@apostrophecms/ui/ui/apos/scss/global/_tables.scss, modules/@apostrophecms/ui/ui/apos/scss/shared/_table-rows.scss, modules/@apostrophecms/ui/ui/apos/scss/shared/_table-vars.scss, test/pages.js
- https://linear.app/apostrophecms/issue/PRO-1172/general-manager-sprucing
- https://linear.app/apostrophecms/issue/PRO-1156/signal-a-document-is-draft-only
- Adds context menus for documents in piece managers and page manager
- Wires up context actions for docs (archive, unarchive, edit, preview, discard draft)
- Adds generic AposLabel component
- Adds labels to docs in managers indicating unpublished, active draft, archived
=> PRO-1172 manager tables, manager context menus, etc

modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
No changelog entry needed because it was never released with the bug.
=> new piece button fix

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/global/index.js, modules/@apostrophecms/piece-type/index.js
* Piece types marked as singletons (like the global doc) should never offer "archive" or "duplicate" on the More menu.
* Also streamlined the process of setting appropriate browser side config for singletons to be more automatic.
* I opened a separate ticket to address the fact that you can "preview draft" (and of course you then get an error) because it is not a given that no singleton piece type will ever have a `_url`, so we want a separate option there.
=> PRO-1190 sensible singletons

CHANGELOG.md, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManagerDisplay.vue
We were using the value rather than the name of the field as a v-for key, which does not make sense (two columns could have the same value).
=> PRO-1203 closes #2902

CHANGELOG.md, modules/@apostrophecms/template/lib/custom-tags/fragment.js, modules/@apostrophecms/template/lib/custom-tags/render.js
Make sure fragments can:
* render other fragments declared in the same source file, like macros can
* render other fragments imported by their source file, like macros can
It took me forever to figure out these six lines of code on my own time tonight. Just couldn't let this go unfixed. Needed to know if we were going to have to pivot to twigjs or even write something new. The answer is "not today."
Nunjucks makes the proper context available in the run() function that handles the "fragment" tag itself, so I needed to return that context as part of the node so it would be available later in the run() fragment of the "render" tag.
=> PRO-1185 fragments calling fragments

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/file-tag/index.js, modules/@apostrophecms/file/index.js, modules/@apostrophecms/image-tag/index.js, modules/@apostrophecms/image/index.js, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerSelections.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/permission/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManagerDisplay.vue, modules/@apostrophecms/user/index.js
But you still have to select things for relationships. So there is a basic read only experience in the manage view when used as a chooser. Did not attempt to open the editors in read only mode, I just don't let you launch editors for now when using the manage view as a chooser without permission to edit. That could be a follow-on at some point.
One unrelated change: "this.pieces" is now "this.items" in the docs manager because that is what some of the mixins were expecting and I ran into showstoppers that wouldn't let me continue.
=> PRO-1170 contributors cannot touch files and images

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextModeAndSettings.vue, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocMoreMenu.vue, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/ui/ui/apos/mixins/AposPublishMixin.js
* "Dismiss Submission" on the "more" menu for both pieces and pages
* Contributors can do it too, as long as it was their own submission
* Also refactored a little to reduce code duplication in the submit/dismiss routes
* /dismiss route is now /dismiss-submission to match the language elsewhere
=> dismiss submissions

CHANGELOG.md, modules/@apostrophecms/template/index.js, modules/@apostrophecms/template/lib/custom-tags/fragment.js, modules/@apostrophecms/template/lib/custom-tags/render.js, test/modules/fragment-all/views/fragment-print.html, test/modules/fragment-all/views/fragment.html, test/modules/fragment-all/views/macro.html, test/modules/fragment-all/views/page.html, test/modules/fragment-all/views/test.html, test/templates.js
Allow similar to macro `call`/`caller` feature:
```njk
{% rendercall fragment.test() %}
BODY
{% endrendercall %}
```
where `BODY` can be any valid sync and async nunjucks source.
The fragment definition is able to access the `BODY` via `rendercall` local function:
```njk
{% fragment test() %}
...
{{ rendercaller() }}
...
{% endfragment %}
```
ref #2930
Allows a mix of positional and keyword arguments (see the docs from the link above)
```njk
{% fragment test(pos1, pos2, kw1 = 'default value', kw2 = 'default value') %}
...
{% endfragment %}
```
This would be called in various ways, just some examples (some weird too!):
```njk
{% render test('pos1', 'pos2') %}
{% render test('pos1', 'pos2', kw2 = 'value') %}
{% render test(kw1 = 'value', 'pos1', 'pos2') %}
```
=> Fragment `rendercall` and keyword arguments

modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
Page tree was inadvertently nuked by a recursive loop because "items" is computed and references headers in the page manager, and vice versa. Moved the computed property for "headers" to the respective managers because it is no longer a good candidate to share.
=> PRO-1211 restore page tree

modules/@apostrophecms/page-type/index.js
custom page's `action` route doesn't do anything as far as i know .. this would be helpful for generic functions that work with both pages and pieces
=> sets custom page types to default their action to @apostrophecms/page's

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/util/ui/public/2-http.js
The preview button should immediately land on the page in preview mode.
Note that the query parameter you see added here gets hidden after arrival for a clean URL.
`apos.http.addQueryToUrl` now supports a merge option to make this kind of thing all the way easy on the front end.
=> PRO-1033 fix the preview button so it goes right into preview mode

CHANGELOG.md, lib/modules/apostrophe-pages/lib/api.js, test/pages.js
Currently, when redirecting a page using `req.redirect = '/somewhere'`, it is not possible to set the status code to be used for the redirection. In fact, the redirection will always use the status code 302 Found.
However, some modules like `apostrophe-personas` makes the assumption that setting `req.statusCode` will override the status code ([check index.js:302-305 on the latest commit to this day](https://github.com/apostrophecms/apostrophe-personas/blob/31c84c86bd26f42c901b4c91c2d1fd2464da8622/index.js#L302-L305)).
I found this assumption very reasonable in the idea of using ["req as a notepad of things we'd like to happen in res"](https://github.com/apostrophecms/apostrophe/blob/3360af419d73a80a7828472078da4d9b9242edfb/lib/modules/apostrophe-pages/lib/api.js#L1125-L1126), so this PR …
=> Override the default redirection status code when req.statusCode is set

modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
This change just highlights RTEs that have no `textContent` as determined by the DOM parser. Leaves the door open for future auto pruning or whatever we decide
=> PRO-350 visually empty rich text editors are highlighted

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaMenu.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputArea.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue
https://linear.app/apostrophecms/issue/PRO-1085/z-index-context-menus-are-higher-than-the-context-bar
=> PRO-1085 context menu z index modifiers

modules/@apostrophecms/ui/ui/apos/components/AposLabel.vue
Right now labels are not clickable, enforce an auto cursor state for cases where they're inside clickable elements
https://linear.app/apostrophecms/issue/PRO-1201/the-new-status-pills-appear-clickable
=> PRO-1201 3/labels not clickable

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/ui/ui/apos/mixins/AposPublishMixin.js, package.json
I left the edge cases alone because it would be their only use of the mixin and so it is otherwise off topic for them. We could put the method in a mixin all to itself to also cover the two "cell" components that have it, but it's a one-liner so that feels really excessive to me, at least for now.
I also fixed a package.json issue: a package was required separately as a regular and a dev dependency, with different major versions. Fun times.
=> PRO-1237: factored manuallyPublished to a mixin, for use cases that make sense for the mixin already

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/ui/ui/apos/mixins/AposPublishMixin.js
Fetch draft properly when refreshing context bar after discarding draft; remove beforeMove handlers made obsolete and problematic by the decision to just autopublish moves (those scenarios no longer apply and the handlers caused the original bug of this ticket); remove redundant logic for discard draft messaging; return doc correctly from discard draft; consistent messaging
=> PRO-1219 PRO-1257 Contributors can "discard draft" properly via the on-page kebab menu

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocMoreMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellContextMenu.vue
Both for and for pieces.
Related: removed unnecessary logic to pass on filters from the manager modal, which caused a secondary bug blocking the "view" feature after I added it. All we ever really needed there was to pass on `archived=any` to make sure this use case was accommodated.
@localghost443 has also asked whether something should happen when you click on the title of a page in the page tree, I'm not going there in this PR, just addressing the original ask for the context menu to provide a "view" option and for it to work for both pages and pieces.
=> PRO-1261 You can now "view" an archived item via the context menu

modules/@apostrophecms/schema/ui/apos/components/AposInputString.vue
Firefox's clear buttons are sufficiently padded away from our icons, chrome's cal/time icons are hidden in favor of ours
=> PRO-83 clean up chrome/firefox default time/date indicators

modules/@apostrophecms/doc/index.js
There is no migration to go with this because I did not want to add that weight for something that was never publicly released. So if you try to use an EXISTING image in an image widget to test this you will not be able to see it in an incognito window, but if you upload a new image to an image widget you will see it.
=> PRO-1277: newly inserted images and files should still be visible to the public

modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManagerDisplay.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellLabels.vue, modules/@apostrophecms/ui/ui/apos/mixins/AposCellMixin.js
https://linear.app/apostrophecms/issue/PRO-1282/pieces-not-getting-the-pending-update-label
@boutell as a side note, its confusing we're passing `item`, `draft`, and `published` into all these components, `item` being a moving target. Should we just normalize all the cells to expect `draft` and `published`?
=> PRO-1282 check for drafts modified prop

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
I believe this resolves it for all cases. Keep in mind though that detecting changes in real time — changes made by another user, while this page was open for this user— is out of scope, so a page refresh is needed before checking what a contributor can do after an admin in another window takes some action.
=> PRO-1255 fix for edge cases re: when you're allowed to click Submit Changes and when you're not

CHANGELOG.md, modules/@apostrophecms/migration/index.js
I tested this using:
```
NODE_ENV=production npx mocha test/pages
```
Which fails without this patch, passes with it.
=> PRO-1298 PRO-1300 make sure parked pages get inserted if the database is brand new, even if in production

modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManagerDisplay.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellContextMenu.vue
Also fixed docs manager to call the context menu exactly like it is a cell, even if it does not choose to invoke it through the loop like other cells, because the page manager does invoke it like a cell and it expects certain params like a cell otherwise it throws errors.
Yes this is a workaround! I have opened PRO-1304 to refactor this in beta 2. I want to refactor this, it's giving me hives. However doing so today would risk introducing too many issues on a launch day. Would die on this hill.
=> PRO-1303 brought back context menus in page tree by using the mixin, resolving a bug

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaMenu.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputArea.vue
previously we were passing this prop through a bunch of components, but as widgets get nested the chain is broken due to the unpredictable nature of what is being rendered within widgets.
Opt to simply look up the DOM tree for a data attribute that schema areas append. This attribute is not present in in-context areas
=> PRO-1292 fix schema area zindex issues

modules/@apostrophecms/module/index.js
Fixes a doc comment referencing a non-existent method.
=> there is no addHelper

CHANGELOG.md, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/uploadfs/index.js
See ticket. This allows for environments where several apos objects should share static assets. The default behavior has not changed.
=> PRO-1101 optional separate uploadfs instance for asset module

CHANGELOG.md, lib/modules/apostrophe-attachments/lib/api.js
When `enableAltField` option is set to `true` and you author the `alt` on the `apostrophe-images`, the `alt` attribute was not captured if you were using `apos.images.first` or `apos.attachments.first`. This pull request is an attempt to fix it. 
=> Copy alt field from apostrophe-images to attachment piece

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/util/ui/public/2-http.js
Also:
* eslint fixes.
* Don't manually chop off old query strings before calling, `addQueryToUrl` is smart enough to do that.
=> PRO-1341 preserve the hash when updating query strings

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/Styles.js
The rich text editor now supports specifying a `styles` array with no `p` tags properly. A newly added rich text widget initially contains an element with the first style, rather than always a paragraph. If no styles are configured, a `p` tag is assumed. Thanks to Stepan Jakl for reporting the issue.
=> PRO-1372 dethrone the P tag, impostor king

CHANGELOG.md, CONTRIBUTING.md, lib/modules/apostrophe-login/index.js, lib/modules/apostrophe-permissions/index.js
No issue to link to, but this is a simple pull request asked for in Discord by another Apostrophe-CMS user. This is my first pull request, let me know if there's anything I forgot/should improve on. I'm also not completely sure the option name makes sense, but couldn't think of anything better that wasn't very long - let me know if you prefer a different name.
I did update the documentation (and add an Options header) for the apostrophe-permissions module.
Current behavior for admin permissions on piece types is that if you apply admin permissions for a single piece type, all piece types become visible in the admin bar, even though the editing windows end up being empty. It sounds like this was originally done to prevent errors for joins and relationships between piece types (i.e. if you …
=> Allowing Disabling of Global Piece Admin Permissions

modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue
I lost a lot of time on this because I stopped being able to even see drop zones for quite a while. I went back to beta 1 and even earlier and still had the problem, did more npm installs, got it working in beta 1.2, then said wait a minute and came back to this one-line fix for beta 2 and... working fine.
So I think I experienced some red herrings due to dependency hell, and in any case experienced them in long-published releases, so even if that were ever to recur it's not a new regression. This one-line fix is correct for the ticket that was opened.
=> PRO-1391 PRO-1392 restore ability to move pages, with correct enforcement

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-page-type/index.js, modules/@apostrophecms/piece-type/index.js
This way we don't hit the wall on the first custom type we encounter that has these properties.
=> PRO-1473 PRO-1405 dynamically determine whether a "save and view" button etc. is a good idea

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/index.js
remove text alignment controls until sanihtml can be auto configured to save style properties.
=> temporarily remove text align controls

modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/TextStyle.js
- Currently spans without style attrs get parsed out on tiptap remount, modify the extension to return all spans
=> Extend Tiptap2 TextStyles to accept all spans, not just ones with `style` attrs

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposRelationshipEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/schema/ui/apos/lib/detectChange.js
* Relationship subfields can now be edited when selecting in the full "manage view" browser, as well as in the compact relatio
nship field view which worked previously.
* A console warning when editing subfields for a new relationship was fixed.
* Relationship subfields now respect the `def` property (there was no real previous implementation of initializing the object, with or without defaults, so no reason not to do it right the first time).
=> PRO-1535: relationship subfields working in expanded chooser (manager view), also fixed initialization with support for defaults

modules/@apostrophecms/asset/index.js
Also: read things properly as utf8 strings before concatenating them since if we're going to do stringy operations on them we really should parse them as the right kind. (We were already doing that for other builds.)
=> tolerate a missing CSS build artifact, some pipelines produce none if they find none

CHANGELOG.md, modules/@apostrophecms/template/lib/custom-tags/render.js, test/modules/fragment-all/views/fragment.html, test/modules/fragment-all/views/page.html, test/templates.js
This patch is an attempt to cleanup the fragment arguments computation logic and it solves the issue when unknown keyword arguments are being available in the fragment context.
ref #3102
=> 3.0: Refactor input computation and filter kwargs

CHANGELOG.md, modules/@apostrophecms/asset/index.js
This fixes a regression in formerly working logic for this.
=> PRO-1640 admin UI rebuilds only if package-lock.json is newer than the last bundle built. ui/src still rebuilds all the time, by design

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
There is even logic for this but it got thrown off by later logic examining the document itself. Simple to fix by passing the intended mode to `setContext`.
=> PRO-1621: when pushing a secondary context document (such as palette) draft mode should always be entered, as worked in the past before 3.0.0 stable

CHANGELOG.md, package.json, test/widgets.js
This will get us passing npm audit. This requires https://github.com/apostrophecms/oembetter/pull/16 to be merged and published.
=> Updates oembetter and cheerio

CHANGELOG.md, modules/@apostrophecms/asset/index.js
Since `ui/src/index.js` files must export a function to avoid a browser error in production which breaks the website experience, we now detect this at startup and throw a more helpful error to prevent a last-minute discovery in production.
This is not perfect, in particular we could look more specifically for the export being a function, but I don't want to mess this up by failing to think about cases that are valid but use different syntax. Making sure "export default" exists should cover 99% of likely developer errors on this point.
=> PRO-1679 lint for missing export default

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
No changelog entry because this regression was never released.
=> PRO-1681 switchDraftMode no longer implies refresh, call refresh ourselves

modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
I'm not sure when setContext stopped refreshing the main content area in all cases where we don't leave the page and the context isn't a pushed context (not palette), but that's fixed now, addressing Alex's bug.
=> setContext is refreshing again, as promised, rather than me working around it by refreshing manually in various cases

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
trying to switch to the utility rail on error hides all tab content in the main body
=> PRO-1397 dont try to switch to the utility group on error, not a 'real' group

modules/@apostrophecms/user/index.js
There is a field typo in the `user` module, reported by @kimsmouter 
My most significant yet apos contribution :)
I suppose it doesn't need a special CHANGELOG entry? If it needs indeed, let me know.
=> 3.0: fix field label typo

modules/@apostrophecms/oembed-field/ui/apos/components/AposInputOembed.vue
Fixes two bugs in oembed fields
- Detecting existing field values was getting tripped up between `null` and `undefined`. If our content has an existing oembed value we know it will be an object so we don't have to be so careful as to what to expect
- the field's validation didn't account for filling in a field and then manually clearing it. A newly-empty oembed string field always produced an error and blocked save.
=> oembed field fixes

CHANGELOG.md, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/video-widget/ui/src/index.js
- `mapMongoIdToJqtreeId` isn't used anymore because we don't use jqTree anymore.
- An eslint fix in `AposDocsManager.vue` since the return isn't doing anything.
- Some line break stuff since 80 character line lengths are the meaning of life.
=> Removes a defunct jqtree method; tidies code

test/i18n.js, test/modules/apostrophe-fr/l10n/fr.json
No changelog entry because it's just a unit test of functionality that's being announced already in the changelog.
=> passing unit test showing that two modules can contribute separate languages to the same i18n namespace

lib/moog-require.js, test-lib/test.js
The fix for ignoring transitive dependencies as apostrophe modules didn't work for devDependencies. Fixed that and provided coverage. `apostrophe` does count as a valid test, as it loads as an ordinary bundle and no tests pass if that doesn't work.
=> fix devDependencies and provide coverage (forward port from moog-require)

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposWidgetControls.vue
- There were conflicting versions of the method `regenerateIds` which was causing a bug in both Duplicate and clipboard paste.
- In demo prep and testing with Alex we decided to clear the clipboard contents on paste, as it felt strange to have the very specific duplication follow you around forever in areas.
- Hide Copy button for now. Between Duplicate and Cut/Paste, Copy felt like a confusing use case. Something to revisit, potentially with some improved widget control bar UI
=> PRO-1877 fix duplicte bug, clear clipboard on paste

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputRange.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_inputs.scss
sister PR in `@apostrophecms-pro/palette` completes the lewk
https://github.com/apostrophecms/palette/pull/26
=> PRO-1790 accomodations for inline micro range

CHANGELOG.md, modules/@apostrophecms/express/index.js, modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/task/index.js, modules/@apostrophecms/util/index.js
Cloning `req` naively yields an object with no `get` method, which is an issue for code that calls `req.get`. Opening separate ticket to replace *all* naive `{ ...req, ...}` clones of req with calls to this method.
=> req.clone is available, and used where mission critical, for localeReq. A separate ticket is open to use req.clone consistently

CHANGELOG.md, modules/@apostrophecms/migration/index.js
This was causing serious demo grief, but has also caused surprise unique key errors from the migrations module during ordinary dev.
=> PRO-1907 Defensive driving: clean up before inserting migrations into a "new" database

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/page/index.js, modules/@apostrophecms/ui/ui/apos/lib/i18next.js, modules/@apostrophecms/util/index.js
The basics of localizing a page are working (not related documents yet). I fixed some bugs and oversights to get us there at a decent level for a demo:
* Localization API preserves non-schema properties when updating an existing page or piece (overwriting existing English with French). Without this the page tree breaks.
* Static i18n fallback works properly for browser-side UI (Vue). This requires that we push both locales to the browser when the active locale is not the default locale.
* Localized more titles.
=> PRO-1900: localize modal should actually localize, part 1: just the page itself

CHANGELOG.md, modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/task/index.js, modules/@apostrophecms/template/index.js, modules/@apostrophecms/template/lib/custom-tags/render.js
Very basic fallback to just outputting the key given (which in 2.x practice is probably the English text) and warning the developer. These were never official in 3.x but from some recent correspondence it's clear they could be encountered, so let's not crash.
=> #1920 bc for old __ helpers

CHANGELOG.md, modules/@apostrophecms/page/index.js
This patch fixes a migrate task crash when new parked page is inserted.
1. not yet existing in the DB page is available in the parked list
2. migrate task is executed
3. park sync logic is triggered on after:migrate (more than once)
4. the `implementParkOne` calls internally `insert`
5. the internal `insert` method is mutating the original parked configuration
6. on subsequent `implementParkOne` invocation, the script is crashing with error message `TypeError: Cannot read property 'slug' of undefined`
The parked configuration is shallow cloned before processed in the internal `insert` method. No other logic is changed. 
A follow up from the PR against a stale branch #3308
=> 3.0: fix TypeError while parking missing parked page

modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
Resolves:
- https://linear.app/apostrophecms/issue/PRO-1828
Doesn't allow the current locale for the current document to be selected and removes styles to make it look like it can be clicked.
=> don't allow the current locale to be selected or look like it can

modules/@apostrophecms/i18n/index.js
Was previously not pointing to the right module for the trustProxy option.
=> Fixes trustproxy option reference in i18n

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposCellDate.vue
AposCellDate component should increment the month value when formatting because the value is zero-based.
=> 3.0: [UI] fix AposCellDate typo

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/file/index.js, modules/@apostrophecms/image/index.js, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue, modules/@apostrophecms/user/index.js
Clicking between archived images triggered the "discard changes?" modal. The media manager and its ever-open editor is the only place this would really come up on its own. It came down to the slug field seeing a change in the incoming value and triggering prefix checking, but not accounting for how archived images get two prefixes: `deduplicate-[ID]-` and `image-`.
The main thing I'm only 97% sure about is how I'm regexing for the dedupe prefix. Though I think the danger might only come in if you make your slugPrefix "deduplicate-", in which case you're an agent of chaos. ... Maybe we should prevent that.
Update: I reserved the "deduplicate-" slug.
=> PRO-1892 img slug shenanigans

CHANGELOG.md, lib/modules/apostrophe-templates/index.js
This can be QA'd by throwing an unclosed `{%` at the top of `home.html` in enterprise testbed. The resulting error page should have a 500 status code.
=> DCAD-1089: correct status code for template error page

modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
Resolves:
- https://linear.app/apostrophecms/issue/PRO-1933
To test, select a couple locales in the localize modal. On the last step ensure the text doesn't overlap.
=> fix overlap

CHANGELOG.md, modules/@apostrophecms/i18n/index.js
Lints locale names to start with an alphabetic character. This is primarily to further ensure that the `Object.entries` loops maintain order. Apparently numbers as object keys can take precedence in some environments. https://2ality.com/2015/10/property-traversal-order-es6.html
=> Lints locale names to start with alpha character

.circleci/config.yml, CHANGELOG.md, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/i18n/index.js
A bc break otherwise. Also fix mongo 5.x detection of a certain edge case.
=> PRO-1949: relax the absolute URL thing to the previous standard if there are no locales with hostnames

modules/@apostrophecms/modal/ui/apos/components/AposModalBody.vue
Fixes:
- https://linear.app/apostrophecms/issue/PRO-1948/media-manager-layout-is-disrupted-when-uploading
Original change was made to match the design of the new wizard. Wasn't anticipating this change messing other things up but it did... This ensure's we only stretch it when we add a footer in the body. ( The standard modal footer can't be broken up like the visuals for the wizard. )
=> only stretch the modal body when we have a footer

CHANGELOG.md, modules/@apostrophecms/express/index.js
`bodyParser.json` options passed to `@apostrophecms/express` are currently ignored because they are being wrapped by lodash before spread. This change should fix it. cf #3369
=> Remove lodash wrapper around bodyParser.json options override

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js
The relationship chooser previously selected draft items with the "select all" button. This fixes that and improves the max limit handling.
=> PRO-1536 select all

CHANGELOG.md
Fixes a break in the timeline from #3363 being registered early and merged late.
=> Fixes the changelog from previous commit

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/search/index.js
Since pages were using the regular doc-type `allowedSchema` method they didn't get the parked page checks. So when a page was parked and we tried to edit it there were opportunities to fail, including if we were updating a page whose type was not in the main array of selectable types.
=> PRO-1670 parked defaults

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/image-widget/views/widget.html
render-widget essentially simulates saving the widget so that the loaders can function properly on it. But this simulation was incomplete. Specifically we did not call the method to populate the idsStorage before saving, so upon calling the loaders the image widget's relationship with images was empty.
This bug slid by until 3.3.1 because of a separate bug in which the relate() method didn't replace any existing relationship data when reloading it but rather just appended, which created a major performance issue for an enterprise client, necessitating a hotfix.
As we see here however full QA is always a good idea, even for a hotfix, particularly if it touches on deeper functionality and not a single piece of UI.
=> PRO-2060: a fix introduced in 3.3.1 revealed broken render-widget logic that was getting by due to the bug fixed in 3.3.1

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
If we don't do this with nested widgets and their sub-properties get edited, we wind up in trouble when resubmitting these objects as patches for undo purposes.
=> PRO-2063 use klona when adding a patch to the patchesSinceLoaded list

CHANGELOG.md, lib/moog.js
The documented recommendation is to only use `self` as an argument to customization functions. This should be reflected in error messages as well.
=> Fixes error messages to remove the options argument recommendation

CHANGELOG.md, index.js
The existing tests didn't support official Apostrophe modules well since they created a symlink test node module named after the package directory. A3 modules do not include the namespace in the package directory typically. This supports adding the namespace for a test module.
In our official modules in packages like `form` or `seo` we would use `testModule: '@apostrophecms'` on test apps to namespace the symlink.
=> Supports adding a test module namespace

CHANGELOG.md, lib/moog.js, test/moog.js
I couldn't let this go anymore. Seems like a simple fix for a big quality of life improvement. Devs no longer need to know what the inherited fields in a group are.
=>  PRO-1114 Updates cascade grouping to combine like-named groups' fields

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
We originally hid the Add Content buttons when a widget was focused to separate the concepts of 'adding content to an area' from 'editing the settings of an individual widget' but this felt like it was getting in the way more than guiding the editor, especially when they tried to use the breadcrumb UI for wayfinding (using the breadcrumbs focuses the parent widget, which would hide the Add Content UI, only providing half the utility).
This helps to alleviate scenarios like #3388
=> Keep Add Content controls accessible when widgets are focused

CHANGELOG.md, package.json
In a3-demo webpack simply fails to build `apos-build.js`, with no error, when `NODE_ENV=production` unless I pin `vue-material-design-icons` to the previous minor version. I took a look and it's basically a whole lot more icons, I really don't know how that could cause webpack to silently fail to produce an output file, but there you are.
=> PRO-2096 fix webpack fail

CHANGELOG.md, index.js
This was throwing an error in the new form modules tests since there were no other modules in the test suite to lint. The `fs.readdirSync` ran into trying to do something with the non-existent directory.
=> Exits lintModules if there are no modules to lint

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/src/webpack.scss.js
We are solving an issue where `css-loader` is trying to parse `url()` inside `modules/@apostrophecms/assets`. This is to no avail as webpack is the one that should compile paths. 
Solution established with @boutell
=> Webpack css loader config

CHANGELOG.md, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/module/index.js
@stuartromanek pointed out that aliases didn't work in `ui/src/index.js` files, at least not until next tick. Now they are initialized earlier to save hassle.
In the changelog I couldn't help writing a note explaining when this even makes sense to try to use and how, a lil' bit. Bea, feel free to steal this for a doc page on the topic...
=> PRO-1853 module aliases now available when ui/src logic starts up

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/doc/index.js
Also added a decent error message when you forget to nest `widgets` in `options`, because that was making it painful to test the other thing.
=> PRO-1739 fixed foreign area editing

modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
Regression: autocomplete in the locale searcher didn't work
Small UX bit around resetting the search when the remaining results are probably not actionable.
=> fix autocomplete

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
A small addition so that the `context-editing` event can explicitly manage the "hey the user is currently typing / manipulating, chill on the UI changes" state when desired.
=> PRO-2055 (the core bit)

CHANGELOG.md, lib/modules/apostrophe-doc-type-manager/lib/routes.js, lib/modules/apostrophe-schemas/index.js
[SUP-155](https://apostrophecms.atlassian.net/browse/SUP-155)
When opening a modal, some 500 errors was popping about some `joinByOne` fields that are required, even if these fields are hidden. This behavior has been fixed in the PR.
Create a simple widgets that have a `joinByOne` field that can be hidden by a select field with a `showFields` property. If the `joinByOne` field is hidden, even if it's empty, it should never throw a 500 error.
=> Avoid 500 error when field is hidden and required

test/login-throttle.js
This feature is not critical and the node 8 test does not pass in circle, although it does locally. Not worth a deep dive in circle's environment etc. as node 8 is quasi-supported until various legacy servers are shut down.
=> skip unreliable test on node 8 for noncritical feature

modules/@apostrophecms/modal/ui/apos/components/AposDocsManagerToolbar.vue
In the case of grouped/nested batch operations, the properties on line 42 were mostly from the _group_, not the individual action. We need to find the action within the group. No changelog since this fixes an unreleased feature.
----------------
=> Fixes bug preventing nested batch operations from running

CHANGELOG.md, modules/@apostrophecms/image-widget/index.js, modules/@apostrophecms/image-widget/views/widget.html
Hi, 
When running analysis on the bundle performance with Lighthouse, we found one of the poor metrics was not setting width & height attributes on images which resulted in long blocking time. 
See [lighthouse guide on dimensions](https://web.dev/optimize-cls/?utm_source=lighthouse&utm_medium=devtools#images-without-dimensions)
Therefore it would be great if we can set the width and height attributes on the image widget from the attachment data which we already have from the images.
=> Set width and height from image data

modules/@apostrophecms/modal/ui/apos/components/AposDocsManagerToolbar.vue
This label prop was using the actual string "label" since it wasn't using v-bind/`:`
=> Fixes the batch operation button labels

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, test/pieces.js
[PRO-2339](https://linear.app/apostrophecms/issue/PRO-2339/fixes-the-presentfieldsonly-option-of-the-convert-method)
`fieldsPresent` method in doc-type was broken, looking for properties in strings and wasn't returning anything.
Check that when calling the method `self.convert` with the option `presentFieldsOnly` set to true you're getting the right properties.
=> Fix convert method

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
@myovchev reported a bug where the component would crash the UI when a rich text widget was configured with an empty styles array: 
```
{
className: 'smr-widget smr-widget--rich-text',
toolbar: [
'bold',
'italic',
'strike',
'link'
],
styles: []
}
```
In this case the RTE widget component will treat this as if there was no `styles` configuration. The particular configuration pattern is no longer necessary since the toolbar does not have a `styles` button included. No styles will display. This may not have been the case in early versions of Apostrophe.
=> Ensures a style for empty rich text widgets

CHANGELOG.md, modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/module/index.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/template/index.js
This removes the deprecated A2 method `self.partial`. It was undocumented and effectively unused in A3. The only appearance in code was not actually used by the application.
=> Removes the partial method

CHANGELOG.md, modules/@apostrophecms/page/index.js, modules/@apostrophecms/task/index.js
No more "cannot set headers after they are sent to the client" and "req.res.redirect not defined" messages when handling URLs with extra trailing slashes.
=> PRO-2357 fix "cannot set headers"

CHANGELOG.md, modules/@apostrophecms/i18n/index.js
During documentation I noticed the server-side and template l10n strings were not debugged the same as UI strings. The plugin needed to be activated in the init method.
+++++++++++++++
=> Fixes the server-side and template l10n debugging plugin

README.md
As documented in [this](https://stackoverflow.com/questions/70269088/how-do-i-produce-a-status-that-can-be-displayed-via-the-badge-from-a-github-acti) Stack Overflow post, the URL for the status badge was incorrect.
This PR updates the URL to match the project.
=> Update CI badge URL to point to correct image

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/index.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, package.json
Needed to install the appropriate tiptap extension and add the `u` tag to the sanitizeHtml options computation.
=> PRO-2370 underline works properly

CHANGELOG.md, lib/moog.js, modules/@apostrophecms/schema/index.js, test/moog.js, test/schemas.js
We didn't have a way to put fields at the end of a widget's schema UI since we can't put them in their own group. This new field option, `last: true` puts the field at the end of its group (for any schema). This is especially useful for improving modules, which don't know the rest of the schema to do reordering. This also parallels the similar field group option.
-------------------
=> Adds a field option to put a field last in its group

CHANGELOG.md, package.json
Resolves PRO-2255
Run `npm test` and it should include an auditing step at the end.
=> PRO-2255 Adds the audit step of testing back in

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/lib/i18next.js
Closes #3475 
Closes PRO-2173
Use `htmlHelp` help text on a doc type field, such as:
```
htmlHelp: 'This link to the <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea" target="_blank">MDN textarea reference</a> should display properly.',
```
In the main branch this will only display the part after the colon. With this branch it will display that properly as HTML with a link. 
=> PRO-2173 Properly displays UI strings with colons.

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputArea.vue
Currently if you click "New Page" and then immediately switch page types without touching anything else, you get a console error, which is alarming although so far we have not identified any functional consequences. If there are any this could be turned into a hotfix release, otherwise it'll just come out normally. I've asked the client who reported it to clarify if there is a functional issue or not.
* Click "new page" in a3-boilerplate
* Without touching anything else, try to change the page type
* You should not get a console error with this fix in place
- [N/A] Related documentation has been updated
**Other …
=> PRO-2422 fix console error when switching page type immediately after clicking New Page

CHANGELOG.md, modules/@apostrophecms/util/index.js
Removes a utility template helper that would be throwing an error if used. indexBy is not included in lodash 4, which A3 uses.
No testing needed. You can test `indexBy` in the `main` branch to confirm it throws an error.
=> Removes util.indexBy

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputCheckboxes.vue
…
Fix the above bug. Fields of type `checkboxes` should not show as `malformed` if the value is switched to null momentarily during a page type switch.
See notes in linear.
=> PRO-2456 Switching page types fails with a "malformed" error if checkboxes are present

CHANGELOG.md, modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/ui/ui/apos/lib/i18next.js
Closes PRO-2406, supporting l10n keys in the UI without a namespace.
1. Use the testbed project branch PRO-2406-l10n, or register a l10n key for a piece type pluralLabel option. Previously the admin bar UI would display the l10n key, not its value.
2. Check the admin bar UI to make sure no l10n keys are showing instead of their values.
=> PRO-2406 Registers the default namespace in the UI i18n instance

CHANGELOG.md, lib/modules/apostrophe-login/index.js
Resolves ﻿PRO-2449. The string was using a pluralization namespace method, but due to the "(s)" part was not taking advantage of pluralization, so it does not need to be using `__ns_n()`.
1. Pull and install the https://github.com/apostrophecms/apostrophe-boilerplate/tree/temp-pro-2449 branch of apostrophe-boilerplate for A2.
2. Create a user, then attempt to log in three times with an incorrect password. Without this change, you will get a 500 error, shutting down the site. With this change, you see an error message that you'll have to wait 120 minutes.
=> PRO-2449 Fixes i18n processing of login throttle message

modules/@apostrophecms/piece-page-type/index.js, test/pieces-page-type.js
Closes issue #3650 by using `apos.util.addSlashIfNeeded` to correctly build URLs for all piece-page-types, even if they are at the root of the webpage.
Also added a test for it!
> 2. Set the homepage to a piece-page-type.
> 3. Use the _url property of a single piece in your template.
> 4. Check that the _url is `baseUrl/:slug` instead of `baseUrl//:slug`
=> Fix double slash URL bug when a piece-page-type is set as the homepage.

CHANGELOG.md, modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue, test/pieces-page-type.js
[PRO-2515](https://linear.app/apostrophecms/issue/PRO-2515/login-transition-is-not-working-well-when-leaving)
Fixes transitions between login steps, to transition in and out for each one.
*For example:*
> 1. Run a testbed project (or other) with afterPasswordVerified login steps.
> 2. Check that transitions between login pages and next steps are goind well.
=> fixes transitions

CHANGELOG.md, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, package.json
[PRO-2490](https://linear.app/apostrophecms/issue/PRO-2490/integrate-the-express-cache-on-demand-middleware-in-a3-core)
Adds Express cache on deman on get routes for pieces and pages (getOne / getAll). Also on the main route for rendering pages.
Has been tested with refactored `cache-on-demand` and `express-cache-on-demand`. See these PRs:
* [cache-on-demand](https://github.com/apostrophecms/cache-on-demand/pull/2)
* [express-cache-on-demand](https://github.com/apostrophecms/express-cache-on-demand/pull/5)
⚠️ This one should wait that both above have been merged and released.
Tested with 50 concurrent users and 200 reps, on benchmark mode (so without delays between requests), we can see an obvious difference on the Elapsed time, an average of 20 seconds (even more on the example) of …
=> Pro 2490 cache on demand

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuDialog.vue
These should allow you to get very close to what you asked for. To avoid pushing props too deeply there are some cases where you'll need a simple descendant selector too. For the username and password fields, use the existing `data-apos-field` selectors as a starting point to reach those fields by name.
=> PRO-2601 simple selectors for QA tests

CHANGELOG.md, modules/@apostrophecms/module/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/task/index.js, test/pages-public-api.js, test/pages.js, test/pieces-public-api.js, test/pieces.js
[PRO-2573/](https://linear.app/apostrophecms/issue/PRO-2573/caching-offer-a-simple-way-to-set-max-age-for-apostrophe-page-and-get)
Add the simple way to cache pages and pieces responses.
- Add the following config (diff below) to a project using A3, and `npm link` `apostrophe` (on the `2573-max-age` branch)
```diff 
diff --git a/modules/@apostrophecms/express/index.js b/modules/@apostrophecms/express/index.js
index 819359f..f2c0ac2 100644
--- a/modules/@apostrophecms/express/index.js
+++ b/modules/@apostrophecms/express/index.js
@@ -10,6 +10,10 @@ module.exports = {
role: 'admin'
}
}
-      : null
+      : {
+        myapikey: {
+          role: 'admin'
+        }
+      }
}
};
diff --git a/modules/@apostrophecms/page/index.js b/modules/@apostrophecms/page/index.js
index 6580174..fe2ebbc …
```
=> handle max-age cache-control

CHANGELOG.md, modules/@apostrophecms/login/index.js, test/login.js, test/modules/@apostrophecms/home-page/views/page.html
…
API keys and bearer tokens beat session cookies if both are present. Explicit should beat implicit. Needed for cypress tests.
See `test/login.js` which covers this (last test in file). Also general logged-in functionality should continue to work properly and no other tests should break.
=> api keys and bearer tokens should beat session cookies when both are present

modules/@apostrophecms/asset/index.js
The code to check whether a build is relevant to a scene was lost in the transition to extra bundles. I brought that logic back.
"npm run dev" while logged out on the testbed. Without this fix you get a console error from Apos UI code.
=> Fix from QA: public bundle should not receive apos UI build

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/apos/webpack.config.js, modules/@apostrophecms/asset/lib/webpack/src/webpack.config.js
It is now possible to use `npm link` to develop a module like `@apostrophecms/login-totp` that imports its own npm dependencies from frontend `ui/apos` or `ui/src` code.
In addition, apostrophe itself can be brought into a project with `npm link` without an error about failure to resolve `css-loader`, even if `css-loader` is not currently in project-level node_modules.
Of course, the module-level dependencies must be present in the npm linked module (I think npm link enforces that, but just to be clear).
Using up to date npm, you should be able to git clone and npm install testbed, then git clone and npm install `@apostrophecms/login-totp`, then run `npm link` in the login-totp folder, then run `npm link @apostrophecms/login-totp` in the testbed folder.
After these steps `npm run dev` …
=> PRO-2510 allow npm installed frontend dependencies of npm linked modules to work

CHANGELOG.md, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/asset/lib/webpack/src/webpack.config.js, modules/@apostrophecms/asset/lib/webpack/src/webpack.scss.js, modules/@apostrophecms/asset/lib/webpack/utils.js, modules/@apostrophecms/template/lib/bundlesLoader.js, test/assets.js, test/modules/bundle-page/ui/src/extra.js, test/modules/bundle-widget/ui/src/extra2.js
Fixes missing piece of the feature. Now multiple modules can contribute to the same bundle, they now export default functions. We reuse logic to write the import files.
Tweak webpack config to create bundles with the right name (`-module-bundle`) without touching the src-build bundle. and without having to copy manually our bundles...
Contribute to the same bundle from different modules.
You must export default function in your bundle files.
A module extending another that has a bundle will load this bundle too.
Check the order of apparition of your log adn see that the order of modules is respected.
=> Fixes bundles contribution

modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/image-widget/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposImageRelationshipEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue
[PRO-2680](https://linear.app/apostrophecms/issue/PRO-2680/actual-cropped-images-are-generated-when-the-cropping-modal-is-saved)
Call `/attachment/crop` route when `AposImageRelationshipEditor` modale is saved.
- add an image 
- click on "Image Adjustments"
- enter cropping data manually
- save the modal
- verify appropriate image filenames and sizes appear in public/uploads/attachments after cropping
=> call crop route when saving editor modal

.editorconfig, CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/module/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-page-type/index.js, modules/@apostrophecms/piece-type/index.js, test/docs.js, test/pages-public-api.js, test/pages.js, test/pieces-public-api.js, test/pieces.js
[PRO-2576](https://linear.app/apostrophecms/issue/PRO-2576/caching-emit-etags-for-the-context-document-and-invalidate-them-based)
Emit `ETags` that are used to cache pages and pieces.
When the `Etag` value of a doc is unchanged, the client will use the cached version version of the page or REST GET response (of a single piece or page, i.e: `getOne()`).
`ETags` value rely on the `cacheInvalidatedAt` docs field, which is updated every time the doc or one of its related docs is updated (thanks to backlinks: the `relatedReverseIds` field).
The related docs of a doc have also their `cacheInvalidatedAt` field updated, when the doc is updated
First, ensure that HTTP cache is not disabled:
**Pages**
- In private window tabs, go to:
- the GET REST API route of the homepage …
=> emit and handle etags

modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, test/pages-public-api.js, test/pages.js, test/pieces-public-api.js, test/pieces.js
In addition to #3692, give the possibility to set etags cache option for `api` _**and/or**_ `page` cache options, rather than setting it globally for `api` **_and_** `page` cache options.
See #3692 
=> move etags as a sub property of api and page cache options

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputString.vue
If a field of type float has max value set to 4, then:
- when typing 3.01 the value becomes 31 
- when typing 42.01 the value is as expected 42.01
The bug occurs when there is no error and the first number after the decimal (.) is `0`.
Closes PRO-2641.
Passing UI tests.
=> PRO-2641: fix float field value typing bug

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, test/pieces-public-api.js
Resolve attachment owned `_urls` for API calls.
Closes #3643 
Closes PRO-2502
Related to https://github.com/apostrophecms/apostrophe/pull/3525
Attachment URLs are computed by default.
=> PRO-2502: Resolve _urls by default

CHANGELOG.md, modules/@apostrophecms/image-widget/index.js, modules/@apostrophecms/image/index.js, modules/@apostrophecms/schema/index.js
* Piece type modules may specify a default set of fields for any relationship with that type, as well as a vue component to be used to edit those fields.
* Configured that for the `@apostrophecms/image` type and removed it from the `@apostrophecms/image-widget` type, showing that custom slideshow widgets etc. will "just work" with cropping without having to think about this.
*For example:*
Crop an image for a particular placement in an image widget in the testbed, as per normal. Note that this works and displays the proper editor even though the configuration for that exists only in the image piece type.
=> PRO-2687 default relationship editor and fields

CHANGELOG.md, modules/@apostrophecms/asset/lib/globalIcons.js, modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/image/index.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlatList.vue
[PRO-733](https://linear.app/apostrophecms/issue/PRO-733/as-a-user-i-should-not-be-able-to-crop-an-svg-ie-it-should-not-try-and)
Reuse logic from A2 to check if an image attachment is croppable or not.
Passes the info to frontend when requesting documents attachments.
Renames `labelKey` in `editRelationLabel` to make it understandable. Uses this one instead of the classic one when passed.
* Link the branch in an A3 project (testbed)
* Add image widget on a page
* Add normal images and see you can still open the cropping modal
* Add svg image in the widget and see the context menu disapear.
=> pro-733 No cropping for svg

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/doc/index.js, test/docs.js
Allow every module to add custom context operations to `AposDocContextMenu`.
Use `apos.doc.addContextOperation()` to add context operation from within any module. Enter edit mode and find the corresponding context menu (Editor modal and In-context editor menu). Click it to open the provided modal component.
Corresponding UI tests are to be found in the testbed.
=> PRO-2696: Add support for custom context operations 

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/i18n/es.json, modules/@apostrophecms/i18n/i18n/pt-BR.json, modules/@apostrophecms/i18n/i18n/sk.json, modules/@apostrophecms/piece-type/ui/apos/components/AposImageCropper.vue
[PRO-1973](https://linear.app/apostrophecms/issue/PRO-1973/as-a-user-i-can-specify-a-focal-point-on-an-image-in-an-image-field)
Handle focal point by moving it via drag&drop and clicking on the image.
Focal point coordinates are relative to the stencil (cropper rectangle), and are set as percentages.
For instance, clicking at the very center of the stencil, focal point coordinates will be `{ x: 50, y: 50 }`.
When clicking or moving it outside the stencil, coordinates will be sent as `{ x: null, y: null }`.
**Important note:** we cannot rely on the cropper coordinates that come from its API, because they do not reflect reality.
In other words, the cropper coordinates are updated when zooming on the image, but the focal position remains the same.
So taking the cropper coordinates provided …
=> 1973 focal point

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
`AposDocEditor` updates its doc contents on `content-changed` (bus emit).
Fire from the dev console:
```js
apos.bus.$emit('content-changed', {
doc: newDoc,
action: 'someAction'
});
```
where `newDoc` is a patched version of the current edited document.
=> PRO-2699: Let AposDocEditor pickup changes from other modals

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputArea.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputObject.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue
We don't really deep-watch the value prop of AposSchema for performance reasons, schemas can be deeply nested and the potential for this to cause severe performance problems if we check it every time `value` changes due to our own `input` event is too great. `value` is primarily consulted only at mount time so this is usually OK, however occasionally a truly external change to the data does occur and there must be a way to force a refresh of all fields. Implement and internally document that mechanism so our internal developers know we're not strictly respecting `v-model` in this component.
When npm linked to both this branch of apostrophe and the corresponding branch of Document Versions, open Document Versions for the home page, then try this in the browser console:
``` …
```
=> PRO-2768 workaround for not deep watching value of AposSchema

modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/doc/index.js, test/docs.js
Custom menus can define `manuallyPublished` property. Based on that value they will be shown only in the desired context. For example `manuallyPublished :true` will show the menu only when the corresponding doc module options are `autopublish: false` and `localized: true`.  
Set `manuallyPublished: true` to a custom menu. E.g. Users piece should not have that context menu available.
=> PRO-2779: allow manuallyPublished chck for the custom context menus

modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/image/index.js, modules/@apostrophecms/image/ui/apos/components/AposImageRelationshipEditor.vue
The manual cropping interface does not appear for SVGs, whether the placement involves a fixed aspectRatio or not.
The autocrop feature should behave analogously by just not trying to autocrop SVGs.
(Not allowing them to be selected in the presence of aspectRatio is an interesting idea but not in scope and not required for A2 parity.)
* Fire up the `feature-image-cropping` branch of `testbed` with the `autocropping-versus-svg` branch of apostrophe
* Verify you can pick an svg for an image widget nested in a two-column widget (has 3x2 aspect ratio constraint). The svg will not be constrained, that's OK
* Verify that if you pick a jpg it does get constrained when you save the widget, even if you never manually crop it (this is autocrop)
If adding a new feature without …
=> Autocropping versus svg

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
The generation prop must work for changes to widgets within areas. Fun fact: `:key` is not just for v-for...
https://vuejs.org/api/built-in-special-attributes.html#key
Two consecutive versions in which a rich text widget **already exists but has a different value** should display properly when clicking them in the versions modal.
Changelog is N/A because the larger feature this completes has not yet shipped.
=> widgets must respect the generation prop

CHANGELOG.md, lib/moog-require.js
The `nestedModuleSubdirs` feature no longer throws an error and interrupts startup if a project contains both `@apostrophecms/asset` and `asset`, which should be considered separate module names.
* Check out `apostrophecms/utah-a3`, switch branches to `nestedModules`, npm install, npm link with this branch of apostrophe. Launching "node app" reaches "listening on port 3000" without issue.
* Switch back to the "main" branch of apostrophe and restart. Throws an error complaining that there are two folders for the asset module, which is wrong (the namespaced module `@apostrophecms/asset` should be considered completely unrelated to the module `asset`).
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait …
=> PRO-2739 fix nestedModuleSubdirs bug

CHANGELOG.md, modules/@apostrophecms/asset/index.js
…
Properly detect package lock file based on npmRootDir, not rootDir, in case they differ (multisite)
Adding `@apostrophecms-pro/document-versions` to an existing assembly project (not just single site) should correctly rebuild the admin UI the next time `npm run dev` is invoked. This already worked for single-site projects, and of course must continue to work for them.
=> PRO-2808: properly detect package lock file based on npmRootDir, not rootDir, in case they differ (multisite)

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
[PRO-2746](https://linear.app/apostrophecms/issue/PRO-2746/aposdoceditor-should-inject-originaldoc-into-descendant-components)
Provides the original document to `AposDocEditor` children.
Inside a child component (`AposModalRail.vue` for instance), inject `originalDoc` and display one of its properties:
```vue
<template>
<div class="apos-modal__rail" :class="`apos-modal__rail--${type}`">
<p>{{ originalDoc.ref && originalDoc.ref.lastPublishedAt }}</p> 
<slot />
</div>
</template>
<script>
export default {
name: 'AposModalRail',
inject: [ 'originalDoc' ], // INJECTION
props: {
type: {
type: String,
default: 'left'
}
},
computed: {
}
};
</script>
```
The property of the doc should be accessible:
=> provide original doc to editor component's children

.stylelintrc, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarLocale.vue, modules/@apostrophecms/image/ui/apos/components/AposImageCropper.vue, modules/@apostrophecms/image/ui/apos/components/AposImageRelationshipEditor.vue, modules/@apostrophecms/login/ui/apos/components/TheAposLoginHeader.vue, modules/@apostrophecms/ui/ui/apos/components/AposSpinner.vue, package.json
[PRO-2735](https://linear.app/apostrophecms/issue/PRO-2735/fix-stylelint-issues)
- add `stylelint` command to `lint` script, to run it in CI
- fix style lint errors
- remove unused `stylelint-config-standard` dependency
**before**
```sh
modules/@apostrophecms/image/ui/apos/components/AposImageCropper.vue
432:5   ✖  Expected "z-index" to come before "position"                 order/properties-order                  
432:5   ✖  Expected variable, function or keyword for "1" of "z-index"  scale-unlimited/declaration-strict-value
439:22  ✖  Expected a minimum of 150 milliseconds                       time-min-milliseconds                   
439:22  ✖  Expected a minimum of 150 milliseconds                       time-min-milliseconds …
```
=> run stylelint in ci and fix errors

CHANGELOG.md, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/i18n/i18n/en.json, test/assets.js
Keep the same Apostrophe process alive between front-end builds in a development environment.
Awaits #3752 and consequent merge from `build-optimization` branch in order to avoid double code review.
> The node modules paths are adapted so that they don't blow up the developer's machine when deep circular matches are found (think of linked apostrophe, having linked test having linked apostrophe) due to linked modules in development having other linked modules. @boutell  
Closes PRO-2784
- In a3-boilerplate and testbed, changes to ui/src or ui/apos or ui/public do not trigger a nodemon restart, yet the build process is successfully repeated, by the existing process.
- A page refresh is triggered in this situation.
- The newly built assets load properly in this situation. 
*(Check at least …
=> PRO-2784: Add build watcher

modules/@apostrophecms/page-type/index.js
In the case where modules are improving `@apostrophecms/doc-type` and add some custom fields, these custom fields are placed _before_ the follwing default `page-type` module's fields:
```
'slug',
'type',
'visibility',
'orphan',
```
To prevent that and keep these fields above ☝️, _above_ the rest, merge the ones added by modules improving `doc-type` into the `page-type` ones.
Example with a module that improves `doc-type` and adds the `Publish this document on` and `Unpublish this document on` fields:
**before**
**after**
=> keep default page-type fields at the beginning

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/page-type/index.js
Pass an option to unpublish children when archiving a page.
Regression appeared in #3754 
- archive a page that has children
- choose the "Archive this page and all child pages" option
- no such following error message should appear and the page children should be in draft (i.e. unpublished) and moved to the archive
=> fix page children archiving

CHANGELOG.md, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/task/index.js, test/assets.js
Recover after a build error when in a watch mode. This fix provides solution in two stages:
- Add a rebuild error handling so that errors don't break the process
- Fixes an issue with `task.invoke` when it doesn't reset properly the apos `argv` which is best observable in this particular scenario but it also affects any error handled task invocations (`apos.isTask()` will always return `true`). 
Closes PRO-2830
Run application in development mode and:
- Edit a watched asset and create a bad code to reproduce webpack build error
- Console log should show detailed information about the error
- The page should not be reloaded
- Edit the same file and correct the error
- A normal rebuild should occur
- The page should be reloaded 
=> PRO-2830: recover after a build error

CHANGELOG.md, modules/@apostrophecms/asset/index.js
A patch related to https://github.com/apostrophecms/apostrophe/pull/3769
- Make `argv.changes` command line friendly (comma separated list). Introduces limitation when build paths should not contain comma characters.
- Add missing entry of `task.invoke` fix to the CHANGELOG
No change in the behavior introduced in the related PR (see above).
=> Make changes argument command line friendly, add missing CHANGELOG entry

CHANGELOG.md, modules/@apostrophecms/login/index.js
[1142](https://gitlab-dcadcx.michelin.net/pa/apostrophe-enhancements/-/issues/1142)
Fixes missing plural label for login max attempts error message.
For normal login and requirement verification
* Link branch to A3 project
* Setup `lockoutMinutes` in login module config
```javascript
'@apostrophecms/login': {
options: {
throttle: {
lockoutMinutes: 2
}
}
},
```
* Try to exceed max login attempt in initial login, the message should take into account the lockoutMinutes value
* Try to exceed max login attempt in totp login, the message should take into account the lockoutMinutes value
=> Fix max login attempts msg

CHANGELOG.md, package.json
dart sass got pickier (or buggier?) in 1.52.2, printing:
SassError: RangeError: Invalid value: Not in inclusive range 0..145: -1
1.52.1 does not do that, so pinning for now. Absolutely not doing anything more ambitious in a hotfix. I'll open tickets for deeper solutions.
* Blow away `package-lock` and `node_modules` in your checkout of apostrophe itself. Now `npm install` there. Make sure you are npm linked to that checkout in a3-boilerplate. Now try to run `APOS_DEV=1 npm run dev`. You can't, you get the SASS error.
* Now Check out this branch and run `npm install` in your apostrophe folder.
`APOS_DEV=1 npm run dev` should work now.
Pinned sass version temporarily.
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for …
=> Release 3.21.1

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposFile.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue
* Disable the slat controls of the attachment component while uploading.
* Fixes bug when re-attaching the same file won't trigger an upload.
* AposSlat now fully respects the disabled state.
1. Use attachment field to upload a large file
2. Verify the preview link and the remove attachment button are disabled during the upload
3. Verify the preview link and the remove attachment button are disabled after the upload is finished
4. Remove the attachment
5. Select the SAME file to upload
6. The upload should start
=> PRO-2640: The "remove attachment" button should be disabled during upload

CHANGELOG.md, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/schema/ui/apos/components/AposArrayEditor.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue, package.json
- If an array field's `titleField` option is set to a select field, use the select's label as a slat label rather than it's value
- Fixes the current array slat's label color
- Prevents an array slat's label from obscuring the Remove button in narrow viewports
*For example:*
1. In the a3-demo repo you can checkout  & link [test-select-label-as-slat-label](https://github.com/apostrophecms/a3-demo/tree/test-select-label-as-slat-label)
2. `npm run dev`
3. In the Topics piece admin, the Fancy Fields > Array Field uses a select field as its titleField. Confirm the select's `label` is being used as the slat label
**Other …
=> Array editor's slats use titleField's select label

CHANGELOG.md, modules/@apostrophecms/asset/index.js, test/assets.js
Fix a Webpack cache issue leading to modules symlinked in `node_modules` not being rebuilt. 
Copy the asset module index.js from this PR to `node_modules/apostrophe/modules/@apostrophecms/asset/index.js` in the dedicated test repo. Clear the Webpack cache, boot and do changes. The changes should be applied.
Fixes a random failing test due to wrong expectations.
=> Fix symlinked node modules not being rebuilt

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/i18n/es.json, modules/@apostrophecms/i18n/i18n/fr.json, modules/@apostrophecms/i18n/i18n/pt-BR.json, modules/@apostrophecms/i18n/i18n/sk.json, test/docs.js
Add the "Share draft" option to the context menu of pages and pieces (only pieces that have an index page of their type).
- run testbed
- add an article
- the "Share draft" option should not be displayed in the context menu:
- open pages manager
- create a page 
- the "Share draft" option should be displayed for this page:
- now create a page of the type `Article Index`
- go back to the articles manager
- articles should now display the "Share draft" option:
=> add share draft option to context menu

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/i18n/es.json, modules/@apostrophecms/i18n/i18n/fr.json, modules/@apostrophecms/i18n/i18n/pt-BR.json, modules/@apostrophecms/i18n/i18n/sk.json, modules/@apostrophecms/modal/ui/apos/components/AposModalShareDraft.vue, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js
[PRO-2814](https://linear.app/apostrophecms/issue/PRO-2814/as-a-frontend-developer-i-can-invoke-a-draft-sharing-rest-api)
Checks infos from the current document to see if it's sharable, otherwise close the modal and notify the user.
When toggling button, call the right API route to share or unshare a document, update url depending on the response.
Adds translation to manage error in notification
* Link branch in testbed (or another project)
* In a piece context menu click on `share draft`
* It should open the share draft modal disabled
* Try to enable it, it should create and url and allow to copy it through a link
* Close to modal, if you come back the share draft should be enabled when opening the modal
* When disabling enabling, the  `aposShareKey` should be new
* Do the same test for …
=> Pro 2814 invoke share api

CHANGELOG.md, lib/modules/apostrophe-soft-redirects/index.js, test/soft-redirects.js
Take into account query string in redirections.
- create a page or a piece
- change its slug
- access the the old slug with one or multiple query params
- you should be redirected to the new slug, with the query param(s)
=> keep query string in redirections

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/login/index.js, modules/@apostrophecms/module/index.js, modules/@apostrophecms/permission/index.js, modules/@apostrophecms/soft-redirect/index.js, test/modules/test-page/views/page.html, test/pages.js, test/pieces.js
Grant access to the preview of a shared draft.
To do this, provided that the URL query string contains the right key, we hide the admin UI by removing the user from `req`, we edit mongo criteria to force-fetch the draft, and we transform the draft data to make it pass for a published doc.
- edit a piece (article for instance, and check that a Article Piece Index page has been created first)
- enable the draft sharing option
- use the URL
- while logged-in 👉 you should see your last modification (not yet published), without any admin UI
- while logged-out 👉 you should see your last modification (not yet published)
- do the same for a page
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval …
=> give preview access to a shared draft

CHANGELOG.md, index.js, lib/moog-require.js
I am using symlinks in a project. A module inside `modules` folder has other nested modules. Without the `follow: true` flag, `glob` package does not register the nested modules during Apostrophe's module initialisation.
*For example:*
> 1. Add a symlink folder inside `modules` folder
> 2. Add nested modules
> 3. Register nested modules inside `modules.js`
=> follow symlinked directories when expanding ** patterns

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue
This patches disabled context menu for relationship editing as reported in #3820.
Optional chaining added in order to not break the Vue Devtools while debugging.
Closes PRO-2928, Closes #3820
Follow the steps to reproduce from the original report #3820. The context menu in question should be enabled.
- [] Related documentation has been updated
=> PRO-2928: Fix missing Vue binding

CHANGELOG.md, modules/@apostrophecms/polymorphic-type/index.js, modules/@apostrophecms/task/index.js
Useful for this ticket [PRO-2881](https://linear.app/apostrophecms/issue/PRO-2881/getcontenttypesreq-method-of-advanced-permissions)
Adds the `showPermissions` options set to false to the `polymorhic` module.
Fixes the getReq method, extract the right `role` property from the options.
*For example:*
=> Permission options

CHANGELOG.md, modules/@apostrophecms/i18n/index.js, test/pages.js, test/pieces.js, test/static-i18n.js
If a locale has a `private: true` option, accessing to the content in that locale while logged out will result in a 404.
Link `apostrophe` into a project.
In the project, configure `@apostrophecms/i18n` module with one or several locales with the `private: true` option:
While logged in, you should be able to access to the private locales, but not logged out.
=> handle private locales

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposArrayEditor.vue
The `def` items were not displayed in the UI because they were missing an `_id`.
Link `apostrophe` into an A3 project, and add default items to an array field type, as below:
```js
people: {
type: 'array',
fields: {
add: {
firstName: {
type: 'string'
},
lastName: {
type: 'string'
}
}
},
def: [
{
firstName: 'Jane',
lastName: 'Doe'
},
{
firstName: 'Saul',
lastName: 'Goodman'
}
]
}
```
The 2 items above should be added by default:
Saving a doc without having edited the array field will still store the default fields:
=> handle default array items in array editor modal

CHANGELOG.md, lib/modules/apostrophe-caches/index.js, test/caches.js
…name
Fix bug preventing two caches from having a key by the same name
* `npx mocha test/caches.js` should pass (in a proper checkout of this branch in which `npm install` has been completed)
* Project-level code in which two differently named caches have a key with the same name should work properly
=> PRO-2956: fix bug preventing two caches from having a key by the same name

CHANGELOG.md, package.json
Just a release PR, and bump sanitize-html dependency to ensure the DOS attack fix.
=> release 3.25.0

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposImageRelationshipEditor.vue, modules/@apostrophecms/permission/ui/apos/components/AposInputRole.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputSelect.vue, modules/@apostrophecms/ui/ui/apos/components/AposSelect.vue
`AposSelect` to emits `JSON.parse` value on change event
1. Login to the backoffice
2. Find a piece with an `AposSelect` element and change the value (e.g. `Event`, requires `@apostrophecms/event` to be installed)
3. Save the piece and reload the edit modal to see if the new value is still there
4. Insert an image into a page and change the crop ratio. The selected value must be reflected in the crop area
5. Edit a user and change the `Role`. If you save it and reload, you must see the previously selected value
=> emit JSON.parse value on change event for AposSelect

CHANGELOG.md, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/util/index.js
This PR implements the `getObjectManager` method for `Object` field types. This closes #3755.
Create a field of type `Object` with a sub-field of type `area`. The area should be rendered properly this time with no templating errors being raised.
=> Implement getObjectManager for Object field types

CHANGELOG.md, modules/@apostrophecms/asset/index.js
Closes #2630 
Don't just rely on setTimeout to do the job of DOMContentLoaded. This can break if the download of the page itself takes a while, resulting in no admin UI.
`npm run dev` and the admin UI works normally. TOUGH to prove a negative, but it should still work (eventually) when Chrome's network speed simulator is set to "fast 3G" (checking this is optional).
This could also explain occasional failures in CI, cc Miro.
=> PRO-3071 cannot find #apos-modals sometimes

CHANGELOG.md, package.json
Release PR only. Urgent hotfix for an enterprise client, previously reviewed approved and tested. No code changes. First to approve it gets... a fist bump?
=> release 3.26.1 (urgent for HO)

modules/@apostrophecms/asset/lib/webpack/apos/webpack.scss.js, package.json
Remove stylelint plugin from webpack, this was causing breakage for our staging site after the move of stylelint to devDependencies. We don't need this in webpack because we have it in the lint subtask of our npm tests. Automatically linting project specific apos custom admin styles was nice but not worth the install weight in production. Project level developers should set their own style linting rules.
staging should autodeploy successfully after this merges
=> Remove stylelint from webpack

CHANGELOG.md, modules/@apostrophecms/login/index.js
A successful call to the login API to retrieve a session cookie currently does not return any information for the body. If a developer tries to query the fetch response this results in an invalid JSON error. This PR fixes this by adding the return of an empty object. Closes PRO-3073.
*For example:*
1. Create a new site instance.
2. Submit a request for a session cookie to the API with the …
=> Pro 3073 login json

modules/@apostrophecms/permission/ui/apos/components/AposInputRole.vue, modules/@apostrophecms/permission/ui/apos/components/AposPermissionGrid.vue
- [PRO-2876 - Displaying the permissions grid as part of the rolesByType field](https://linear.app/apostrophecms/issue/PRO-2876/displaying-the-permissions-grid-as-part-of-the-rolesbytype-field)
- [PRO-2883 - rolesByGroup custom schema field type](https://linear.app/apostrophecms/issue/PRO-2883/rolesbygroup-custom-schema-field-type)
Related PR: https://github.com/apostrophecms/advanced-permission/pull/9
Extract the permission grid in order to be able to instantiate it from different contexts, passing it a `role` (default parameter in core), `rolesByTypes` or `_groups` params (used in advanced permission module, see https://github.com/apostrophecms/advanced-permission/pull/9).
The API params are used to call the permission module's `/grid` POST route API.
```vue
<AposPermissionGrid …
```
=> extract permission grid

modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/attachment/lib/tasks/rescale.js
Closes #2712 
Updates the `attachment` module to accept .webp file uploads
>1. Run the website and log in as an admin
>2. Upload any `.webp` image
>3. Save and add the image to a section of the website
Testing an upload locally - *[Screencast](https://watch.screencastify.com/v/wdjD1oB47OGGQtzdXSYZ)*
With animated webp - *[Screencast](https://watch.screencastify.com/v/y180R24gJHyVibxBPfEH)*
`Uploadfs` with ImageMagick appears to support .webp out of the box without additional changes - *[Test cases](https://asciinema.org/a/476097)*
=> update attachment module to accept .webp files

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue
Add a `click` event on the modals' overlay to close them.
Open some modals (widget modals, Pages, Articles, Files ones etc) and open other modals inside them and so on...
Check that clicking outside each one closes them _the same way_ the ESC key does.
A bit of 🐒 testing won't do any harm
=> close modal by clicking outside of it

CHANGELOG.md, modules/@apostrophecms/attachment/index.js
The `attachment` module currently assigns an empty object to the `attachment._crop` property. Both the `getHeight()` and `getWidth()` template helpers of this module interrogate this property to return either the original dimension or the cropped dimension by simply testing truthiness. Since an empty object is true, the methods are returning `undefined` for the dimension of uncropped images. This PR changes the assignment of the value of `attachment._crop` to `undefined`, which is falsy if no crop has occurred. This PR also changes the assignment of `attachment._focal` for consistency. Closes PRO-3112.
*For example:*
> 1. Run the website and …
=> Change _crop assignment to allow `getHeight()` and `getWidth()` to work correctly

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/i18n/es.json, modules/@apostrophecms/i18n/i18n/fr.json, modules/@apostrophecms/i18n/i18n/pt-BR.json, modules/@apostrophecms/i18n/i18n/sk.json, modules/@apostrophecms/rich-text-widget/index.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, package.json
Depends on #3882
Closes [PRO-3146](https://linear.app/apostrophecms/issue/PRO-3146/implement-per-area-and-global-fallback-placeholder-options-for-rich)
Set a default placeholder value for rich text widget:
The placeholder disappears as soon as we start typing in.
It's overridable on project side, so if it's overridden with a falsy value, it will display the normal/previous behaviour.
On testbed:
```js
// in a project's modules/@apostrophecms/rich-text-widget/index.js
options: {
placeholderText: 'Start typing here!!!'
},
```
👇 
---
```js
// in a project's modules/@apostrophecms/rich-text-widget/index.js
options: {
placeholderText: false // or any falsy value
},
```
👇 
If adding a new feature without an already open issue, it's best to open a **feature request issue** …
=> display placeholder for rich-text-widget

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue
Depends on #3882
Display default values defined in widgets options of a specific area.
On testbed,
In  _topic-widget/index.js_:
- add the `initialModal: false` option to the module
- add `def: 'default title'` to the title field
In _lib/area.js_:
- configure the topic and rich text widget as follow:
```js
topic: {
_def: {
title: 'Default title everywhere'
}
},
'@apostrophecms/rich-text': {
_def: {
content: '<i>Default content everywhere</i>'
},
// ...
```
In _modules/articles/article-page/index.js_:
```js
widgets: {
topic: {
_def: {
title: 'Default title in article pages'
}
},
'@apostrophecms/rich-text': {
_def: {
content: '<i>Default content in article pages</i>'
},
// ...
```
---
Add a rich text and a topic widget to the home page, they should have should the default data set in the …
=> display default area-specific widget content

modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue
Time is limited this week, so I didn't dig hard to figure out why `options.widgets` was not populated here, I just provided a utility to rifle through it for the appropriate set of widget options in either format.
Verify the expanded widget menu and regular widget menu still work properly both on the page and in the modal.
=> PRO-3196 widget options might not be flattened in AposAreaEditor, find them in groups if needed

modules/@apostrophecms/widget-type/index.js, test/widgets.js
Render widgets that have a placeholder, only on edit mode.  
| edit mode                                                                                                      | preview mode                                                                                                   |
|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/8301962/193244758-1ffcfee4-9464-49a8-9344-bd247a03dd5c.png) | ![image](https://user-images.githubusercontent.com/8301962/193244890-0b29f0fe-49db-473e-bf3e-88056c4a7af8.png) |
Ensure that placeholders are rendered only on edit …
=> do not render widgets placeholder on preview mode

CHANGELOG.md, modules/@apostrophecms/login/ui/apos/components/TheAposLogin.vue
https://linear.app/apostrophecms/issue/PRO-3101/login-button-remains-disabled-after-invalid-login-attempt-when-using
Remove requirements check after a failed login attempt (because it has been validated before submission)
=> fix captcha bug when login failed

CHANGELOG.md, modules/@apostrophecms/express/index.js
The `express` CLI task `list-routes` help message was malformed and using a `help` rather than `usage` property. This PR corrects this. Closes PRO-3205.
*For example:*
1. In an apostrophe project run the command: `node app help @apostrophecms:list-routes`
2. Observe the returned usage message
If adding a new feature without an already open issue, it's best to open a …
=> Pro 3205 express cli help error

CHANGELOG.md, modules/@apostrophecms/attachment/index.js
This refactors the `addFileGroup()` method to not just expand existing file groups but also add new groups. Closes PRO-3112.
*For example:*
1. Create a file like `modules/@apostrophecms/custompiece/index.js` file.
2. Add the following code:
```
init(self) {
const newGroup = {
name: 'movies',
extensions: [
'mp4'
],
extensionMaps: {}
}; …
```
=> refactor addFileGroup method

modules/@apostrophecms/area/index.js, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/image-widget/index.js, modules/@apostrophecms/rich-text-widget/index.js, modules/@apostrophecms/video-widget/index.js, modules/@apostrophecms/widget-type/index.js, modules/@apostrophecms/widget-type/ui/apos/mixins/AposWidgetMixin.js, test/modules/placeholder-widget/index.js
Add `placeholder` option to widget modules.
If truthy, it will automatically disable the initial modal (by setting `initialModal` to false) and render widgets that do not have data yet with their placeholder(s).
Placeholder for image, video and rich text widgets are enabled by default in core.
In testbed, add `placeholder: true` to a widget of your choice.
- the initial modal should not appear
- the widget should have been inserted with the placeholder defined in the widget field(s).
- image, video and RT widgets should be inserted directly with their placeholder by default.
- placeholders should be overridable (`placeholderUrl` for image and video widgets, `placeholderText` for rich text widget, and `placeholderClass` for any other widget)
- placeholders can be disabled by setting it to …
=> add placeholder widget option

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/apos/webpack.config.js, package.json
* vue 2 admin UI build coexists with vue 3 project level build
* Check out the `pro-2568` branch of `testbed` and `npm install` it normally (do not npm link). It has a github dependency on the appropriate branch of the apostrophe module.
* `npm run dev`
* Note that a vue 3 component (self-identified) appears on the page and has a functioning button
* Note that the admin UI also works if logged in
* Make sure everything also works, including tweaking the admin UI code (touch a core admin UI vue component), if you `npm link` apostrophe into the project.
We had originally pinned `vue-loader` to a slightly earlier release because of a release that broke our ability to `npm link` apostrophe and still have a valid admin UI build. However I did not observe this bug today. I think they introduced …
=> PRO-2568: vue 2 admin UI build coexists with vue 3 project level build

modules/@apostrophecms/widget-type/index.js, test/modules/bundle-page/ui/src/extra.js, test/widgets.js
* do not try to "convert" while aposPlaceholder is still in effect (it breaks required fields)
* do not clone unnecessarily (performance)
* always respect placeholders regardless of field values until aposPlaceholder is cleared
See the `link-widget` branch of `testbed` which introduces a simple link widget that exercises the features that required the "no convert when aposPlaceholder is true" fix. The other changes were not critical for that particular QA test but are still improvements.
=> QA errata for placeholders

CHANGELOG.md, package.json
Release 3.31.0, with tweaks to changelog including correct final link to the widget placeholder docs.
=> release 3.31.0

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js
Add `null` to select fields with a function name as choices.
When there is a select field with a function as choices and a filter for this same field, documents are not displayed in the manager modal by default. One has to select a namespace in the filter to see some pieces. It’s because of `def: null` in the filters.
1. Create a module with a schema using a select with a function name for choices:
```js
options: {
label: 'test',
},
fields: {
add: {
item: {
label: 'Item,
choices: 'getItems',
},
},
},
filters: {
add: {
item: {
label: 'Item',
def: null,
},
},
},
methods(self) {
return {
getItems(req) {
return [{ label:'item 1', value: 'item1' }, { label: 'item 2', value: 'item2' }] 
},
}
},
}
```
2. Create pieces and …
=> Add `null` to select fields with a function name as choices

CHANGELOG.md, modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
Solves the problem of navigating the modal wizard, while the state is not ready for that. No matter we introduce the global busy state (the blue screen of death) on every request to the back-end, it takes reasonable time before it shims the entire screen. With this patch the action buttons are always disabled when an action should not be performed.
See the ticket acceptance criteria.
=> PRO-3170: Better i18n UI state management

modules/@apostrophecms/asset/lib/globalIcons.js, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue
- Nudges styles to accommodate larger schemas
- Displays `titleField` labels like the full array editor
- Collapse/expand mechanism for editing
=> massages inline array styles and ux

CHANGELOG.md, lib/modules/apostrophe-doc-type-manager/index.js, lib/modules/apostrophe-docs/lib/api.js, lib/modules/apostrophe-pages/lib/api.js, lib/modules/apostrophe-permissions/lib/strategiesApi.js, lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-users/index.js, test/permissions.js, test/schemas.js
⚠️ this is an **Apostrophe 2** feature request
Allow to exclude certain groups from seeing a piece or a page
Pre-requisite:
`apostrophe-users` option `groups` must be false for `Groups` to appear in the admin-bar.
1. Create 2 groups `premium` & `basic` with the `Guest` permission
2. Create 2 users `premium` & `basic` and assign it the group with the same name
3. Create a new page `premium` and select in the `Permissions` tab the following
a. `Who can view this?` = `Certain people`
b. `These Groups can View` = `premium`
4. Create a new page `basic` and select in the `Permissions` tab the following
a. `Who can view this?` = `Exclude Certain people`
b. `These Groups cannot View` = `premium`
5. Login as `premium` and check that you can only see the `premium` page
6. Login as `basic` and check …
=> Apostrophe 2: add excludeCertainUsers from seeing a piece or a page

CHANGELOG.md, modules/@apostrophecms/schema/index.js, test/concurrent-array-relationships.js
See the A2 ticket. In A3 it's not clear if this bug is really possible because the `_arrays` and `_dotPaths` properties are never deleted at present, but it is advisable not to share these properties between requests.
New tests pass (but they also pass without the patch 🤷‍♂️)
=> Protect against any possibility of dcad-1191 manifesting in A3

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
For easier extension of the rich-text, checking and adding all `defaultOptions` to the `activeOptions`.
*For example:*
> 1. Extend your rich-text-widget with new `defaultOptions` (maybe you want to use them in a new and fancy component you've written)
> 2. Check the `activeOptions` for the new `defaultOptions`
- as far as I have seen there is nothing to update
- as far as I have seen there is nothing to update
=> Flexible rich text default options

CHANGELOG.md, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/page/index.js
See changelog. I couldn't wait for UT to start up one more time. Also important for good performance of relationships at all times.
Start up a site with a lot of related documents or images on the home page. Parked pages don't take forever and slow down your progress. (I did this already with UT.)
=> fast parking

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js, modules/@apostrophecms/search/index.js
Makes sure you can search i18n static pieces by value and not just by key. This was never properly ported from A2 to A3 before.
=> fix the search index

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/Default.js, modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/ListItem.js
* Fixed bulleted and ordered lists. You can select existing text and create a list from it
* You can then continue the list with the "enter" key and you get the default style of your particular rich text widget as expected inside each item
* You can select existing text and create a list from it (if you don't see any bullets make sure your project has styles, or check the inspector; but definitely make sure the markup is there)
* There will be paragraphs (or your other default style's tag) inside each list item, this is mandatory ProseMirror behavior, I did not come to catch that fish today
=> PRO-3428 fix lists

CHANGELOG.md, lib/modules/apostrophe-areas/lib/api.js, package.json
All versions of package deep-get-set are vulnerable to Prototype Pollution via the 'deep' function. Note: This vulnerability derives from an incomplete fix of [CVE-2020-7715](https://security.snyk.io/vuln/SNYK-JS-DEEPGETSET-598666)
> 2. Edit an area and check if it saved correctly
=> Remove deep-get-set package

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/file-tag/index.js, modules/@apostrophecms/image-tag/index.js, package.json
Every module extending `doc-type` has now `options.shortcut`, allowing it to re-map its manager command shortcut.
Login in any Apostrophe application and open Image tags manager via `g,o` shortcut and File tags manager via `g,g` shortcut. 
=> Add manager shortcut option for every doc type

CHANGELOG.md, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/polymorphic-type/index.js, modules/@apostrophecms/polymorphic-type/lib/migrations.js
Remove noisy polymorphic-type has no manager warning when running testbed
1. Setup testbed to use `github:apostrophecms/apostrophe#pro-3223-type-without-manager-polymorphic`
2. Run cypress tests. You don't need to wait for the full tests to complete. Each scenario was previously returning the warning.
You can compare the output from https://github.com/apostrophecms/testbed/actions/runs/3819327850 (without the fix) vs https://github.com/apostrophecms/testbed/actions/runs/3828244225 (with the fix included).
=> Pro 3223 type without manager polymorphic

CHANGELOG.md, modules/@apostrophecms/asset/index.js
- Do not merge module `webpack.extensions` configuration with the core `apos` build
- Allow applications and modules to control array and object Webpack configuration merging 
**A (Real World) Scenario**
A module `public-forms` is providing public forms via a Vue 3 UI. It extends webpack configuration in order to achieve that. Here is the relevant implementation, that is only possible with the changes made in this PR (explanations "How" can be found below).
```js
// possible npm module  'public-forms' - index.js
webpack: {
extensions: {
vue3: {
resolve: {
extensions: [ '*', '.js', '.ts', '.vue', '.json' ],
alias: {
// The application should introduce vue3 dependency, 
// ensure to build without vue runtime duplicates.
vue$: path.resolve(
process.cwd(), …
```
=> Fix and enhance the public build Webpack configuration merging

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/image-widget/index.js, modules/@apostrophecms/image-widget/views/widget.html, modules/@apostrophecms/module/index.js, modules/@apostrophecms/widget-type/index.js
See changelog.
* Note that preview images (in the expanded menu, which can be found *only* in the "widget previews" page type on testbed) work in the corresponding branch of testbed (which I'd like to merge), even if they are added at project level on behalf of a core module (image-widget)
* Note that the image widget placeholder image still works even though I changed the standard config to use the new `placeholderImage` option, which works like `previewImage` and shares an implementation
=> PRO-3284: fix bugs in widget preview image URL handling, introduce placeholderImage option, consolidate the implementations

CHANGELOG.md, modules/@apostrophecms/attachment/index.js
Emit event before inserting an attachment in order to be able to modify it.
Necessary for the enterprise [@apostrophe-pro/doc-global-sharding](https://github.com/apostrophecms/doc-global-sharding) module.
cf. https://github.com/apostrophecms/doc-global-sharding/pull/4
=> emit beforeInsert event in attachment module

CHANGELOG.md, modules/@apostrophecms/user/index.js
Emit event before inserting a safe user in order to be able to modify it.
Necessary for the enterprise [@apostrophe-pro/doc-global-sharding](https://github.com/apostrophecms/doc-global-sharding) module.
cf. https://github.com/apostrophecms/doc-global-sharding/pull/3
=> emit beforeSaveSafe event providing the safe user and the user

CHANGELOG.md, modules/@apostrophecms/page/index.js, test/modules/test-page/views/page.html, test/pages.js
Convert uppercase URLs automatically to their lowercase version - can be disabled through `forceLowerCaseUrls` option in `@apostrophecms/page/index.js`.
Run tests
=> Page: uppercase URL is redirected to lowercase URL if not found

CHANGELOG.md, modules/@apostrophecms/attachment/index.js, modules/@apostrophecms/attachment/lib/tasks/download-all.js
New command line task to download all attachments from any uploadfs backend.
```
mkdir /some/test/dir
node app @apostrophecms/attachment:download-all --to=/some/test/dir
```
If your existing site is using local uploadfs storage (the default) then it will finish really fast, but it's still a valid test because uploadfs abstracts away differences between storage backends.
Note that nonexistent files are skipped without a panic because it is super common for some expected files to be missing, inaccessible or of sizes the developer never bothered to rescale existing uploadfs to. We log the error code instead. We do try to throw an error and stop if we see `ENOSPC` (out of disk space).
You can use `--parallel=3` to download more than one attachment at a time, which makes sense only up to a …
=> PRO-3558 download all attachments from any uploadfs backend

CHANGELOG.md, lib/modules/apostrophe-pages/index.js, lib/modules/apostrophe-pages/lib/api.js, test/pages.js
[PRO-3534](https://linear.app/apostrophecms/issue/PRO-3534/[a2-version]-as-a-user-when-typing-%E2%80%8B%E2%80%8Ba%E2%80%8B%E2%80%8B-url-slug-with-uppercase)
Porting [this PR](https://github.com/apostrophecms/apostrophe/pull/3995) to A2.
I guess we should create an issue to update the documentation also.
> 1. Link to an A2 project
> 2. Try to access pages with uppercase letters in the slug, it should redirect to the lowercase version by default 
> 3. Verify that params are not touched (you can add random params to test).
> 4. Disable the option `redirectFailedUpperCaseUrls` by setting it to false in the options of the `apostrophe-pages` module.
=> Pro 3534 slugs lowercase

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/lib/addFieldTypes.js, modules/@apostrophecms/widget-type/index.js, test/pieces.js, test/schemas.js
Add support for `viewPermission`
1. `npm test`
2. Add `permission` or `viewPermission` to a widget schema and look for warnings in the server console
3. Add `permission` or `viewPermission` to a top level piece type schema field, you should see no warnings
4. Add `permission` or `viewPermission` to a sub level piece type schema field, you should see warnings in the server console
5. On the browser, open the `Network` panel and check the API response request when you open the manager modal for the piece having `permission` or `viewPermission` attributes. Try it with multiple credentials and verify that the fields is visible or not present for each case.
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait …
=> Pro 3517 view permission

CHANGELOG.md, package.json
Due to client need (and the client's contribution of the fix too!) I'm putting this out as a hotfix. Convenient today because nothing else has landed in main since yesterday's release, otherwise I'd make a fussier PR off the previous release.
=> release 3.39.1: just the rescale task fix for 1N

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/apos/webpack.config.js, modules/@apostrophecms/asset/lib/webpack/apos/webpack.js.js, modules/@apostrophecms/asset/lib/webpack/apos/webpack.mjs.js, package.json
Hotfix for webpack's decision not to accept "import foo from 'lodash/foo'" as an equivalent for "import foo from 'lodash/foo.js'" anymore, by opting into the old behavior. We should talk to tiptap about fixing their import syntax and consider reverting this workaround afterwards.
"npm run dev" succeeds when this branch is a git dependency. (The bug doesn't seem to occur with symlinks so we can't test that way.) I have already done this test.
=> Release 3.39.2

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js, modules/@apostrophecms/schema/ui/apos/components/AposInputRange.vue, test/schemas.js
Range field correctly handles the def attribute set to 0 now.
The default range field will be used when the field has no value provided; a value going over the max or below the min threshold still returns null.
- link apostrophe (on pro-3629-fix-def-range) to testbed
- edit `modules/topic/index.js` as follow:
```diff
rangeField: {
type: 'range',
label: 'Range',
-        help: 'From 18 to 32, with steps of 2',
-        min: 18,
+        help: 'From 18 to 32, with steps of 2, defaults to 0',
+        def: 0,
+        min: 0,
max: 32,
step: 2 // optional
```
- create a topic, leave its range field to 0
- create a topic page and visit it
- the topic should have its range showing 0:
- checkout `main` on apostrophe
- edit the topic again (leave it's range field to 0)
- the range field default …
=> fix range field def `0` value

modules/@apostrophecms/asset/lib/globalIcons.js, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue
As an admin I can easily understand what is needed when the user or group permission list is empty
The visualization of the initially empty selections (see first image above) will be handled by introducing a new feature of inline array fields, activated by a new whenEmpty option. whenEmpty can have label and icon subproperties. When this option is configured for an inline array field and the array is currently empty, the configured icon and label are displayed per the design above. Icons themselves should be added to the system the same way widget icons already are (see the documentation and the source code for examples).
When an inline array is empty, a hint appears as described above.
When an inline array is no longer empty, the hint disappears.
Configure these per the design for the …
=> Add "whenEmpty" prop to "array" field

CHANGELOG.md, index.js, test/attachments.js, test/base-url-env-var.js
* For devops purposes, add support for an `APOS_BASE_URL` environment variable.
* You can start up with `APOS_BASE_URL` set to `http://imadethisup` in your environment. Links to subpages or articles etc. on the front end (not in the admin UI) should be prefixed with that (and will fail of course unless you add that name to your /etc/hosts, which is not necessary to the test).
=> Support for APOS_BASE_URL

CHANGELOG.md, modules/@apostrophecms/area/index.js, package.json
Replace `deep-get-set` with lodash's get and set functions.
In testbed, create an article with nested areas in it (two-column for instance).
Then use the API to fetch one article or all of them, with the `?render-areas=true` query parameter:
`http://localhost:3000/api/v1/article/clee30s0h00177d1u6lne6gyf:en:draft?render-areas=true`
`http://localhost:3000/api/v1/article?render-areas=true`
The `_rendered` property should be set:
```js
{
"_id": "clee30s0h00177d1u6lne6gyf:en:draft",
"title": "test",
"blurb": {
"_id": "clee307jt000v3b68xq2c8wzw",
"metaType": "area",
"_edit": true,
"_docId": "clee30s0h00177d1u6lne6gyf:en:draft",
👉  "_rendered": "\n<div class=\"apos-area\">\n  \n\n<div data-rich-text class=\"demo-rte\" >\n  <p>qedfqwef</p>\n</div>\n</div>\n"
},
"slug": "test",
// ....
```
```js …
```
=> remove deep-get-set dependency to fix vulnerability scan report

CHANGELOG.md, package.json
[PRO-3654](https://linear.app/apostrophecms/issue/PRO-3654/[a2]-passport-package-vulnerability)
Upgrades passport to 0.6 due to security vulnerabilities.
I tested, the login system that uses passport methods, and checked signatures of internally used methods:
* initialize
* session
* use
* authenticate
* serializeUser
* deserializeUser
Is still working on version 0.6. The Local strategy and TOTP one have been successfully tested.
I noticed that `apostrophe-passport` also interacts with passport instance through `self.apos.login.passport`.
Since it uses the same methods than the core and nothing more (authenticate, use), it should work as well (and we can't test every possible passport module).
A warning has been added in the changelog since I didn't test every passport method. Some …
=> [A2] upgrades passport version

CHANGELOG.md, package.json
[PRO-3812](https://linear.app/apostrophecms/issue/PRO-3812/[a3]-passport-package-vulnerability)
Upgrades passport version to 0.6 due to security vulnerabilities.
A3 uses passport the exact same way as [A2 does](https://github.com/apostrophecms/apostrophe/pull/4059).
I tested, the login system that uses passport methods, and checked signatures of internally used methods:
* initialize
* session
* use
* authenticate
* serializeUser
* deserializeUser
Is still working on version 0.6. The Local strategy and the TOTP one have been successfully tested.
`passport-bridge` is the equivalent of `apostrophe-passport` and uses the same methods as the core like for A2.
A warning has been added in the changelog since I didn't test every passport method. Some projects may interact with the passport …
=> [A3] upgrades passport version

CHANGELOG.md, lib/modules/apostrophe-schemas/index.js, lib/modules/apostrophe-schemas/public/js/user.js, lib/modules/apostrophe-schemas/views/macros.html, lib/modules/apostrophe-ui/public/css/components/fields.less, lib/modules/apostrophe-ui/views/components/fields.html, test/schemas.js
Add `readOnlyFields` option, following the `showFields` logic.
Add `readOnlyFields` to a boolean field `choices` option such as:
```js
{
type: 'boolean',
name: 'boolean',
label: 'Boolean',
choices: [
{
value: true,
readOnlyFields: [ 'foo', 'bar' ]
},
{
value: false,
readOnlyFields: [ 'baz' ]
}
]
},
```
When saving the document with the boolean field set to `true`, the `foo` and `bar` field should now be read-only (setting it to `false` will set `baz` read-only and set `foo` and `bar` editable again.
Same logic for `select` and `checkboxes` fields:
```js
{
type: 'select', // or checkboxes
name: 'select',
label: 'Select',
choices: [
{
label: 'First choice'
value: 'one',
readOnlyFields: [ 'foo', 'bar' ]
},
{
label: 'Second choice'
value: 'two',
readOnlyFields: [ 'baz' ]
}
]
},
```
*(Check at …
=> add readOnlyFields option

modules/@apostrophecms/doc/index.js
There is a small typo in modules/@apostrophecms/doc/index.js.
Should read `identifier` rather than `idefntifier`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, idefntifier -> identifier

CHANGELOG.md, modules/@apostrophecms/doc/ui/apos/apps/AposDoc.js, modules/@apostrophecms/image/index.js, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposUtilityOperations.vue, modules/@apostrophecms/ui/ui/apos/lib/i18next.js
Improvements to the `utilityOperations` cascade and related features. Please see the changelog.
* When editing a relationship between piece types (example: in the testbed, edit an Article and click browse to select a Topic), the kebab menu at top right of the manager still appears and the "New Topic" choice within it still works.
* If you temporarily add `button: true` to the definition of that button in `piece-type/index.js`, it shows up as an independent button instead, which also supports `icon` and `iconOnly` properties (icons must be registered in the usual way in the icons property, and icons are not supported at all right now unless `button: true` is used).
* If you temporarily remove `relationship: true` from the definition of that button, a redundant "New" button appears in the …
=> enhancements to utility operations

modules/@apostrophecms/i18n/i18n/de.json, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/i18n/es.json, modules/@apostrophecms/i18n/i18n/fr.json, modules/@apostrophecms/i18n/i18n/pt-BR.json, modules/@apostrophecms/i18n/i18n/sk.json, modules/@apostrophecms/schema/ui/apos/components/AposInputCheckboxes.vue, modules/@apostrophecms/ui/ui/apos/components/AposCombo.vue
[PRO-3900](https://linear.app/apostrophecms/issue/PRO-3900/as-a-user-i-can-multiple-select-from-a-large-number-of-choices-without)
Adds a new style for the  `checkboxes` field called `combo`.
When this one is selected it renders a sort of multi select. It looks like this
By default, when the checkboxes are in style `combo`, a button `Select All` or `field.all.label` key that is added as first element of select options.
If the field has explicit `all: false` this button is not added. It is also not added if a max is set to the field and is below the amount of choices.
You can link it in any A3 project,
create a new field of type `checkboxes` with a style `combo`
Try with `all: false`, you should have no `Select All`
Try with `all: { label: 'my-locale-key' }`, you should see the right …
=> Pro 3800 checkboxes field combo

CHANGELOG.md, modules/@apostrophecms/schema/index.js, test/schemas.js
- adapt dynamic choices to accept a module name at the beginning and parenthesis at the end
- adapt and use method shared with external conditions
- adapt and add tests for `/choices` api
In the example below, we're defining methods to get choices dynamically, from the same module, from another module, with parenthesis.
Test that it still works without parenthesis,  and that an unknown module or method name will result in clean 400 errors (in backend, and clean message given to the frontend and displayed in the modal).
Defining a method with parenthesis with an argument should send a warning on server-side.
```js
// in "article" piece
fields: {
add: {
select: {
label: 'Dynamic select',
choices: 'getChoices()'
},
checkboxes: {
label: 'Dynamic checkboxes',
type: …
```
=> dynamic choices syntax accepts module and parenthesis

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/schema/index.js, test/schemas.js
- send result in an object otherwise result as a number is interpreted as empty
- change notification to error (in cypress tools, the `danger` type is not handled, it's easier and makes sense to change it to `error` here so that e2e tests pass)
Add an external condition that expects a number, such as:
```js
coupon: {
label: 'Coupon',
help: 'Enter a coupon. On the 10th order, write "ORDER10" to get a discount!',
required: true,
if: {
'coupon:getOrdersCount()': 10
}
},
```
see https://github.com/apostrophecms/testbed/pull/139
=> send external condition result in an object so that numbers work

modules/@apostrophecms/ui/ui/apos/components/AposCombo.vue
Fixes initial list position not being good when component is mounted but not visible.
Uses a resize observer to perform that.
Check that even in another tab the list appears at the right position.
=> fix uses observer for select resize

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/schema/index.js
"required" errors are not displayed anymore for fields that are hidden and for which the required rule does not apply.
This also fixes errors that are not correctly thrown back to the browser when a module or a method defined in an external condition key does not exist (a non-required field could have a badly formatted external condition -with an unknown module or method- and we could still save the doc).
Tests being covered in https://github.com/apostrophecms/testbed/pull/139
=> do not display errors for hidden fields

modules/@apostrophecms/ui/ui/apos/components/AposCombo.vue
[PRO-3987](https://linear.app/apostrophecms/issue/PRO-3987/combobox-ui-needs-basic-keyboard-accessibility)
Adds accessibility for the new combo checkboxes field:
* tab navigation
* space to open or close list
* arrow to navigate through select items
* auto scroll when item not visible
Changelog will be updated when the feature branch is merged.
* Use the new field
* navigate from other fields to this one with tab
* Once focus click space to open the list
* navigate the list with arrows and space to add an item
* backspace should close the list
* tab should work also when list open and close it
=> Pro 3987 combobox keyboard accessibility

modules/@apostrophecms/ui/ui/apos/components/AposCombo.vue
[PRO-4057](https://linear.app/apostrophecms/issue/PRO-4057/support-readonly-on-new-combobox-field)
Manages readonly display for AposCombo field.
* Check a readonly combo field, it should have a specific display
* List should never open
* selected items can't be removed
=> manages readOnly display for AposCombo field

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue
In the relationship input search suggestion list:
The suggestion help is now hidden when we start typing into the search bar, and is displayed again when the search bar is cleared.
|-------|-------|
|![image](https://user-images.githubusercontent.com/8301962/226943628-9b54c816-bbdf-4e94-b3ca-23cafd7f8a87.png)|![image](https://user-images.githubusercontent.com/8301962/226943868-d20b8746-1781-45fc-99f3-bc0f3fd53e95.png)|
=> hide suggestion help from the relationship input

CHANGELOG.md, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue
The default "Add Item" button label can now be overridden by setting the `itemLabel` option of an `array` field.
Run testbed (or any Apostrophe 3 project) with the `pro-4014-change-add-item-label` version of apostrophe.
Add `itemLabel` to an array field, as below:
```js
inlineArrayField: {
label: 'Favorite Flavors',
itemLabel: 'Favorite Flavor', // 👈
type: 'array',
inline: true,
help: 'Think Baskin Robbins',
fields: {
add: {
flavor: {
label: 'Flavor',
required: true
}
}
}
},
```
| without `itemLabel`  | with `itemLabel` |
|-|-|
| ![image](https://user-images.githubusercontent.com/8301962/227996953-194ee551-e4b6-4dc1-adad-dfdd0b6149b8.png) | ![image](https://user-images.githubusercontent.com/8301962/227996825-aef9b62d-4ca1-4626-acfb-e3be225391bb.png) |
*(Check at least …
=> add the possibility to override the array "add item" button label

CHANGELOG.md, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlatList.vue
Hide contextual menu on relationship entries when relationship field has no field.
=> hide relationship context menu when it has no field

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/modal/ui/apos/mixins/AposModalTabsMixin.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManagerDisplay.vue
* Hide document versions if the current user cannot edit
* Hide discard draft if the current user cannot edit
* Hide quick create if the current user cannot edit
* Hide localize if the current user cannot localize
N.A.
Fixes 
* https://linear.app/apostrophecms/issue/PRO-4081/menu-in-admin-bar-shows-up-for-types-you-only-have-per-doc-permissions
* https://linear.app/apostrophecms/issue/PRO-4042/document-versions-appears-for-documents-i-cant-edit-in-page-manager
* https://linear.app/apostrophecms/issue/PRO-4041/discard-draft-appears-for-documents-i-cant-edit-in-page-manager-maybe
* …
=> Pro 3901 localize

CHANGELOG.md, modules/@apostrophecms/piece-type/index.js
https://linear.app/apostrophecms/issue/PRO-4128/batch-operations-are-missing-permission
Batch operations are always present in the manager modal.
This is an issue when the current user does not have the required permissions to perform the action (e.g. publish).
Within apostrophe core, we can set a permission to tell the frontend what are the required operation for the item to be visible.
• I should see Publish batch operation only if I have the permission to publish the related content
=> Check user permission before displaying batch operations

CHANGELOG.md, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/widget-type/index.js
Fix for issue 1365.
Disallow "type" property name in _piece-type_ and _widget-type_ fields.adds.
Example:
```javascript
modules: {
foo: {
options: {
name: 'foo',
label: 'Foo'
},
fields: {
add: {
type: {
label: 'Bar',
type: 'string'
}
}
}
}
}
```
* Added a check inside `modules/piece-type.js` and `modules/widget-type.js`. If there is a field property name as "type" it will error and exit.
* Closes #1365 
*For example:*
> 3. Click the "Archive" button on the top left of the manager and confirm that it should …
=> Fix for issue 1365. Disallow "type" property name in fields

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputSelect.vue, modules/@apostrophecms/schema/ui/apos/lib/detectChange.js, modules/@apostrophecms/schema/ui/apos/lib/object.js, modules/@apostrophecms/schema/ui/apos/mixins/AposInputChoicesMixin.js, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
Closes https://github.com/apostrophecms/apostrophe/issues/4049
Fixes:
**Empty choice** (covered by e2e tests https://github.com/apostrophecms/testbed/pull/150)
- Add empty choice for dynamic optional select field type
- Add empty choice for required select fields, if they have no `def` option
**Falsy value selection** (covered by e2e tests https://github.com/apostrophecms/testbed/pull/151)
- Choosing a falsy value should triggers a change, and update conditional display
- when choosing `false` in a boolean field that had no preset value (ie. field not required)
- when choosing a falsy value in a select after an empty choice was selected (ie. a `null` choice)
**Default values** (covered by e2e tests https://github.com/apostrophecms/testbed/pull/151)
- Populate new widget instances and …
=> fix various issues on conditional fields

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue
Expand inline array display to fit content
1. With advanced-permission, check the per-document permissions inline array display. It should have a width flush with the center column as before.
=> auto expand inline arrays

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
Save rich text widgets on actual tiptap editor focus changes, not just blurs from widget to widget at the area level
=> fast rich text save

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/apps/AposModals.js, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/modal/ui/apos/components/TheAposModals.vue, modules/@apostrophecms/ui/ui/apos/lib/click-outside-element.js, modules/@apostrophecms/ui/ui/apos/lib/vue.js, package.json
Address the document click issues by replacing `v-click-outside-element` with a custom implementation that is aware of modal stack relationships.
=> Fix document click issues

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
Prevent error in browser console when `e.doc` is undefined when handling `content-changed` event.
1. Install `@apostrophecms-pro/data-set` and import a document
2. Check the browser console for error after the import
=> check e.doc during content-changed event handling

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/ui/apos/components/AposArrayEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputObject.vue, modules/@apostrophecms/schema/ui/apos/mixins/AposInputFollowingMixin.js, test/follow-ancestors.js
Allow nested fields (array and object schema fields) to follow field values from the parent schema.
In order to be done, the nested fields should use syntax `<fieldToFollow`, which will result following of values of a field named `fieldToFollow` from the parent schema. `<<fieldToFollow` would follow a field from the grand parent, and so on.
Here is an example, that involves an imaginary field type `stringWithSuggestions` following a parent field:
```js
options: {
name: 'household',
fields: {
add: {
petPreference: {
label: 'Pet Preference',
choices: [
{
value: 'cats',
label: 'Cats'
},
{
value: 'dogs',
label: 'Dogs'
}
],
required: true
},
pets: {
type: 'array',
label: 'Pets',
fields: {
add: {
name: {
// Custom schema …
```
=> Fields nested following

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, package.json
This is a hotfix for an issue discovered when working with the AI helper module, but it has other benefits.
Normally, if you go into the admin bar and edit and save or insert a piece, the main content area of the page should refresh in case that piece is displayed on the page.
However, if a widget editor dialog box is currently open on the page or lower in the modal stack, this is never a good thing because the editing experience is interrupted and the modified piece is generally one that saving the modal will display immediately. Without this fix it doesn't get displayed at all until the page is manually refreshed.
We didn't notice this because uploading images the normal way happens to not trigger this event mechanism, whereas the way AI inserts an image does. But inserting and editing …
=> Hotfix: do not refresh the main content area while a widget editor modal is open

CHANGELOG.md, package.json
To 1.0.0 so it is possible to specify an array of exceptions rather than just one character.
=> update sluggo dep

CHANGELOG.md, modules/@apostrophecms/oembed-field/ui/apos/components/AposInputOembed.vue
- clone `this.value.data` so that `this.next` does not keep a previously-discarred value
- use `readonly` rather than `disabled` in order to avoid losing focus when typing
Issue initially raised by iCiMS.
Add a video widget to an area (or add `oembed` field to any widget).
Enable Network Throttling to slow 3G
- when you type, the input should be readonly while the call is made to the server
- when the call is finished, the focus should still be on the input and **you should be able to continue typing**
- save the widget
- edit the widget
- edit the value and **cancel** the widget edition
- edit the widget
- the value **should not be the one that was set when canceled** (should be the one that was saved)
If adding a new feature without an already open issue, it's …
=> clone value data in oembed field to discard value when cancelling and improve ux

.github/workflows/main.yml, CHANGELOG.md, package.json
This eliminates a snyk vulnerability warning about word-wrap. I have tested that svg uploads, which depends on this for sanitization, still work.
=> Bump jsdom version

CHANGELOG.md, lib/modules/apostrophe-modal/public/js/modal.js
Avoid displaying "(undefined)" in the breadcrumb trail when an array item is nested in another array item, which is new and has never been saved (that is, the outer item has never been saved and its sub-array is being edited)
See also dcad-1209 branch of apostrophe-enterprise-testbed, in which this can be tested by creating a new "product", going to the "info" tab and hitting "edit" for address. I don't plan to land a PR for that branch
=> fix for dcad-1209

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue, modules/@apostrophecms/schema/lib/addFieldTypes.js, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue
Allow `@` when a document is a template (doc-template-library module).
https://linear.app/apostrophecms/issue/PRO-4125/create-the-template-library-module-with-template-query-builder
=> Allow `@` when a document is a template (doc-template-library module).

CHANGELOG.md, index.js, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/schema/lib/addFieldTypes.js, modules/@apostrophecms/util/index.js
See changelog
* Startup of existing, working projects should not print a warning
* Startup of a project that makes a query with relationships too early should print a warning (before potentially crashing)
Example: pro-4289-fail-demo branch of a3-boilerplate will print the warning and then crash (might not crash if there are no articles in the database yet at startup)
I will also submit a docs PR.
=> lint for premature use of database queries

modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
tiny follow up to the RT rodeo: we were using different classes for placeholders with and without insert menus, but the markup and style is the same, only the placeholder text changes.
This makes them use the same class and fixes the case where no placeholder would appear without an insert menu
=> RT Placeholder not appearing without insert menu

CHANGELOG.md, modules/@apostrophecms/page/index.js
Test procedure:
* Create a grandparent page in the page tree.
* Use `node app @apostrophecms/page:reattach slug-of-that-page --new-slug=/something-new` to move it up as the last child of the home page and give it a new slug as well.
* Note that this is what actually happens in the page tree manager.
The new-slug option is currently necessary because manual slug editing is rather busted at the moment (separate issue unrelated to this PR as such).
=> task to reattach a page to the tree if the path property becomes invalid somehow

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
Change the URL of the browser so that it reflects the slug of the document and its current mode (draft vs. published).
e2e test: https://github.com/apostrophecms/testbed/pull/178
https://linear.app/apostrophecms/issue/PRO-4327/change-the-browser-url-to-reflect-the-document-mode
=> change browser url according to the doc slug of the chosen mode

CHANGELOG.md, modules/@apostrophecms/page/index.js
Like said the the comment before the page post route. It should be possible the create a page without defining the target ID, it doesn't work currently, this PR fixes it.
It will now take the home page by default.
You should be able to create a page from the page post route without specifying the `_targetId` property.
=> Fix page creation without target

CHANGELOG.md, modules/@apostrophecms/schema/index.js
see changelog
* Check out the pro-4407 branch of a3-boilerplate and link this branch of apostrophe
* Create a Default page (the home page does not have that type)
* Go to the page of type Default that you created
* Edit its settings
* Set "Need Room" to "yes" and populate "Room Numbers" with a couple characters, so that "min" shows up
* Change "Need Room" to "no"
* Save. Should save successfully
* Reopen and switch "Need Room" to "yes." "Room Number" should now be blank, because it was (1) invalid and (2) locked out by a conditional at save time
=> PRO-4407 fix for invalid values blocking save operations

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/doc/index.js
[PRO-4026](https://linear.app/apostrophecms/issue/PRO-4026/as-an-admin-i-want-to-decide-who-has-permission-to-create-delete)
To finish the work of the ticket above we need to allow `permission` property to the method `addContextOperation`.
This method can be a string or an array.
The available values are the ones that have a can method associated in `AposDocContextMenu`.
A validate function has been added to the method `addContextOperation` to save precious time to the user in case of bad configuration.
What it does is that it checks the permission value, if I set it to `edit` it will run the method `canEdit` in the vue component and shows the operation button only if this one returns `true`. 
Since we supports arrays too, we can check multiple permissions here. eg. if I set permission …
=> Permission support context operations

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
Currently, typing a slash at the beginning of a line in the rich text editor results in the removal of the slash if the user then selects something from the insert menu. However, if the user first types some characters and then the slash, as would be potentially expected for an inline image, the slash is not removed following selection from the insert menu. This PR fixes this issue. Closes PRO-4400.
*For example:*
> 4. Check that all pieces have …
=> alter removeSlash for proper function

CHANGELOG.md, modules/@apostrophecms/login/index.js
Prior to this fix, an `afterSessionLogin` event handler, such as those found in certain client projects, could crash the process by throwing an error in Node 15 or newer. These errors are now properly caught and delivered to the callback of `req.login`.
=> Do not restart the process when an afterSessionLogin event throws an error

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/ui/ui/apos/lib/i18next.js, modules/@apostrophecms/user/index.js, test/i18n.js
Adds support for UI language (static i18n), introducing `adminLocales` and `defaultAdminLocale` options. Those are independent from the `locales` options (no interception required). Adds `adminLocale` user field, when `i18n.options.adminLocales` option is configured. Setting the user field shows the preferred interface language, not matter the current site locale.
**NOTE:** `defaultAdminLocale` will work independently of `adminLocales`. Even if no  `adminLocales` option is set, `defaultAdminLocale: 'fr'` will force the admin UI to be shown always in French, no matter of the current site `locale`. However, if `adminLocales` is configured, `defaultAdminLocale`, if set, should match an item from it. This is done to avoid user confusion. In this case, creating new User will auto select the …
=> PRO-4529: i18n admin locales and user adminLocale field

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
Remove focus parent event listeners for area widget when unmounted/destroyed. Currently the event listeners are not being garbage collected and if a page contains many area widgets then performance becomes 
*For example:*
> 2. Open a page that contains area widget
> 3. Use DevTools to observe heap
> 4. Select "preview" and "edit" repeatedly. 
In current version you will see linear growth. With this change you will see that after garbage collection you will see it return to initial size. There may still be other issues though as I've noticed very small growth still occurring but that may be due to code on my end. Will investigate more.
If adding a new feature without an already open issue, it's best to open a **feature …
=> fix: remove focus parent listener on destroy in area widget

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellLabels.vue, modules/@apostrophecms/ui/ui/apos/mixins/AposCellMixin.js
A way to indicate a doc should be treated as autopublished in the frontend UI
=> Fix save as template

defaults.js, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/settings/index.js, modules/@apostrophecms/settings/ui/apos/components/AposSettingsManager.vue, modules/@apostrophecms/settings/ui/apos/components/AposSubform.vue, modules/@apostrophecms/settings/ui/apos/logic/AposSettingsManager.js, modules/@apostrophecms/settings/ui/apos/logic/AposSubform.js, modules/@apostrophecms/settings/ui/apos/logic/TheAposSettings.js, test/settings.js
Add `@apostrophecms/settings` module. Implement settings configuration per logged in user (UI and backend). 
Although fully functional, the final UI will be done in a following ticket. 
Use Testbed branch `feature-user-settings`, link Apostrophe locally while in the current branch. Boot the app, force rebuild (`CI=1 APOS_DEV=1 npx nodemon`)
"Manage Settings" should be visible above the "Logout" menu item (top right user menu). Clicking it should open "Manage Settings" modal. "UI Language" schema should be visible. Changing it should change the current user "UI Language" field (can be checked in the users piece). Re-opening the settings manager should show the new "UI language" setting by default.
If adding a new feature without an already open issue, it's best to …
=> PRO-4543 settings module

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/scss/global/_widgets.scss
Blank lines respected in CMS rich text editor
https://linear.app/apostrophecms/issue/PRO-4526/blank-spacing-not-being-respected-in-cms-rich-text-editor
Edit mode:
Preview mode:
1. Run the website and log in
2. Edit a rich-text editor, add new lines by hitting the button "Enter". Publish changes.
3. Go in preview mode and check the new lines are respected out of the edit mode
4. Log out and check new lines are still present
=> Default height for empty paragraphs in rich-text editor

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
`AposDocEditor` `onSave` method is always called with an object
Check `onSave` usage in the file.
=> fix typo with onSave navigate

modules/@apostrophecms/modal/ui/apos/mixins/AposModalTabsMixin.js
`conditionFields` does not exist in the context of `AposRelationshipEditor`
1. Run cypress `fields.spec.js`
=> conditional fields are not available in AposRelationshipEditor

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalTabs.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposModalTabsMixin.js, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
Add support for tabs without `isVisible` property.
1. Open a piece or page `Document Versions`. The first tab must be selected and non-empty.
=> Pro 4542 support tab without is visible

CHANGELOG.md, lib/check-if-conditions.js
Adds `$and` operator on `addContextOperation` `if` property in order to check multiple fields before showing or hiding a context operation
Related to https://github.com/apostrophecms/import-export/pull/1/files
=> addContextOperation: Adds `$and` operator

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
Removing the rule to compute default values only when we can edit the document. 
N/A. I'm removing a feature I've added in my last PR for template llibrary
=> Pro 4542 compute diff

defaults.js, modules/@apostrophecms/log/index.js, modules/@apostrophecms/module/index.js, modules/@apostrophecms/module/lib/log.js, modules/@apostrophecms/util/index.js, modules/@apostrophecms/util/lib/logger.js, test/log.js
- Add structured logging API - `logDebug`, `logInfo`, logWarn` and `logError` (can be used in any module):
```js
self.logError('event-type');
self.logError('event-type', { some: 'data' });
self.logError('event-type', 'some message', { some: 'data' });
// prepend `req` to also log valuable request data, followed by any of the above arguments
self.logError(req, ...);
```
- Custom loggers can now be destroyed - provide `async destroy()` method.
- Default logger now stringifies objects.
- Production and non-production default policy is applied for structured logging.
- Filtering by severity and event type per module can be configured for structured logging.
- Format logs for readability in non-production environments.
Closes PRO-4479, PRO-4480, PRO-4481, PRO-4482, PRO-4483, PRO-4486, …
=> Core API, formatting by env, req support, tear down

CHANGELOG.md, modules/@apostrophecms/page/index.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue
https://github.com/apostrophecms/import-export/pull/3 depends on it.
Add the possibility to add utility operation in the page manager.
*For example:*
=> add utility operations in page manager

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js
Fix a downstream bug in the Holon appBuilder when trying to access a property that might not exist [PRO-4674](https://linear.app/apostrophecms/issue/PRO-4674/update-holon-to-latest-version-of-apostrophe)
1. link this pull in Holon
2. in holon `npm run dev`
3. Navigate to a site
4. Click appBuilder in nav bar > Add category
5. The modal loads with content and without errors in the console
=> Hot Fix Holon appBuilder bug

CHANGELOG.md, modules/@apostrophecms/page/index.js, test/pages.js
When invoking `self.apos.page.insert(req, parentId, position, page);` and `parentId` is a published page (ends with `:published`) and `req.mode === 'draft'` the operation results in `notfound` error. The reason is `apos.page.getTarget(req, parentId)` is not inferring the mode from the request. This PR fixes that.
Closes PRO-4696.
Tests should pass.
=> Infer parent ID mode from the request when creating a page

CHANGELOG.md, modules/@apostrophecms/module/index.js
Set the original error message when compiling the REST API error log and not the message meant for the browser `An error occurred`.
When there is an actual unhandled error, the original message should be logged in the CLI instead `An error occurred`. 
=> Send the original error message to the logger

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue
https://linear.app/apostrophecms/issue/PRO-4559/pages-in-autopublish-mode-still-have-the-draft-and-live-switch
Hide dash on autopublished pages title
=> Hide dash on autopublished pages title

CHANGELOG.md, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js
- Introduce `publicApiCheckAsync` wrapper for `publicApiCheck` and use it internally.
- Introduce `omitPermissionCheck` flag on `getRestQuery` for extending purposes. Add a fair warning comment. 
As a part of HOL-2124. 
- Projects can extend/override `async publicApiCheckAsync(req)` when custom async permission check is needed.
- No breaking changes related with the above - `publicApiCheck` still works as expected.
- Projects can extend `getRestQuery` and disable the internal permission check and `publicApiProjection` feature:
```js
extendMethods(self) {
return {
getRestQuery(_super, req) {
// The `true` flag will avoid permission checks starting from v3.55.0
const query = _super(req, true);
// ...extend the query
return query;
}
};
}
```
THE ABOVE SHOULD NOT be used without a good …
=> Async REST API permission check

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
This PR extends the rich-text-widget to allow for custom options to be passed through the per area configuration. This will allow for new Tiptap extensions to pass their own configuration options. A tutorial on this subject and three new improvements to the rich-text-widget will be released to take advantage of this. This change does not alter the existing configuration behavior.
*For example:*
> 4. Check that all pieces have been archived …
=> Add additional rtw area config

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/index.js
Fix inline figure in rich-text + Remove empty paragraph from rich text widget tasks
1. Run the task `node app.js @apostrophecms/rich-text-widget:fix-inline-figure` and confirm
2. Run the task `node app.js @apostrophecms/rich-text-widget:remove-empty-paragraph` and confirm
3. Integration tests must be green
=> Pro 4504 inline figure

CHANGELOG.md, modules/@apostrophecms/module/index.js
See changelog.
Sites render pages as normal.
=> PRO-4745: Make it possible to fetch data rather than a rendered page for any page URL in Apostrophe core

CHANGELOG.md, modules/@apostrophecms/module/index.js, package.json, test/weird-api-errors.js
Hotfix, see changelog
Tests pass
=> hotfix for logging non-Error exceptions from api routes

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js, modules/@apostrophecms/ui/ui/apos/components/AposCellDate.vue
Closes Issue number #4291. Empty dates for piece types are no longer filled with the current date after submitting nothing. 
1. create a default apos app. 
2. create a piece type: 
```module.exports = {
options: {
label: 'Testing Piece',
},
fields: {
add: {
date: {
label: 'Date?',
type: 'date'
},
},
group: {
basics: {
label: 'Basics',
fields: [ 'date']
}
}
},
columns: {
add: {
date: { label: 'Confirmed On', component: 'AposCellDate' }
}
}
};
```
3. create the new piece type and set date as empty
4. the date should remain as an empty string
If adding a new feature without an already …
=> added date verification for null date and no default value

.github/workflows/outdated-dependencies.yml
=> Pro 4734 check outdated deps

.github/workflows/main.yml
* Node versions 18 and 20 are current.
* We don't need to force an npm upgrade for node 14 anymore because it is no longer in the matrix.
=> update permissions matrix, remove unnecessary step

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputArea.vue, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue, modules/@apostrophecms/widget-type/ui/apos/mixins/AposWidgetMixin.js
Given the following setup:
```js
// modules/some-page/index.js
extend: '@apostrophecms/page-type',
fields: {
contentCard: {
type: 'area',
following: [ 'title' ],
options: {
widgets: {
'app-content-card': {}
}
}
},
// ....
}
```
```js
// modules/app-content-card-widget/index.js
extend: '@apostrophecms/widget-type',
options: {
label: 'Content Card',
icon: 'category',
components: {
widget: 'AppCardWidgetPreview'
}
},
fields: {
add: {
templateTitle: {
type: 'text',
label: 'Card Title',
following: [ '<title' ]
},
// ...
}
}
}
```
The following happens:
- `templateTitle` from the widgets schema can follow the page value of `title`
- `AppCardWidgetPreview.vue` will receive now `followingValues`, that will also include root schema values prefixed with `<`. 
- …
=> Allow widgets and custom widget previews to follow parent schema

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/permission/index.js, modules/@apostrophecms/util/index.js, test/pieces.js
Improve the `can` method of the permission module in order to hide warnings by always providing to it the `type` property of a doc or widget and getting the appropriate manager.
Log in as an editor.
Create a new page with a slug `/a`.
Create another page and type `/a` in the slug field
There should be no `type has no manager` error in the server console
=> add "type" property in projections by default to hide permission warnings

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js
Tiny fix see changelog
In the pro-4972 branch of `a3-demo`, linked to this branch of apostrophe, you can try editing an article to include an image in both the main content area and the `featuredImage` content area (it's in the misc tab at the end), and then visiting:
http://localhost:3000/api/v1/article/fetch
Prettyprint the JSON and you'll find that the actual image piece is only fetched for the `featuredImage` content area (you can see why in `article/index.js`, I'm passing `areas: [ 'featuredImage' ]`. You'll see other properties of other areas, that's normal, the difference is that loaders aren't called so their image relationships are not populated fully.
I've done this test myself, of course.
If adding a new feature without an already open issue, it's best to …
=> fix the areas query builder

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, test/pieces.js
Only add `type` to projection if there are no exclusions in the projection
1. `npm test` are green
2. Update `const values = Object.values(projection);` with `const values = [];` in `modules/@apostrophecms/doc-type/index.js`
3. Re-run `'can GET a single product using projections with fields omission'` in `test/pieces.js`, it should fail with `Cannot do exclusion on field in inclusion projection` 
=> only include type to projection if there are no exclusions

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/modal/ui/apos/mixins/AposModalTabsMixin.js, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue, modules/@apostrophecms/schema/ui/apos/lib/conditionalFields.js, modules/@apostrophecms/schema/ui/apos/logic/AposSchema.js, modules/@apostrophecms/schema/ui/apos/mixins/AposInputConditionalFieldsMixin.js
[PRO-4963](https://linear.app/apostrophecms/issue/PRO-4963/frontend-support-for-conditionally-required-fields)
* Refacto `conditionalFields.js` file to support multiple condition types.
* Updates frontend code using `condidionalFields` to use `conditionalFields.if` instead.
Run the `conditional Fields` cypress tests to be sure everything still works as expected.
=> Pro 4963 frontend support for conditionally required fields

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/apos/webpack.config.js, modules/@apostrophecms/asset/lib/webpack/src/webpack.config.js
This PR alters the webpack configuration to turn off warnings about package size limits during the build process. Closes PRO-4955.
*For example:*
1) Run `APOS_RELEASE_ID=1 npm run build.
2) Check output for a lack of size warnings.
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before …
=> Turn off webpack size warnings during build

modules/@apostrophecms/schema/index.js, test/schemas.js
https://linear.app/apostrophecms/issue/PRO-4962/as-a-developer-i-want-to-be-able-to-make-a-required-field-optional
- exact match on a value (boolean, string, number)
- logical AND by default
- logical OR
- not equal with exact match
- all the above with nested properties
```js
requiredIf: {
fieldA: true,
fieldB: 'active',
$or: [
{ fieldC: 10 },
{ fieldD: 20 }
],
fieldF: { $ne: 'default' },
'fieldE.subFieldA': 'AAA'
}
```
- we have conditionally required fields on the backend
- it accepts the same syntax as if
- integration test
=> Pro 4962 required if field

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/express/index.js, modules/@apostrophecms/module/index.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/lib/addFieldTypes.js, modules/@apostrophecms/template/index.js
Initial support for external front end rendering, e.g. adapters for Astro etc.
* Use this branch of apostrophe with the `astro-demo-core` branch of `a3-boilerplate` as the Apostrophe side, and the `apostrophecms/astro-demo` project as the astro side
* Be sure to do a fresh `npm install` on the astro side
* Everything still works
* Re PRO-4773, I tested that object fields do get populated by newInstance and wind up in the database with valid area objects for any area fields, even if just a part of a parked page and not mentioned in the parked properties
=> PRO-4773 PRO-4997

CHANGELOG.md, modules/@apostrophecms/schema/index.js, test/schemas.js
https://linear.app/apostrophecms/issue/PRO-5117/[regression]-a-required-field-is-still-enforced-when-the-field-is-not
Fix `if` and `requiredIf` fields inside array.
=> Fix conditional fields

CHANGELOG.md, modules/@apostrophecms/area/index.js
Clément at Michelin pointed out he didn't have access to schema level options when rendering widgets. For full page renders the issue was in the astro-integration module, however for the render-widget route used when re-rendering a single widget during contextual editing, there was a missing property on our side.
See the PR on astro-integration for details on testing.
=> pass on widget options in render-widget route

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js
Hotfix to correct an issue where template docs were not found during localization to a new locale, resulting in crashes.
I tested it using mongodumps provided by a client.
Adding a new locale to a site with template pages should not crash on startup.
=> PRO-5234: use findForEditing consistently so that doc-template-library does not cause crashes during the addition of new locales

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputPassword.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputSelect.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputString.vue, modules/@apostrophecms/ui/ui/apos/components/AposSelect.vue
Add `autocomplete` attribute to schema fields that implement it (cf. [HTML attribute: autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)).
```js
slug: {
type: 'slug',
autocomplete: 'off'
},
string: {
autocomplete: 'off'
},
password: {
type: 'password',
autocomplete: 'new-password'
},
url: {
type: 'url',
autocomplete: 'off'
},
textarea: {
textarea: true,
autocomplete: 'off'
},
select: {
choices: [
{
label: 'Foo',
value: 'foo'
},
{
label: 'Bar',
value: 'bar'
}
],
autocomplete: 'off'
}
```
☝️ these fields should be empty when creating a page/piece/widget etc.
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for …
=> add autocomplete field attribute

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js
This PR adds the `validate` method from the `string` schema field to the `url` field definition. This allows for the safe use of the `pattern` property in a `url` schema field type. Closes PRO-5252.
*For example:*
1. Add a `url` schema field with a disallowed `pattern` property, such as `pattern: 123`
2. Try to bring the site up and you should have an error appear in the console
*(Check at …
=> Pro 5252 add url validation

CHANGELOG.md, modules/@apostrophecms/module/index.js, modules/@apostrophecms/template/index.js
…
See above.
Without this information, piece-pages cannot be handled by Astro because it cannot distinguish the "index page" from the "show page."
Also this allows a more idiomatic pattern for "page not found" templates and others with no `data.page`. They have their standard full names from Apostrophe (module-name:templateName) and these can be mapped in Astro (see corresponding PR in astro-integration).
See the `pro-5272` branches of `starter-kit-essentials` and `astro-demo`.
Adding a blog page works.
Populating a blog post works and then you can see it on the index page and click through to the show page.
Simple pagination works (I did not go full crazy mode here or build in the other blog filters, but I did provide a simple way to manipulate query parameters so developers can …
=> PRO-5272: Astro needs to know the full template name, which also includes the module name, and for convenience the module name alone

CHANGELOG.md, index.js
See:
https://github.com/apostrophecms/apostrophe/commit/19115b62fecc67f7494889cd31e61cee7073d155#commitcomment-135083415
That's 2.x, but the issue also exists in 3.x.
`@apostrophecms/advanced-permission` module tests still pass while this branch of apostrophe is npm linked in. e.g. I didn't make anything worse!
Here's the minimal version (one test is sufficient):
```
npx mocha test/group.js
```
I did this and it passed.
=> Safe test check

CHANGELOG.md, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/schema/ui/apos/components/AposArrayEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputPassword.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue, modules/@apostrophecms/schema/ui/apos/logic/AposArrayEditor.js, modules/@apostrophecms/schema/ui/apos/logic/AposInputPassword.js, modules/@apostrophecms/schema/ui/apos/logic/AposInputSlug.js, modules/@apostrophecms/ui/ui/apos/components/AposCheckbox.vue, modules/@apostrophecms/ui/ui/apos/components/AposLabel.vue, modules/@apostrophecms/ui/ui/apos/mixins/AposAdvisoryLockMixin.js, modules/@apostrophecms/ui/ui/apos/scss/global/_theme.scss
[PRO-4788](https://linear.app/apostrophecms/issue/PRO-4788/[frontendui]-implement-the-new-ui-that-allows-admins-to-enable-many)
* Improves `AposCheckBox` component to be used out of `AposSchema`, and to take a single model value instead of an array.
* Adds tag feature for fields
* Few tiny fixes
* Verify that checkboxes still behave the same in core.
* You can now add a tag to a field with:
```javascript
tag: {
value: 'apostropheAdvancedPermission:sensitive',
type: 'sensitive'
}
```
* Adds new label color for sensitive
=> Fix checkbox component

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js
In writing the documentation for query builders added to schema fields, I found that when I queried on the date field, a single date would work, but an array containing two dates wouldn't return any documents. While looking at the array handling in the custom query builder I realized that the query was not updated with the calculated criteria. This PR fixes this. Closes PRO-5299.
*For example:*
> 4. Check that all pieces have been archived …
=> Refactor `date` query builder

CHANGELOG.md, package.json
Just pin it
To reproduce the bug:
```
cd a3-demo
git pull
export APOS_DEV=1
rm -rf node_modules && rm package-lock.json && npm install
npm run dev
```
Try to open the rich text toolbar. You can't.
To reproduce the fix:
* Change your apostrophe dependency in a3-demo's `package.json` to this branch, `hotfix-3.61.1`
* `export APOS_DEV=1`
* `rm package-lock.json && rm -rf node_modules/ && npm install && npm run dev`
I will PR the basis branch back to main after release of the hotfix.
=> PRO-5362 fix the toolbar bug

CHANGELOG.md, modules/@apostrophecms/page/index.js, modules/@apostrophecms/schema/ui/apos/logic/AposInputRelationship.js, test/pages-autocomplete.js
Add support for `type` query parameter in page `autocomplete` mode.
Pages will be suggested based on the type provided and if provided. 
=> PRO-5330: Add type support for page autocomplete

.gitignore, CHANGELOG.md, modules/@apostrophecms/permission/index.js, test/permissions.js
[PRO-4792](https://linear.app/apostrophecms/issue/PRO-4792/in-core-queries-for-create-and-delete-permission-must-be-handled)
See ticket.
Tests added must cover new actions added:
In can method:
* `create` action should be treated like `edit`
* `delete` should be handled appropriately following ticket instructions.
In criteria method:
* `create` and `delete` actions return the same criterias than `edit`.
=> Supports create and delete permissions

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/doc-type/ui/apos/logic/AposDocContextMenu.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue, modules/@apostrophecms/permission/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/ui/ui/apos/components/AposTree.vue, modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue
[PRO-5388](https://linear.app/apostrophecms/issue/PRO-5388/were-using-archive-and-delete-interchangeably-in-advanced-permissions)
See ticket
Also handle `discard draft` for pieces and pages:
* If user can archive but not publish, he can delete draft.
* If user cannot archive he cannot delete draft.
* If user can archive and publish he can delete draft and archive
* If user cannot edit but can archive he can delete draft (doesn't work rn because `findForEditing` checks for `edit` permission).
I also updated the frontend for the pages because we never passed the moduleOptions to the page item context menus where we need to check if we show discard draft etc..
=> renames archive in delete

modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/page/ui/apos/logic/AposPagesManager.js, modules/@apostrophecms/ui/ui/apos/components/AposCheckbox.vue
Remove annotate permission with `create`. If it's a new document, it will not be present in the DB and the annotate `create` won't be available.
Is indeterminate on checkboxes is needed to be able to tell is all checkboxes on the row are checked.
*For example:*
=> Pro 4801 is indeterminate

.gitignore, CHANGELOG.md, modules/@apostrophecms/rich-text-widget/index.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapLink.vue, modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/Link.js, test/rich-text-widget.js
- `linkFields` top configuration property (cascade) can be configured on a project level to add additional schema for rich text Link extension.
- `htmlAttribute: 'attribute-name'` should be set on every link attribute field in order to be functional
- There are no constraints on the types, but some types won't make sense (object, array, etc). The functionality is tested against `string`, `select`, `choices` (with one only option), `boolean`. 
- ~~Schema order and overall all standard schema features are supported, including remote choices.~~ Schema order and dynamic choices are not supported.
Extend `@apostrophecms/rich-text-widget`:
```js
linkFields: {
add: {
ariaLabel: {
label: 'Aria Label',
htmlAttribute: 'aria-label'
}
}
}
};
```
~~The field order …
=> PRO-5341: Link HTML attributes for rich text widget 

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaUploader.vue
https://linear.app/apostrophecms/issue/PRO-5419/upload-input-still-displayed-when-you-cant-create
This is in the Manage view of images -- only in the manage view, because when you edit an image you can also upload an image to change it and this one is not part of the issue.
=> Changes support for image upload from `canEdit` to `canCreate`.

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerSelections.vue
See title
* Give a group "create" permission for images
* Create a user and put them in that group
* Experiment with uploading images and then editing their metadata
* You can do so
* But you don't see anyone else's media in the media library, unless you are using it as a chooser for a relationship
=> PRO-5473: media manager compatible with per doc edit permissions

modules/@apostrophecms/ui/ui/apos/scss/global/_inputs.scss, modules/@apostrophecms/ui/ui/apos/scss/mixins/_theme_mixins.scss
[PRO-5439](https://linear.app/apostrophecms/issue/PRO-5439/updates-to-the-disabled-checkbox-state-styles)
Instead of updating the disabled variable value, only apply changes to checkboxes (no changes for normal inputs).
read only fields text became invisible, it's back to its initial state:
Checkboxes disabled  state use the right color:
Check that document versions read only fields are visible.
Checkboxes in disabled state must use the `--a-base-7` variable for background and border.
=> fixes broken disabled style

modules/@apostrophecms/piece-type/index.js
`insertPublishedOf` now does the same permissions bypass for pieces that I already added for pages, after first confirming publish permission.
=> PRO-5529: same fix as for pages

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue
https://linear.app/apostrophecms/issue/PRO-5511/investigate-1nces-reported-piece-editor-interface-bug
Display the "Browse" button in a relationship inside an inline array
Get this
instead of this
=> Display the "Browse" button in a relationship inside an inline array

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue
https://linear.app/apostrophecms/issue/PRO-5444/the-remove-userorgroup-ui-should-be-an-x-situated-in-the-first-column
Clicking on it still works as expected. Also tested drag-n-drop as Val requested.
Old icon:
New icon:
=> Inline array: change trash icon

modules/@apostrophecms/area/ui/apos/components/AposWidgetControls.vue
- Restores the 'copy' button on in-context widget controls
- update the tooltip object
1. link a demo and run
2. get to an area
3. use the 'copy' button (pictured below)
4. be able to paste the widget in an area
5. clipboard is cleared
6. saving works, etc
=> Restore widget copy button

CHANGELOG.md, modules/@apostrophecms/page-type/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapImage.vue, test/pages.js
Also closes PRO-5151
Publish and move published page just after a (same level, sibling) draft page works as expected. 
> It also fixes eslint warning that annoys me from some time!
Create 3 draft pages on a same tree level. Publish the last one (no errors). Moved it after the 1st one (no errors). Should work for any tree level (all pages above should be the same level).
=> PRO-5513: Fix publish after draft

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc/index.js, test/docs.js
[PRO-5489](https://linear.app/apostrophecms/issue/PRO-5489/[advanced-permission-3]-deleting-draft-does-not-remove-per-doc)
* When deleting a draft document, we remove related reverse IDs of documents having a relation to the deleted one.
* Updates docs.js tests to make them independants.
* Adding two test for the fix (one for delete draft, one for delete unlocalized docs).
Deleting a draft document should delete the related reverse IDs of all document having a relation to the deleted document.
=> removes related reverse IDs when deleting a draft document

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/components/AposModalShareDraft.vue
* Share Drafts modal styles made larger and it's toggle input has a larger hitbox.
*For example:*
1. npm run dev
2. Share Draft
3. see a larger description text
4. see a larger input label
5. click a large toggle hitbox
=> make type larger, make toggle input hitbox larger

CHANGELOG.md, modules/@apostrophecms/login/index.js, modules/@apostrophecms/login/ui/apos/components/AposLoginForm.vue, modules/@apostrophecms/login/ui/apos/logic/AposLoginForm.js
Add support for `uponSubmit` requirements in login phases
Each steps below requires on valid login attempt upon page load and one invalid then valid login attempt to validate that we can recover the login process after a failed attempt.
1. Try to login without any login requirements
2. Try to login with login-recaptcha enabled (you will need https://github.com/apostrophecms/login-recaptcha/pull/10)
3. Try to login with login-totp enabled
4. Try to login with login-hcaptcha enabled
5. Try to login with both login-recaptcha and login-totp enabled (you will need https://github.com/apostrophecms/login-recaptcha/pull/10) …
=> Pro 4998 recaptcha token on submit

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue, modules/@apostrophecms/schema/ui/apos/logic/AposInputSlug.js
https://linear.app/apostrophecms/issue/PRO-5490/crash-due-to-adding-a-slash-in-a-page-slug-field
Prevent infinite loop in pages if typing a slash in slug.
Standard slugs for pieces work correctly.
=> Block typing slash key in slugs

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposInputSlug.vue, modules/@apostrophecms/schema/ui/apos/logic/AposInputSlug.js
https://linear.app/apostrophecms/issue/PRO-5490/crash-due-to-adding-a-slash-in-a-page-slug-field
Tested in dev and prod modes, works correctly: slashes can be added in a slug without problem.
=> Remove blocking page slug

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc-type/ui/apos/logic/AposDocContextMenu.js, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/page/index.js
* Allow to restore pages with `create` permission
* Hide `Preview` and `Share Draft` on archived pieces and pages
1. Archive a page and try to restore it without errors
2. Archived pages and pieces don't have the `Preview` nor `Share Draft` context operation
=> Pro 4801 context operation

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
The height of the admin bar spacer was not updated when the context was conditionnally displayed, when opening palette for instance.
In `TheAposContextBar.vue`, an event was emitted to update the height of the spacer, but only from the `mounted()` method.
To fix that, the event is now emitted when the `contextBarActive` computed changes in order to update the spacer height every time the context bar is displayed or hidden.
1. Run a project with advanced permission 2:
`APOS_ADVANCED_PERMISSION=2 npm run dev` for instance.
2. Create a user that has at least the `Modify` right on palette:
3. Log-in with that user
4. Open palette
5. The context bar should not overlap the top palette drop-down
|--------|--------|
| ![image](https://github.com/apostrophecms/apostrophe/assets/8 …
=> fix admin bar spacer height when context bar is conditionally displayed

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/translation/index.js, modules/@apostrophecms/translation/ui/apos/components/AposTranslationIndicator.vue, modules/@apostrophecms/ui/ui/apos/components/AposCellLabels.vue
[PRO-5643](https://linear.app/apostrophecms/issue/PRO-5643/ui-manager-indicators)
Handles the new  `Pending Translations` on pieces and pages managers.
⚠️ Must be tested with [this PR](https://github.com/apostrophecms/automatic-translation/pull/1) in `automatic-translation`.
Since the conditions about the meta isn't existing for now you won't see the new indicator.
You can change the condition in `automatic-translation` to see the indicator being showed or you can create a new one.
=> Pro 5643 manager indicator

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/index.js
- Register spans as a `textStyle` and pass them into the RT configuration so they can be rendered
1. link to a demo, like a3-demo
2. make a RT widg, set some text to a span with a class
3. refresh the page, see that the RT editor renders the span + class
=> Rt render span classes

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/widget-type/index.js, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
Add the possibility to make widget modals wider, which can be useful for widgets that contain areas taking significant space.
Default width is now `540px`.
Add new `origin` and `width` options in order to configure widget modals at module level.
Setting the width to `half`, the widget modal will take 50% of the screen.
Setting the width to `two-thirds`, the widget modal will take 66% of the screen.
Setting the width to `full`, the widget modal will take 100% of the screen.
Setting the origin to `left`, the widget modal will be displayed on the left hand side of the screen. 
=> make widget modal width and origin configurable

modules/@apostrophecms/ui/ui/apos/components/AposTree.vue, modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue
[PRO-5744](https://linear.app/apostrophecms/issue/PRO-5744/redirect-module-vue3-adding-a-new-redirect-with-an-internal-page-link)
Fix the checkboxes in the apos pages tree.
You should be able to select pages properly in pages relationships, like in redirects.
=> fix apos tree checkboxes

modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue
[PRO-5699](https://linear.app/apostrophecms/issue/PRO-5699/localization-wizard-should-not-ask-to-localize-non-localized-content)
Ignores non localized related docs when localizind, like users.
You should never see this:
Check that documents from module having `localized: false` never appears in the related docs list.
=> ignores non localized related docs

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, package.json
TL;DR: mutating things, even subproperties of things, causes Vue 3 to consider them to have changed and can lead to unexpected behavior. Methods that return a result usually don't alter their arguments. This is a safe workaround for now
=> PRO-5793 hotfix for rich text styles option bug

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarMenu.vue
needed for https://github.com/apostrophecms/testbed/pull/236
passes `item.action` in order to fill the Button data-test attribute.
=> fix button data-test attribute

modules/@apostrophecms/modal/ui/apos/apps/AposModals.js
Fixes a bug introduced in https://github.com/apostrophecms/apostrophe/pull/4482.
Before, components were entirely stored in the modal stack.
In https://github.com/apostrophecms/apostrophe/pull/4482, the logic has been changed to store the modal element inside a reactive object, under `modalEl`.
So now, we need to use `modalEl` and not `$el` anymore.
=> fix modal ref in onTopOf

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
This PR modifies the logic in the `TheAposContextBar.vue` component to not strip query parameters when in edit mode. This prevents developers from testing page additions that depend on these parameters.
*For example:*
1. Create a new page
2. While editing in context, add query parameters to the URL and hit return.
3. The page should reload and maintain the same query parameters in the URL. …
=> Modifies conditional return to maintain query parameters

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/logic/AposInputSlug.js
*The page editor stops generating slug if a '/' appears in the page title. "Closes #4086"*
*For example:*
> 2. Click on pages button placed on top left.
> 3. click on new page button top right.
> 4. Add string like "new pages / new page" in title field.
> 5. You will observe slug field include value like "/new pages / new page".
=> fixed slug creation issue for '/'

CHANGELOG.md, lib/modules/apostrophe-schemas/views/macros.html, package.json
Simple change, tested in kimpton dashboard. Chrome still tries to helpfully suggest you might want to autofill your password, but it doesn't silently auto-stuff it anymore!
I also verified that the actual login page has its own custom, non-schema driven markup so this won't disable autocomplete there.
=> use autocomplete="new-password" to get the right effect in modern browsers

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue
Fixes a bug where pages were not able to be dragged between different levels of hierarchy.
1. `npm run dev`
1. Use the Page manager to create Pages, navigate to a Page and create a Child Page.
1. Edit the Page Tree by dragging Pages. You should be able to move Pages between different levels of heirarchy.
=> update options to allow drag/drop betweeen parents and children

CHANGELOG.md, modules/@apostrophecms/asset/index.js
Adds a publicBundle option to `@apostrophecms/asset` - when set to `false`, it will prevent from rebuilding asset bundles unless `APOS_DEV` env variable is set or when there is no bundle already built - to be used when using Apostrophe with an External Front End
*For example:*
=> Implement publicBundle option for assets builds (A3 backport)

CHANGELOG.md, modules/@apostrophecms/asset/index.js
Adds a `publicBundle` option to `@apostrophecms/asset` - when set to `false`, it will prevent from rebuilding asset bundles unless `APOS_DEV` env variable is set or when there is no bundle already built - to be used when using Apostrophe with an External Front End
*For example:*
=> Implement publicBundle option for assets builds

CHANGELOG.md, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
This PR alters the widget modal tab component to list any groups that a dev has created, even if it is a single group. It will skip tab display if there is no group(s) set. Closes PRO-6051
*For example:*
**Other …
=> Add alternative fix for "ungrouped" tab

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/tiptap-extensions/Heading.js
- Unsets marks on heading close, as reported in #4538
- Soft returns remain in tact
1. Configure a RT widget with inline styles and headings
2. Add a heading, style it with a mark
3. Smash return, the next line should return to the default style.
=> unset marks on heading return

modules/@apostrophecms/modal/ui/apos/components/AposModalTabs.vue
According to the design (and Stu), text should be centered in the tabs. Currently, text was left-justified and this is most noticeable when a label is displayed on two lines. This PR changes the CSS to center align the text. Closes PRO-6048
*For example:*
1. Add a widget group with a long label.
2. Check that the text is centered for both lines.
If adding a new feature …
=> Center widget tab text

CHANGELOG.md, modules/@apostrophecms/doc/lib/migrations.js, package.json
Simple hotfix for missing manager scenario. Unfortunately migrations have to be just as smart about these as the rest of Apostrophe.
=> Hotfix 4.3.1: fix migration bug that impacted our client demo, could impact other projects with stray documents corresponding to no module

CHANGELOG.md, modules/@apostrophecms/modal/ui/apos/components/AposWidgetModalTabs.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuItem.vue, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
Hopefully this time github will be kind enough to show that most of this code is already merged! I didn't change anything, just fighting with github.
=> Pro 6049 tab indicator

CHANGELOG.md, modules/@apostrophecms/page/index.js, test/pages.js
Recognize when the slug of a new child already contains the new parent's slug and not double it
1. `npx mocha test/pages.js` must be green.
2. the [Checks](https://github.com/apostrophecms/apostrophe/pull/4530/checks) tab is green
=> Pro 5937 move peer page

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue
Field components can access the "live" document value now. 
A field component (or any other component below the `AposDocEditor`) can now do `inject: [ 'liveOriginalDoc' ]` in order to get access to the reactive document value.  
=> PRO-6127: Add field access to the reactive document value

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue, modules/@apostrophecms/command-menu/ui/apos/components/AposCommandMenuShortcut.vue, modules/@apostrophecms/command-menu/ui/apos/components/TheAposCommandMenu.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/i18n/ui/apos/components/AposI18nLocalize.vue, modules/@apostrophecms/image/ui/apos/components/AposImageRelationshipEditor.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/modal/ui/apos/apps/AposModals.js, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalConfirm.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalShareDraft.vue, modules/@apostrophecms/modal/ui/apos/components/TheAposModals.vue, modules/@apostrophecms/modal/ui/apos/composables/AposFocus.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue, modules/@apostrophecms/page/ui/apos/logic/AposPagesManager.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposRelationshipEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposArrayEditor.vue, modules/@apostrophecms/schema/ui/apos/logic/AposArrayEditor.js, modules/@apostrophecms/settings/ui/apos/components/AposSettingsManager.vue, modules/@apostrophecms/settings/ui/apos/logic/AposSettingsManager.js, modules/@apostrophecms/ui/ui/apos/lib/vue.js, modules/@apostrophecms/ui/ui/apos/stores/modal.js, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue, package.json
[PRO-5818](https://linear.app/apostrophecms/issue/PRO-5818/get-rid-of-double-modals-stack-array)
* Adds pinia
* Stores modals and modals logic in a pinia store. Methods are attached to `apos.modal` accessible in and out of vue components.
* Only BC is that `apos.modal.stack` isn't existing anymore, a method called `apos.modal.get()` allows to get all modals or one by ID. Not sure users needed to call this `apos.modal.stack` before.
* Fixes the `esc` that close modals that wasn't working like before.
[PR in Cypress-tools](https://github.com/apostrophecms/cypress-tools/pull/43):
* `hasModalCount` method has been updated to use `apos.modal.get()` instead of `apos.modal.stack`.
[PR in document-versions](https://github.com/apostrophecms/document-versions/pull/58):
* Use the store to get the …
=> Get rid of the double modals stack

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue, modules/@apostrophecms/schema/ui/apos/logic/AposArrayEditor.js, modules/@apostrophecms/schema/ui/apos/logic/AposSchema.js
[PRO-6200](https://linear.app/apostrophecms/issue/PRO-6200/issues-adding-to-array-field-on-staging-site)
Fixes bug by removing the excess of `nextTick` use and making the `AposSchema` reload fields when they are from another document (by using `v-for` keys), which is a more idiomatic way to.
See ticket, you can create a random array field, with some required fields, when you add an item and make it show the required field message, fix it and try to create another item, it breaks.
In prod, when having an array field, 
Cypress tests running [here](https://github.com/apostrophecms/testbed/actions/runs/9350527931). 🟢
=> Pro 6200 broken array modal

CHANGELOG.md, modules/@apostrophecms/command-menu/index.js, modules/@apostrophecms/command-menu/ui/apos/components/TheAposCommandMenu.vue, modules/@apostrophecms/settings/index.js, modules/@apostrophecms/ui/ui/apos/stores/modal.js
[PRO-6137](https://linear.app/apostrophecms/issue/PRO-6137/fix-commands-shortcuts-openingclosing)
* Fixes `TheAposCommandMenu` modals not computing shortcuts from the current opened modal.
You can open modals then the apos command menu that matches the right modal.
When leaving a modal it computes the new context.
Cypress tests running [here](https://github.com/apostrophecms/testbed/actions/runs/9362961049) 🟠
=> Pro 6137 shortcuts modals bugs

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/page/ui/apos/components/AposPagesManager.vue, modules/@apostrophecms/page/ui/apos/logic/AposPagesManager.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/schema/ui/apos/logic/AposSchema.js
[PRO-6071](https://linear.app/apostrophecms/issue/PRO-6071/the-select-all-checkbox-doesnt-work-when-trying-to-give-a-user)
Fix select all broken for all relationships + for manually published relationships.
Update code to remove the `updateCheckedDocs` watcher. When checking a box it use a proxy to properly updated `checked` and `checkedDocs` together. And we have proper methods to set, add, remove checked docs (that will updated both).
The reason behind this change is code predictability improvement, it's easier to understand what code does, also to avoid side effects which can be really hard to debug.
Watchers are great but the often can be avoided with more straightforward implementations.
Also the bug we had here was linked to the watcher not being triggered when doing a …
=> fixes selectAll of relationship items

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue, modules/@apostrophecms/page/ui/apos/logic/AposPagesManager.js, modules/@apostrophecms/schema/ui/apos/components/AposInputRelationship.vue, modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue
[PRO-5949](https://linear.app/apostrophecms/issue/PRO-5949/relationship-fields-with-max-n-browse-button-should-always-remain)
For relationship fields:
* Browse button isn't disabled when limit is reached
* Pages relationships editor modal now disables checkboxes when limit is reached.
* Fixes Media manager not disabling checkboxes when limit is reached.
Verify above points.
=> Pro 5949 relationship browse button

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
[PRO-6156](https://linear.app/apostrophecms/issue/PRO-6156/tip-tap-anchor-buggy)
* Fixes tiptap bubble menu jumping on firefox when clicking on buttons. 
* Fixes the fact that double clicking on bubble menu out of buttons would prevent it from closing when unfocusing the rich text area.
Cypress tests running [here](https://github.com/apostrophecms/testbed/actions/runs/9482181140) 🟠 
Check that above described points are resolved.
=> Pro 6156 tiptap firefox jump

modules/@apostrophecms/schema/lib/addFieldTypes.js, test/schemas.js
Reverts apostrophecms/apostrophe#4570
Unfortunately this causes `doc-template-library` tests to fail because `type` is somehow being laundered to undefined, which shouldn't happen because a valid value should definitely be being passed according to the test POST request code in question. This is probably revealing a bug somewhere else, e.g. the absence of `field.def` as a fallback reveals a bug, but we can't fix it on release day so we'll delay this fix possibly to be a hotfix next week depending on customer urgency.
=> Revert "Pro 6140 no def in convert"

CHANGELOG.md, modules/@apostrophecms/piece-page-type/index.js, package.json, test/search.js
Resolve excessive recursion risk introduced by `_parent` in 4.4.0
=> 4.4.2: hotfix for _parent bringing in too much recursion risk

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputColor.vue, modules/@apostrophecms/ui/ui/apos/components/AposButtonSplit.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposSlat.vue
[PRO-6252](https://linear.app/apostrophecms/issue/PRO-6252/page-context-menu-is-badly-displayed)
Fixes display of context menu by removing unnecessary offsets.
Update Context menu to accept array of offset or single number.
Where the offset have been removed the `AposContextMenu` is a good position.
=> Pro 6252 fix context menu position

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
Fixes bug spotted since a cypress test was red. When updating an image, the `checkedDoc` wasn't updated so we wasn't seeing the changes in the right panel (when updating title).
also update listener of ·`content-changed` to update the list already available instead of re fetching everything.
For performances we get the index of the item and checkedDoc and update the one that has been updated.
Cypress tests running [HERE](https://github.com/apostrophecms/testbed/actions/runs/9665065638) 🟢 
=> Fix media update

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js
The password field needs a fallback default that makes sense given its representation in the field, just like string fields and their "subclasses"
We don't need all that other fancy null testing! Phew
See my PR on multisite-dashboard, this allows it to work with just a one-line fix in core
=> PRO-6279: simpler fix for simpler problem

CHANGELOG.md, modules/@apostrophecms/admin-bar/index.js, modules/@apostrophecms/admin-bar/ui/apos/apps/AposAdminBar.js
Add `getShowAdminBar` method.
1. Login
2. Set `getShowAdminBar` to always return `false` and validate that the admin bar is missing
3. Set it back to `!!req.user`, the admin bar should be back.
4. Logout
5. There should be no errors in the browser/server console
=> add getShowAdminBar method

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/logic/AposInputSlug.js
[PRO-6275](https://linear.app/apostrophecms/issue/PRO-6275/cms-pages-show-the-slug-twice-in-the-url)
Fixes weird frontend behaviors around slug:
* Infinite recursion between watcher and slugify methods is fixed, deep watcher removed since followingValues is always recomputed from scratch and we verify old and new value to run the code in watcher.
* Check if parent slug has changed since mounted, if yes we don't update slug.
* Fixes ICIMS issus about duplication.
Play with slugs
[Cypress tests](https://github.com/apostrophecms/testbed/actions/runs/9779699120) 🟢
=> Pro 6275 duplicated slug

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/index.js
Fixes the new rich-text-widget color picker options to align with the options used in the color schema field.
*For example:*
1. Add an area with a rich-text widget with the following in the configuration:
```
pickerOptions: {
presetColors: [ '#000000', '#ffffff', '#ff0000', '#00ff00', '#0000ff'],
disableAlpha: true,
disableFields: true
}
```
This should change the swatches and disable all of …
=> Fix rtw colorpicker options

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue
FIX
* Fixes media manager not loading images when last infinite scroll page have been reached (when uploading image for example).
Reach end of infinite scroll, then upload image then scroll again, it should work.
=> Fix media scroll after upload

modules/@apostrophecms/rich-text-widget/index.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapColor.vue
This PR changes the options for the rich-text-widget color button to be less ambiguous. All the four properties `format`, presetColors`, `disableAlpha`, and `disableFields` can be passed through an object supplied by the `colorOptions` in the area configuration or project-wide.
This PR also fixes a bug that was missed during original testing where color styling could be added to non-span tags resulting in sanitization and loss of styling when the page was published or previewed.
*For example:*
> 3. Click the "Archive" button on the top left …
=> Rtw color picker options restructure

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarMenu.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalToolbar.vue, modules/@apostrophecms/schema/ui/apos/components/AposSchema.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_normalize.scss, modules/@apostrophecms/ui/ui/apos/scss/global/_tables.scss
- Removes unnecessary, broadly applied `line-height` property used in our admin UI that may conflict with project-level CSS
https://gitlab-dcadcx.michelin.net/pa/apostrophe-enhancements/-/issues/1163
https://linear.app/apostrophecms/issue/PRO-6226/page-rendering-discrepancies-between-logged-and-anonymous-users-edit
=> Pro 6226/global line height

CHANGELOG.md, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuDialog.vue
Fixes `editorModal` and `managerModal` overrides
1. Add `article` module `modules/article/index.js`
```javascript
options: {
label: 'Article',
pluralLabel: 'Articles',
components: {
editorModal: 'CustomArticleEditor'
}
},
fields: {
add: {
title: {
label: 'Title'
}
}
}
};
```
2. Duplicate `[AposDocEditor](https://github.com/apostrophecms/apostrophe/blob/main/modules/%40apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue)` as `modules/article/ui/apos/components/CustomArticleEditor.vue`
3. Change the `background-color` in `CustomArticleEditor
4. Open the articles manager modal and when you use `New Article` button, check the background color
5. Use the quick create to create an article, and check the background …
=> set editorModal and managerModal in components browserData

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapLink.vue
- Fix a bug where the Remove Link button was not displayed when editing existing links
- Fix a bug where the Apostrophe Page relationship field was not displayed when editing an existing link to an apos page
- update the key detection strategy for keyboard handling
=> rich text link tool bugs

CHANGELOG.md, lib/mongodb-connect.js
Just as it says.
I tested this by throwing an error instead of setting `parsed` and it did allow the URL to fall through successfully to the mongodb driver. (On a Mac that could cause a failure because of localhost not resolving to ip4 etc., which is why we parse the mongodb URI at all. On Linux it was easier to test.)
I didn't test this with an actual replica set but passing the URL as-is to the driver is pretty much all we can do here.
=> if we cannot parse a mongodb URL ourselves just give it to the driver

modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocLocalePicker.vue, modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/ui/ui/apos/components/AposLocalePicker.vue, modules/@apostrophecms/ui/ui/apos/lib/tooltip.js
Blocks user from accessing the create editor modal in a locale he cannot create this type of document.
Adds new route to get permissions for type and a list of locales.
If a user has edit permissions but no create permission for a piece he shouldn't be able to switch to a locale where he cannot create a document.
Also a tooltip has been added:
=> Handle permission

modules/@apostrophecms/doc-type/ui/apos/components/AposDocLocalePicker.vue, modules/@apostrophecms/i18n/index.js
* pass draft option to check if users have create permission in draft since they should be able to save draft and submit.
* slightly refactor the method that check locales perm by not using fake docs.
Tests are green.
Works with and without advanced permission.
=> Fix locale switcher perm

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
> @haroun note that this is a follow-on PR to the original admin bar accessibility PR
- adds handlers and visual states for engaging with areas and widgets in-context
https://github.com/user-attachments/assets/675bb9ed-1c51-4c13-b13c-8f4ecaa13d35
The above video shows the scope of this change. In the video, the user's keyboard focus travels down from the admin bar to the areas and widgets below. Each area wrapper has a visual focus state. If a widget is focused and the user hits Enter or Space, the admin UI engages the widget and displays its controls (in Apostrophe we call this part 'focus'). The user can then keyboard tab through the newly displayed controls. The user can also use Escape to disengage Apostrophe focus.
=> area / widget focus states and keyboard accessibility 

CHANGELOG.md, modules/@apostrophecms/db/index.js
This was unnecessary, see:
https://mongodb.github.io/node-mongodb-native/6.8/classes/MongoClient.html#db
=> do not parse the mongodb uri where we do not have to

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/apos/webpack.config.js
* Throw an uncaught exception, reference an undefined variable on purpose, or otherwise crash at runtime in admin UI code, like in apostrophe core or a custom field type or whatever.
* Make sure your admin UI is rebuilt: be sure to do `APOS_DEV=1 npm run dev`
* In the Chrome console you should get the right line of the right source file, not the compiled bundle and/or wrong file like before.
* Verify that if the `@apostrophecms/security-headers` module is enabled, you do NOT get source maps, you just get the error line in the compiled bundle, because it is incompatible by design (forbids eval, and eval-source-map is the only kind that …
=> fix source maps for admin UI build

CHANGELOG.md, modules/@apostrophecms/asset/index.js
When one and the same Vue material icon is registered (via a module option) even with different "name", the Apostrophe UI build is failing. This patch fixes that.
* In a module "A" declare an icon `something-icon: 'Download'`
* In a module "B" declare an icon `another-icon: 'Download'`
* The build should pass, both icons should be visible
=> Fix duplicate icons breaking the build

CHANGELOG.md, modules/@apostrophecms/asset/index.js
When one and the same Vue material icon is registered (via a module option) even with different "name", the Apostrophe UI build is failing. This patch fixes that.
* In a module "A" declare an icon `something-icon: 'Download'`
* In a module "B" declare an icon `another-icon: 'Download'`
* The build should pass, both icons should be visible
=> [A3] Fix duplicate icons breaking the build

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/doc/index.js, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/lib/addFieldTypes.js, modules/@apostrophecms/widget-type/index.js, test/schemas.js
[PRO-6387](https://linear.app/apostrophecms/issue/PRO-6387/[import-export]-images-not-displayed-after-import-in)
[PRO-6420](https://linear.app/apostrophecms/issue/PRO-6420/convert-call-made-by-importer-should-be-altered-not-to-actually-fetch)
Rework in core to allow running `convert` method on data from DB.
To do so, add a method `simulateRelationshipsFromStorage` that does the opposite than `prepareForStorage` partially.
It adds a property to relationships that can be converted.
Also add an option to convert to be able to not check if relationships already exist. In the case of imports we cannot verify the order of insertion, especially when a document is a relation to different documents of the same import.
Update convert methods for different fields where needed like: `area` (as well …
=> Pro 6387 images errors

CHANGELOG.md, modules/@apostrophecms/i18n/index.js
A simple GET API at `/api/v1/@apostrophecms/i18n/locales` which returns the configured locales of the site. This is a public API intended to ease the implementation of locale switching in headless applications.
=> PRO-6438: API to expose locales

CHANGELOG.md, modules/@apostrophecms/doc/index.js, test/change-doc-ids.js
Add option `skipReplace` for `apos.doc.changeDocIds` method to skip the replacing of the "old" document in the database.
Opting in for this option, results in no DB operations related with the "old" document and the "new" document ID used as a reference for retrieving the "existent" document from the database. 
=> PRO-6418: skipReplace for changeDocIds

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaContextualMenu.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaMenu.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/scss/mixins/_zindex.scss
The idea for this fix is that when a widget's context menu is open that widget should assume focus until something else takes it. With this we can ensure all the proper UI stays on the screen without exact pointer interactions
=> Keep widget focused when menu is open

modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue
- Removes focus blocker props from checkboxes in the page relationship editor. You can now tab focus the checkbox
https://linear.app/apostrophecms/issue/PRO-4435/%5Baccessibility%5D-make-checkboxes-focusable-and-clickable
1. link a demo, npm run
2. in a page relationship field (like SEO Canonical link), test the tab-ability of the page picker
=> remove focus blockers in page relationship editor

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarLocale.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBarUser.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue, modules/@apostrophecms/doc-type/ui/apos/components/AposDocLocalePicker.vue, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposIndicator.vue
[PRO-6316](https://linear.app/apostrophecms/issue/PRO-6316/fix-context-menu-position)
find a way to center to a specific button icon when asked to, instead of manually placing arrows with padding that could break when zooming or with different wording.
So AposButton and AposIndicator emit the icon element. If we asked to the context menu to center on the icon, it will do it. Pretty simple.
Check that context menu arrow is properly centered on:
*  `draft/published` switch on admin bar.
* User settings in admin bar
* Locale switch on admin bar
* New locale switcher in doc editor
=> Improve context menu positions

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposSlatList.vue
- Fixes order on drag reorder
1. find an array schema field, add some stuff, drag to reorder
=> fix slat order on drag reorder

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/image/ui/apos/components/AposImageCropper.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/schema/ui/apos/logic/AposInputSlug.js, modules/@apostrophecms/ui/ui/apos/utils/index.js, package.json, test/utils.js
Cancel debouncers, guard against unhandled promise rejections and potential memory leaks.
No 'canceled' promise rejections. No UI regressions. 
=> PRO-6477 undhandled promise errors

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/logic/AposDocContextMenu.js, modules/@apostrophecms/i18n/i18n/en.json
Add `replaces` (boolean, `false` by default) option to the context operation definition (registered via `apos.doc.addContextOperation()`) to allow the operation to require a replace confirmation before being executed. The user confirmation results in the Editor modal being closed and the operation being executed. The operation is not executed if the user cancels the confirmation.
Using a menu item, having `replaces: true` configuration option, results in a confirmation dialog. Confirming closes the editor modal and executes the operation, canceling does not execute the operation and does not close the editor modal. …
=> PRO-6418: Add replaces configuration for editor context menus

CHANGELOG.md
We accidentally removed this from the "fixes" section.
=> we should take credit for the fix as well as the "change"

CHANGELOG.md, modules/@apostrophecms/attachment/index.js
- Adds `<use>` tag to DOMPurify allow list config on svg upload
Test file
There is a configuration profile specifically for SVGs, I would have felt better of using that just *worked*, but it did not. That would look like.
```
// allow all safe SVG elements and SVG Filters, no HTML or MathML
const clean = DOMPurify.sanitize(dirty, {USE_PROFILES: {svg: true, svgFilters: true}});
```
=> add <use> tag to DOMPurify allow list when sanitizing uploaded SVGS

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaUploader.vue, modules/@apostrophecms/ui/ui/apos/components/AposFile.vue
https://linear.app/apostrophecms/issue/PRO-4438/%5Baccessibility%5D-make-attachment-fields-visually-focused
- Adds focus state to attachment input's file UI
- Adds keyboard accessibility to trigger file selection from attachment input file UI
- Refactors focus states for Media Library's uploader tile 
https://github.com/user-attachments/assets/076e0397-4e7a-4581-aca0-2762452b8e00
=> adds focus states for file input and media lib uploader

CHANGELOG.md, modules/@apostrophecms/page/index.js, test/content-i18n.js, test/events2.js, test/parked-pages.js
Ensure `slug` is not modified for parked pages when not configured in `_defaults`. Migrate any site having "home" parked doc with slug different than `/`,
Slug of parked page can't be changed if not present in the `_defaults` configuration.
=> PRO-6591: parked slug overrides

CHANGELOG.md, modules/@apostrophecms/schema/index.js, modules/@apostrophecms/schema/lib/addFieldTypes.js
See https://github.com/apostrophecms/starter-kit-essentials/pull/63
=> fix piecesFilters with dynamic choices

modules/@apostrophecms/migration/lib/addMissingSchemaFields.js
Fix issues that came up in testbed.
=> fix oversights in add missing schema fields

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/logic/AposInputArray.js, modules/@apostrophecms/ui/ui/apos/components/AposSlatList.vue
- Fix a reorder issue for arrays (UI array editor)
- Fix inline array items label to be consistent with the standard array slat list
- Reorder an array item via drag-n-drop in the Array Editor for standard and inline arrays should work as expected
- The inline array item label now uses `title` for `titleField` by default (consistent with the Slat list)
=> PRO-6627: Fix array reorder and labels

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaMenu.vue
This PR is in response to a customer complaint that when an area has `expanded: true` then the `max` option is no longer respected. The `AposAreaMenu.vue` component passes both `disabled: false` and `max-reached` props. The `AposAreaContextualMenu.vue` component then sets `disabled` using both the passed values of disabled and max-reached. The button component, that allows the opening of the expanded widget preview, does not check the value of max-reached, only disabled. This change alters the value of `disabled` being passed so that the expanded menu respects max-reached. Closes PRO-6621.
*For example:*
> 1. Run the website and log in as an …
=> Modify disabled prop

CHANGELOG.md, modules/@apostrophecms/asset/index.js
Fix a problem when using `pnpm` option:
```js
// app.js
require('apostrophe')({
pnpm: true
});
```
that results in Apostrophe crash "can not invoke `add` of undefined".
Adding the option above is not crashing the instance.
=> [A3] Fix pnpm: true

CHANGELOG.md, modules/@apostrophecms/asset/index.js
Fix a problem when using `pnpm` option:
```js
// app.js
require('apostrophe')({
pnpm: true
});
```
that results in Apostrophe crash "can not invoke `add` of undefined".
Adding the option above is not crashing the instance.
=> Fix pnpm: true

CHANGELOG.md, index.js, lib/moog.js, test/modules-order.js, test/modules/test-before/index.js
Modules can now have a `before: "module-name"` property in their configuration to run (initialization) before another module. That works only for target modules that are initializable. 
```js
// my-module/index.js
// will be initialized before the core image piece
before: '@apostrophecms/image'
}
```
=> PRO-6660: modules order

CHANGELOG.md, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue
See changelog
Open a context menu, then, without closing this one, open another one.
The secondly opened menu should be focused and not the button of the first one that has been closed.
=> Fix menu focus

CHANGELOG.md, modules/@apostrophecms/admin-bar/index.js, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposAdminBar.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBreakpointPreviewMode.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextTitle.vue, modules/@apostrophecms/asset/index.js, modules/@apostrophecms/ui/ui/apos/components/AposButton.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuDialog.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenuItem.vue
[PRO-6678](https://linear.app/apostrophecms/issue/PRO-6678/as-a-developer-i-want-all-breakpoints-to-display-in-a-dropdown-menu-so)
* Adds possibility to have two icons on `AposButton`.
* Adds possibility to have icons in `AposContextMenuItem.vue`.
* Adds an `active` state for context menu items (only if `isActive` prop is passed).
* Adds a dropdown for non shortcuts screen of the mobile preview breakpoints.
* Show dropdown only if some screens exist without the prop `shortcut` set to true.
⚠️  For now, when nothing is selected, the button shows `Preview` next ticket is being designed.
Play with the config `breakpointPreviewMode` in the asset modules adding breakpoints and check the dropdown reacts well.
=> Pro 6678 mobile preview dropdown

CHANGELOG.md, modules/@apostrophecms/schema/lib/addFieldTypes.js
[PRO-6666](https://linear.app/apostrophecms/issue/PRO-6666/when-i-drag-and-drop-a-page-into-a-different-order-the-pending-updates)
Fix pages being marked with `Pending Updates` when moved.
It appeared because the areas comparison was comparing draft areas with temporary properties (`_edit`, `_docId`) and areas without.
Move pages, you should never see a `Pending Updates` that wasn't here before appearing after a page move.
=> Pro 6666 page move setting page as modified

modules/@apostrophecms/util/index.js, test/log.js
Before:
After:
This regressed when we introduced structured logging and has looked kind of doofy ever since.
=> warnDev now prefixes in the expected way

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/apos/webpack.scss.js, modules/@apostrophecms/asset/lib/webpack/src/webpack.scss.js
Just silence the deprecation warning for `@import` for now, see changelog for rationale
=> sass import warning

CHANGELOG.md, modules/@apostrophecms/admin-bar/index.js, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue
The admin UI now functions reasonably when the current URL was rendered directly with `sendPage` and there is no "in context" page or piece.
I tested this fix in BM's project, then gave them a simpler way since their situation really did call for a "current page" to exist anyway (they were implementing fancy rendering of a parked page and didn't know about dispatch yet).
=> PRO-6742: don't fall over if there is no context page or piece

CHANGELOG.md, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBar.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextBreakpointPreviewMode.vue, modules/@apostrophecms/admin-bar/ui/apos/components/TheAposContextUndoRedo.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_breakpoint_preview.scss
Target only data-apos-refreshable + move saving indicator after breakpoint preview
1. in `modules/@apostrophecms/asset/index.js`, set one breakpoint with `shortcut: false` and another one with `shortcut: true`
2. enable breakpoint preview and navigate between the shortcut preview and the non shortcut preview + check the display of the breakpoint preview in the admin bar
3. edit a rich-text and look for the saving indicator next to the breakpoint preview icon in the admin bar
=> target only data-apos-refreshable

modules/@apostrophecms/doc-type/index.js, test/pieces.js, test/relationships.js
[PRO-6535](https://linear.app/apostrophecms/issue/PRO-6535/projection-not-working-with-nested-relationships)
Revision of done work, Still works well when `relationships` is an array and asks specifically for a relationships (that can be nested using dot notation).
Remove support when `relationships` is true, that I modified to make it get only the first level of relationships.
One thing that could be improve in the future could be the support for abstract relationships projections, eg `_article: 1`.
Rollbacks test is green.
New ones too.
=> Pro 6535 revision

CHANGELOG.md, modules/@apostrophecms/template/lib/bundlesLoader.js, modules/@apostrophecms/widget-type/index.js
Extra bundle detection should take into account the new `build` module property and normalize when an external build module is available.
Extra bundles detection for the current page (based on the page AND widgets) now works correctly when external build module is registered.
=> Fix extra bundle detection

modules/@apostrophecms/command-menu/ui/apos/components/AposCommandMenuShortcut.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalConfirm.vue, modules/@apostrophecms/modal/ui/apos/components/AposModalShareDraft.vue
[PRO-6783](https://linear.app/apostrophecms/issue/PRO-6783/investigate-display-issue-on-confirmation-modals)
Fix modal style when using vite to build
Check `Unsaved Changes` modal
as well as `share draft`
and others (the ones that override `AposModal` style)
=> fixes modals deep selectors

CHANGELOG.md, package.json
New major version because the better validation in the underlying `cookie` module could be a problem for some. It's not for us. This resolves an npm audit warning.
=> PRO-6790: express-bearer-token updated

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapStyles.vue, modules/@apostrophecms/rich-text-widget/views/widget.html
[a11y] Typography selector have a visual focused state.
Typography selector have a visual focused state when focused (via keyboard or mouse).
=> PRO-6735: Rich text styles toolbar focused state

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/rich-text-widget/index.js
…
See changelog
* npm link into `starter-kit-essentials`
* make an inline permalink (not a pasted URL link) to another page, refresh page — it is still recognized as such by the link dialog
* same for inline images in rich text — still recognized as an existing inline image by the editor on next visit
* note the incognito view still fully resolves the URLs of linked pages and inline images (desirable behavior, except in the editor)
* Now, while logged in, use the GET REST API to access the home page at `http://localhost:3000/api/v1/@apostrophecms/page/_home`
* Note that inline images and permalinks are *not* fully resolved (appropriate because we might be editing)
* Now add `?render-areas=inline`
* Note that each widget now has an additional `_rendered` property containing fully rendered …
=> PRO-6587: access to fully rendered rich text widgets without giving up all access to other area properties or logging out

CHANGELOG.md, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue
[PRO-6810](https://linear.app/apostrophecms/issue/PRO-6810/search-feature-bug-tags-not-showing-after-clearing-search-field)
Performs the search even if the last is empty. Allows to reset the search to its initial state.
Make search on pieces, them empty it, should work.
[Cypress tests](https://github.com/apostrophecms/testbed/actions/runs/11918428484) 🟢
=> Pro 6810 search empty broken

CHANGELOG.md, modules/@apostrophecms/color-field/ui/apos/components/AposColor.vue, modules/@apostrophecms/color-field/ui/apos/lib/AposColorEditableInput.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputArray.vue, modules/@apostrophecms/schema/ui/apos/scss/AposInputArray.scss
[PRO-6822](https://linear.app/apostrophecms/issue/PRO-6822/ui-color-in-list-and-z-index-issues)
* Fixes color picket hidden in inline array (above ticket)
* Fixes color pickets inputs going off the context menu.
Color picker is not hidden by a overflow hidden in inline array
Color picker doesn't have input going off the modal
=> Pro 6822 color picker broken

CHANGELOG.md, modules/@apostrophecms/module/index.js
The new build system (when external build module is self-registered) doesn't need any computations about "what is the override of a given module". The asset override is done on `fs` level and the path doesn't need "my-*" prefix in the URL. However, the legacy Webpack system still needs the computations. This patch fixes it all in a BC way. 
Override a preview image for `@apostrophecms/image-widget` in `modules/@apostrophecms/image-widget/public/preview.jpg` (project level).
When no external build module (Vite) is registered the preview will be resolved (and properly shown) to:
```
/apos-frontend/default/modules/@apostrophecms/my-image-widget/preview.jpg
```
When external build module (Vite) IS registered the preview will be resolved (and properly shown) to:
``` …
```
=> PRO-6835: Determine Best AssetUrl is in easy mode with the new build system

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/modal/ui/apos/components/AposModal.vue, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
When tabbing into a widget editor, the focus should work again. Also when closing the widget, the previous modal (if available) should keep its focus. 
Focus works as described
=> PRO-4492: Fix widget Editor focus and cross modal focusing

CHANGELOG.md, modules/@apostrophecms/template/lib/bundlesLoader.js, test/asset-external.js
Fix an issue, when custom bundle CSS, that is extracted from the JS land is not injected in the page. This can happen when the bundle doesn't provide any `ui/src/bundle-name.scss`. 
CSS built from framework components (e.g. `.vue`, `.svelte`) is correctly injected in pages when custom bundle JS is loaded.
=> PRO-6904: Fix custom bundles CSS injection

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocContextMenu.vue, modules/@apostrophecms/doc-type/ui/apos/logic/AposDocContextMenu.js, modules/@apostrophecms/doc/index.js
[PRO-6843](https://linear.app/apostrophecms/issue/PRO-6843/as-a-user-i-want-to-be-able-to-move-palette-so-that-i-can-see-elements)
I need to add in palette a new item in the context menu.
This item should not open any modal but just emit an event I could listen to know user clicked on it. So I cannot use `customOperations` here.
I just added the possibility to pass an array of extra items to a `AposDocContextMenu` component.
This one can be used to call an action like we already do, or to emit a simple event when closing to the parent, like I do with palette.
It allows me to do this in palette:
```javascript
<AposDocContextMenu
:doc="docFields.data"
:show-edit="false"
:additional-menu-items="[{
label: 'aposPalette:resetPalettePosition',
action: 'reset-position',
emitEvent: true
}]" …
```
=> Pro 6843 context menu additional items

CHANGELOG.md, modules/@apostrophecms/schema/ui/apos/logic/AposInputRange.js
Fix range component to make it take into account the `0` value.
In a piece or widget, add the following field:
```js
rangeRequired: {
label: 'range',
type: 'range',
min: -70,
max: 70,
def: 5,
required: true
}
```
Edit the piece/widget and set the range value to `0`.
Save
Re-open, the range field should be set to `0`, not set to the default value.
=> range field now correctly takes 0 into account

CHANGELOG.md, modules/@apostrophecms/asset/lib/webpack/apos/webpack.scss.js
[PRO-6901](https://linear.app/apostrophecms/issue/PRO-6901/apostrophe-manager-and-edit-modals-are-broken-in-testbed-environments)
Apos style does not go through mobile preview plugin.
No more apos broken UI.
mobile preview still transforms public styles
=> removes use of mobile preview plugin for apos build

CHANGELOG.md, package.json, test/esm-project/app.js, test/workspaces-project/app.js
a necessary bug fix in the site map module broke the apostrophe core tests, no actual functionality changes in core
=> hotfix to get tests passing after a change in the sitemap module

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue
Fixes a regression, where images  in Media manager are not selectable (click on an image does nothing) in both default and relationship mode.
The source of the problem is a `:key` prop that is randomized on click, probably due to an immediate (outside) re-rendering of the component. The provided solution: memoize media item keys so that the "key" is attached to an image item just once.
Selecting an image in Media Manager works as expected.
=> Fix media image select

CHANGELOG.md, package.json
Fixes a bug where images in Media manager are not selectable (click on an image does nothing) in both default and relationship mode.
=> release 4.11.2

CHANGELOG.md, modules/@apostrophecms/color-field/index.js, modules/@apostrophecms/color-field/ui/apos/components/AposColor.vue, modules/@apostrophecms/color-field/ui/apos/components/AposInputColor.vue, modules/@apostrophecms/color-field/ui/apos/lib/AposColorHue.vue, modules/@apostrophecms/color-field/ui/apos/logic/AposInputColor.js, modules/@apostrophecms/color-field/ui/apos/mixins/AposColorMixin.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapColor.vue
- Adds support for disabling the color spectrum UI of a color field
- Adds module level default options for color pickers
- Refactors portions of the implementation of color pickers by schemas and RT widgets
- Removes `pickerOptions` from the options API and moves its properties up a level
**old:**
```
options: {
format: 'hex6',
pickerOptions: {
disableFields: true,
presetColors: [ '#fff', '#000' ]
}
}
```
**new:**
```
options: {
format: 'hex6',
disableFields: true,
presetColors: [ '#fff', '#000' ]
}
```
- Fixes an issue where the RT control bar would close while using the color picker
- Fixes an issue where clicking the color picker's hue field wouldn't update
✅ [UI tests passing](https://github.com/apostrophecms/testbed/actions/runs/12304447531)
*For example:*
1. checkout …
=> Color field: disable spectrum, merge `pickerOptions`, refactor

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/logic/AposDocContextMenu.js, modules/@apostrophecms/modal/ui/apos/components/AposDocsManagerToolbar.vue, modules/@apostrophecms/page/ui/apos/logic/AposPagesManager.js
[PRO-6871](https://linear.app/apostrophecms/issue/PRO-6871/missing-space-between-templates-and-the-menu-above-it-in-the-template)
[PRO-6870](https://linear.app/apostrophecms/issue/PRO-6870/when-i-try-to-export-a-document-template-from-within-the-templates)
- https://github.com/apostrophecms/apostrophe/pull/4834
- https://github.com/apostrophecms/import-export/pull/99
- https://github.com/apostrophecms/doc-template-library/pull/79
* Add margin top to grid
* Gets related types in export modal for all checked doc types (and not for the doc template module itself).
* There is a nice margin between the manager toolbar and the grid.
* When export batching, the related types you can check should match all the types of templates you checked (and not the related types of the template module). …
=> PRO 6870 Export Templates / pass module labels to AposDocContextMenu for modals

CHANGELOG.md, modules/@apostrophecms/asset/lib/globalIcons.js, modules/@apostrophecms/color-field/ui/apos/components/AposInputColor.vue, modules/@apostrophecms/color-field/ui/apos/lib/AposColorInfo.vue, modules/@apostrophecms/color-field/ui/apos/logic/AposInputColor.js, modules/@apostrophecms/schema/ui/apos/components/AposInputRange.vue, modules/@apostrophecms/schema/ui/apos/components/AposInputWrapper.vue, modules/@apostrophecms/schema/ui/apos/logic/AposInputRange.js, modules/@apostrophecms/schema/ui/apos/logic/AposInputWrapper.js, modules/@apostrophecms/schema/ui/apos/logic/AposSchema.js, modules/@apostrophecms/ui/ui/apos/scss/global/_inputs.scss
[PRO-6974](https://linear.app/apostrophecms/issue/PRO-6974/update-field-uis)
See tickets, also tries to improve some inline generic style.
See design, to test with this [palette PR](https://github.com/apostrophecms/palette/pull/101)
[Cypress tests](https://github.com/apostrophecms/testbed/actions/runs/12905813636) 🟢
=> Pro 6974 update UI fields

modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapColor.vue
=> adds transparency checkerboard to RT color control

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, modules/@apostrophecms/schema/index.js, test/relationships.js
=> PRO-6876: implicit properties for reverse relationship projectionsnship projections

CHANGELOG.md, lib/modules/apostrophe-docs/lib/api.js, lib/modules/apostrophe-docs/lib/routes.js
- do refresh a stale lock in order to avoid having the popup (+ refresh) when the lock for a doc is stale, as long as the context id (ie. tab) is the same
- improve messages:
|--------|--------|
| <img width="480" alt="image" src="https://github.com/user-attachments/assets/5d1a9054-43ad-4365-bc83-0ca688f3b2a5" /> | <img width="462" alt="image" src="https://github.com/user-attachments/assets/d24b2cec-536f-4bb8-811f-bef9e6b00b53" /> | 
*For example:*
If adding a new feature without an already open …
=> improve docs lock system

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue
Fixes an issue, when a selected from a relationship image is not present in the currently loaded images and not editable. 
1. Modify an image widget.
2. Click on Browse Images.
3. Select an image from page 2 or later in the image manager modal.
4. Save the widget.
5. Reopen the Modify Image Widget.
6. Click Browse Images again.
7. Click on Edit in the preview of the previously selected image.
8. Edit works as expected.
=> PRO-7152: Fix media manager edit when image not loaded

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/ui/ui/apos/scss/global/_widgets.scss
* Fixes margin collapse in nested areas by switching to `padding` instead of `margin`
=> fix nested area margin collapse

CHANGELOG.md, modules/@apostrophecms/file/index.js
We already have a file tags piece type and the means to populate that relationship, but forgot to include it on the "Filters" dropdown so users can have some joy of it.
=> we forgot to configure the tags filter for files

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/doc-type/ui/apos/logic/AposDocContextMenu.js, modules/@apostrophecms/image/index.js, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue, modules/@apostrophecms/job/index.js, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js, modules/@apostrophecms/notification/ui/apos/components/AposNotification.vue, modules/@apostrophecms/page/index.js, modules/@apostrophecms/page/ui/apos/logic/AposPagesManager.js, modules/@apostrophecms/piece-type/index.js, modules/@apostrophecms/piece-type/ui/apos/components/AposDocsManager.vue, modules/@apostrophecms/ui/ui/apos/stores/notification.js
[PRO-7017](https://linear.app/apostrophecms/issue/PRO-7017/[media-library]-as-an-editor-i-should-be-able-to-select-multiple)
* Adds batch operations to media manager.
* Removes the `publish` batch operation for `autopublished` docs.
Test media manager batch operations:
* Archive
* Restore
* Export
* Localize
[Cypress tests](https://github.com/apostrophecms/testbed/actions/runs/13970947161) 🟢
=> Pro 7017 image batch operations

CHANGELOG.md, modules/@apostrophecms/express/index.js, modules/@apostrophecms/page/index.js, modules/@apostrophecms/piece-type/index.js
See changelog. The `express-cache-on-demand` middleware should be instantiated separately for each instance of ApostropheCMS, it must not be instantiated at top level.
In addition, there is no need for multiple instances of the middleware within a single instance of ApostropheCMS, so create a single one and attach it to `self.apos` in `@apostrophecms/express`.
=> PRO-7472 hotfix: release 4.14.1

.eslintrc, CHANGELOG.md, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapAnchor.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapColor.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapImage.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapInsertItem.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapLink.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapMarks.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapStyles.vue, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposTiptapTable.vue, modules/@apostrophecms/ui/ui/apos/components/AposTreeRows.vue, package.json
[PRO-7371](https://linear.app/apostrophecms/issue/PRO-7371/buggy-behavior-with-the-pages-manager-when-opening-it-from-a-link)
[PRO-7392](https://linear.app/apostrophecms/issue/PRO-7392/rich-text-widget-image-insertion-menu-not-working-correctly)
[PRO-7370](https://linear.app/apostrophecms/issue/PRO-7370/rich-text-toolbar-doesnt-close-automatically-when-i-save-link)
* No more double click needed to select a page when coming from rich text
* Rich text toolbar doesn't get stuck (some workarounds)
* Fix bug of the insert menu for images (image menu not being properly closed)
[Cypress](https://github.com/apostrophecms/testbed/actions/runs/142231822 …
=> Pro 7371 link pages

modules/@apostrophecms/i18n/i18n/en.json, modules/@apostrophecms/image/ui/apos/components/AposMediaUploader.vue
> Note: no need of changelog, an issue introduced by unreleased changes.
Let the Media Manager emit the results and show the failed upload number. When not doing so, it breaks our improved flow (no server requests, handling properly the empty placeholders based on failed/succeeded uploads). 
Upload X files, having a forbidden extension (e.g. `.js`) among them. The succeeded files should show after upload, the failing upload placeholder should be removed, additional notification should be shown informing about the number of failed files. 
=> PRO-7346: Add missing  error handling related with a previous patch

CHANGELOG.md, modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerDisplay.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposDocsManagerMixin.js
[PRO-7563](https://linear.app/apostrophecms/issue/PRO-7563/bring-back-the-code-that-hides-the-checkboxes-select-all-on-media)
Gets back images checkboxes, do you see any place where we want to hide them now? Maybe we can just remove the option, or maybe not for BC.
Checkboxes are visible like before for batch operations.
[Cypress](https://github.com/apostrophecms/testbed/actions/runs/14449929568) 🟢
=> Pro 7563 images checkbox

modules/@apostrophecms/doc/index.js, modules/@apostrophecms/i18n/index.js, modules/@apostrophecms/piece-page-type/index.js
[PRO-7547](https://linear.app/apostrophecms/issue/PRO-7547/locale-switcher-does-not-work-for-pieces-if-the-piece-page-exists-but)
See ticket:
Fix switch locale from piece to piece when the index page in the target locale is draft only.
⚠️ Most of the changes are linter only. I added two comments where the important code is located with some explanations.
* Create a piece in two locales
* Create an index page for these pieces in both locale
* In the target locale make the index page only draft
* Switch locale when on the piece page on the initial locale to the target locale
* It should find the target locale piece, even if its parent page is draft only
=> Pro 7547 locale switcher

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/image/ui/apos/components/AposMediaManagerEditor.vue
Adds missing notifications and error handling in media manager and save notification for auto-published pieces.
Notifications are shown for archive, restore and update in media manager, and save for autopublished pieces. Archive errors in media manager are handled correctly. 
=> PRO-7367: Add missing notifications and error handling

CHANGELOG.md, package.json
hotfix for XSS issue.
The major version bump in dompurify is OK because all they did was remove IE support (not relevant in nodejs validation). I have verified that I can still upload SVG files to apostrophecms.
=> PRO-7633: Hotfix 4.15.2

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/area/ui/apos/components/AposAreaEditor.vue, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue
- Introduces a new POST route `@apostrophecms/area/validate-widget`.
- Refactor the area API routes to avoid code duplication. 
- Adds a server validation before adding a widget to an area.
- Let the generic server error handler (UI) look for `data.details` as per latest standard.
Extend a widget's `sanitize` method and throw an error. Attempt to add that widget to some area - you should see the error message (the one from `{ details: xxx }` if you provide it) as notification. 
=> PRO-7309: Widget server validation

CHANGELOG.md, modules/@apostrophecms/doc-type/index.js, test/autocomplete.js
Due to the lack of unique sort value, autocomplete and search (pieces/pages manager) can return randomly sorted results and duplicates during pagination. 
Search and autocomplete with the same phrase returns always the same result. 
=> PRO-7308: Fix autocomplete sorting

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
[PRO-7664](https://linear.app/apostrophecms/issue/PRO-7664/yet-another-widget-z-index-issue)
Fix the second level controls being under the `+` button
See above.
=> AposAreaWidget: fixes z-index of controls over + button

CHANGELOG.md, modules/@apostrophecms/module/index.js
* Set the `Cache-Control` header to `no-store` for error pages in order to prevent the risk of serving stale error pages to users.
=> do not cache error pages

CHANGELOG.md, modules/@apostrophecms/express/index.js, test/express.js
* Using an API key with the editor, contributor or guest role now have a `req` object with the corresponding rights. The old behavior gave non-admin API keys less access than expected.
=> use req with the corresponding right when using an api key

modules/@apostrophecms/schema/index.js
I tiny change to ensure a safe convert check.
=> Ensure convert doesn't fail on its own

CHANGELOG.md, modules/@apostrophecms/rich-text-widget/index.js, modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue
The in-context editing relies on `modified` document property, returned by the backend, to enable the "Update" (publish) context bar button. However, the `isEmpty()` handler of the rich text "understands" only a plain text as non-empty state. This is wrong from some time (because we have pure HTML nodes as `figure` and `table`). We detect just a "string" now.
Additionally,  the visually empty check of the UI is improved to avoid (visual) confusion. 
The Update button in the in-context editing is enabled when rich text Image is inserted in an empty area.
=> PRO-7811: Rich text modified state not detected correctly by the backend

modules/@apostrophecms/rich-text-widget/ui/apos/components/AposRichTextWidgetEditor.vue, package.json
Unpin `prosemirror-model` and fix the underlying issue.
**The long story:**
We use custom extension named `defaultNode` in order to allow rich-text areas to have a "default style". A scenario - a configured by a developer rich text placed to produce `h1` on a page doesn't require the editor to switch the style manually to `h1`. 
The `defaultNode` can adapt and based on the configured style with `def: true`, become a simple extension of `paragraph`, `heading` or just a text node (`span`). The problem arising with this approach is how prosemirror handles parsing - it needs 1-to-1 mapping of a "nodeName" to a "nodeElement". When the DOM parser attempts to parse the tree and in our case - to validate a list, it matches the configured list item `content`, in our case `defaultNode`. However, …
=> PRO-7797: Ensure defaultNode has highest priority

modules/@apostrophecms/image-widget/views/fragment.html
A tiny bug, when no `options.className` is set (or no context option with the same name), the figure class is set to `false_wrapper`. This patch just removes the class attribute in that case.
No `false_wrapper` class is set. 
=> PRO-7943: Fix wrapper class when no base class is set

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/rich-text-widget/index.js
- Removes lodash (questionable usage with find method not fitting the current documentation) and replaces it with a simple array `find`.
- Allow `import.imageTags` (array of image tag IDs) to be passed to the rich text widget when importing (see https://docs.apostrophecms.org/reference/api/rich-text.html#importing-inline-images).
Image tags can be assigned to imported images.
=> PRO-7932: Simplify field options and allow import image tags

modules/@apostrophecms/image/ui/apos/components/AposMediaManager.vue, modules/@apostrophecms/modal/ui/apos/components/AposDocsManagerToolbar.vue, modules/@apostrophecms/ui/ui/apos/components/AposContextMenu.vue, modules/@apostrophecms/ui/ui/apos/components/AposTagApply.vue
[PRO-8007](https://linear.app/apostrophecms/issue/PRO-8007/batch-tagging-in-the-tag-list-view-the-dialogue-should-have-a-fixed)
[PRO-8003](https://linear.app/apostrophecms/issue/PRO-8003/batch-tagging-the-manage-tags-ui-should-open-the-image-tag-manager-not)
* Batch tagging popover has a fixed height of 450px. 
* When clicking on `manage tags` we open the image-tags manager:
* When closing the images-tag manager, we refresh the `AposMediaManager` selected images and all tags to be sure changes saved are reflected in the UI.
* Check that the popover has a fixed height and that scroll is still working.
* Manager tags buy clicking `manager tags` and check changes are reflected in media manager and tags popover (which is closed and reopened).
=> Pro 8003 manage tags

CHANGELOG.md, modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/attachment/index.js
I removed comments that were too long for eslint because they were also not really necessary to keep, they made sense in the context of explaining the changes but are more self-evident going forward.
When releasing this, please make sure the release note makes crystal clear there was no actual vulnerability (there wasn't, the CVE is disputed because it says "OMG, a module for uploads allows uploads")
=> thanks our contributor for the lovely PR

CHANGELOG.md, modules/@apostrophecms/piece-type/ui/apos/components/AposUtilityOperations.vue
Regression: this got broken when we expanded the amount of information these operations can pass, between April and July. Impacts the ai helper module, but also new work like section template library that needs a utility operation not hidden away in a menu.
=> PRO-8220: "button: true" works again for piece module utility operations

CHANGELOG.md, modules/@apostrophecms/doc-type/ui/apos/components/AposDocEditor.vue, modules/@apostrophecms/image-widget/ui/apos/components/AposImageWidget.vue, modules/@apostrophecms/modal/ui/apos/composables/AposEditor.js, modules/@apostrophecms/modal/ui/apos/mixins/AposEditorMixin.js, modules/@apostrophecms/piece-type/ui/apos/lib/postprocessRelationships.js, modules/@apostrophecms/schema/ui/apos/logic/AposInputRelationship.js, modules/@apostrophecms/schema/ui/apos/logic/AposSchema.js, modules/@apostrophecms/ui/ui/apos/composables/AposTheme.js, modules/@apostrophecms/ui/ui/apos/mixins/AposThemeMixin.js, modules/@apostrophecms/widget-type/ui/apos/components/AposWidgetEditor.vue, modules/@apostrophecms/widget-type/ui/apos/composables/AposWidget.js
[PRO-8087](https://linear.app/apostrophecms/issue/PRO-8087/autocrop-doesnt-work-for-image-widgets)
Fix autocrop in `image-widget`.
[Cypress tests](https://github.com/apostrophecms/testbed/actions/runs/17261371871) 🟢 
[Cypress PR](https://github.com/apostrophecms/testbed/pull/372).
Autocrop should work for:
* Quick image upload from media manager
* Drag and drop
* Quick image upload from your device
* Old school widget editor selection
Also it now works with live preview properly without slowing everything up.
It fixes a problem of updated data not being properly synced between the editor `docFields.data` and `AposSchema` `fieldState` / `next`. It's better that data updates come from inputs / schema and not from above to avoid bugs / confusion.
I moved the postprocess relationship logic …
=> Pro 8087 aspect ratio image widget

CHANGELOG.md, modules/@apostrophecms/login/index.js, test/login.js
This PR refactors the `login/whoami` route as accessible both by `POST`, which is recommended, and `GET`, for BC. It also updates the Mocha tests to use the recommended verb. Closes POST-8236.
*For example:*
**Other …
=> refactor whoami route and update tests

modules/@apostrophecms/image-widget/ui/apos/components/AposImageWidget.vue
=> the moduleName passed to a doc type manager is the doc type, not the widget type you happen to be picking it for

CHANGELOG.md, modules/@apostrophecms/area/index.js, modules/@apostrophecms/area/ui/apos/components/AposAreaContextualMenu.vue, modules/@apostrophecms/area/ui/apos/components/AposAreaExpandedMenu.vue, modules/@apostrophecms/area/ui/apos/lib/filter-create-widget-operations.js, modules/@apostrophecms/area/ui/apos/lib/get-widgets.js, modules/@apostrophecms/widget-type/index.js
... So we don't offer "insert section" if none of the widget types allowed in this area are permitted to be the basis for a section.
This does NOT mean you can never hit "insert section" and find an empty list. That would require an expensive API call, so it's not worth it.
=> PRO-8256: allow createWidgetOperations to be filtered based on a list of widget types

modules/@apostrophecms/layout-widget/ui/apos/components/AposAreaLayoutEditor.vue, modules/@apostrophecms/layout-widget/ui/apos/components/AposGridLayout.vue, modules/@apostrophecms/layout-widget/ui/apos/components/AposGridManager.vue, modules/@apostrophecms/layout-widget/ui/apos/lib/grid-manager.js, modules/@apostrophecms/layout-widget/ui/apos/lib/grid-state.mjs
Let move/resize snapping result in temporal preview layout state.
=> PRO-8303 temporal state

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue
=> Move away side effect in copmuted definition

CHANGELOG.md, index.js, package.json
The important part is that the multisite module just never asked apostrophe *not* to exit, which, fun fact, it does by default if initialization of the whole site fails.
Secondary is that I added better handling so multisite can decide how to log it via `exit: 'throw'`, and also added any logging at all if `exit: false` is used, way to go past Tom some real thorough thinking there 👀
=> PRO-8348: part of the hotfix for poor error handling if one site in a multisite project does not initialize properly

modules/@apostrophecms/layout-widget/index.js, modules/@apostrophecms/layout-widget/ui/apos/components/AposAreaLayoutEditor.vue, modules/@apostrophecms/layout-widget/ui/src/_breakpoints.scss, modules/@apostrophecms/layout-widget/ui/src/layout.css, modules/@apostrophecms/layout-widget/views/column.html, package.json
- Load and preprocess the public styles on init
- Inject the appropriate style on runtime
- Remove the public sass
- Fix a glitch when manage UI is not properly shown when mobile preview is active
Closes PRO-8322
=> Process manually and inject CSS, fix manage layout CSS glitch

modules/@apostrophecms/area/ui/apos/components/AposAreaWidget.vue, modules/@apostrophecms/layout-widget/ui/apos/components/AposAreaLayoutEditor.vue
Disallow the double click when the edit widget operation is disabled.
=> PRO-8370: Prevent double click edit when edit is disabled
